### ISSUE TITLE
examples should be in their own folders

### ISSUE THREAD

**Issue by mattetti** [hybridgroup/gocv#1]
`go-opencv3/examples/facedetect.go` > `go-opencv3/cmd/facedetect/main.go`

We should have 1 main per folder/package and the convention is to use have a cmd folder containing those CLI tools/examples.

**Comment by deadprogram** [comment]
I had not really thought about them as useful in their own rights as command-line tools, but seems like a cool idea. PR?

**Comment by deadprogram** [comment]
This is now done, thank you again @mattetti for the good suggestion.
