### ISSUE TITLE
rfc: code generation

### ISSUE THREAD

**Issue by berak** [hybridgroup/gocv#100]
opencv has generator scripts for the python/java/matlab wrappers

see, e.g [here](https://github.com/opencv/opencv/tree/master/modules/python/src2)

while i definitely dig your  ("move slow, don't break anything, do it in small, comprehensive parts, also have tests for anything") style, 

even the core module  won't be wrapped fully, until the sun melts. given the current pr rate of .5 functions a day (yea, needs more monkeys. don't pray on that)

don't get me wrong, i'm not voting for a full-blown code generation on the client side (far too early), more like  tooling to speed-up well-needed pr's

we could use stuff like that, to improve code wrapping in small batches, like 5 a day

apply your time-sclice on writing tests / samples, not on  the actual wrapping.

**Comment by deadprogram** [comment]
Hi @berak I feel you. I've been thinking about what sort of tooling might help accelerate the process, without going for full code gen like Python/Java. Any ideas you have on this would be appreciated.
