### ISSUE TITLE
rfc: renaming enums

### ISSUE THREAD

**Issue by berak** [hybridgroup/gocv#102]
imho, it's not desirable, to rename opencv constants. (even if those are not much go-like)

if the opencv docs say, it is BORDER_REFLECT, it should be **exactly** the same in cvgo, else it's only a source of unnessecary confusion.

**Comment by deadprogram** [comment]
I have been somewhat conflicted by this. On the one hand, I'd really like GoCV to be as "Go-like" as possible. On the other hand, your point about confirming to all the other available docs about OpenCV is right on, and would be desirable.

I'd love to hear from other users and contributors what you all think would be the best approach. Stick to the more idiomatic Go approach, or use identical constants to the OpenCV C++ code?

**Comment by willdurand** [comment]
I like having the go version of the constants iif we only have to "camel case" them, e.g., `BORDER_REFLECT` => `BorderReflect`.

It is elegant and it should not confuse the  users. I think reading opencv official doc and looking for the GoCV camel cased constants is something Go devs will do.

**Comment by berak** [comment]
ok. outvoted ;)

let's keep it consistant, and stick with camels, then..
