### ISSUE TITLE
How to implement cv2.divide in gocv ?

### ISSUE THREAD

**Issue by jingsupo** [hybridgroup/gocv#1022]
**I want result like this in python:**

`res = cv2.divide(gray, 255 - blur, scale=255)`

**In gocv:**

`gocv.Divide(gray, blurInv, &res)`

**but the two results is different, what shoud i do ?**

**Comment by kevincua-umbocv** [comment]
https://docs.opencv.org/4.x/d2/de8/group__core__array.html#ga6db555d30115642fedae0cda05604874

`res = cv2.divide(gray, 255 - blur, scale=255)` uses scale while `gocv.Divide(gray, blurInv, &res)` doesn't.

You have to perform your own scale on the gocv version

**Comment by jingsupo** [comment]
@kevincua-umbocv Thank you very much.

I use the bellow code:

```
gocv.Divide(gray, blurInv, &res)
res.MultiplyFloat(255)
```

but its result is also different from `res = cv2.divide(gray, blurInv, scale=255)`

How shoud i do to perform my own scale on the gocv version ?

**Comment by kevincua-umbocv** [comment]
@jingsupo 
`𝚍𝚜𝚝(𝙸) = 𝚜𝚊𝚝𝚞𝚛𝚊𝚝𝚎(𝚜𝚛𝚌𝟷(𝙸)*𝚜𝚌𝚊𝚕𝚎/𝚜𝚛𝚌𝟸(𝙸))`
This is the formula from opencv for `cv2.divide`, try to do it in the same order

If it's still not the same, then your src2 is probably different. Make sure each matrix has the same value

**Comment by kevincua-umbocv** [comment]
@jingsupo just wondering if you out what the issue was?

**Comment by jingsupo** [comment]
@kevincua-umbocv Still not very clear :(

**Comment by jingsupo** [comment]
I achieved the `res = cv2.divide(gray, 255 - blur, scale=255)` effect using the following code

```
func pixelDiv(cvMat1, cvMat2 gocv.Mat) gocv.Mat {
	cvMatBytes1 := cvMat1.ToBytes()
	cvMatBytes2 := cvMat2.ToBytes()
	var resBytes []byte
	for i := 0; i < len(cvMatBytes1); i++ {
		val := float64(cvMatBytes1[i]) / float64(cvMatBytes2[i]) * 255
		if val > 255 {
			val = 255
		}
		resBytes = append(resBytes, byte(math.Round(val)))
	}
	result, _ := gocv.NewMatFromBytes(cvMat1.Rows(), cvMat1.Cols(), gocv.MatTypeCV8U, resBytes)
	return result
}
```
