### ISSUE TITLE
Add cv::cuda::TemplateMatching bindings

### ISSUE THREAD

**Issue by danhab99** [hybridgroup/gocv#1043]
Hello friends, I was wondering about the fesability of binding the `matchTemplates` cuda implementation https://docs.opencv.org/3.4/d2/d58/classcv_1_1cuda_1_1TemplateMatching.html ? I've been trying to make it happen myself but it's above my skill level.

**Comment by deadprogram** [comment]
Hello @danhab99 please give a try to https://github.com/hybridgroup/gocv/pull/1044

:christmas_tree:

**Comment by danhab99** [comment]
Thanks for the pullrequest @deadprogram. It looks like its working out. Now I gotta learn more about graphics card processing bc my algo seems to be slower now (out of scope of this). Thank you for your efforts!
