### ISSUE TITLE
cv::Point2f data structure in Go?

### ISSUE THREAD

**Issue by willdurand** [hybridgroup/gocv#105]
Hi,

`gocv` relies on the Go [`image.Point`](https://golang.org/pkg/image/#Point) (X and Y are integers) but it seems opencv uses `cv::Point2f` time to time and we do not have a Go data structure for it. Should we add it or is there something I've overlooked?

Cheers,
William

**Comment by berak** [comment]
@willdurand , if you want my 2ct, -- [do it  !!](https://github.com/opencv/opencv/search?utf8=%E2%9C%93&q=Point2f&type=) 

from there on, it would probably be a good idea, to have Mat setters / getters for this, so we don't need an additional C structure for `vector<Point2f>` or `vector<vector<Point2f>>`

again, opencv's own python/java wrappers treat a `vector<Point2f>` simply as a `Mat(h,w,CV_32FC2)`, and a `vector<vector<Point2f>>` would translate to a `struct Mats` 
(very much simplifying the internal wrapping, and leaving the problem, how to access items to userland)

**Comment by willdurand** [comment]
This is an interesting approach, I like it.

**Comment by willdurand** [comment]
@deadprogram could you assign me to this? I'd like to give it a shot

**Comment by deadprogram** [comment]
Done... go get 'em, tiger! :)

**Comment by deadprogram** [comment]
Just wonder if the recent #139 sufficiently addresses this, or if more needs to be done.

@willdurand @berak what do you think?

**Comment by deadprogram** [comment]
Pinging to update this issue... what is the status on it?

**Comment by deadprogram** [comment]
This was actually implemented long ago. Oops! Now closing.
