### ISSUE TITLE
Converting `gocv.Mat` to array

### ISSUE THREAD

**Issue by modanesh** [hybridgroup/gocv#1055]
How one could convert the `gocv.Mat` to other formats like `arrays`?

## Description
I am reading an image from file and processing it using `gocv`. As long as `gocv` is being used, everything's fine, but when I want to feed this image (`gocv.Mat`) to a function of another package (e.g. in [tfgo](https://github.com/galeone/tfgo)) it should be converted to another type like `arrays`. 

## Steps to Reproduce
N/A

## Your Environment
* Operating System and version: Ubuntu 20.04
* OpenCV version used: 4.7
* How did you install OpenCV? `sudo apt install`
* GoCV version used: latest
* Go version: 1.17
* Did you run the `env.sh` or `env.cmd` script before trying to `go run` or `go build`? no

**Comment by yg7001** [comment]
try mat.DataPtrUint8()
