### ISSUE TITLE
Implement FaceDetectorYN class in gocv 

### ISSUE THREAD

**Issue by SakthiMahendran** [hybridgroup/gocv#1058]
"FaceDetectorYN" is very powerful face detection class that is used to detect faces using "YuNet" algorithm (CNN).
It is faster and more accurate than "Harcascade" algorithm.
So it is a great advantage to implement such an class in gocv
And also can any one describe that how can I use this with gocv.ReadNet(), is it even possible ?

Thanks in advance 🙂.

**Comment by deadprogram** [comment]
This is in the new release 0.39.0 thanks to @diegohce now closing.
