### ISSUE TITLE
Raspberry Pi 4B does not need "-D ENABLE_VFPV3=ON"

### ISSUE THREAD

**Issue by hare-siterwell** [hybridgroup/gocv#1059]
When I run `make build_raspi`, there is an error reported

```sh
Required baseline optimization is not supported: VFPV3
```

**Comment by swdee** [comment]
The flag `-D ENABLE_VFPV3=ON` needs to be removed from the `Makefile` build here.

https://github.com/hybridgroup/gocv/blob/579545a364744945c08186e8feca10258c73fefd/Makefile#L121
