### ISSUE TITLE
How do I call cvCreateImage, cvCreateHist among opencv methods?

### ISSUE THREAD

**Issue by sanghogu** [hybridgroup/gocv#1095]
How do I call **cvCreateImage**, **cvCreateHist** among opencv methods?

I came across golang recently and installed it, but it was quite different from the opencv wrapper of c++, so I was confused.

## Your Environment

* Operating System and version: windows
* OpenCV version used: 4.8
* GoCV version used: 0.34
* Go version: 1.21

**Comment by deadprogram** [comment]
Please take a look at the GoCV package docs here:
https://pkg.go.dev/gocv.io/x/gocv

GoCV tries to map as closely as possible to the C++ API, not the C ones you reference in your question. Hope that helps!

**Comment by sanghogu** [comment]
aha. Thanks  I looked at your ripple and looked closely and there was a difference from the opencv version I was using in c. Thanks again.
