### ISSUE TITLE
Support for imreadmulti?

### ISSUE THREAD

**Issue by 4imothy** [hybridgroup/gocv#1125]
I am creating a program that must read a stacked tiff file, I am able to read such an image with ```imreadmulti``` in my python equivalent but would prefer to use Go. Are there plans to support this function?

* Operating System and version: MacOS Venture 13.6
* OpenCV version used: 4.8.0
* How did you install OpenCV? homebrew, ```brew install opencv```
* GoCV version used: 0.34.0
* Go version: 1.21.1 darwin/arm64
* Did you run the `env.sh` or `env.cmd` script before trying to `go run` or `go build`? No

**Comment by deadprogram** [comment]
Tagging to close this issue after next release now that #1196 has been merged into `dev`.
