### ISSUE TITLE
New release? 

### ISSUE THREAD

**Issue by willdurand** [hybridgroup/gocv#114]
Hi

Some nice work has been done in the [`dev` branch](https://github.com/hybridgroup/gocv/compare/dev)  and it would be cool to have a new release. What's the release strategy? Can we get a new release?

Thank you!

**Comment by deadprogram** [comment]
Agreed. Working on a branch for https://github.com/hybridgroup/gocv/issues/109 right now...

**Comment by deadprogram** [comment]
Release 0.10.0 is now out, so closing.

**Comment by willdurand** [comment]
Thank you!

![](https://media.giphy.com/media/26gsdJuCKyXixRbVu/giphy.gif)
