### ISSUE TITLE
Newbie contribution doubts

### ISSUE THREAD

**Issue by morfeo8marc** [hybridgroup/gocv#117]
Hi,
Before I submitted pull request #116, tried to run `go test core_test.go` and got the following error:
```
# command-line-arguments
./core_test.go:11:9: undefined: NewMat
./core_test.go:18:9: undefined: NewMatWithSize
./core_test.go:18:34: undefined: MatTypeCV8U
./core_test.go:41:9: undefined: NewMatWithSize
./core_test.go:41:34: undefined: MatTypeCV8U
./core_test.go:53:9: undefined: NewMatWithSize
./core_test.go:53:34: undefined: MatTypeCV8U
./core_test.go:55:10: undefined: NewMat
./core_test.go:69:9: undefined: NewMatWithSize
./core_test.go:69:34: undefined: MatTypeCV8U
./core_test.go:69:34: too many errors
FAIL	command-line-arguments [build failed]

```
What am I doing wrong(even running `go test core_test.go core.go` I get and even longer error that I will not paste to keep it short)? Because on the other hand, if I execute `go test -run TestMeanStdSDev` the test runs successfully:
```
PASS
ok  	gocv.io/x/gocv	0.030s
```

Thanks in advance.

**Comment by deadprogram** [comment]
Hello @morfeo8marc you normally use the `go test` with command to run tests on packages, not on individual files. Hence a command like `go test core_test.go` is not expected to work.

**Comment by willdurand** [comment]
Yes I ran into this too, the best way to isolate a test case, as you wrote, is to use `-run`.

**Comment by deadprogram** [comment]
Additional documentation on how to run tests is now part of v0.11.0 thank you. Now closing.
