### ISSUE TITLE
OSX : clang: error: /usr/local/Cellar/opencv/3.4.1_2/include: 'linker' input unused [-Werror,-Wunused-command-line-argument]

### ISSUE THREAD

**Issue by mmerlange** [hybridgroup/gocv#124]
Hello,

I followed the steps in the installation process and I got the following error. Any hint ?
And great thanks you to the team, I'm switching to go because of this package !
Michaël

go run ./cmd/version/main.go
# runtime/cgo
clang: error: /usr/local/Cellar/opencv/3.4.1_2/include: 'linker' input unused [-Werror,-Wunused-command-line-argument]
clang: error: /usr/local/Cellar/opencv/3.4.1_2/include/opencv2: 'linker' input unused [-Werror,-Wunused-command-line-argument]

About my versions :
gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 9.0.0 (clang-900.0.39.2)
Target: x86_64-apple-darwin17.4.0
Thread model: posix

brew info opencv
opencv: stable 3.4.1 (bottled)
Open source computer vision library
https://opencv.org/
/usr/local/Cellar/opencv/3.3.0_3 (516 files, 122.9MB)
  Poured from bottle on 2017-09-01 at 18:08:45
/usr/local/Cellar/opencv/3.4.1_2 (558 files, 98.6MB) *

**Comment by deadprogram** [comment]
Hi @mmerlange from your output it appears that you have 2 versions of OpenCV installed via homebrew: 3.4.1_2 and also 3.3.0_3 which is likely the cause of your compilation woes. Perhaps running `brew cleanup opencv` might help resolve? Please give that a try.

**Comment by deadprogram** [comment]
Also, make sure that you have run `source $GOPATH/src/gocv.io/x/gocv/env.sh` before trying to run any gocv code. You need to do this one time per terminal session, in order to setup the needed ENV vars for CGo.

**Comment by mmerlange** [comment]
oh my god ! It works. Thanks a lot deadprogram ! I'm ready to play :)
