### ISSUE TITLE
cgo clang linker issue on macOS

### ISSUE THREAD

**Issue by milosgajdos83** [hybridgroup/gocv#129]
I tried to follow the Getting Started guide step by step but when I attempted to run the first ["print the lib version"] example on `macOS` I get the following `cgo` linker errors:

```
$ go run ./cmd/version/main.go
# runtime/cgo
clang: error: /usr/local/Cellar/opencv/3.4.1_2/include: 'linker' input unused [-Werror,-Wunused-command-line-argument]
clang: error: /usr/local/Cellar/opencv/3.4.1_2/include/opencv2: 'linker' input unused [-Werror,-Wunused-command-line-argument]
```

`macOS` version:
```
macOS Sierra
10.12.6 (16G1212)
```

I'm wondering if this has something to do with particular `go` version I'm trying to run this example with:
```
$ go version
go version go1.10 darwin/amd64
```

Or maybe it is a `clang` version issue:
```
$ clang --version
Apple LLVM version 9.0.0 (clang-900.0.39.2)
Target: x86_64-apple-darwin16.7.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

`OpenCV` version:
```
$ brew info opencv
opencv: stable 3.4.1 (bottled)
Open source computer vision library
https://opencv.org/
/usr/local/Cellar/opencv/3.4.0_1 (531 files, 97.7MB)
  Poured from bottle on 2018-02-18 at 01:40:53
/usr/local/Cellar/opencv/3.4.1_2 (558 files, 98.6MB) *
  Poured from bottle on 2018-03-09 at 16:03:28
```

`XCode` version:
```
XCode:
Version 9.2 (9C40b)
```

I would appreciate any pointers to how can I fix these errors.

**Comment by willdurand** [comment]
You have two version of `opencv` installed and this is not supported yet. You should:

1. run `brew cleanup opencv` to keep the latest `opencv` version
2. run `source path/to/env.sh` again

**Comment by milosgajdos83** [comment]
Removing older version of `opencv` solved the issue.

Thanks!
