### ISSUE TITLE
Use astyle to auto-format C/C++ code

### ISSUE THREAD

**Issue by willdurand** [hybridgroup/gocv#131]
In order to keep/improve consistency on the C/C++ code of this project, I'd like to suggest [astyle](http://astyle.sourceforge.net/) to automatically format our files, just like we do for the Go part.

It could be an optional dev dependency, the only thing needed would be a new config file `.astylerc` with the following content:

<code snippet redacted, see #133>

I tried to use it locally and it does not change everything, so I guess the config is quite accurate (comes from more or less what Google uses).

WDYT?

**Comment by berak** [comment]
* pro:
1. uniform style

* contra:
1. we should focus more on making gocv more usable, not so much on code formatting of implementation details
2. requires anyone trying to contribute , to install another tool, also an additional local build step, slowing down development
3. your "conventions" might not be mine, useless flame-war guaranteed (2-spaces indent ? please, no!)

<br>

maybe it's a better idea, not to do this locally, but on the whole codebase, e.g. before a  release ?

**Comment by willdurand** [comment]
Indeed, I don't expect random contributors to run astyle but for us, yes. I disagree with your focus on feature though, it is not mutually exclusive, especially with a tool and it is easier to fix a small code base than a big one.

As for 2 vs 4 spaces, I don't care but 2 spaces was used in this project.

**Comment by berak** [comment]
@willdurand , i have to apologize here for taking you for an arbitrary gramma nazi before.
your phd is about scaling (hopefully) large systems, all that nitpicking all makes more sense, now ;)

(my problem is more a "down-to-earth-one". i need to move from python to *something-else* as soon as possible. lot of webserver related stuff, and recent pip bindings all need X-window, also noone wants to write a webserver in c++)

we could be a great team !

**Comment by berak** [comment]
@willdurand , "focus on feature"  
please try to understand  the "other side of the table".
most gocv users will be noobs to opencv (and probably go, too !), 
and if this library wants to thrive, it has to solve *their* problem, not ours (aka devs), in the 1st place..

here's a little challenge for you, should you care to accept it...
(i hope, you're not old enough for the tv reference, sadly i am ...):

there's this funny little image: ![yikes, it's the opencv logo!](http://answers.opencv.org/m/opencv/media/images/logo.png?v=6)

your task would be, to locate the centers of the 3 (broken) circles, it's a typical opencv noob job.

using, gocv, ofc !
given a phd, it should not take more than 20 minutes, right ? `</sarcasm>`

some hints, typical attempts would use:
* SimpleBlobDetector (it has builtin means to find "circular" things)
* connectedComponents (withStats)
* houghCircles
* findContours/moments

**Comment by willdurand** [comment]
@berak what are you trying to prove with this M:I challenge?

**Comment by berak** [comment]
focus on users, not devs, maybe.

but really, *try* to solve it !

**Comment by willdurand** [comment]
I have to learn opencv first :)

**Comment by berak** [comment]
k.k. let's cut it short.

the 1st 3 things won't work at all:
* SimpleBlobDetector would need it's Params, not implemented
*  connectedComponents does not exist (save the "withParams" extension, which would give you at least a bbox
*  and houghCircles is useless, if you can't specify min/max radius

do you get my point about usability vs. cpp code indentation ?

**Comment by willdurand** [comment]
I don't think I have ever been against usability, quite the contrary actually, and that's likely why you think I am a "grammar nazi" or whatever you called me when I reviewed your great PRs and cared about documentation. That's the first thing users see and read. I started learning opencv with this lib, half a day after I was contributing functions I needed to do what I wanted to achieve with opencv.

I'll continue to contribute code but my experience showed me that technical debt is by no mean fun and should not be neglected. I get that you need this lib to do whatever you have to do at work, but that's open source and I can decide what I think is best to contribute, according to... me.

In that specific case (i.e. this issue), I suggested to give more love to the C code since adding more code will be easier once we all follow the same rules. Feel free to disagree, it took me 30min to find the right tool, another 30min to configure it and to apply it on this project. I found `astyle`, which I did not know before, but I am glad to have discovered it since I will be able to tell my clients about it in the future.

In #137, I question the current design because, as a user and Go developer, I am not used to the API this library offers me. Then again, feel free to disagree. We can either talk about it publicly and decide to do something or not before `1.0.0` is released or leave it "as is" and get stuck in 6 months with +150% LOC and no way to introduce BC breaks.

As La Fontaine said, "Rien ne sert de courir, il faut partir à point" (slow and steady wins the race).

PS: While you are at it, you should open issues for each usability bug you found in the functions you mentioned.

**Comment by berak** [comment]
* "grammar nazi" -- i apologized , before
* astyle -- great tool, great idea, but you want to weight the significance of "usability vs ??" again.
* I suggested to give more love to the C code -- do you care about *efficiancy* ?
( maybe , there could be an easy:
     #ifdef __cplusplus
        
typedef std::vector<cv::Mat> vector_Mat
#else  
    typedef void* vector_Mat
#endif

**Comment by berak** [comment]
as long, as you don't have any "domain knowledege" on the library you're trying to contrib to, you'll have to face the "grammar nazi" tag. 
(and i apologized before)

in the long run, count me out. this will be always a "toy" lib, as long as *you* are hindering any progress.

**Comment by deadprogram** [comment]
Friends, we can certainly accommodate these concerns with good planning and communication. Different contributor priorities help make for more robust designs and implementations, IMO.

**Comment by deadprogram** [comment]
So, having some auto-format that the core maintainers can use to cleanup the C++ code seems like a good idea. Good thought to not require it as a build step in the CI build, so we do not force devs to install C++ toolchain items that they may not have, unlike `gofmt` which they will have installed. This also allows contributors who just want to help implement some functionality they need for a particular purpose to avoid going down that rabbit hole.

The 2-space indent is just an artifact of an editor config, not even a particular opinion. This PR could be a good place to change that.

In any case, improving the functionality, and also proivding some tooling to keep code standards to help contributors, are not mutually exclusive concerns, and I an certain that the project can accommodate both!

**Comment by willdurand** [comment]
I switched to 4 spaces in https://github.com/hybridgroup/gocv/pull/133 (which is good to review btw).

**Comment by willdurand** [comment]
closing now.
