### ISSUE TITLE
Convert RGB image to BGR

### ISSUE THREAD

**Issue by milosgajdos83** [hybridgroup/gocv#132]
How does one go about converting `RGB` image to `BGR`?

I tried to write a simple program which does just that, but since there is no [obvious] `ColorConversionCode` for this transformation like there is one in OpenCV (`CV_BGR2RGB`) I figured I'd try either of `ColorRGBToBGR565` or `ColorRGBToBGR555`.

The test program is super simple:

```go
package main

import (
	"fmt"
	"os"

	"gocv.io/x/gocv"
)

func main() {
	imgPath := "pizza.png"
	// read in an image from filesyste,
	img := gocv.IMRead(imgPath, gocv.IMReadColor)
	if img.Empty() {
		fmt.Printf("Could not read image %s\n", imgPath)
		os.Exit(1)
	}
        imgCopy := img.Clone()
	// Convert BGR to RGB image
	gocv.CvtColor(img, imgCopy, gocv.ColorBGRToRGB)
        // Convert back from RGB to BGR
	foo := gocv.NewMat()
	gocv.CvtColor(imgCopy, foo, gocv.ColorRGBToBGR565)
	// Write BGR image to filesystem
        gocv.IMWrite("foo.jpeg", foo)
}
```

Is there any way to convert `RGB` image back to `BGR` one so the image saved by `IMWrite()` is saved with the correct channel ordering?

**Comment by berak** [comment]
maybe you only [missed it](https://github.com/hybridgroup/gocv/blob/e287c967cda307b2d9e042bfeacac51f854a7020/imgproc_colorcodes.go#L24) ?

**Comment by milosgajdos83** [comment]
Uh, so embarrassing. Better get me a pair of glasses o_O

Thanks @berak 

Is there any slack channel or some kinda chat for `gocv` user? I bet there is one, only my blind eyes can't find any mention of it anywhere 😇

**Comment by berak** [comment]
no idea about slack channels. 

go and found one ?

**Comment by willdurand** [comment]
Can we start a gitter channel instead? cc @deadprogram

**Comment by milosgajdos83** [comment]
That would be dope @willdurand  -- I guess I need to read up on `C++` bindings first, because `gocv` essentially adds a `Go` thing layer on top of it -- I had anticipated `Python`-ish sort of UX 😇

But having a place where one can ask n00b questions would be ace!
