### ISSUE TITLE
Makefile upgrade task

### ISSUE THREAD

**Issue by deadprogram** [hybridgroup/gocv#140]
We need to add an upgrade task to the Makefile so we do not leave the target machine in a state with 2 different versions of OpenCV installed.

**Comment by deadprogram** [comment]
Now that the `Makefile` is stabilized, perhaps we can implement this now. @maruel what do you think?

**Comment by maruel** [comment]
upgrade: download build sudo_install clean verify

but the trick would be to query the current version and not upgrade if not necessary. In practice, it can be

OPENCV_VERSION=3.5.8 make install

**Comment by maruel** [comment]
change the "install" dependency order to uninstall before installing? Or make sudo_install to always force reinstall?

**Comment by deadprogram** [comment]
A manual make uninstall task also will need to remove the pkg-config file `opencv.pc` which on my Ubuntu installation is located at `/usr/local/lib/pkgconfig\opencv.pc`.

**Comment by deadprogram** [comment]
I think this has been addressed some time ago, so closing.
