### ISSUE TITLE
Hi, can I know the roadmap for gocv? Is it going to be actively maintained?

### ISSUE THREAD

**Issue by yxchng** [hybridgroup/gocv#144]
Hi, can I know the roadmap for gocv? Is it going to be actively maintained?

**Comment by deadprogram** [comment]
Hello @yxchng please check out https://github.com/hybridgroup/gocv/blob/master/ROADMAP.md

So far the community has been very active at contributing to the project. Only time can tell, but it seems like the future is bright.

Hope that helps!

**Comment by deadprogram** [comment]
I will close this issue now, please reopen if you have further questions.
