### ISSUE TITLE
Motion Tracking

### ISSUE THREAD

**Issue by IaBurton** [hybridgroup/gocv#15]
Hi there! Thanks for the great package, I've been using it recently in a Raspberry Pi project and had a couple of questions.

While trying to get basic motion detection working on a Pi Zero W with the pi camera I noticed that the face detect easily consumed 100% cpu and would result in less than 1 frame per second (even at only 640x480 resolution). I've since looked into implementing algorithms akin to https://www.pyimagesearch.com/2015/05/25/basic-motion-detection-and-tracking-with-python-and-opencv/ since I don't really need to detect faces, just motion, but seem to be missing some functions (like threshold, contours, etc). I'm not sure if it's an OpenCV 2 vs 3 thing (this is my first attempt at really using OpenCV) but I was curious as to how motion tracking could be implemented given the functions/bindings that are available? I noticed that there are "trackers" in OpenCV 3 as well but couldn't tell if they were available in this Go package. Thanks again!

**Comment by deadprogram** [comment]
Hi @IaBurton sounds like you are doing some cool things with GoCV. I checked out the link you provided, and seems like there are a few OpenCV functions used in that Python code from OpenCV's `imgproc` module that are not yet wrapped up in GoCV. 

Specifically:

- cv::threshold()
https://docs.opencv.org/3.3.0/d7/d1b/group__imgproc__misc.html#gae8a4a146d1ca78c626a53577199e9c57
- cv::findContours()
https://docs.opencv.org/3.3.0/d3/dc0/group__imgproc__shape.html#ga17ed9f5d79ae97bd4c7cf18403e1689a
- cv::contourArea()
https://docs.opencv.org/3.3.0/d3/dc0/group__imgproc__shape.html#ga2c759ed9f497d4a618048a2f56dc97f1
- cv::boundingRect()
https://docs.opencv.org/3.3.0/d3/dc0/group__imgproc__shape.html#gacb413ddce8e48ff3ca61ed7cf626a366

By implementing these wrappers, then seems like the Golang version of that code would be very easily doable. I'd be delighted to accept a PR that added them, and/or to help out myself when I get a chance.

**Comment by deadprogram** [comment]
These four functions have now been added to the `dev` branch, for anyone who wants to try using them.

**Comment by deadprogram** [comment]
Hello @IaBurton I've added a command example `motion-detect` loosely based on the code you mentioned. It is in the `dev` branch here: https://github.com/hybridgroup/gocv/blob/dev/cmd/motion-detect/main.go

I will close this issue once the new version of GoCV with these changes is released, which will probably be either today or tomorrow.

**Comment by IaBurton** [comment]
Hey @deadprogram, sorry about the silence, I actually left on vacation shortly after creating the issue, and wont be back for another couple of weeks still :)

Thank you for adding these functions, and so quickly, I'll be sure to play around with them when I get a chance and report back!

**Comment by deadprogram** [comment]
I ended up changing a bunch of the logic to use MOG2 instead of the more static first frame technique. In any case, I will close this issue now, please reopen if needed.
