### ISSUE TITLE
[Question] How to mask a coloured image

### ISSUE THREAD

**Issue by milosgajdos83** [hybridgroup/gocv#152]
So I've been playing around with `gocv` past few days learning the api and documenting it [here](https://github.com/milosgajdos83/gocv-playground), but I still can't seem to find a way to apply a mask (i.e. bitwise operation) to a coloured image.

What I end up doing is iterating over all image channels i.e. something like this:
```go
// get some mask
mask := gocv.NewMat()
gocv.Threshold(img, mask, 10.0, 255.0, gocv.ThresholdBinary)
// apply the mask on image
channels := gocv.Split(img)
for i := 0; i < len(channels); i++ {
        gocv.BitwiseAnd(channels[i], mask, channels[i])
}
gocv.Merge(channels, img)
```
Is there a better way to go about this? If not, it would be dope to have `gocv.BitwiseAnd` do the "heavy lifting" of `for` loop across all source image channels. I'd be happy to open a PR for this, but don't want to do some work that might not be necessary if there is some part of api that does this already, but keeps slipping my attention.

**Comment by milosgajdos83** [comment]
Yes, I'm familiar with `CopyToWithMask`, but even that function doesn't quite cut it in terms of ease of use with it when it comes to masking colored images:

* It expects the mask to be the same size as the source image. This is ok wrt the pixel size, but the mask also needs to have 3 channels if you wan to use it to mask a coloured image i.e. you can't pass in 1D mask to `CopyToWithMask`: Python API `cv2.bitwise_and` is way more convenient as it handles the multi channel case for you (I'm guessing there is some `numpy` broadcasting happening over all channels).  So you need to do `gocv.Merge([]gocv.Mat{mask, mask, mask, yourMask})` to create a mask which you can actually pass in as a parameter to `CopyToWithMask`.  

* Furthermore the function itsel doesn't quite behave as expected. Consider the following part of the [code](https://github.com/milosgajdos83/gocv-playground/blob/master/02_Airthmetics/main.go#L46-L60) in my playground repo. Corresponding replacement code that uses `CopyToWithMask` would look like this:

```go
// apply inverse mask on roi of messi image
roiMask := gocv.NewMat()
gocv.Merge([]gocv.Mat{maskInv, maskInv, maskInv}, roiMask)
roi.CopyToWithMask(roi, roiMask)
// apply the mask on logo image
logoMask := gocv.NewMat()
gocv.Merge([]gocv.Mat{mask, mask, mask}, logoMask)
logo.CopyToWithMask(logo, logoMask)
```

However, this code doesn't seem to do the same thing that the looping and `BitwiseAnd`-ing [code](https://github.com/milosgajdos83/gocv-playground/blob/master/02_Airthmetics/main.go#L46-L60) over all of the channels does. I might be missing something fundamental about how to actually use `CopyToMask` (check out the output image produced by both codes).

**Comment by deadprogram** [comment]
The GoCV implementation of `BitwiseAnd()` just wraps `cv::bitwise_and()`

https://docs.opencv.org/3.4.1/d2/de8/group__core__array.html#ga60b4d04b251ba5eb1392c34425497e14

Looks like you might be describing the second case in `cv::bitwise_and()`

"An array and a scalar when src2 is constructed from Scalar or has the same number of elements as src1.channels():"

Perhaps passing your desired mask second param to `BitwiseAnd()` as a Mat with number of elements same as number of channelsin `logo` will do what you expect?

**Comment by milosgajdos83** [comment]
Yes, that does the job indeed. Thanks! Can't believe I miss that - it seems pretty obvious now - I guess I just got hung up on using `CopyToMask ` and didnt realize I can do the same trick with `BitwiseAnd`.

Speaking of `Bitwise*` operations/functions, it would be nice to have them apply these ops across all image channels i.e. it would be user friendlier.

Finally, what does `CopyToMask` do then, if you dont mind me asking?

**Comment by deadprogram** [comment]
Seems like used to choose which elements to copy, not a mask to apply to the results:

https://docs.opencv.org/3.4.1/d3/d63/classcv_1_1Mat.html#a626fe5f96d02525e2604d2ad46dd574f
