### ISSUE TITLE
wrapped imencode with params ?

### ISSUE THREAD

**Issue by hurkgu** [hybridgroup/gocv#153]
hello ,
I am wrapped imencode with params from https://docs.opencv.org/master/d4/da8/group__imgcodecs.html#ga461f9ac09887e47797a54567df3b8b63

 imgcodecs.cpp:
`

struct ByteArray Image_IMEncodeParams(const char* fileExt, Mat img, IntVector params) {

    std::vector<uchar> data;

    std::vector<int> compression_params;

    for(int i = 0, *v = params.val; i < params.length; ++v, ++i) {
        compression_params.push_back(*v);
    }

    cv::imencode(fileExt, *img, data, compression_params);
    return toByteArray(reinterpret_cast<const char*>(&data[0]), data.size());
}`

imgcodecs.go
`// IMEncodeParams .

func IMEncodeParams(fileExt FileExt, img Mat, params []int) (buf []byte, err error) {

	cfileExt := C.CString(string(fileExt))
	defer C.free(unsafe.Pointer(cfileExt))
	cparams := []C.int{}
	for _, v := range params {
		cparams = append(cparams, C.int(v))
	}

	paramsVector := C.struct_IntVector{}
	paramsVector.val = (*C.int)(&cparams[0])
	paramsVector.length = (C.int)(len(cparams))

	b := C.Image_IMEncodeParams(cfileExt, img.Ptr(), paramsVector)
	defer C.ByteArray_Release(b)
	return toGoBytes(b), nil
}`

but it may throw panic with the same image when convert to webp,but sometimes it's ok

`OpenCV Error: Assertion failed (code) in imencode, file /root/opencv-3.3.1/modules/imgcodecs/src/loadsave.cpp, line  899
terminate called after throwing an instance of 'cv::Exception'
  what():  /root/opencv-3.3.1/modules/imgcodecs/src/loadsave.cpp:899: error: (-215) code in function imencode
SIGABRT: abort
PC=0x7f93816bc6a0 m=4 sigcode=18446744073709551610
signal arrived during cgo execution

goroutine 53 [syscall, locked to thread]:
runtime.cgocall(0x849ea0, 0xc421cbeb18, 0xc420c00100)
	/usr/local/go/src/runtime/cgocall.go:131 +0xe2 fp=0xc421cbead0 sp=0xc421cbea90
gocv.io/x/gocv._Cfunc_Image_IMEncodeParams(0x7f9360026a40, 0x7f936010bf10, 0xc420c00870, 0x2, 0x0, 0x0)
	gocv.io/x/gocv/_obj/_cgo_gotypes.go:1190 +0x57 fp=0xc421cbeb18 sp=0xc421cbead0
gocv.io/x/gocv.IMEncodeParams.func2(0x7f9360026a40, 0x7f936010bf10, 0xc420c00870, 0x2, 0x0, 0x0)`

Could you give me some help?
thanks!

**Comment by deadprogram** [comment]
Hello @hurkgu the code got a little scrambled up. Perhaps you have a repo? In any case, I have not done a lot with the WEBP encoding, but if it works sometimes but not all the time, but with the same params, that seems like an OpenCV issue perhaps? Not sure.

You probably should make sure you are using the latest OpenCV if possible. From your code sample, it appears you are using OpenCV 3.3.1.

**Comment by deadprogram** [comment]
Hello @hurkgu were you ever able to get further information on this issue?

**Comment by deadprogram** [comment]
Closing due to age. Please reopen if needed.
