### ISSUE TITLE
Alpine support

### ISSUE THREAD

**Issue by denismakogon** [hybridgroup/gocv#154]
So, there's a certain amount of work needs to be done to support alpine builds.

**Comment by willdurand** [comment]
I dont think it is in the scope of this Golang lib. You can use the official Golang alpine image: https://hub.docker.com/_/golang/ as a base image and install OpenCV. There are various Docker images for OpenCV + alpine for inspiration.

**Comment by deadprogram** [comment]
If there are any differences in install paths for OpenCV for Alpine there *might* need to be modifications to the `env.sh` file once OpenCV/GoCV is installed here:

https://github.com/hybridgroup/gocv/blob/master/env.sh#L23-L27

**Comment by denismakogon** [comment]
There is one more thing, a configuration in Makefile (plus docker support, i.e. no sudo) for apk.

**Comment by deadprogram** [comment]
@denismakogon would be be willing/able to submit a PR with that, now that the `Makefile` is a bit more stable?

**Comment by denismakogon** [comment]
yeah, i already did builds for https://github.com/denismakogon/gocv-alpine.

there's more, i'd like to add video support to builds here as well

**Comment by deadprogram** [comment]
@denismakogon this is really cool work. Perhaps we can add something to the docs to refer people to your repo?

**Comment by deadprogram** [comment]
I've just added reference to this in both the README and on the GoCV site. Now closing.
