### ISSUE TITLE
Image serialization/deserialization problems

### ISSUE THREAD

**Issue by denismakogon** [hybridgroup/gocv#155]
So, here's the thing. I can load an image successfully from the file path. But can't create a new image from  serialized one

Here's the code:
```go
package main

import (
	"gocv.io/x/gocv"
	"fmt"
)

var HaarPath = "/function/haarcascade_frontalface_default.xml"

func pv(m gocv.Mat) *gocv.Mat {
	return &m
}

func main() {

	m := gocv.IMRead("/function/happy.jpg", gocv.IMReadUnchanged)

	newM := gocv.IMDecode(pv(m).ToBytes(), gocv.IMReadColor)
	classifier := gocv.NewCascadeClassifier()
	defer classifier.Close()
	if !classifier.Load(HaarPath) {
		fmt.Printf("Error reading cascade file: %v\n", HaarPath)
		return
	}
	rects := classifier.DetectMultiScale(m)
	fmt.Printf("found %d faces\n", len(rects))

	rects = classifier.DetectMultiScale(newM)
	fmt.Printf("after decoding found %d faces\n", len(rects))
}
```
So, the result is:
```
found 1 faces
after decoding found 0 faces
```
My assumotion is that images should be semantically equal.

**Comment by deadprogram** [comment]
Hello @denismakogon that certainly seems like it should be the case. Thanks for investigating, anyone else have any specific ideas on this?

**Comment by willdurand** [comment]
could it be because the type might be different in `IMDecode()`?

**Comment by deadprogram** [comment]
That seems like worth verifying. Good idea @willdurand

**Comment by deadprogram** [comment]
Anything ever happen on testing this specific case?

**Comment by denismakogon** [comment]
Not on my side.

**Comment by berak** [comment]
@denismakogon ,

> My assumotion is that images should be semantically equal.

no, it is not so (and there is no bug).

imread() already decodes the image, it strips the headers / exif, and decompresses the image.

you would use imdecode() for a byte buffer straight from disk, not on already decoded image.

**Comment by deadprogram** [comment]
Thanks for clarifying @berak that makes perfect sense. Now closing, thank you!
