### ISSUE TITLE
update for opencv 3.3.1

### ISSUE THREAD

**Issue by tmc** [hybridgroup/gocv#16]

**Comment by deadprogram** [comment]
Hi @tmc thanks for pinging on this. We'll get a new release out today, hopefully.

**Comment by deadprogram** [comment]
The `dev` branch https://github.com/hybridgroup/gocv/tree/dev now has been updated for OpenCV 3.3.1, for anyone who wants to try it out before the update.

**Comment by deadprogram** [comment]
This code has now been released as part of v0.3.1. Now closing.
