### ISSUE TITLE
Calib wrappers

### ISSUE THREAD

**Issue by kylycht** [hybridgroup/gocv#160]
Hello, I have been wondering if anyone is already working on? 
https://docs.opencv.org/trunk/db/d58/group__calib3d__fisheye.html

I can try to do pr

**Comment by deadprogram** [comment]
Please do!

**Comment by deadprogram** [comment]
Hi @kylycht did you ever have a chance to work on this? :)

**Comment by kylycht** [comment]
@deadprogram hi, I have started it and covered few functions, but sadly did not get chance to cover more(currently busy with other projects). I will try to add some tests and do PR this weekend with what I have.

**Comment by deadprogram** [comment]
Thanks @kylycht

**Comment by deadprogram** [comment]
Ping! :)

**Comment by kylycht** [comment]
sorry for such a delay, here is a small PR 

https://github.com/hybridgroup/gocv/pull/226

I could not cover all module and removed some untested code(kept in history)

Basically, results are:
![fisheye_sample-up](https://user-images.githubusercontent.com/16954693/41093197-a2d94730-6a85-11e8-9c8b-2d4653d71763.jpg)
![fisheye_sample](https://user-images.githubusercontent.com/16954693/41093198-a301460e-6a85-11e8-8457-d6db4d79cb31.jpg)

Thanks for the awesome repository, I will try to contribute as much as I can.

**Comment by deadprogram** [comment]
Thanks for your PR @kylycht I have merged it into `dev` branch. Also, I have updated the ROADMAP doc here: https://github.com/hybridgroup/gocv/blob/dev/ROADMAP.md

**Comment by deadprogram** [comment]
This code is now released as part of v0.14.0 so closing. Thank you again!
