### ISSUE TITLE
Make fail on ubuntu 17.10

### ISSUE THREAD

**Issue by muka** [hybridgroup/gocv#162]
Hi
`make install` fails on ubuntu 17.10 and fallback to fedora(?) `dnf` install. I do know if would make sense to handle this also for ubuntu 18 which is going to  be released

Also `libjasper-dev` is unavaliable in ubuntu after 17.04
A workaround is here https://stackoverflow.com/a/48326450/833499

```
sudo add-apt-repository "deb http://security.ubuntu.com/ubuntu xenial-security main"
sudo apt update
sudo apt install libjasper-dev
```

Thanks!

**Comment by Auenc** [comment]
Also occurs on Ubuntu 16.04

**Comment by deadprogram** [comment]
Any one able to create a PR with changes to the Makefile to accommodate this?

**Comment by maruel** [comment]
I think disabling jpeg2000 support in opencv is a saner solution (nobody uses this format) than modifying the host's apt configuration to fetch from old releases (and not a backport proper).

Testing locally with `sudo apt remove libjasper-dev` then doing a full rebuild with `WITH_JASPER=OFF`

**Comment by muka** [comment]
Yes I agree, your solution is saner definitely!

sent from my phone

Il mar 1 mag 2018, 14:36 M-A <notifications@github.com> ha scritto:

**Comment by hubyhuby** [comment]
+1
I can confirm the same issue on my Ubuntu 17.10
make deps
make deps_fedora
sudo: dnf: command not found
Makefile:32: recipe for target 'deps_fedora' failed
make[1]: *** [deps_fedora] Error 1

...

**Comment by deadprogram** [comment]
Using the `dev` branch, @hubyhuby or the `master`?

**Comment by gibeautc** [comment]
With 18.04 the Makefile seems to think the system is Fedora..... allthought it seems the commands the Makefile uses are still returing correclty.  I was able to modifiy it,and removed the install of of jasper-dev, now stuck on 
/sbin/ldconfig.real: /usr/local/lib/libhidapi-libusb.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libhidapi-hidraw.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/lib/libhidapi-libusb.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/lib/libhidapi-hidraw.so.0 is not a symbolic link

comes up for both make deps, and make build
