### ISSUE TITLE
Intel Deep Learning Inference Engine samples Support

### ISSUE THREAD

**Issue by antoniomtz** [hybridgroup/gocv#170]
Are you guys considering integration of the Intel Deep Learning Inference Engine ?

https://software.intel.com/en-us/inference-engine-devguide-using-sample-applications 

Thanks

**Comment by deadprogram** [comment]
Yes, absolutely.

**Comment by deadprogram** [comment]
To track the work in progress happening on this, please follow the https://github.com/hybridgroup/gocv/tree/feature/openvino-ie-support branch.

**Comment by antoniomtz** [comment]
@deadprogram Oh yeah, I've been following that branch already :) good job. Thanks.

**Comment by deadprogram** [comment]
This code is now released as part of v0.14.0 so closing. Thank you!
