### ISSUE TITLE
Prevent gocv.VideoWriterFile from panic if numerical parameters are empty

### ISSUE THREAD

**Issue by denismakogon** [hybridgroup/gocv#186]
It's definitely my fault, but would be nice to prevent code from doing panic.
Here's the case:
```
OpenCV(3.4.1) Error: Assertion failed (result || fps != 0) in cvCreateVideoWriterWithPreference, file /tmp/opencv/opencv-3.4.1/modules/videoio/src/cap.cpp, line 389
terminate called after throwing an instance of 'cv::Exception'
  what():  OpenCV(3.4.1) /tmp/opencv/opencv-3.4.1/modules/videoio/src/cap.cpp:389: error: (-215) result || fps != 0 in function cvCreateVideoWriterWithPreference

```
Assume you have service A and service B. Service A sends a payload that containers a list of images (1 video second, i.e. 25 to 60 FPS). With a dummy payload check, service tries to define a new FPS fro video segment and somehow defines FPS as `0`.
So, when calling the following code:
```go
	writer, err := gocv.VideoWriterFile(
		tempVideoFileName, "MP4V",
		float64(len(framesReceived)),
		Dimensions["width"], Dimensions["height"])
```
where `float64(len(framesReceived))` is zero, code panis with hello of the output, which is quite not nice i suppose.

So, as a developer, I'd like to get the error if any of numerical parameters (FPS, width, height) is empty instead of panic.

**Comment by deadprogram** [comment]
The core issue is that OpenCV throws an exception instead of returning an error. In the case of Windows, this is a problem due to https://github.com/golang/go/issues/13672

@denismakogon seems like we can add our own validation code before calling into OpenCV, but we cannot really depend on OpenCV itself in this case.

What do you think?

**Comment by denismakogon** [comment]
Yeah, validation before passing values to OpenCV is what I’d like to see. Panic is a smash-hammer I really want to avoid.

**Comment by deadprogram** [comment]
Sounds good to me. PR, please? :smile_cat:

**Comment by denismakogon** [comment]
Sure, later today.
