### ISSUE TITLE
[feature] Get string representation of a video codec

### ISSUE THREAD

**Issue by denismakogon** [hybridgroup/gocv#192]
Assume you have a video file that has the following parameter(s):
 - codec: `H.264`

According to GoCV docs you can get video codec using the following code:
```
video.Get(gocv.VideoCaptureFOURCC)
```
which returns `float64`

There should be built-in method to get a video codec string representation. Unfortunately, there is no built-in feature in OpenCV except manual FOURCC parsing, so i suggest to make it available in GoCV:
```go
package main

import (
	"fmt"
)

func Codec(codecID int64) string {
	res := ""
	hexs := []int64{0xff, 0xff00, 0xff0000, 0xff000000}
	for i, h := range hexs {
		res += string(codecID & h >> (uint(i * 8)))
	}
	return res
}


func main() { 
	c := Codec(int64(828601953))
	fmt.Println(c)
}

```
Link: https://play.golang.org/p/5zmVJffYST9
This function turns FourCC into a sane representation of the codec that can be used later with video writer.

Proposed signature:
```go
func (v *VideoCapture) CodecString() string
```

Implementation:
```go
func (v *VideoCapture) CodecString() string {
	res := ""
	hexs := []int64{0xff, 0xff00, 0xff0000, 0xff000000}
	for i, h := range hexs {
		res += string(int64(v.Get(VideoCaptureFOURCC)) & h >> (uint(i * 8)))
	}
	return res
}
```

**Comment by deadprogram** [comment]
Seems like a very good idea to me!

**Comment by denismakogon** [comment]
closing one as done

**Comment by deadprogram** [comment]
I will close this issue after the next release. Thanks again @denismakogon
