### ISSUE TITLE
Building gocv package under visual studio code

### ISSUE THREAD

**Issue by Fookiwara** [hybridgroup/gocv#209]
Hello,
I cannot run my test application under Visual Studio Code.
I have the following error:
file not found: opencv2/opencv.hpp
Any idea?
Regards
Fooky

**Comment by deadprogram** [comment]
Please make sure that you follow the install instructions for your OS to install OpenCV https://github.com/hybridgroup/gocv/blob/master/README.md#how-to-install as well as the "How to go build/go run your code".

**Comment by Fookiwara** [comment]
I follow the instruction but it failed.
The exact error is: 
# gocv.io/x/gocv
In file included from core.cpp:1:0:
core.h:24:30: fatal error: opencv2/opencv.hpp: No such file or directory

**Comment by deadprogram** [comment]
You have to follow the instructions under "How to go build/go run your code" in the README for your platform.

**Comment by Fookiwara** [comment]
this instruction failed "go run .\cmd\version\main.go"
with the same error "No such file or directory"

**Comment by deadprogram** [comment]
Did you run `source ./env.sh` in your terminal as described here?

https://github.com/hybridgroup/gocv/blob/master/README.md#how-to-go-buildgo-run-your-code

**Comment by deadprogram** [comment]
Also how did you install OpenCV and what OS are you using?

**Comment by Fookiwara** [comment]
Yes I launch it and there were no error.
I follow the instructions here to install OpenCV: https://gocv.io/getting-started/windows/
OS: windows

**Comment by deadprogram** [comment]
Can you please elaborate on the comment "Yes I launch it and there were no error."? What did you launch?

**Comment by deadprogram** [comment]
For Windows, you need to follow these instructions: https://github.com/hybridgroup/gocv/blob/master/README.md#how-to-go-buildgo-run-your-code-2

Please note that the script `./env.cmd` has to be run one time per console session, not just once at the original installation time.

**Comment by Fookiwara** [comment]
I already did that :(

**Comment by golang2018** [comment]
You can run your vscode with root
source ./env.sh
/usr/share/code/code

**Comment by deadprogram** [comment]
Hi @Fookiwara 

What @golang2018 mentions is how I execute the VSCode editor. But I do not run the golang code within VSCode, I just use it as my editor. 

When I want to execute my Golang code, I switch over to a command line running at the same time in another window. In that other window, I have also run the `./env.cmd` script before running my GoCV code.

**Comment by Fookiwara** [comment]
@golang2018, my os is windows... Aren't the commands different to launch VScode? Do i have to use Powershell or commande line?

**Comment by golang2018** [comment]
@Fookiwara 
Adding CGO_CPPFLAGS=-IC:\opencv\build\install\include in env.cmd directly to the environment variable, and then starting vscode, is feasible.

**Comment by Fookiwara** [comment]
ok for creating a new environment variable manually:
CGO_CPPFLAGS=-IC:\opencv\build\install\include

But what do you mean by "in env.cmd directly"?

**Comment by Fookiwara** [comment]
I finally understand what you mean by using env.cmd.
I have another error while using mingw32-make: it concerns object... "opencv_dnn":
[ 60%] Building CXX object modules/dnn/CMakeFiles/opencv_dnn.dir/layers/layers_common.avx512_skx.cpp.obj
C:\Users\AHMAD-~1\AppData\Local\Temp\ccidPhmf.s: Assembler messages:
C:\Users\AHMAD-~1\AppData\Local\Temp\ccidPhmf.s:21800: Error: invalid register for .seh_savexmm
C:\Users\AHMAD-~1\AppData\Local\Temp\ccidPhmf.s:21802: Error: invalid register for .seh_savexmm
C:\Users\AHMAD-~1\AppData\Local\Temp\ccidPhmf.s:21804: Error: invalid register for .seh_savexmm
C:\Users\AHMAD-~1\AppData\Local\Temp\ccidPhmf.s:21806: Error: invalid register for .seh_savexmm
C:\Users\AHMAD-~1\AppData\Local\Temp\ccidPhmf.s:21808: Error: invalid register for .seh_savexmm
C:\Users\AHMAD-~1\AppData\Local\Temp\ccidPhmf.s:21810: Error: invalid register for .seh_savexmm
C:\Users\AHMAD-~1\AppData\Local\Temp\ccidPhmf.s:21812: Error: invalid register for .seh_savexmm
C:\Users\AHMAD-~1\AppData\Local\Temp\ccidPhmf.s:21814: Error: invalid register for .seh_savexmm
C:\Users\AHMAD-~1\AppData\Local\Temp\ccidPhmf.s:21816: Error: invalid register for .seh_savexmm
C:\Users\AHMAD-~1\AppData\Local\Temp\ccidPhmf.s:21818: Error: invalid register for .seh_savexmm
C:\Users\AHMAD-~1\AppData\Local\Temp\ccidPhmf.s:21820: Error: invalid register for .seh_savexmm
C:\Users\AHMAD-~1\AppData\Local\Temp\ccidPhmf.s:21822: Error: invalid register for .seh_savexmm
C:\Users\AHMAD-~1\AppData\Local\Temp\ccidPhmf.s:21824: Error: invalid register for .seh_savexmm
C:\Users\AHMAD-~1\AppData\Local\Temp\ccidPhmf.s:21826: Error: invalid register for .seh_savexmm
modules\dnn\CMakeFiles\opencv_dnn.dir\build.make:1015: recipe for target 'modules/dnn/CMakeFiles/opencv_dnn.dir/layers/layers_common.avx512_skx.cpp.obj' failed
mingw32-make[2]: *** [modules/dnn/CMakeFiles/opencv_dnn.dir/layers/layers_common.avx512_skx.cpp.obj] Error 1
CMakeFiles\Makefile2:3946: recipe for target 'modules/dnn/CMakeFiles/opencv_dnn.dir/all' failed
mingw32-make[1]: *** [modules/dnn/CMakeFiles/opencv_dnn.dir/all] Error 2
Makefile:161: recipe for target 'all' failed
mingw32-make: *** [all] Error 2
Any idea?

**Comment by deadprogram** [comment]
Looks like this https://stackoverflow.com/questions/49863632/opencv-3-4-1-error-invalid-register-for-seh-savexmm

**Comment by Fookiwara** [comment]
![sans titre](https://user-images.githubusercontent.com/37213073/40605285-24d7d8b8-6262-11e8-873f-247bf085c111.png)
It seems this option is deactivated....

**Comment by deadprogram** [comment]
That was the solution used for building GoCV on AppVeyor https://github.com/hybridgroup/gocv/commit/90df890c1308c5a425ea0241a739766ad942bb45

**Comment by Fookiwara** [comment]
thanks, i'm gonna try it now :)

**Comment by Fookiwara** [comment]
where can i find AppVeyor app?

**Comment by deadprogram** [comment]
Appveyor is the Windows CI system not an app.

**Comment by Fookiwara** [comment]
Windows CI system?

**Comment by deadprogram** [comment]
https://www.appveyor.com

https://en.m.wikipedia.org/wiki/Continuous_integration

**Comment by Fookiwara** [comment]
thanks.
Im not familiar with appveyor...
what's the simplest procedure to build opencv with appveyor?

**Comment by deadprogram** [comment]
I think perhaps there is some misunderstanding here. 

My point in the link to AppVeyor was that we are able to successfully build OpenCV and GoCV and then run the tests on our Windows-based CI.

In other words, it is "known to work on Windows". So it should be a matter of figuring out what is needed to build on your machine.

In the case of changing the CMake flag for `CPU_DISPATCH`, you will need to build OpenCV again on your machine once you change that setting.

**Comment by Fookiwara** [comment]
I finally found where the error comes from.
I launch cmake via command line:
cmake C:\opencv\opencv-3.4.1 -G "MinGW Makefiles" -BC:\opencv\build -DENABLE_CXX11=ON -DOPENCV_EXTRA_MODULES_PATH=C:\opencv\opencv_contrib-3.4.1\modules -DBUILD_SHARED_LIBS=ON -DBUILD_EXAMPLES=OFF -DBUILD_TESTS=OFF -DBUILD_PERF_TESTS=OFF -DBUILD_opencv_java=OFF -DBUILD_opencv_python=OFF -DBUILD_opencv_python2=OFF -DBUILD_opencv_python3=OFF -DBUILD_DOCS=OFF -DENABLE_PRECOMPILED_HEADERS=OFF -DBUILD_opencv_saliency=OFF -DCPU_DISPATCH= -Wno-dev
