### ISSUE TITLE
features2d.cpp:329:18: error: expected expression

### ISSUE THREAD

**Issue by TorettoLong** [hybridgroup/gocv#212]
hello  features2d.cpp:329:18: error: expected expression

gocv version: 0.12.0
opencv lib version: 3.4.1

**Comment by deadprogram** [comment]
Hi @TorettoLong how exactly did you receive that error? What code did you execute?

**Comment by TorettoLong** [comment]
@deadprogram run the demo of readme

**Comment by lpmrz** [comment]
I have the same problem. When I try to compile it with Visual Studio, I have this;

# gocv.io/x/gocv
features2d.cpp:329:18: error: expected expression
features2d.cpp:347:18: error: expected expression
exit status 2
Process exiting with code: 1

When I try to build it via terminal I get this;

features2d.cpp:329:18: error: expected expression
features2d.cpp:347:18: error: expected expression

**Comment by deadprogram** [comment]
Which OS and version of Go?

**Comment by lpmrz** [comment]
Os is Mac, but I don't know how to check the Go version.

By the way, I have reinstalled go and gocv. Now I have such an error;

go run ./cmd/version/main.go
 runtime/cgo
clang: error: /usr/local/Cellar/opencv/3.4.1_5/include: 'linker' input unused [-Werror,-Wunused-command-line-argument]
clang: error: /usr/local/Cellar/opencv/3.4.1_5/include/opencv2: 'linker' input unused [-Werror,-Wunused-command-line-argument]

**Comment by deadprogram** [comment]
Not sure on that one, perhaps you did not install Xcode or whatever compiler is needed on macOS. Last time I checked that was `xcode-select --install`

**Comment by lpmrz** [comment]
I have found my answer here;

https://github.com/hybridgroup/gocv/issues/129

Thanks though:)

**Comment by himanshusingh3011** [comment]
Hi, me also facing above error 
features2d.cpp:329:18: error: expected expression
features2d.cpp:347:18: error: expected expression

**Comment by deadprogram** [comment]
What OS?
What code did you try to run?
How did you install OpenCV?
What version of OpenCV?
Did you run the `env.sh` or `env.cmd` script before trying to `go run` or `go build`?

**Comment by himanshusingh3011** [comment]
macOS 10.13.3
Simply did "go build".
OpenCV with brew (version - 3.4.1)
No, did not run `env.sh` or `env.cmd`.

**Comment by himanshusingh3011** [comment]
Yeah, after running `source env.sh` command, it worked.
Thanks for help!

**Comment by deadprogram** [comment]
We just released v0.13.0 which removes the need to run `env.sh` or `env.cmd` unless you are using a custom build environment. That should help remove a lot of confusion when getting started with GoCV.

I am going to close this issue now, please reopen if needed. Thank you!
