### ISSUE TITLE
Mat.Foreach

### ISSUE THREAD

**Issue by Fookiwara** [hybridgroup/gocv#213]
Hello,

does mat.foreach exists in gocv?

in c++, it does:
cv::Mat img;
img.forEach<cv::Vec3w>
(
[](cv::Vec3w &pixel, const int * position) -> void
{
					pixel[0] = pixel[0] >> 2;
					pixel[1] = pixel[1] >> 2;
					pixel[2] = pixel[2] >> 2;
}
);

Regards

**Comment by deadprogram** [comment]
Hello @Fookiwara that is not one of the currently implemented functions. You might want to take a look at the Set/Get functions of Mat as an alternate implementation: https://godoc.org/gocv.io/x/gocv#Mat.SetDoubleAt

**Comment by Fookiwara** [comment]
Thanks.
How to change a pixel channels value R,G, B from mat?
I use this: 
v := img.GetVeciAt(x,y);
but does v[0] = new R

**Comment by milosgajdos83** [comment]
@Fookiwara this is roughly how you can change the values of pixel intensity in each colour channel of an image -- note the below code snippet is only for illustration purpose and it merely sets the value of *every pixel* in *every channel* 

```go
    // split image channels
    imgChans := gocv.Split(img)
    // iterate through image channels
    for c := 0; c < imgChans; c++ {
        for i := 0; i < rows; i++ {
            for j := 0; j < cols; j++ {
                // set pixel_intensity on channel "c"
                imgChans[c].SetUCharAt(i, j, uint8(pixel_intensity))
            }
        }
    }
    // merge the channels into new image
    newImg := gocv.NewMat()
    gocv.Merge(imgChans, &newImg)
```

**Comment by deadprogram** [comment]
Any further questions about this @Fookiwara or can we close this issue?

**Comment by Fookiwara** [comment]
Thanks!
