### ISSUE TITLE
Byte array to mat

### ISSUE THREAD

**Issue by theRoughCode** [hybridgroup/gocv#215]
Hi,  I'm currently trying to figure out GoCV's Resize function.  I have an image in a byte array;  I want to resize it and return a byte array of the resized array.  In order to use the Resize method, I have to have a Mat.  I tried the following:
```
mat, _ := gocv.IMDecode(b, gocv.IMReadUnchanged)
return mat.ToBytes()
```

However, this does not return the given image (returns a valid but corrupt image).  Where am I going wrong?

**Comment by theRoughCode** [comment]
Using `mat, err := gocv.NewMatFromBytes(w, h, gocv.MatTypeCV8U, b)` works, but I'm wondering why the above does not?

**Comment by deadprogram** [comment]
Hello @theRoughCode `gocv.IMDecode()` is intended to use for when you have a fully encoded image (for example a JPEG with all the headers) in a byte array, and want to turn it into a `Mat`. `gocv.NewMatFromBytes()` is intended for when you already have a `Mat` in a byte array, and want to read that into a `Mat`.

**Comment by theRoughCode** [comment]
Oh I see, thanks for the response!  It was not very intuitive working with GoCV so I've swapped over to another open-source openCV wrapper for now.  Maybe giving a full example of how to resize an image from a byte array in the docs would help the next person along?  GoCV is a great project, but I feel that it's documentation can be improved.
