### ISSUE TITLE
Q: Is it possible to use a lower version opencv?

### ISSUE THREAD

**Issue by fastfading** [hybridgroup/gocv#220]
In readme opencv lib version is 3.4.1
in ubuntu 18.04   
apt install libopencv-dev       would install version 3.2 
I wonder if gocv can use a lower version opencv?
Is there any problem ?

apt install package will be more simple than build install.
I wonder if this is OK?

**Comment by deadprogram** [comment]
The short version is that GoCV is intended to work with the latest OpenCV only. 

You'd be better off installing 3.4.1 it as a package from another package repo.
