### ISSUE TITLE
I am getting an error "eigenNonSymmetric is not a member of 'cv' "   at  core.cpp:344:9 

### ISSUE THREAD

**Issue by Kabariya** [hybridgroup/gocv#221]
I want to work on Opencv3 with Go-Lang. I have followed step according to http://gocv.io  I have installed it successfully but now I am getting an error "eigenNonSymmetric is not a member of 'cv' "   at  core.cpp:344:9  any help. And I am on Ubuntu 18.04

## Description

I am getting this error

# gocv.io/x/gocv
core.cpp: In function ‘void Mat_EigenNonSymmetric(Mat, Mat, Mat)’:
core.cpp:345:9: error: ‘eigenNonSymmetric’ is not a member of ‘cv’
     cv::eigenNonSymmetric(*src, *eigenvalues, *eigenvectors);
         ^~~~~~~~~~~~~~~~~

## Your Environment

* Operating System and version: Ubuntu 18.04
* OpenCV version used: 3.4.1
* How did you install OpenCV? according to gocv.io
* GoCV version used: latest
* Go version: 1.10.2
* Did you run the `env.sh` or `env.cmd` script before trying to `go run` or `go build`? no

**Comment by deadprogram** [comment]
Hello @Kabariya when you mention "have installed it successfully" how did you verify the OpenCV install? Also what code did you run to receive the error you describe?

**Comment by Kabariya** [comment]
well I verify it by python
$python
$>>> import cv2
$>>> cv2.__version__

and  output is 3.4.1 

and this error I am getting by running program which is inbuilt in 
/home/username/go/src/gocv.io/x/gocv/cmd/version/main.go

**Comment by deadprogram** [comment]
How exactly did you install GoCV? 
Can you run any other Go programs? 
What is the command you ran, and from what directory did you run it? 

The kind of error you describe is normally from not being able to locate either the include or lib files. The latest GoCV uses `pkg-config` to locate the files in their normally installed location on all OS which are supported.

**Comment by Kabariya** [comment]
I used command

go get -u -d gocv.io/x/gocv
cd $GOPATH/src/gocv.io/x/gocv
make deps
make download
make build

I ran in /home/username/go/src/gocv.io/x/gocv

yes I can run other Go program

**Comment by deadprogram** [comment]
What is your output from the following commands:

```
pkg-config opencv --cflags
```

and

```
pkg-config opencv --includes
```

**Comment by Kabariya** [comment]
okay wait i will tell you

**Comment by Kabariya** [comment]
where do I run this cmd. I mean which directory

**Comment by deadprogram** [comment]
That should not matter.

**Comment by Kabariya** [comment]
okay

**Comment by Kabariya** [comment]
FIRST 
-I/usr/include/opencv

SECOND
-lopencv_shape -lopencv_stitching -lopencv_superres -lopencv_videostab -lopencv_aruco -lopencv_bgsegm -lopencv_bioinspired -lopencv_ccalib -lopencv_datasets -lopencv_dpm -lopencv_face -lopencv_freetype -lopencv_fuzzy -lopencv_hdf -lopencv_line_descriptor -lopencv_optflow -lopencv_video -lopencv_plot -lopencv_reg -lopencv_saliency -lopencv_stereo -lopencv_structured_light -lopencv_phase_unwrapping -lopencv_rgbd -lopencv_viz -lopencv_surface_matching -lopencv_text -lopencv_ximgproc -lopencv_calib3d -lopencv_features2d -lopencv_flann -lopencv_xobjdetect -lopencv_objdetect -lopencv_ml -lopencv_xphoto -lopencv_highgui -lopencv_videoio -lopencv_imgcodecs -lopencv_photo -lopencv_imgproc -lopencv_core

**Comment by Kabariya** [comment]
hi, are you there? can you please reply?

**Comment by deadprogram** [comment]
You are missing the `-L` param for the linker to know in which directory to locate the lib files, which would normally be configured during installation.

For example:

```shell
$ pkg-config opencv --cflags
-I/usr/local/include/opencv -I/usr/local/include

$ pkg-config opencv --libs                                                                                                                        
-L/usr/local/lib -lopencv_videostab -lopencv_stitching -lopencv_superres -lopencv_face -lopencv_photo -lopencv_tracking -lopencv_datasets -lopencv_text -lopencv_fuzzy -lopencv_ccalib -lopencv_reg -lopencv_xobjdetect -lopencv_bioinspired -lopencv_xphoto -lopencv_dnn_objdetect -lopencv_dnn -lopencv_hdf -lopencv_hfs -lopencv_aruco -lopencv_surface_matching -lopencv_optflow -lopencv_plot -lopencv_freetype -lopencv_ximgproc -lopencv_structured_light -lopencv_phase_unwrapping -lopencv_stereo -lopencv_line_descriptor -lopencv_bgsegm -lopencv_xfeatures2d -lopencv_shape -lopencv_video -lopencv_ml -lopencv_img_hash -lopencv_dpm -lopencv_objdetect -lopencv_saliency -lopencv_rgbd -lopencv_calib3d -lopencv_features2d -lopencv_highgui -lopencv_videoio -lopencv_imgcodecs -lopencv_imgproc -lopencv_flann -lopencv_core
```

You will need to figure out where you installed OpenCV to, and set the `-L` flag for the linker appropriately. Take a look at the section https://github.com/hybridgroup/gocv/blob/master/README.md#custom-environment for more information.

Hope that helps!

**Comment by Kabariya** [comment]
O followed the gocv.io so do you know any command through which i can know where it is installed and if you don't know then do you know how to set -L  flag? actually i am new to all of these :)

**Comment by deadprogram** [comment]
Given the info returned by your previous response, I'd probably try this:

```shell
export CGO_CXXFLAGS="--std=c++11"
export CGO_CPPFLAGS="-I/usr/include"
export CGO_LDFLAGS="-L/usr/lib -lopencv_videostab -lopencv_stitching -lopencv_superres -lopencv_face -lopencv_photo -lopencv_tracking -lopencv_datasets -lopencv_text -lopencv_fuzzy -lopencv_ccalib -lopencv_reg -lopencv_xobjdetect -lopencv_bioinspired -lopencv_xphoto -lopencv_dnn_objdetect -lopencv_dnn -lopencv_hdf -lopencv_hfs -lopencv_aruco -lopencv_surface_matching -lopencv_optflow -lopencv_plot -lopencv_freetype -lopencv_ximgproc -lopencv_structured_light -lopencv_phase_unwrapping -lopencv_stereo -lopencv_line_descriptor -lopencv_bgsegm -lopencv_xfeatures2d -lopencv_shape -lopencv_video -lopencv_ml -lopencv_img_hash -lopencv_dpm -lopencv_objdetect -lopencv_saliency -lopencv_rgbd -lopencv_calib3d -lopencv_features2d -lopencv_highgui -lopencv_videoio -lopencv_imgcodecs -lopencv_imgproc -lopencv_flann -lopencv_core"
go run -tags customenv ./cmd/version/main.go
```

**Comment by Kabariya** [comment]
okay
let me try

**Comment by Kabariya** [comment]
well that errors are gone but i got new error ): 
# runtime/cgo
/usr/bin/x86_64-linux-gnu-ld: cannot find -lopencv_tracking
/usr/bin/x86_64-linux-gnu-ld: cannot find -lopencv_dnn_objdetect
/usr/bin/x86_64-linux-gnu-ld: cannot find -lopencv_dnn
/usr/bin/x86_64-linux-gnu-ld: cannot find -lopencv_hfs
/usr/bin/x86_64-linux-gnu-ld: cannot find -lopencv_xfeatures2d
/usr/bin/x86_64-linux-gnu-ld: cannot find -lopencv_img_hash
collect2: error: ld returned 1 exit status

**Comment by deadprogram** [comment]
Looks like your install of opencv was incomplete. Those are all modules that should have been installed, according to your own `pkg-config` results, but that are apparently not installed form the error above.

Examples: 

- `libopencv_dnn` which is part of the main opencv package
- `libopencv_img_hash` which is part of opencv-contrib package

You might want to reinstall OpenCV. I would try to remove your previous installs first, just in case.

**Comment by Kabariya** [comment]
but  when i run on python it work below command. so do you mean that it could be possible that still it's not installed? 

import cv2
cv2.__version__

**Comment by Kabariya** [comment]
how to remove completely previous version of Opencv?  cz i have done it two or three times so if you know any trick so i can complitly remove it :)

**Comment by Kabariya** [comment]
or is there any way that i can get these library  from externally and i put it into that folder from where it is getting miss. Does it work?

**Comment by Kabariya** [comment]
I remove old version and install new one now I am getting something like this

# pkg-config --cflags opencv
Package opencv was not found in the pkg-config search path.
Perhaps you should add the directory containing `opencv.pc'
to the PKG_CONFIG_PATH environment variable
No package 'opencv' found
pkg-config: exit status 1

**Comment by deadprogram** [comment]
How did you uninstall OpenCV? The GoCV Makefile does not include any such task.

Also, was just realizing taht you must have also installed opencv some other way originally, because the GoCV `Makefile` does not install Python libs for OpenCV at all, in fact they are disabled here: https://github.com/hybridgroup/gocv/blob/master/Makefile#L58

**Comment by Kabariya** [comment]
I followed this page
http://www.srccodes.com/p/article/56/uninstall-remove-opencv-raspberry-pi-jessie-debain-make-uninstall-open-source-computer-vision-opencvlib

and i did the three step that you told me previously and now all library are not found ):

and it's not even uninstalling it's showing 

Package opencv was not found in the pkg-config search path.
Perhaps you should add the directory containing `opencv.pc'
to the PKG_CONFIG_PATH environment variable
No package 'opencv' found

**Comment by Kabariya** [comment]
and one more thing it's not even istalling on Raspbery pi 3 b+ after 10% it hang :)

**Comment by deadprogram** [comment]
OpenCV and GoCV are both known to work on Raspberry Pi. 

I'd suggest you start with a fresh OS install on your Raspi, since it sounds like you have followed a number of different guides for install/uninstall at this point.

**Comment by Kabariya** [comment]
I have succeeded once to install opencv and I was using a library

 import "github.com/lazywei/go-opencv"

but as you know I am new to this, I tried to use this library and I have found no one using this library and in Go document, they haven't given full specification about function. that's why I have to move to GOcv
so is there any solution for that. you know in case you know :)

**Comment by Kabariya** [comment]
Hi, I have fresh installed ubuntu on my vm player and still ia m getting this

**Comment by Kabariya** [comment]
Finally i have got it on ubuntu .. I have ran
sudo make install  

https://github.com/go-opencv/go-opencv/issues/57#issuecomment-335254931

-->instead of 

make build

and it worked. Thanks for your support :)

**Comment by deadprogram** [comment]
Thanks for helping out here @Kabariya I've updated the installation info on the web site here https://gocv.io/getting-started/linux/ and also the README file in the `dev` branch.

Now closing, thanks again!

**Comment by Kabariya** [comment]
No problem @deadprogram :+1:
