### ISSUE TITLE
Training your own classifiers?

### ISSUE THREAD

**Issue by emmetthitz** [hybridgroup/gocv#224]
## Description

Basically exactly what the title says. I want to use GoCV to hook some webcams up to my Kubernetes cluster to do facial recognition. Is there no feasible way to train classifiers with this library? Do I need to interface with https://docs.opencv.org/3.0-beta/modules/face/doc/facerec/facerec_api.html#FaceRecognizer%20:%20public%20Algorithm directly?
## Steps to Reproduce
This is probably closer to a feature request than a bug report.

## Your Environment

* Operating System and version:
Linux (docker)
* OpenCV version used:
3.4.1
* How did you install OpenCV?
With the makefile
* GoCV version used:
0.13.1
* Go version:
1.10.2
* Did you run the `env.sh` or `env.cmd` script before trying to `go run` or `go build`?
No, but I'm not having any issues getting anything to run.

**Comment by deadprogram** [comment]
Hello @emmetthitz you should take a look at https://godoc.org/gocv.io/x/gocv/contrib#LBPHFaceRecognizer.Train

That is the only one of the `face` opencv-contrib module algorithms that has been implemented so far.

**Comment by emmetthitz** [comment]
@deadprogram excellent! Thank you.

I'm still relatively new to CV, in case I didn't make it horribly obvious.

**Comment by hxdef2517** [comment]
@deadprogram is there any sample codes for any face recognition using this library ?
