### ISSUE TITLE
how to find contours center

### ISSUE THREAD

**Issue by Kabariya** [hybridgroup/gocv#225]
## Description
I am trying to find out center point of contours and for that I am doing this

count := gocv.FindContours(res1, 3, 1)
m := gocv.Moments(count[i], true)

##error
cannot use count[k] (type []image.Point) as type gocv.Mat in argument to gocv.Moments

and if i am doing  
m := gocv.Moments((my original image ), true)

I am only get one center everytime

## Your Environment

* Operating System and version: Ubuntu 18.04
* OpenCV version used: 3.4.1
* How did you install OpenCV? according to gocv.io
* GoCV version used: latest
* Go version: 1.10.2
* Did you run the `env.sh` or `env.cmd` script before trying to `go run` or `go build`? no

**Comment by deadprogram** [comment]
Hello again @Kabariya you might want to look at the https://github.com/hybridgroup/gocv/blob/master/cmd/motion-detect/main.go sample which uses `gocv.FindContours()` as a starting point.

Hope that helps!

**Comment by Kabariya** [comment]
Hi @deadprogram, I have looked into that file 
on line number 101
gocv.PutText(&img, status, image.Pt(10, 20), gocv.FontHersheyPlain, 1.2, statusColor, 2)

here in third argument image.Pt(10,20), how do you know the the center i mean how do you get to know that center is 10,20 

there is function in python 

moments --> which takes []image.Point  from [][]image.Point means array of image.points for particular contours and gives us back dictionary of all moment values calculated
see in link you will get more idea

https://docs.opencv.org/3.1.0/dd/d49/tutorial_py_contour_features.html

and in gocv it's not taking argument as []image.Point. we need to provide Mat and that's the problem
we get array of []image.Point from function FindCountours() and that what we can't use in moments

so if you know any way that can convert []image.point to Mat then it can work or may be we need new function which can take []imge.Point as an argument and gives us back  dictionary of all moment values calculated

**Comment by deadprogram** [comment]
I think this is a misunderstanding, as the code you reference `gocv.PutText(&img, status, image.Pt(10, 20), gocv.FontHersheyPlain, 1.2, statusColor, 2)` is intended to draw text at a fixed location relative to the window.

If what you are looking for is `gocv.Moments()` it is here: https://godoc.org/gocv.io/x/gocv#Moments

**Comment by Kabariya** [comment]
Have you visited the link which i have sent in previous comment? it shows that how we can find out center of any shape by using Momemts()

and here is one more example for it, it's video 

https://www.youtube.com/watch?v=IG3UkAqHnQI&t=428s

**Comment by deadprogram** [comment]
I already referred you to the Godocs link to `gocv.Moments()`. Use it however you wish based on its capabilities.

Hope that helps. Now closing this issue.

**Comment by Kabariya** [comment]
thanks for support :)

**Comment by benjcal** [comment]
For those that need help in the future here is how I accomplished finding the center of a contour without `gocv.Moments()`

Just use `gocv.MinAreaRect(contour).Center` and that will give you the center point that you need.

I was pretty frustrated because the C++/Python documentation doesn't translate to gocv since it's not possible to pass a contour to `gocv.Moments()` but for my use case the previous code worked alright
