### ISSUE TITLE
Wrong guide for installing on Ubuntu/Linux

### ISSUE THREAD

**Issue by edwvee** [hybridgroup/gocv#227]
Having Ubuntu 16.04 x86_64. So, I did ```make deps```, ```make download```, ```make build``` - everything was fine. But when I tried to run example printing version of opencv and gocv it said that it couldn't find opencv.pc file.
The thing was that everything what was built was lying in /tmp/opencv. Tried to find a solution. But then I removed /tmp/opencv, tried to start ```make install```, and everything went fine: downloading, building, placing built files in right directories. Moreover, it started example itself.
Why not to replace all the sequence of commands in installing on Ubuntu/Linux with just this command? Or add the missing part between ```make build``` and running example.

**Comment by deadprogram** [comment]
Hi @edwvee the README was already updated in the `dev` branch but has not yet been released: https://github.com/hybridgroup/gocv/blob/dev/README.md#quick-install

The GoCV website was already updated: https://gocv.io/getting-started/linux/#quick-install

**Comment by edwvee** [comment]
That could saved me a lot of time, oh...
