### ISSUE TITLE
Readme and Makefile issues

### ISSUE THREAD

**Issue by tzununbekov** [hybridgroup/gocv#230]
Recently I was trying to reinstall latest gocv master branch on Ubuntu 18.04 and faced following issues with Readme installation steps:

1. First step in "Ubuntu/Linux" section, `make deps`, failing because `apt-get install $(DEBS)` command expects user input to confirm packages installation. `-y` argument passed to apt-get command fixes this issue, and probably it's true for yum and dnf as well.

2. Last two `make *` commands for Ubuntu/Linux installation are `build` and then `clean`, but there is no installation step between them - this leads to multiple "not defined" and "missing" errors for any gocv call, just like gocv was not installed in system. This issue may be fixed by updating Readme either with `make install` command instead of `make deps, download, build, etc.` or by adding `make sudo_install` after `make build` step.      

Maybe I'm just miss some important information in Readme, please correct me in this case

**Comment by deadprogram** [comment]
Hi @tzununbekov the README was already updated in the `dev` branch that will be part of the next release:

https://github.com/hybridgroup/gocv/blob/dev/README.md#quick-install

The web site was already updated here:

https://gocv.io/getting-started/linux/#quick-install

**Comment by tzununbekov** [comment]
@deadprogram oh, looks like I faced this issue before website was updated. And what about first case regarding deps installation?

Btw, wanted to ask about contrib.SIFT memory issue which I described in this comment:
https://github.com/hybridgroup/gocv/issues/205#issuecomment-391718343

I think we've found the reason of constantly increasing memory consumption and tested fix, but I'm not sure about the way we did it. Could you take a look on it?
https://github.com/tzununbekov/gocv/commit/6c3f14599b718c0abc918eb6879cf26f65d1e180

**Comment by deadprogram** [comment]
Can you post that info to the #205 and we can continue the discussion there, please? Also seems like this issue #230 can be closed?

**Comment by tzununbekov** [comment]
@deadprogram could you clarify question about `make deps` first and then we can close this issue 
And sure, we can move memory leak discussion back to #205, I'll post there

**Comment by deadprogram** [comment]
Hi @tzununbekov yes we need `-y` for Debian install, and equivalent param for other Linux distros.

**Comment by deadprogram** [comment]
I've updated the `Makefile` with the appropriate `-y` flags for each of the various package managers.

I will close this issue after the next release of GoCV/

**Comment by deadprogram** [comment]
These docs are now released as part of v0.14.0 so closing this PR. Thank you!
