### ISSUE TITLE
cv::calcHist() function not yet implemented

### ISSUE THREAD

**Issue by Anveena** [hybridgroup/gocv#237]
I got some trouble in finding this fuction :"cv::calcHist (const Mat *images, int nimages, const int *channels, InputArray mask, SparseMat &hist, int dims, const int *histSize, const float **ranges, bool uniform=true, bool accumulate=false)"
https://docs.opencv.org/3.4.1/d6/dc7/group__imgproc__hist.html#ga994f53817d621e2e4228fc646342d386

**Comment by deadprogram** [comment]
Hello @Anveena if you check out the ROADMAP document in the `dev` branch, work has been started on the imgproc histogram functions, but `cv::calcHist()` still needs implementation:

https://github.com/hybridgroup/gocv/blob/dev/ROADMAP.md

We'd gladly accept a pull request that added that function! Please take a look at https://github.com/hybridgroup/gocv/blob/master/CONTRIBUTING.md if you would be willing.

**Comment by milosgajdos83** [comment]
I started working on adding [calcHist](https://docs.opencv.org/master/d6/dc7/group__imgproc__hist.html#ga6ca1876785483836f72a77ced8ea759a) into `gocv` in this [PR](https://github.com/hybridgroup/gocv/pull/241). 

It needs more work (tests etc.), but the basic implementation seems to be working

**Comment by milosgajdos83** [comment]
I added basic tests, it seems to be passing so the PR could be clear to go 🤞

**Comment by deadprogram** [comment]
Thanks for working on this @milosgajdos83 your PR was merged.

I will close this issue once the next release of GoCV goes out.

**Comment by deadprogram** [comment]
This code is now released as part of v0.14.0 so closing. Thank you!
