### ISSUE TITLE
Bilaterial filter breaks on particular image

### ISSUE THREAD

**Issue by edwvee** [hybridgroup/gocv#239]
Windows 10 x64, go 1.10, opencv 3.4.1.
Code:
```go
mat := gocv.IMRead("favicon.png", gocv.IMReadColor)
	defer mat.Close()
	mat2 := gocv.NewMat()
	defer mat2.Close()
	gocv.BilateralFilter(mat, &mat2, 10, 20, 20)
```
I receive long stack trace starting with:
```
OpenCV(3.4.1) Error: Assertion failed ((src.type() == (((0) & ((1 << 3) - 1)) + (((1)-1) << 3)) || src.type() == (((0) & ((1 << 3) - 1)) + (((3)-1) << 3))) && src.data != dst.data) in bilateralFilter_8u, file C:\opencv\opencv-3.4.1\modules\imgproc\src\smooth.cpp, line 4895
```
I don't see a reason to put here all stack trace, because example is easy runnable if you have gocv installed.
Strange that IMRead return Mat with 1 channel, but the image is colored.
The code and image are attached.
What't wrong with this particular image and how to avoid such situations (but bilaterial must work on 1 channel mats), and, if possible, how to prepare such "special" images for opencv processing functions to execute them painlessly? Looks like there are lot of rakes to step them on.
[bil_not_works.zip](https://github.com/hybridgroup/gocv/files/2116156/bil_not_works.zip)

**Comment by deadprogram** [comment]
Hello @edwvee the exception message is returned by OpenCV itself, not GoCV. 

Acording to the docs at https://docs.opencv.org/3.4.1/d4/d86/group__imgproc__filter.html#ga9d7064d478c95d60003cf839430737ed the source image must be "Source 8-bit or floating-point, 1-channel or 3-channel image."

If we look at it carefully it does indeed explain the problem with the image, although the assertion is very hard to read. Let's decipher it:

It says that the source Mat must be either type() == 0 aka MatTypeCV8U or else type() == 16 aka MatTypeCV8UC3.

If you want to know the type of your image in the above code, add a `fmt.Println(mat.Type())` before the call to the filter, and see what type it is.

Hope that helps!

**Comment by edwvee** [comment]
println(mat.Type()) gives 0...

**Comment by deadprogram** [comment]
In that case, perhaps you might want to post to https://github.com/opencv/opencv with this question.

**Comment by deadprogram** [comment]
Hi @edwvee any further information on your issue?

**Comment by deadprogram** [comment]
Closing due to age. Please reopen if needed. Thanks.
