### ISSUE TITLE
Win 10  Instructions - Something missing?

### ISSUE THREAD

**Issue by DerekL** [hybridgroup/gocv#24]
Followed docs for Win 10 to the letter, upon attempting to run cmd/version: 

```
C:\Work\src\gocv.io\x\gocv>set CGO_CPPFLAGS=-IC:\opencv\build\install\include

C:\Work\src\gocv.io\x\gocv>set CGO_LDFLAGS=-LC:\opencv\build\install\x64\mingw\lib -lopencv_core330 -lopencv_videoio330 -lopencv_imgproc331 -lopencv_highgui331 -lopencv_imgcodecs331 -lopencv_objdetect331 -lopencv_calib3d331 -lopencv_video331

C:\Work\src\gocv.io\x\gocv> go run .\cmd\version\main.go
# gocv.io/x/gocv
C:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/5.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lopencv_core330
C:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/5.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lopencv_videoio330
collect2.exe: error: ld returned 1 exit status

C:\Work\src\gocv.io\x\gocv>opencv_version
3.3.1
```

Any ideas?

**Comment by hooklife** [comment]
i hava a same problem

**Comment by hooklife** [comment]
@DerekL 
i fix it
do you forget
`Last, add C:\opencv\build\install\x64\mingw\bin to your System Path.`

**Comment by DerekL** [comment]
Ha! I did the same thing and now have this: 

In file included from ..\..\core.cpp:1:0:
..\..\core.h:17:30: fatal error: opencv2/opencv.hpp: No such file or directory
compilation terminated.

**Comment by hooklife** [comment]
@DerekL 
i got what's wrong
it works
https://github.com/hybridgroup/gocv#windows-1
it doesn't work
https://gocv.io/getting-started/windows/#how-to-build-run-code

**Comment by deadprogram** [comment]
Thanks for finding this. The docs in the site have been updated to match the README in this commit: https://github.com/hybridgroup/gocv-site/commit/d1b4e945c862c8935ede2c2f4ca6a267e17bc23f

Now closing, please reopen if needed.
