### ISSUE TITLE
How to use kmeans function on gocv?

### ISSUE THREAD

**Issue by higoalespn** [hybridgroup/gocv#243]
## Description

I not find the function of kmeans on gocv, how to use it?

## Your Environment

* Operating System and version: Windows10
* OpenCV version used:3.4.1
* GoCV version used:0.13.0
* Go version: go version go1.8 windows/amd64

**Comment by milosgajdos83** [comment]
@higoalespn unfortunately [opencv::kmeans](https://docs.opencv.org/master/d5/d38/group__core__cluster.html#ga9a34dc06c6ec9460e90860f15bcd2f88) function hasn't been ported from `opencv` to `gocv`, yet.

Judging by the look of the function in the official docs and C++ code, it seems like it shouldn't be hard to port it over.

**Comment by deadprogram** [comment]
This was added in v0.21.0 so now closing. Thanks!
