### ISSUE TITLE
OpenVino PVL example fails

### ISSUE THREAD

**Issue by muka** [hybridgroup/gocv#245]
I am getting started with OpenVino and would like to try out a movidius stick

## Description
OpenVino PVL face detection example fails

## Steps to Reproduce
`go run cmd/openvino/pvl/facerecognizer/main.go `  

also with `customenv` tag

```
# gocv.io/x/gocv/openvino/pvl
In file included from face.cpp:1:0:
face.h:8:27: fatal error: opencv2/pvl.hpp: No such file or directory
 #include <opencv2/pvl.hpp>
                           ^
compilation terminated.
```

## Your Environment
* Operating System and version: ubuntu 18.04
* OpenCV version used: 3.4.1
* How did you install OpenCV? `make download build sudo_install`
* GoCV version used: `master` and `dev`
* Go version: 1.10.1
* Did you run the `env.sh` or `env.cmd` script before trying to `go run` or `go build`? 

with custom tags as in the README

**Comment by deadprogram** [comment]
Hello @muka I'd recommend you use the `openvino-ie-support` branch and follow the instructions in https://github.com/hybridgroup/gocv/blob/feature/openvino-ie-support/openvino/README.md to use GoCV with OpenVINO until the next GoCV release.

**Comment by muka** [comment]
Than you 
I did some experiments. I am unfortunately using ubuntu 18.04 and had to play with mismatching shared libraries versions (here the script to generate 16.04 compatible libs https://github.com/muka/openvino-docker)

Now I do not have any missing lib reference but still erroring, seems the cv calls are not aligned

```
# gocv.io/x/gocv
/tmp/go-build561284225/b023/_x013.o: In function `Fisheye_UndistortImage':
calib3d.cpp:(.text+0xcd): undefined reference to `cv::fisheye::undistortImage(cv::_InputArray const&, cv::_OutputArray const&, cv::_InputArray const&, cv::_InputArray const&, cv::_InputArray const&, cv::Size_<int> const&)'
/tmp/go-build561284225/b023/_x013.o: In function `Fisheye_UndistortImageWithParams':
calib3d.cpp:(.text+0x267): undefined reference to `cv::fisheye::undistortImage(cv::_InputArray const&, cv::_OutputArray const&, cv::_InputArray const&, cv::_InputArray const&, cv::_InputArray const&, cv::Size_<int> const&)'
collect2: error: ld returned 1 exit status
```

**Comment by deadprogram** [comment]
That looks a lot like you are missing the `-lopencv_calib3d` from the `CGO_LDFLAGS` env var to me. I seems to recall I had that exact error earlier this week.

**Comment by muka** [comment]
Good one, work  now. Thank you

I had also to add also `inference_engine` path to `$LD_LIBRARY_PATH`

```
LD_LIBRARY_PATH=/opt/intel/computer_vision_sdk_2018.2.300/deployment_tools/inference_engine/lib/ubuntu_16.04/intel64:$LD_LIBRARY_PATH
```

I am curious to see if the movidius is picked up automatically by open vino

**Comment by deadprogram** [comment]
I have used that exact configuration with a Movidius Myriad 2, so it should work for you, @muka

**Comment by deadprogram** [comment]
Very important info to know is that the PVL does not use the inference engine at all. 

For one of the examples that *can* use IE, you can look at https://github.com/hybridgroup/gocv/blob/feature/openvino-ie-support/cmd/caffe-classifier/main.go

You should be able to run that example with the Movidius like this:

```shell
go run ./cmd/caffe-classifier/main.go 0 ~/Downloads/bvlc_googlenet.caffemodel ~/Downloads/bvlc_googlenet.prototxt ~/Downloads/synset_words.txt openvino vpu
```

**Comment by muka** [comment]
Thanks it's working now, very impressing!

**Comment by w910820618** [comment]
Does opencv4.1.1 support openvino PVL?

Error message：
# gocv.io/x/gocv/openvino/pvl
In file included from face.cpp:1:0:
face.h:7:10: fatal error: opencv2/opencv.hpp: No such file or directory
 #include <opencv2/opencv.hpp>
          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
