### ISSUE TITLE
Odd installation issue on RPi

### ISSUE THREAD

**Issue by stevef1uk** [hybridgroup/gocv#246]
$go get -u -d gocv.io/x/gocv
# cd /home/pi/godev/src/gocv.io/x/gocv; git pull --ff-only
From https://github.com/hybridgroup/gocv
   65d6ebd..0999444  master     -> origin/master
   a2659fd..c866bf2  dev        -> origin/dev
 * [new branch]      feature/openvino-ie-support -> origin/feature/openvino-ie-support
 * [new tag]         0.13.1     -> 0.13.1
 * [new tag]         0.10.0     -> 0.10.0
 * [new tag]         0.11.0     -> 0.11.0
 * [new tag]         0.12.0     -> 0.12.0
 * [new tag]         0.13.0     -> 0.13.0
error: Your local changes to the following files would be overwritten by merge:
	imgproc.go
Please commit your changes or stash them before you merge.
Aborting
Updating 65d6ebd..0999444

Details of RPi:
go version go1.10 linux/arm
Linux rpi3fr 4.14.21-v7+ #1095 SMP Fri Feb 23 18:21:29 GMT 2018 armv7l GNU/Linux

**Comment by deadprogram** [comment]
You might want to use `git pull --rebase` instead. Which branch is it that you want to be using?

**Comment by deadprogram** [comment]
Hello @stevef1uk any further details on this issue?

**Comment by deadprogram** [comment]
Hello @stevef1uk any further update on this, or should it be closed?

**Comment by stevef1uk** [comment]
Please close
