### ISSUE TITLE
Crash with face example in readme.md

### ISSUE THREAD

**Issue by Chipsterjulien** [hybridgroup/gocv#25]
Hello. I try the example face detect, launch sources env.sh and finally go run main.go.
I have this issue:

    VIDIOC_QUERYCTRL: Input/output error
    start reading camera device: 0
    OpenCV Error: Assertion failed (!empty()) in detectMultiScale, file /build/opencv/src/opencv-3.3.1/modules/objdetect/src/cascadedetect.cpp, line 1698
    terminate called after throwing an instance of 'cv::Exception'
      what():  /build/opencv/src/opencv-3.3.1/modules/objdetect/src/cascadedetect.cpp:1698: 
    error: (-215) !empty() in function detectMultiScale

    SIGABRT: abort
    PC=0x7fe6c2ab08a0 m=0 sigcode=18446744073709551610
    signal arrived during cgo execution

    goroutine 1 [syscall, locked to thread]:
    runtime.cgocall(0x49ebd0, 0xc42004fdf0, 0xc42004fe18)
	    /usr/lib/go/src/runtime/cgocall.go:132 +0xe4 fp=0xc42004fdc0 sp=0xc42004fd80 
    pc=0x411704
    gocv.io/x/gocv._Cfunc_CascadeClassifier_DetectMultiScale(0x1535f10, 0x163e620, 0x0, 0x0)
	    gocv.io/x/gocv/_obj/_cgo_gotypes.go:291 +0x57 fp=0xc42004fdf0 sp=0xc42004fdc0 pc=0x49c207
    gocv.io/x/gocv.(*CascadeClassifier).DetectMultiScale.func1(0x1535f10, 0x163e620, 0x0, 0x0)
	    /home/julien/.golang/src/gocv.io/x/gocv/objdetect.go:53 +0xb5 fp=0xc42004fe38 sp=0xc42004fdf0 pc=0x49d995
    gocv.io/x/gocv.(*CascadeClassifier).DetectMultiScale(0xc42004ff28, 0x163e620, 0x0, 0x0, 0x0)
	    /home/julien/.golang/src/gocv.io/x/gocv/objdetect.go:53 +0x63 fp=0xc42004feb0 sp=0xc42004fe38 pc=0x49d143
    main.main()
	    /home/julien/Programmation/Golang/hogg/hogg.go:50 +0x230 fp=0xc42004ff80 sp=0xc42004feb0 pc=0x49dfe0
    runtime.main()
	    /usr/lib/go/src/runtime/proc.go:195 +0x226 fp=0xc42004ffe0 sp=0xc42004ff80 pc=0x438a56
    runtime.goexit()
	    /usr/lib/go/src/runtime/asm_amd64.s:2337 +0x1 fp=0xc42004ffe8 sp=0xc42004ffe0 pc=0x4612e1

    rax    0x0
    rbx    0x6
    rcx    0x7fe6c2ab08a0
    rdx    0x0
    rdi    0x2
    rsi    0x7ffc2ad0b460
    rbp    0x7fe6c2e2e680
    rsp    0x7ffc2ad0b460
    r8     0x0
    r9     0x7ffc2ad0b460
    r10    0x8
    r11    0x246
    r12    0x1642920
    r13    0x7ffc2ad0c860
    r14    0x6a2
    r15    0x10
    rip    0x7fe6c2ab08a0
    rflags 0x246
    cs     0x33
    fs     0x0
    gs     0x0
    exit status 2

I use openCV-3.3.1 on ArchLinux. I try to comment some lines and, as soon as i uncomment rects := classifier.DetectMultiScale(img), i have this error

**Comment by deadprogram** [comment]
Hello @Chipsterjulien do you have the haarcascade file `data/haarcascade_frontalface_default.xml` in the correct location relative to the directory you are trying to run the file in? Sounds like the file is not getting loaded correctly by the classifier? You might be better off executing the cmd example https://github.com/hybridgroup/gocv/blob/master/cmd/facedetect/main.go

**Comment by Chipsterjulien** [comment]
Hello. I apologize for the inconvenience caused because the file haarcascade_frontalface_default.xml did not point in the right place. For my part, it was necessary to put:
/usr/share/opencv/haarcascades/haarcascade_frontalface_default.xml

**Comment by deadprogram** [comment]
No inconvenience at all, glad you've got it working.
