### ISSUE TITLE
Direct access to Mat data

### ISSUE THREAD

**Issue by vcabbage** [hybridgroup/gocv#250]
## Description

I have a case where I need access to the underlying bytes of a Mat, but don't hold on to them longer than the Mat exists. As an optimization I access the C allocated data directly rather than copying it into Go memory with `Mat.ToBytes`. I'm currently using `Mat.Ptr` to accomplish this, but it's rather ugly.

Would it make sense to add a method which allows this more easily? From what I've seen, the existing API strives to be safe, so I'm not sure how well it would fit with the goals of this project. Perhaps something like `func (*Mat) DataPtr() unsafe.Pointer` to reduce the chance of it being used inadvertently. In my case I'm dealing with the CV_32FC2 result from `CalcOpticalFlowFarneback`, so I have to use unsafe to cast to a `[]float32` anyway.

Thanks for the project and taking the time to consider this issue.

## Steps to Reproduce

n/a

## Your Environment

n/a

**Comment by deadprogram** [comment]
Hi @vcabbage that you for the issue, I think this is a very good idea. 

Do you think there should be a version for each of the various casts e.g. `Mat.DataPtrFloat()`, `Mat.DataPtrInt()`? Also should it perhaps be called `RawPtr()` or `DirectPtr()`?

Perhaps you can submit a PR with an implementation of this?

**Comment by vcabbage** [comment]
Would the `Mat.DataPtrFloat()` return something other than `unsafe.Pointer`? I could see an API like `Mat.DataFloat32() []float32` so that the user doesn't need to deal with unsafe themselves. The downside of this approach is that it may not be obvious that the data isn't valid after the Mat is closed. It's also not immediately obvious to me what the behavior should be if `Mat.DataFloat32()` were called on, for example, a 2x3 Mat of CV_8U. As it's not possible to correctly do that cast I suppose returning an error or panic'ing would be appropriate.

`RawPtr()` and `DirectPtr()` are both fine by me, whichever you'd prefer.

I'd be happy to submit a PR. I'll hold off until we determine what the API should be.

**Comment by deadprogram** [comment]
Good points, @vcabbage 

Seems like `Mat.DataPtrFloat32() ([]float32, error)` etc. would be a reasonable definition. 

Agreed that we need to document in the GoDoc the lifetime rules about these functions. Also agree that if the cast is being called on a Mat of the wrong type, it should return an error.

How does that sound?

**Comment by vcabbage** [comment]
@deadprogram Sounds good to me. I opened #251.

**Comment by deadprogram** [comment]
This has now been released as part of v0.15.0 so closing. Thank you very much!
