### ISSUE TITLE
I am getting error with OpenVino on Windows

### ISSUE THREAD

**Issue by Kabariya** [hybridgroup/gocv#255]
## Description
I want to use Openvino and i have installed it on windows 10. Only one peoblem is I am getting error something like this.

![screenshot 86](https://user-images.githubusercontent.com/16531938/42675348-3ed0bcaa-8691-11e8-9bc5-2367b4d2e3e0.png)

* Did you run the `env.sh` or `env.cmd` script before trying to `go run` or `go build`?  

there is no file at

source /opt/intel/computer_vision_sdk/bin/setupvars.sh

and i tried to find it out but it was for ubuntu and i ran it it's not working.

so can you help me out here. where can i get  

> **setupvars.sh** for window 10

## Your Environment

* Operating System and version:Windows 10
* OpenCV version used:3.4.1
* How did you install OpenCV? according to gocv.io
* GoCV version used: latest
* Go version: 10.1.2

**Comment by deadprogram** [comment]
OpenVINO support for GoCV is only available on Ubuntu, due to https://github.com/golang/go/issues/20982

You can use GoCV with OpenCV on Windows by compiling OpenCV from source, as described here: https://github.com/hybridgroup/gocv#windows

**Comment by Kabariya** [comment]
need one more help if you can? how do you install Openvino on ubuntu? I try to follow their website suggested page but l am getting lots of error like 

libgstreamer0.10-dev
libpng12-dev

are not fond 

can you help me out... if you can :)

**Comment by Kabariya** [comment]
that's the problem ... I am getting all that error with that file
libgstreamer0.10-dev
libpng12-dev

that's why i have changed script 
libgstreamer0.10-dev to  libgstreamer0.10
libpng12-dev to libpng-dev

now it nstalled but i ma getting problem with demo file

**Comment by deadprogram** [comment]
You need the dev versions of those packages in order to obtain the needed header files.

What version of Ubuntu did you install?

**Comment by Kabariya** [comment]
I have installed 18.04. does it work on Ubuntu 18.04 ? And I have made changed cz when I looked on internet I found out that Ubuntu does not provide that Dev version of library anymore. But if you can install on Ubuntu then I should too. What version are you on and if you can help me little more then can you please tell me how can I get that Dev version of library cz I have given my whole day to solve this problem.

**Comment by deadprogram** [comment]
According to the OpenVINO docs the supported Linux operating systems are:

- Ubuntu* 16.04.3 long-term support (LTS), 64-bit
- CentOS* 7.4, 64-bit
- Yocto Project* Poky Jethro* v2.0.3, 64-bit (for target only)

https://software.intel.com/en-us/articles/OpenVINO-Install-Linux

**Comment by deadprogram** [comment]
I use Ubuntu 16.04 LTS. I already had those dependencies installed, but the installed also updated them.

**Comment by Kabariya** [comment]
Hi, Again I have done what you suggested me. I installed Ubuntu 16.04 LTS and I am able to install OpenVINO I have installed GoLang 1.10.3 and it's working perfectly (I mean GoLang 1.10.3 works perffectly)

I have ran openVINO demo also and it works fine

(one question i am bit confuse about : do we need to installed opencv second time cz openvino installed it, we can see opencv folder in openvino installed folder. cz of this confusion i have installed it second time like you suggested on your website gocv.io  )

Now I am getting one more error and yeah i have ran those two command

 (source /opt/intel/computer_vision_sdk/bin/setupvars.sh , source openvino/env.sh) 

also before 

go run -tags openvino ./cmd/version/main.go

but i am getting error : 

# gocv.io/x/gocv
/usr/bin/ld: cannot find -lopencv_face
collect2: error: ld returned 1 exit status

**Comment by deadprogram** [comment]
Hi @Kabariya you do not need to also run the OpenCV install separately if you install OpenVINO, since OpenVINO installs its own build of OpenCV.

You can also install both of them side by side, and as long as you follow the instructions for each in separate terminal windows it works fine.

Glad to be of assistance, now closing this issue.

**Comment by deadprogram** [comment]
I'd suggest looking more closely at the example https://github.com/hybridgroup/gocv/blob/master/cmd/openvino/pvl/smiledetect/main.go

Hope that helps!

**Comment by Kabariya** [comment]
Thanks it helped me alot :)

**Comment by deadprogram** [comment]
That would probably be a good question to ask on the Intel forums:

https://software.intel.com/en-us/forums/computer-vision

**Comment by Kabariya** [comment]
Hi, I have posted my question there but I am not getting a reply it's been two days, Do you have any friends or someone who can help you with this question? and one more question if you can find out the answer, For face recognition I don't think they are using any pre-trained model, I guess they are using OpenCV's facial point I could be wrong. if you can help me with this :)

**Comment by Kabariya** [comment]
I found something...  it's not telling accuracy in number but pretty much good information about PVL and Intel SDK for Computer Vision
