### ISSUE TITLE
cv:: cvAbsDiff() function not yet implemented

### ISSUE THREAD

**Issue by Anveena** [hybridgroup/gocv#256]

**Comment by deadprogram** [comment]
Hello @Anveena you should be using https://github.com/hybridgroup/gocv/blob/0d9b22a6450a7d81761a4b763f58fb99e962ab47/core.go#L602

The functions that are C-style definitions that are named `cvAbsDiff()` have been deprecated in OpenCV itself.

Hope that helps!

**Comment by Anveena** [comment]
sorry.
