### ISSUE TITLE
Use Windows GOPATH

### ISSUE THREAD

**Issue by naratteu** [hybridgroup/gocv#257]
i'm trying this tutorial : https://gocv.io/getting-started/windows/
but this tuotorial and batchfile's GOPATH is hardcoded on [%USERPROFILE%\go], and my %GOPATH% is customed on [C:\GoCode] already

This seems a little uncomfortable.

**Comment by deadprogram** [comment]
Hello @naratteu since you have a custom install location for your Go, you should be able to just substitute that directory. For example, in your case:

```
chdir C:\GoCode\src\gocv.io\x\gocv
.\win_build_opencv.cmd
```

Hope that helps!

**Comment by deadprogram** [comment]
I've just updated the README and site docs to use `%GOPATH%` as one would normally expect on Windows. I will close this issue after the next GoCV release.

Thank you!

**Comment by deadprogram** [comment]
This has been released as part of v0.15.0 now closing. Thank you!
