### ISSUE TITLE
make -j freezes my PC

### ISSUE THREAD

**Issue by sanyatuning** [hybridgroup/gocv#258]
https://github.com/hybridgroup/gocv/blob/0d9b22a6450a7d81761a4b763f58fb99e962ab47/Makefile#L59

please add limit to make -j
for example:
```
make -j `grep -c ^processor /proc/cpuinfo`
```
or just:
```
make -j 4
```

**Comment by deadprogram** [comment]
Hello @sanyatuning that seems like a reasonable modification. Would you like to submit a PR with that change?

**Comment by sanyatuning** [comment]
#264 done

**Comment by deadprogram** [comment]
This has been released as part of v0.15.0 now closing. Thank you!
