### ISSUE TITLE
gocv houghlines function prints error

### ISSUE THREAD

**Issue by minominium** [hybridgroup/gocv#259]
## Description

HI I'm really new to GitHub....and very first using go language.

But my go code prints out weird error.

I'll attach my main code below:

## Steps to Reproduce

`func main() {
        mat := gocv.IMRead("C:/Users/hinmo/Desktop/R720x0.jpg", gocv.IMReadGrayScale)
	window := gocv.NewWindow("ImgProc")
	defer window.Close()

	matLines := gocv.NewMat()
	matCanny := gocv.NewMat()
	
	matOutput := gocv.NewMat()
	defer matOutput.Close()
	
	gocv.MedianBlur(mat, &mat, 5)
	
	if mat.Empty() {
		fmt.Println("Did not load")
	}
	
	gocv.Canny(mat, &matCanny, 720, 480)
	gocv.HoughLinesP(mat, &matLines, 0.5, math.Pi/360, 300)
	
	if !mat.Empty() {
		fmt.Println(matLines.Cols())
		fmt.Println(matLines.Rows())
		for i := 0; i < matLines.Rows(); i++ {
			pt1 := image.Pt(int(matLines.GetVeciAt(i, 0)[0]), int(matLines.GetVeciAt(i, 0)[1]))
			pt2 := image.Pt(int(matLines.GetVeciAt(i, 0)[2]), int(matLines.GetVeciAt(i, 0)[3]))
			gocv.Line(&matOutput, pt1, pt2, color.RGBA{0, 255, 0, 50}, 10)
		}
		//gocv.Line(&mat, image.Pt(0, 0), image.Pt(500, 500), color.RGBA{0, 255, 0, 255}, 10)
	}
	
	for {
		window.IMShow(matOutput)
		if window.WaitKey(10) >= 0 {
			break
		}
	}
}`

and my Error Code looks like this:

> Exception 0x20474343 0xf4ed20 0x64945188 0x7ff87b06a388
PC=0x7ff87b06a388
signal arrived during external code execution

>gocv.io/x/gocv._Cfunc_Window_IMShow(0xf4e840, 0xf4ec50)
        _cgo_gotypes.go:4416 +0x48
>gocv.io/x/gocv.(*Window).IMShow.func2(0xf4e840, 0xf4ec50)
        C:/Users/hinmo/Documents/GoWS/src/gocv.io/x/gocv/highgui.go:158 +0x67
>gocv.io/x/gocv.(*Window).IMShow(0xc04205a3e0, 0xf4ec50)
        C:/Users/hinmo/Documents/GoWS/src/gocv.io/x/gocv/highgui.go:158 +0x80
main.main()
        C:/Users/hinmo/Documents/GoWS/src/ImgProcTest/src/main/main.go:44 +0x47d
rax     0x400
rbx     0xf4ed20
rcx     0x332856436e65704f
rdi     0xf4ed60
rsi     0x613fe9b0
rbp     0xffffff29
rsp     0x78f950
r8      0x2e776f646e69775c
r9      0x3a3635333a707063
r10     0x203a726f72726520
r11     0x131322d00
r12     0x78fc90
r13     0x5f
r14     0x5e
r15     0x200
rip     0x7ff87b06a388
rflags  0x206
cs      0x33
fs      0x53
gs      0x2b
exit status 2

## Your Environment

What should I Do?? I'm using golang with

eclipse photon, 
gocv based on OpenCV 3.4.0
go 1.10.3 (which is latest stable.)

on Windows 10. Is my main code is wrong? or what?

**Comment by deadprogram** [comment]
Hello @minominium you have a few errors in that code.

Try this code instead:

```go
package main

import (
	"fmt"
	"image"
	"image/color"
	"math"

	"gocv.io/x/gocv"
)

func main() {
	mat := gocv.IMRead("C:/Users/hinmo/Desktop/R720x0.jpg", gocv.IMReadColor)

	matCanny := gocv.NewMat()
	matLines := gocv.NewMat()

	gocv.Canny(mat, &matCanny, 50, 200)
	gocv.HoughLinesP(matCanny, &matLines, 1, math.Pi/180, 80)

	fmt.Println(matLines.Cols())
	fmt.Println(matLines.Rows())
	for i := 0; i < matLines.Rows(); i++ {
		pt1 := image.Pt(int(matLines.GetVeciAt(i, 0)[0]), int(matLines.GetVeciAt(i, 0)[1]))
		pt2 := image.Pt(int(matLines.GetVeciAt(i, 0)[2]), int(matLines.GetVeciAt(i, 0)[3]))
		gocv.Line(&mat, pt1, pt2, color.RGBA{0, 255, 0, 50}, 10)
	}

	window := gocv.NewWindow("ImgProc")

	for {
		window.IMShow(mat)
		if window.WaitKey(10) >= 0 {
			break
		}
	}
}
```

Hope that helps!

**Comment by minominium** [comment]
Man It compiles well and works nice!! But here's my another question:
Is "gocv.NewWindow" function must call finally?? 
And if "gocv.HoughLinesP" weren't find line well, which variable should be changed?

Your advice actually helps, thanks again!

**Comment by deadprogram** [comment]
Sorry I do not understand the question "Is "gocv.NewWindow" function must call finally??"

For a good description of the Hough transform, check out http://homepages.inf.ed.ac.uk/rbf/HIPR2/hough.htm

**Comment by minominium** [comment]
I mean,
in my code, `window := gocv.NewWindow("ImgProc")`

**Comment by deadprogram** [comment]
There is no difference in the placement of the call to `gocv.NewWindow()`. I probably should have left that line alone to avoid confusion.

Anyhow, I added the example to the `dev` branch, so I will close this issue on the next release.

**Comment by minominium** [comment]
Ok, Really thanks to your fast and nice reply!
