### ISSUE TITLE
Threshold Not Implemented? 

### ISSUE THREAD

**Issue by DerekL** [hybridgroup/gocv#26]
Please forgive my salient newbishness. 

Is [Threshold](https://docs.opencv.org/3.3.1/d7/d1b/group__imgproc__misc.html#gae8a4a146d1ca78c626a53577199e9c57) not implemented? 

I am looking to isolate dark spots before applying edge detection.

**Comment by deadprogram** [comment]
Hello @DerekL the `Threshold` function was recently implemented in the `dev` branch, and will be part of the next GoCV release, probably happening in the next couple of days:

https://github.com/hybridgroup/gocv/blob/dev/imgproc.go#L470

Hope that helps!

**Comment by deadprogram** [comment]
The new version with `Threshold()` has been released. Now closing.
