### ISSUE TITLE
how to provide two input to tensor-flow pre-trained  model

### ISSUE THREAD

**Issue by Kabariya** [hybridgroup/gocv#265]
I have a tensorflow model which takes two input. so I am using

    net := gocv.ReadNetFromTensorflow()

after this, I have to provide two input but I am not able to with

net.SetInput()

can we provide two input?

**Comment by deadprogram** [comment]
Hi @Kabariya you can call `net.SetInput()` multiple times, once for each input. 

Once you have set all of the inputs, you can then call `net.Forward()` for a single output or `net.ForwardLayers()` if there are multiple outputs.

**Comment by Kabariya** [comment]
I have one question. can we pass float with net.SetInput() ? Or we can use it only for blob? and what do I use if I want to pass float?

**Comment by deadprogram** [comment]
You could pass a blob that contains just a single element with one float, I suppose The OpenCV API expects a blob.

**Comment by Kabariya** [comment]
thank you again... I think maybe it will work. I realized that in order to use Tensorflow model I need config file and for my own model which only takes float as input it doesn't have a config file so I can't test what you have suggested. And I think you are also right about blob I mean since opencv is a tool for working with images so it expects blob only. I am closing it now. :)

**Comment by Kabariya** [comment]
hi again, One question is there any way to set threshold while we are using face-recognizer with gocv and openVINO? By threshold I mean I want to tell programme that if it verifies that person is let says around 80% to 85% accurate then and only then it shows that this is this or that person.
