### ISSUE TITLE
Where is the remap()?

### ISSUE THREAD

**Issue by jmnmu** [hybridgroup/gocv#267]

**Comment by deadprogram** [comment]
Hello @jmnmu please checkout https://github.com/hybridgroup/gocv/blob/master/CONTRIBUTING.md#something-you-wantneed-from-opencv-does-not-appear-to-be-in-gocv and then look at https://github.com/hybridgroup/gocv/blob/master/ROADMAP.md in the section "Geometric Image Transformations".

**Comment by deadprogram** [comment]
This was implemented long ago, but forgot to close this. Thanks!
