### ISSUE TITLE
No Polylines method ? 

### ISSUE THREAD

**Issue by zak905** [hybridgroup/gocv#268]
Polylines methods seems like an important method that allows drawing polygons, it is missing from `gocv`

https://docs.opencv.org/master/d6/d6e/group__imgproc__draw.html#gaf30888828337aa4c6b56782b5dfbd4b7

**Comment by deadprogram** [comment]
Please see:

https://github.com/hybridgroup/gocv/blob/master/CONTRIBUTING.md#something-you-wantneed-from-opencv-does-not-appear-to-be-in-gocv

and

https://github.com/hybridgroup/gocv/blob/master/ROADMAP.md under "imgproc - Drawing functions"

**Comment by zak905** [comment]
I see. If ever there is time, I will help on this one. I need it in my app.

**Comment by deadprogram** [comment]
This was implemented at some point, but forgot to close this issue. Now closing, thanks!
