### ISSUE TITLE
gocv.NormMixMax should be gocv.NormMinMax

### ISSUE THREAD

**Issue by esimov** [hybridgroup/gocv#269]
This is actually not an issue, but a notice that `gocv.NormMixMax` const in fact should be `gocv.NormMinMax` to get aligned with the standard OpenCV `NORM_MINMAX` enum type. 

Here is the reference for it: https://docs.opencv.org/master/d2/de8/group__core__array.html#gad12cefbcb5291cf958a85b4b67b6149f

It's just a bit confusing.

**Comment by deadprogram** [comment]
That looks like a typo bug to me. Thanks for pointing that out, @esimov

**Comment by deadprogram** [comment]
This has been corrected in the `dev` branch. I will close this issue on next release.

**Comment by esimov** [comment]
@deadprogram great, thank you.

**Comment by deadprogram** [comment]
This has been released as part of v0.16.0 thank you.
