### ISSUE TITLE
Ubuntu 17.10 - Webcam not detected

### ISSUE THREAD

**Issue by alexandrevilain** [hybridgroup/gocv#27]
Hi ! 

I'm using this awesome library, thank you ! 
I was using it with MacOs X for dev, it worked well. 

But, with ubuntu 17.10 it doesn't work, and no error is displayed. I can see my webcam with mplayer for instance, but opencv doesn't start it.

Do you have any idea ? 

Thanks, 
Alexandre.

**Comment by deadprogram** [comment]
Hi @alexandrevilain 

A few questions:

- How did you install OpenCV?
- Which version of OpenCV?
- Which camera are you using?
- Do you have more than 1 camera, and if so, are you using the correct ID for that camera in your code?

**Comment by alexandrevilain** [comment]
Hi ! Thanks for you answer.

The problem, is now solved for me. The problem was my computer configuration.

Alexandre.
