### ISSUE TITLE
Run OpenCV build in parallel during Windows installation

### ISSUE THREAD

**Issue by viktor-ferenczi** [hybridgroup/gocv#275]
Installation on Windows takes a lot of time due to OpenCV compilation being very slow.

## Description

Installation on Windows is very slow even on a fast 8 core machine. Likely reason is OpenCV is not utilizing the CPU cores available.

## Steps to Reproduce
1. Follow Windows installation instructions on a multi-core machine
2. Open Task Manager and monitor CPU load
2. Notice that only a single core is utilized for compilation of cpp files during the OpenCV build

OpenCV build time was around 50 minutes (!) on a Ryzen 1800X CPU @3.6 GHz, which has 8 physical (16 logical) cores. Whole system is on an NVMe disk which can read 3.2GB/s and write 2.1GB/s. So hardware is definitely not the bottleneck here. It could go 8-15x faster with build parallelism enabled.

Looks like mingw is making is super slow as well (filesystem access is slow?), but parallelism should still help it that option is available for the OpenCV build.

## Your Environment

* Operating System and version: Windows 10 Pro 64bit
* OpenCV version used: 3.4.2
* How did you install OpenCV: Followed Windows installation instructions
* GoCV version used: 0.15.0
* Go version: 1.10.3
* Did you run the `env.sh` or `env.cmd` script before trying to `go run` or `go build`: No

**Comment by deadprogram** [comment]
You might want to try to if this works:

```
mingw32-make -j%NUMBER_OF_PROCESSORS%
```

That would use all available processors for the build.

If that works as expected, we can add to the default install/build script https://github.com/hybridgroup/gocv/blob/master/win_build_opencv.cmd#L15

**Comment by deadprogram** [comment]
This is now part of the `dev` branch. I will close this issue after the next release.

Thanks for pointing it out, and helping test this out @viktor-ferenczi

**Comment by deadprogram** [comment]
This has been released as part of v0.16.0 thank you.
