### ISSUE TITLE
release tags are not v-prefixed

### ISSUE THREAD

**Issue by danp** [hybridgroup/gocv#284]
## Description

For releases to work with initial support for [modules](https://github.com/golang/go/wiki/Modules#modules) in Go 1.11, they need to be prefixed with `v`.

## Steps to Reproduce

1. use gocv in a new modules-enabled project
2. `go build` and friends find v0.9.0 which is the last `v`-prefixed tag

## Your Environment
* Operating System and version: macOS 10.12.6
* OpenCV version used: 3.4.2
* How did you install OpenCV? homebrew
* GoCV version used: 0.15.0
* Go version: 1.11

**Comment by deadprogram** [comment]
I know that Go decided to require the `v` prefix which was not something I personally agreed with. Semver does not require that. However, we will switch back to the v-prefix just to conform with the rest of the ecosystem on the next release.

**Comment by danp** [comment]
Thanks!

**Comment by deadprogram** [comment]
The latest version includes the v prefix. Thanks again for pointing out. Now closing.
