### ISSUE TITLE
Pls Add CUDA support

### ISSUE THREAD

**Issue by deepch** [hybridgroup/gocv#287]
I will very much wait for cuda without it to work very slowly.

I'm using rtsp camera stream 
gocv + ffmpeg no cuda + cv no cuda = 100% all cpu core and 0 gpu
c code + ffmpeg cuda + cv cuda = 5-10% one core cpu and 10% gpu

Thank you very much for your work, CUDA is really needed.

**Comment by deadprogram** [comment]
True indeed!

**Comment by er1z** [comment]
It'll be better with OpenCL, not bound to single-vendored CUDA.

**Comment by devops787** [comment]
Hi. 

Is there any support for GPUs (OpenCL or Cuda)? I've found that there are some backend and targets for GPUs (like OpenCL, Vulcan) and it's possible to enable Cuda during the OpenCV compilation. Is it a fake or how to use DNN with GPUs (for example, GTX 1060/1080)?

**Comment by deadprogram** [comment]
Some CUDA support has been in GoCV for a couple releases now, so now closing. Thank you.
