### ISSUE TITLE
Calling CascadeClassifier with non-default params

### ISSUE THREAD

**Issue by jhorowitz** [hybridgroup/gocv#29]
The [opencv docs show](https://docs.opencv.org/2.4/modules/objdetect/doc/cascade_classification.html#cascadeclassifier-detectmultiscale)  that I should be able to fine tune some settings on the cascade classifier like scaleFactor and minNeighbors. Is there a way to modify these settings via gocv?

Thanks in advance!

**Comment by deadprogram** [comment]
Hi @jhorowitz I just added https://github.com/hybridgroup/gocv/commit/b056a34804b8e4731780fe5d7516cd5fdcdd603e with a function `DetectMultiScaleWithParams()`

This is the pattern we've been using so far, having a function that calls using all the default values, then another with all of the params. Seems simpler than trying to handle the CGo boundary and the difficulty in overloaded functions.

I will leave this issue open until the code gets to the next release, but you can try it in the `dev` branch now.

**Comment by jhorowitz** [comment]
Thank you! I appreciate the quick response.

**Comment by deadprogram** [comment]
This has now been released as part of v0.5.0 so now closing.

**Comment by jhorowitz** [comment]
Thank you!
