### ISSUE TITLE
use Surf problem   exit status 3221225477

### ISSUE THREAD

**Issue by nan534582559** [hybridgroup/gocv#293]
Description

detector := contrib.NewSURF()
pKeyPoint = detector.Detect(img)

but have some problem:
exit status 3221225477

My Environment
· Operating System and version:Windows10
· OpenCV version used:3.4.2
· GoCV version used:0.16.0
· Go version:go version go1.11 windows/amd64

**Comment by deadprogram** [comment]
Hello @nan534582559 you probably need to convert your img Mat to grayscale. I suggest you look at the test for SURF here: https://github.com/hybridgroup/gocv/blob/master/contrib/xfeatures2d_test.go#L40

Hope that helps!

**Comment by nan534582559** [comment]
thank you  very much

**Comment by nan534582559** [comment]
My code:
package main

import (
	"fmt"

	"gocv.io/x/gocv"
	"gocv.io/x/gocv/contrib"
)

func main() {
	img := gocv.IMRead("1.jpg", gocv.IMReadGrayScale)
	if img.Empty() {
		fmt.Print("Invalid Mat in SURF test")
	}
	defer img.Close()

	dst := gocv.NewMat()
	defer dst.Close()

	si := contrib.NewSURF()
	defer si.Close()

	kp := si.Detect(img)
	if len(kp) == 512 {
		fmt.Print("Invalid KeyPoint array in SURF Detect: %d", len(kp))
	}

	mask := gocv.NewMat()
	defer mask.Close()

	kp2, desc := si.DetectAndCompute(img, mask)
	if len(kp2) == 512 {
		fmt.Print("Invalid KeyPoint array in SURF DetectAndCompute: %d", len(kp2))
	}

	if desc.Empty() {
		fmt.Print("Invalid Mat desc in SURF DetectAndCompute")
	}
}

the problem same

**Comment by deadprogram** [comment]
The unit test passes, so we know that it "works" per se. Something went wrong with your code formatting, but in any case, I suggest you look carefully at the unit test and compare with your own code.

**Comment by deadprogram** [comment]
The unit test is best place to examine for clues.

**Comment by nan534582559** [comment]
If I run 
> C:\Users\Admin\go\src\gocv.io\x\gocv>go test -run SURF
> testing: warning: no tests to run
> PASS
> ok      gocv.io/x/gocv  0.116s

then I run 

> C:\Users\Admin\go\src\gocv.io\x\gocv>go test -args classpath C:\Users\Admin\go\src\gocv.io\x\gocv\contrib\xfeatures2d_te
> st.go
> Exception 0xc0000005 0x0 0x20 0x7ffbc0850638
> PC=0x7ffbc0850638
> runtime: unknown pc 0x7ffbc0850638
> stack: frame={sp:0x6e0cb70, fp:0x0} stack=[0x0,0x6e0feb0)
> 0000000006e0ca70:  0000000002b604e8  0000000006e0ca88
> ..........
> 0000000006e0cc60:  00007ffbd35333c7  0000000000000001
> runtime: unknown pc 0x7ffbc0850638
> stack: frame={sp:0x6e0cb70, fp:0x0} stack=[0x0,0x6e0feb0)
> 0000000006e0ca70:  0000000002b604e8  0000000006e0ca88goroutine 113 [syscall]:
> gocv.io/x/gocv._Cfunc_ORB_Detect(0x2a12bf0, 0x64d9a70, 0x0, 0x0)
>         _cgo_gotypes.go:3958 +0x54
> gocv.io/x/gocv.(*ORB).Detect.func1(0x2a12bf0, 0x64d9a70, 0x0, 0x0)
>         C:/Users/Admin/go/src/gocv.io/x/gocv/features2d.go:319 +0x9b
> gocv.io/x/gocv.(*ORB).Detect(0xc00043bf30, 0x64d9a70, 0x0, 0x0, 0x0)
>         C:/Users/Admin/go/src/gocv.io/x/gocv/features2d.go:319 +0x54
> gocv.io/x/gocv.TestORB(0xc0000aa200)
>         C:/Users/Admin/go/src/gocv.io/x/gocv/features2d_test.go:190 +0x130
> testing.tRunner(0xc0000aa200, 0x60b920)
>         C:/Go/src/testing/testing.go:827 +0xc6
> created by testing.(*T).Run
>         C:/Go/src/testing/testing.go:878 +0x35a
> 
> goroutine 1 [chan receive]:
> testing.(*T).Run(0xc0000aa200, 0x5fc876, 0x7, 0x60b920, 0x474801)
>         C:/Go/src/testing/testing.go:879 +0x381
> testing.runTests.func1(0xc0000aa000)
>         C:/Go/src/testing/testing.go:1119 +0x7f
> testing.tRunner(0xc0000aa000, 0xc00007de08)
>         C:/Go/src/testing/testing.go:827 +0xc6
> testing.runTests(0xc000052420, 0x59f840, 0xaa, 0xaa, 0x40d6f9)
>         C:/Go/src/testing/testing.go:1117 +0x2b1
> testing.(*M).Run(0xc0000a8000, 0x0)
>         C:/Go/src/testing/testing.go:1034 +0x16c
> main.main()
>         _testmain.go:380 +0x144

I don't know how to do

**Comment by deadprogram** [comment]
The message `testing: warning: no tests to run` in your output shows you did not run that test, as it is in the `contrib` sub-package. The correct syntax is:

```
go test ./contrib -run SURF
```

**Comment by nan534582559** [comment]
I change the computer, and I chang the reinstall the software,it works. and I think the problem is my  computer has Other installations opencv2.4*.

**Comment by nan534582559** [comment]
if I run 

> go test ./contrib -run SURF

the result is

> C:\Users\Admin\go\src\gocv.io\x\gocv>go test ./contrib -run SURF
> exit status 3221225477
> FAIL  gocv.io/x/gocv/contrib  0.293s

**Comment by deadprogram** [comment]
As you can tell from Appveyor CI that test is passing, so I would check your local configuration.

https://ci.appveyor.com/project/deadprogram/gocv#L518

**Comment by nan534582559** [comment]
C:\Users\Admin\go\src\gocv.io\x\gocv>echo %PATH%
C:\ProgramData\Oracle\Java\javapath;C:\python36\Scripts\;C:\python36\;C:\Program Files (x86)\Intel\Intel(R) Management E
ngine Components\iCLS\;C:\Program Files\Intel\Intel(R) Management Engine Components\iCLS\;C:\Windows\system32;C:\Windows
;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Intel\Intel(R) Management E
ngine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel
(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (
x86)\Skype\Phone\;C:\Program Files\TortoiseSVN\bin;C:\Program Files\Git\cmd;C:\Program Files (x86)\GtkSharp\2.12\bin;C:\
Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;
C:\Python27;C:\Python27\Scripts;C:\opencv\build\install\x64\mingw\bin;C:\Program Files\mingw-w64\x86_64-7.3.0-posix-seh-
rt_v5-rev0\mingw64\bin;C:\Program Files\CMake\bin;C:\Go\bin;C:\Users\Admin\AppData\Local\Microsoft\WindowsApps;C:\Users\
Admin\AppData\Roaming\npm;%GOPATH%\bin;C:\Program Files\CMake\bin;C:\Program Files\mingw-w64\x86_64-7.3.0-posix-seh-rt_v
5-rev0\mingw64\bin

C:\Users\Admin\go\src\gocv.io\x\gocv>echo %GOPATH%
C:\Users\Admin\go

C:\Users\Admin\go\src\gocv.io\x\gocv>go version
go version go1.10.4 windows/amd64

C:\Users\Admin\go\src\gocv.io\x\gocv>go get -d .

C:\Users\Admin\go\src\gocv.io\x\gocv>go env
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\Admin\AppData\Local\go-build
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\Users\Admin\go
set GORACE=
set GOROOT=C:\Go
set GOTMPDIR=
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\Admin\AppData\Local\Temp\go-build885541182=
/tmp/go-build -gno-record-gcc-switches

C:\Users\Admin\go\src\gocv.io\x\gocv>go test -v .
=== RUN   TestFisheyeUndistorImage
--- PASS: TestFisheyeUndistorImage (0.21s)
=== RUN   TestFisheyeUndistorImageWithParams
--- PASS: TestFisheyeUndistorImageWithParams (0.20s)
=== RUN   TestMat
--- PASS: TestMat (0.00s)
=== RUN   TestMatFromBytesWithEmptyByteSlise
--- PASS: TestMatFromBytesWithEmptyByteSlise (0.00s)
=== RUN   TestMatWithSize
--- PASS: TestMatWithSize (0.00s)
=== RUN   TestMatWithSizeFromScalar
--- PASS: TestMatWithSizeFromScalar (0.00s)
=== RUN   TestMatFromPtr
--- PASS: TestMatFromPtr (0.00s)
=== RUN   TestMatClone
--- PASS: TestMatClone (0.00s)
=== RUN   TestMatCopyTo
--- PASS: TestMatCopyTo (0.00s)
=== RUN   TestMatCopyToWithMask
--- PASS: TestMatCopyToWithMask (0.00s)
=== RUN   TestMatToBytes
--- PASS: TestMatToBytes (0.00s)
=== RUN   TestMatDataPtr
=== RUN   TestMatDataPtr/Uint8
=== RUN   TestMatDataPtr/Int8
=== RUN   TestMatDataPtr/Uint16
=== RUN   TestMatDataPtr/Int16
=== RUN   TestMatDataPtr/Float32
=== RUN   TestMatDataPtr/Float64
--- PASS: TestMatDataPtr (0.00s)
    --- PASS: TestMatDataPtr/Uint8 (0.00s)
    --- PASS: TestMatDataPtr/Int8 (0.00s)
    --- PASS: TestMatDataPtr/Uint16 (0.00s)
    --- PASS: TestMatDataPtr/Int16 (0.00s)
    --- PASS: TestMatDataPtr/Float32 (0.00s)
    --- PASS: TestMatDataPtr/Float64 (0.00s)
=== RUN   TestMatRegion
--- PASS: TestMatRegion (0.00s)
=== RUN   TestMatReshape
--- PASS: TestMatReshape (0.00s)
=== RUN   TestMatPatchNaNs
--- PASS: TestMatPatchNaNs (0.00s)
=== RUN   TestMatConvert
--- PASS: TestMatConvert (0.00s)
=== RUN   TestMatConvertFp16
--- PASS: TestMatConvertFp16 (0.00s)
=== RUN   TestMatSqrt
--- PASS: TestMatSqrt (0.00s)
=== RUN   TestMatMean
--- PASS: TestMatMean (0.00s)
=== RUN   TestLUT
--- PASS: TestLUT (0.00s)
=== RUN   TestMatAccessors
--- PASS: TestMatAccessors (0.00s)
=== RUN   TestMatMutators
=== RUN   TestMatMutators/SetTo
=== RUN   TestMatMutators/SetUCharAt
=== RUN   TestMatMutators/SetUCharAt3
=== RUN   TestMatMutators/SetSCharAt
=== RUN   TestMatMutators/SetSCharAt3
=== RUN   TestMatMutators/SetShortAt
=== RUN   TestMatMutators/SetShortAt3
=== RUN   TestMatMutators/SetIntAt
=== RUN   TestMatMutators/SetIntAt3
=== RUN   TestMatMutators/SetFloatAt
=== RUN   TestMatMutators/SetFloatAt3
=== RUN   TestMatMutators/SetDoubleAt
=== RUN   TestMatMutators/SetDoubleAt3
=== RUN   TestMatMutators/AddUChar
=== RUN   TestMatMutators/SubtractUChar
=== RUN   TestMatMutators/MultiplyUChar
=== RUN   TestMatMutators/DivideUChar
=== RUN   TestMatMutators/AddFloat
=== RUN   TestMatMutators/SubtractFloat
=== RUN   TestMatMutators/MultiplyFloat
=== RUN   TestMatMutators/DivideFloat
--- PASS: TestMatMutators (0.00s)
    --- PASS: TestMatMutators/SetTo (0.00s)
    --- PASS: TestMatMutators/SetUCharAt (0.00s)
    --- PASS: TestMatMutators/SetUCharAt3 (0.00s)
    --- PASS: TestMatMutators/SetSCharAt (0.00s)
    --- PASS: TestMatMutators/SetSCharAt3 (0.00s)
    --- PASS: TestMatMutators/SetShortAt (0.00s)
    --- PASS: TestMatMutators/SetShortAt3 (0.00s)
    --- PASS: TestMatMutators/SetIntAt (0.00s)
    --- PASS: TestMatMutators/SetIntAt3 (0.00s)
    --- PASS: TestMatMutators/SetFloatAt (0.00s)
    --- PASS: TestMatMutators/SetFloatAt3 (0.00s)
    --- PASS: TestMatMutators/SetDoubleAt (0.00s)
    --- PASS: TestMatMutators/SetDoubleAt3 (0.00s)
    --- PASS: TestMatMutators/AddUChar (0.00s)
    --- PASS: TestMatMutators/SubtractUChar (0.00s)
    --- PASS: TestMatMutators/MultiplyUChar (0.00s)
    --- PASS: TestMatMutators/DivideUChar (0.00s)
    --- PASS: TestMatMutators/AddFloat (0.00s)
    --- PASS: TestMatMutators/SubtractFloat (0.00s)
    --- PASS: TestMatMutators/MultiplyFloat (0.00s)
    --- PASS: TestMatMutators/DivideFloat (0.00s)
=== RUN   TestMatAbsDiff
--- PASS: TestMatAbsDiff (0.00s)
=== RUN   TestMatAdd
--- PASS: TestMatAdd (0.00s)
=== RUN   TestMatAddWeighted
--- PASS: TestMatAddWeighted (0.00s)
=== RUN   TestMatBitwiseOperations
--- PASS: TestMatBitwiseOperations (0.00s)
=== RUN   TestMatInRange
--- PASS: TestMatInRange (0.00s)
=== RUN   TestMatInRangeWithScalar
--- PASS: TestMatInRangeWithScalar (0.00s)
=== RUN   TestMatDCT
--- PASS: TestMatDCT (0.00s)
=== RUN   TestMatDFT
--- PASS: TestMatDFT (0.00s)
=== RUN   TestMatDivide
--- PASS: TestMatDivide (0.00s)
=== RUN   TestMeanStdDev
--- PASS: TestMeanStdDev (0.00s)
=== RUN   TestMatMerge
--- PASS: TestMatMerge (0.00s)
=== RUN   TestMatMultiply
--- PASS: TestMatMultiply (0.00s)
=== RUN   TestMatNormalize
--- PASS: TestMatNormalize (0.00s)
=== RUN   TestMatPerspectiveTransform
--- PASS: TestMatPerspectiveTransform (0.00s)
=== RUN   TestMatSplit
--- PASS: TestMatSplit (0.00s)
=== RUN   TestMatSubtract
--- PASS: TestMatSubtract (0.00s)
=== RUN   TestMatTransform
--- PASS: TestMatTransform (0.00s)
=== RUN   TestMatTranspose
--- PASS: TestMatTranspose (0.00s)
=== RUN   TestMatPow
--- PASS: TestMatPow (0.00s)
=== RUN   TestMatSum
--- PASS: TestMatSum (0.00s)
=== RUN   TestTermCriteria
--- PASS: TestTermCriteria (0.00s)
=== RUN   TestScalar
--- PASS: TestScalar (0.00s)
=== RUN   TestToCPoints
--- PASS: TestToCPoints (0.00s)
=== RUN   TestToCStrings
--- PASS: TestToCStrings (0.00s)
=== RUN   TestMatBatchDistance
--- PASS: TestMatBatchDistance (0.00s)
=== RUN   TestMatBorderInterpolate
--- PASS: TestMatBorderInterpolate (0.00s)
=== RUN   TestMatCalcCovarMatrix
--- PASS: TestMatCalcCovarMatrix (0.00s)
=== RUN   TestMatCartToPolar
--- PASS: TestMatCartToPolar (0.00s)
=== RUN   TestMatCheckRange
--- PASS: TestMatCheckRange (0.00s)
=== RUN   TestMatCompleteSymm
--- PASS: TestMatCompleteSymm (0.00s)
=== RUN   TestMatConvertScaleAbs
--- PASS: TestMatConvertScaleAbs (0.00s)
=== RUN   TestMatCopyMakeBorder
--- PASS: TestMatCopyMakeBorder (0.00s)
=== RUN   TestMatDeterminant
--- PASS: TestMatDeterminant (0.00s)
=== RUN   TestMatEigen
--- PASS: TestMatEigen (0.00s)
=== RUN   TestMatEigenNonSymmetric
--- PASS: TestMatEigenNonSymmetric (0.00s)
=== RUN   TestMatExp
--- PASS: TestMatExp (0.00s)
=== RUN   TestMatExtractChannel
--- PASS: TestMatExtractChannel (0.00s)
=== RUN   TestMatFindNonZero
--- PASS: TestMatFindNonZero (0.00s)
=== RUN   TestMatFlip
--- PASS: TestMatFlip (0.00s)
=== RUN   TestMatGemm
--- PASS: TestMatGemm (0.00s)
=== RUN   TestMatHconcat
--- PASS: TestMatHconcat (0.00s)
=== RUN   TestMatVconcat
--- PASS: TestMatVconcat (0.00s)
=== RUN   TestRotate
--- PASS: TestRotate (0.00s)
=== RUN   TestMatIdct
--- PASS: TestMatIdct (0.00s)
=== RUN   TestMatIdft
--- PASS: TestMatIdft (0.00s)
=== RUN   TestMatInsertChannel
--- PASS: TestMatInsertChannel (0.00s)
=== RUN   TestMatInvert
--- PASS: TestMatInvert (0.00s)
=== RUN   TestMatLog
--- PASS: TestMatLog (0.00s)
=== RUN   TestMatMagnitude
--- PASS: TestMatMagnitude (0.00s)
=== RUN   TestMatMax
--- PASS: TestMatMax (0.00s)
=== RUN   TestMatMin
--- PASS: TestMatMin (0.00s)
=== RUN   TestMatMinMaxIdx
--- PASS: TestMatMinMaxIdx (0.00s)
=== RUN   TestMatToImage
--- PASS: TestMatToImage (0.00s)
=== RUN   TestImageToMatRGBA
--- PASS: TestImageToMatRGBA (0.06s)
=== RUN   TestImageToMatRGB
--- PASS: TestImageToMatRGB (0.04s)
=== RUN   TestImageGrayToMatGray
--- PASS: TestImageGrayToMatGray (0.02s)
=== RUN   TestGetVecfAt
--- PASS: TestGetVecfAt (0.00s)
=== RUN   TestGetVeciAt
--- PASS: TestGetVeciAt (0.00s)
=== RUN   TestGetTickFrequencyCount
--- PASS: TestGetTickFrequencyCount (0.00s)
=== RUN   TestReadNet
--- SKIP: TestReadNet (0.00s)
        dnn_test.go:12: Unable to locate Caffe model files for tests
=== RUN   TestCaffe
--- SKIP: TestCaffe (0.00s)
        dnn_test.go:92: Unable to locate Caffe model files for tests
=== RUN   TestTensorflow
--- SKIP: TestTensorflow (0.00s)
        dnn_test.go:138: Unable to locate Tensorflow model file for tests
=== RUN   TestGetBlobChannel
--- PASS: TestGetBlobChannel (0.00s)
=== RUN   TestGetBlobSize
--- PASS: TestGetBlobSize (0.00s)
=== RUN   TestParseNetBackend
--- PASS: TestParseNetBackend (0.00s)
=== RUN   TestParseNetTarget
--- PASS: TestParseNetTarget (0.00s)
=== RUN   TestFP16BlobFromImage
--- PASS: TestFP16BlobFromImage (0.00s)
=== RUN   TestAKAZE
--- PASS: TestAKAZE (0.11s)
=== RUN   TestAgastFeatureDetector
--- PASS: TestAgastFeatureDetector (0.01s)
=== RUN   TestBRISK
--- PASS: TestBRISK (0.46s)
=== RUN   TestFastFeatureDetector
--- PASS: TestFastFeatureDetector (0.00s)
=== RUN   TestGFTTDetector
--- PASS: TestGFTTDetector (0.01s)
=== RUN   TestKAZE
--- PASS: TestKAZE (0.63s)
=== RUN   TestMSER
--- PASS: TestMSER (0.13s)
=== RUN   TestORB
Exception 0xc0000005 0x0 0x20 0x7ffc32640638
PC=0x7ffc32640638

runtime: unknown pc 0x7ffc32640638
stack: frame={sp:0x696cb20, fp:0x0} stack=[0x6771ed0,0x696fed0)
000000000696ca20:  00000000029e04e8  000000000696ca38
000000000696ca30:  0000000000000001  00007ffc00000003
000000000696ca40:  00007ffc3250c970  0000000000000000
000000000696ca50:  000000000696cc70  0000000007433070
000000000696ca60:  000000000696cc70  0000000002a01b00
000000000696ca70:  0000000000000000  0000000000000001
000000000696ca80:  0000000000000000  00007ffc32711da8
000000000696ca90:  0000000000000001  0000000007433070
000000000696caa0:  00007ffc425c1780  000000000696cc70
000000000696cab0:  0000000002a344a0  00007ffc32712884
000000000696cac0:  00000000000003a1  00000000000003a1
000000000696cad0:  0000000000000000  0000000002a1ade0
000000000696cae0:  00000000000003a1  00007ffc3264f215
000000000696caf0:  00007ffc3252bcb0  0000000007433070
000000000696cb00:  0000000000000001  0000000002a01b00
000000000696cb10:  0000000002a344a0  00007ffc32640627
000000000696cb20: <00000000074328d0  0000000000000001
000000000696cb30:  0000000000000000  0000000000000000
000000000696cb40:  00007ffc425c1780  00007ffc32971c50
000000000696cb50:  000000000696cc70  000000000696cc68
000000000696cb60:  0000000002a34f18  00007ffc327bb018
000000000696cb70:  0000000000000001  00007ffc3251d97b
000000000696cb80:  000000000696cc68  00007ffc326dc388
000000000696cb90:  0000000000000001  0000000000000000
000000000696cba0:  fffffffffffffffe  0000000002a349f0
000000000696cbb0:  00007ffc32971c50  00007ffc3252d990
000000000696cbc0:  0000000000000c01  0000979772e8fcb6
000000000696cbd0:  0000000000000001  0000000002a349f0
000000000696cbe0:  00007ffc425c1780  0000000002a34f18
000000000696cbf0:  00007ffc32971c50  00007ffc327bb018
000000000696cc00:  0000000000000001  00007ffc3255b7b0
000000000696cc10:  00007ffc426033c7  0000000000000001
runtime: unknown pc 0x7ffc32640638
stack: frame={sp:0x696cb20, fp:0x0} stack=[0x6771ed0,0x696fed0)
000000000696ca20:  00000000029e04e8  000000000696ca38
000000000696ca30:  0000000000000001  00007ffc00000003
000000000696ca40:  00007ffc3250c970  0000000000000000
000000000696ca50:  000000000696cc70  0000000007433070
000000000696ca60:  000000000696cc70  0000000002a01b00
000000000696ca70:  0000000000000000  0000000000000001
000000000696ca80:  0000000000000000  00007ffc32711da8
000000000696ca90:  0000000000000001  0000000007433070
000000000696caa0:  00007ffc425c1780  000000000696cc70
000000000696cab0:  0000000002a344a0  00007ffc32712884
000000000696cac0:  00000000000003a1  00000000000003a1
000000000696cad0:  0000000000000000  0000000002a1ade0
000000000696cae0:  00000000000003a1  00007ffc3264f215
000000000696caf0:  00007ffc3252bcb0  0000000007433070
000000000696cb00:  0000000000000001  0000000002a01b00
000000000696cb10:  0000000002a344a0  00007ffc32640627
000000000696cb20: <00000000074328d0  0000000000000001
000000000696cb30:  0000000000000000  0000000000000000
000000000696cb40:  00007ffc425c1780  00007ffc32971c50
000000000696cb50:  000000000696cc70  000000000696cc68
000000000696cb60:  0000000002a34f18  00007ffc327bb018
000000000696cb70:  0000000000000001  00007ffc3251d97b
000000000696cb80:  000000000696cc68  00007ffc326dc388
000000000696cb90:  0000000000000001  0000000000000000
000000000696cba0:  fffffffffffffffe  0000000002a349f0
000000000696cbb0:  00007ffc32971c50  00007ffc3252d990
000000000696cbc0:  0000000000000c01  0000979772e8fcb6
000000000696cbd0:  0000000000000001  0000000002a349f0
000000000696cbe0:  00007ffc425c1780  0000000002a34f18
000000000696cbf0:  00007ffc32971c50  00007ffc327bb018
000000000696cc00:  0000000000000001  00007ffc3255b7b0
000000000696cc10:  00007ffc426033c7  0000000000000001

goroutine 177 [syscall]:
gocv.io/x/gocv._Cfunc_ORB_Detect(0x30f8d20, 0x5a93d10, 0x0, 0x0)
        _cgo_gotypes.go:3958 +0x54
gocv.io/x/gocv.(*ORB).Detect.func1(0x30f8d20, 0x5a93d10, 0x0, 0x0)
        C:/Users/Admin/go/src/gocv.io/x/gocv/features2d.go:319 +0x9b
gocv.io/x/gocv.(*ORB).Detect(0xc04243df30, 0x5a93d10, 0x0, 0x0, 0x0)
        C:/Users/Admin/go/src/gocv.io/x/gocv/features2d.go:319 +0x54
gocv.io/x/gocv.TestORB(0xc0420bd2c0)
        C:/Users/Admin/go/src/gocv.io/x/gocv/features2d_test.go:190 +0x12f
testing.tRunner(0xc0420bd2c0, 0x5d7748)
        C:/Go/src/testing/testing.go:777 +0xd7
created by testing.(*T).Run
        C:/Go/src/testing/testing.go:824 +0x2e7

goroutine 1 [chan receive]:
testing.(*T).Run(0xc0420bd2c0, 0x5c8a4e, 0x7, 0x5d7748, 0x472201)
        C:/Go/src/testing/testing.go:825 +0x308
testing.runTests.func1(0xc0420bc000)
        C:/Go/src/testing/testing.go:1063 +0x6b
testing.tRunner(0xc0420bc000, 0xc04207fdf8)
        C:/Go/src/testing/testing.go:777 +0xd7
testing.runTests(0xc04205c420, 0x6de640, 0xaa, 0xaa, 0x410ed3)
        C:/Go/src/testing/testing.go:1061 +0x2cb
testing.(*M).Run(0xc0420b4000, 0x0)
        C:/Go/src/testing/testing.go:978 +0x178
main.main()
        _testmain.go:380 +0x158
rax     0x0
rbx     0x74328d0
rcx     0x1
rdi     0x2a344a0
rsi     0x2a1ade0
rbp     0x0
rsp     0x696cb20
r8      0x0
r9      0x7466bd0
r10     0x743e480
r11     0x696ca90
r12     0x696cc70
r13     0x7ffc425c1780
r14     0x7433070
r15     0x1
rip     0x7ffc32640638
rflags  0x10202
cs      0x33
fs      0x53
gs      0x2b
FAIL    gocv.io/x/gocv  2.034s

C:\Users\Admin\go\src\gocv.io\x\gocv>

**Comment by nan534582559** [comment]
I Reinstalled Windows. it is Ok now
