### ISSUE TITLE
support for writing mp4 video file

### ISSUE THREAD

**Issue by frpunzalan** [hybridgroup/gocv#299]
## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Operating System and version: ubuntu 16.04
* OpenCV version used: 3.4.2
* How did you install OpenCV? by compiling source code
* GoCV version used:
* Go version: 1.11
* Did you run the `env.sh` or `env.cmd` script before trying to `go run` or `go build`? 

I just want to ask if I can write mp4 (h264) video files with gocv. Is it possible?

Thanks.

**Comment by deadprogram** [comment]
Hello @frpunzalan take a look at https://godoc.org/gocv.io/x/gocv#VideoWriterFile which does support MP4 output.

Hope that helps!
