### ISSUE TITLE
Unable to install it in windows 10 !!!

### ISSUE THREAD

**Issue by mohit83k** [hybridgroup/gocv#303]
There was no include folder in opencv directory. 

## Description

I tried to install gocv using the given instruction. Only thing that was different was error Handling method while installing MingW. " seh " method was not available while installing MingW. [( image while installing )](https://i.stack.imgur.com/cs3qO.png)  . So i did it using "sjlj " method and changed the appropriate directory in win_build_opencv.cmd.  It compiled till the end , but there was no include directory and i was not able to check the installation i.e couldn't check the version.

## Steps to Reproduce

1. Install MingW with "sjlj" exception method.
2 .Change the path of MinW in win_build_opencv.cmd

## Your Environment

* Operating System and version: windows 10 , 64-bit operating system , x64-based processor
* OpenCV version used: Default
* How did you install OpenCV?
* GoCV version used: Master Branch
* Go version:  go1.11 windows/amd64
* Did you run the `env.sh` or `env.cmd` script before trying to `go run` or `go build`? No

**Comment by deadprogram** [comment]
Looks like you downloaded the wrong version of compiler to me. Make sure you use the 7.3.0+ version that can be located at the https://sourceforge.net/projects/mingw-w64/files/ page.

**Comment by deadprogram** [comment]
ALso you must run both `mingw32-make` and `mingw32-make install` commands to both build and install OpenCV. Hope that helps!

**Comment by mohit83k** [comment]
> Looks like you downloaded the wrong version of compiler to me. Make sure you use the 7.3.0+ version that can be located at the https://sourceforge.net/projects/mingw-w64/files/ page.

Thank you for your reply.  I recompiled it and it worked.  It required cmd in administrator mode and console window doesn't close while running the Hello,Video example

**Comment by deadprogram** [comment]
Glad it worked out. Now closing.
