### ISSUE TITLE
Converting mat to bytes and back to mat causes image to be seriously distorted

### ISSUE THREAD

**Issue by afdozerman** [hybridgroup/gocv#330]
## Description

![screenshot from 2018-10-04 18-06-05](https://user-images.githubusercontent.com/6539752/46508253-523cb480-c802-11e8-8346-574c0f6ffefc.png)

The eventual objective here is to create a live video stream from a camera to a computer that would process the video by encoding an OpenCV mat and sending from one Go process to another. The problem that I'm running into is that, when I use mat.ToBytes() and then gocv.NewMatFromBytes(), the resulting image is skewed and loses its color. 

The attached image is a screenshot of the program being run. The left window is what happens when the mat is converted to a byte slice and back again and the right window is the expected output. The rest of the source code was copied from the first example on the gocv website.

As far as possible solutions I've already tried, I tried toying with the Mat types but this proved fruitless. I've also tried playing around with the output image size (adding and subtracting from rows/cols) with no success. 

Source code:

```
package main

import (
	"gocv.io/x/gocv"
	"fmt"
)

func main() {
	webcam, _ := gocv.VideoCaptureDevice(0)
	window := gocv.NewWindow("From Bytes")
	window2 := gocv.NewWindow("Without Conversion")
	img := gocv.NewMat()
	
	var buffer []byte

	for {
		webcam.Read(&img)
		
		buffer = img.ToBytes()
		
		image2, err := gocv.NewMatFromBytes(img.Rows(),img.Cols(),1,buffer)
		if err != nil{
			fmt.Println("Oopsie daisy. I made a boo boo!", err)
		}
		
		window.IMShow(image2)
		window.WaitKey(1)
		
		window2.IMShow(img)
		window2.WaitKey(1)
	}
}

```

## Steps to Reproduce
Steps to reproduce:
1. Compile/run above code
2. Stand back and scratch head

## Your Environment

* Operating System and version:
Pop!_OS (Ubuntu derivative) 

* OpenCV version used:
3

* How did you install OpenCV?
Followed the instructions from gocv.io

* GoCV version used:
Most recent (clean, new install)

* Go version:
1.10.1

* Did you run the `env.sh` or `env.cmd` script before trying to `go run` or `go build`?
No.

**Comment by dougnd** [comment]
The code looks very close!  It does look to be a problem with the Mat type.  Specifically, since it is a color image, you probably want to use type `gocv. MatTypeCV8UC3` (a 3 channel; 8 bits/channel) Mat type.  Or, rather than guess, you can use `img.Type()`.  So I'd suggest you change the line to be

```
image2, err := gocv.NewMatFromBytes(img.Rows(),img.Cols(),img.Type(),buffer)
```

As a heads up, `NewMatFromBytes` will create a new Mat that ought to be closed.  So after the IMShows, you may want to do a `image2.Close()`. Otherwise you would have a (admittedly very small) memory leak.

Hope this helps!

**Comment by afdozerman** [comment]
Of course. I facepalmed harder than I should have when I realized the issue. So simple. This works perfectly. Thank you!
![facepalm](https://user-images.githubusercontent.com/6539752/46512191-33e1b380-c818-11e8-8969-e2dd85286143.png)

**Comment by wgjtyu** [comment]
Updated:
I got mat by `fullImage.Region()`, similar to #535 , so solve this problem by `newMat = mat.Clone()`
and then `bytes = newMat.ToBytes()`


-----------------

still not work

here is my code:

```
func test(mat *gocv.Mat) {
	bytes := mat.ToBytes()
	win := gocv.NewWindow("w0")
	win.IMShow(*mat)
	win1 := gocv.NewWindow("w1")
	m1, err := gocv.NewMatFromBytes(mat.Rows(), mat.Cols(), mat.Type(), bytes)
	fmt.Println(err) // nil
	fmt.Println(mat.Rows(), m1.Rows()) // 116 116
	fmt.Println(mat.Cols(), m1.Cols()) // 116 116
	fmt.Println(mat.Type(), m1.Type()) // CV8U CV8U
	fmt.Println(pretty.Diff(bytes, m1.ToBytes())) // []
	win1.IMShow(m1)
	win1.WaitKey(0)
}
```

<img width="312" alt="截屏2022-03-04 11 43 15" src="https://user-images.githubusercontent.com/207818/156695462-34b4702b-2ec2-4cb9-a852-d2a5cf083fc8.png">


<img width="268" alt="截屏2022-03-04 11 43 34" src="https://user-images.githubusercontent.com/207818/156695422-d112a101-aabc-42f1-93c8-cbd6547c71c9.png">



<img width="276" alt="image" src="https://user-images.githubusercontent.com/207818/156694771-bc777e4c-ce8b-476d-a006-5c01adf5d50d.png">
