### ISSUE TITLE
Face recognition bindings

### ISSUE THREAD

**Issue by andboson** [hybridgroup/gocv#34]
Hello!
How i can use facerecognize class bindings?  F.e.  LBPHFaceRecognizer and others?

**Comment by deadprogram** [comment]
Hello @andboson we do not yet have bindings for that module. 

It is part of opencv_contrib which is compiled into OpenCV if you follow our instructions, so it should be a matter of adding bindings in the same fashion that we have for other modules.

We would be very glad to accept a PR that added this functionality!

**Comment by deadprogram** [comment]
In the latest work in the `dev` branch, I have just added a `contrib` sub-package. This is where an implementation of the OpenCV contrib `face` module would go...

**Comment by andboson** [comment]
Hello
I tried to work with C in Go (first time).
Main question is how to pass function parameters from Go to C. 
How I can convert slice of Ints to C vector of C.int and slice of Mat to C vector of C.Mat?

**Comment by deadprogram** [comment]
Hello @andboson what specifically are you trying to do? Mat typically wraps around all values. Check out here for tests that also show how to reference them:

https://github.com/hybridgroup/gocv/blob/master/core_test.go#L97

**Comment by andboson** [comment]
I need pass slice of Mat`s to Facerecognizer->train(vector<Mat>, vector<int>,bool)

**Comment by deadprogram** [comment]
OK @andboson I'm working on some code to show how to pass a `[]Mat` as the needed param. More soon!

**Comment by deadprogram** [comment]
OK, here is how example of how to handle `[]Mat`

The `Merge()` function takes a slice of Mat as param:
https://github.com/hybridgroup/gocv/blob/dev/core.go#L309

Here is the associated C impl:
https://github.com/hybridgroup/gocv/blob/dev/core.cpp#L148

That should get you going. Please let me know if that is enough, or if there is anything else I can do to help.

**Comment by andboson** [comment]
Thank you!
I`ve got the first recognition! ) (used original gocv code)
But how I can run tests (and work) on fork?
I got error on my fork:
 
> drew@drew-Aspire-E1-571G ~/Gopath/src/github.com/andboson/gocv (master) $ go test ./...
> can't load package: package github.com/andboson/gocv: code in directory /home/drew/Gopath/src/github.com/andboson/gocv expects import "gocv.io/x/gocv"
> can't load package: package github.com/andboson/gocv/pvl: code in directory /home/drew/Gopath/src/github.com/andboson/gocv/pvl expects import "gocv.io/x/gocv/pvl"

**Comment by deadprogram** [comment]
This is one very easy way to handle http://blog.campoy.cat/2014/03/github-and-go-forking-pull-requests-and.html

**Comment by andboson** [comment]
Big thanks!
Maybe close this issue tread?

ps: but exists errors in my PR...

**Comment by deadprogram** [comment]
Thanks for the PR @andboson now closing this issue.

**Comment by hxdef2517** [comment]
@andboson Hi, do you have any code samples on how to do basic face recognition ?
