### ISSUE TITLE
Error while building windows exe

### ISSUE THREAD

**Issue by sushanth-s** [hybridgroup/gocv#340]
## Description
Trying to build windows exe, but getting below error

go_path/src/gocv.io/x/gocv/dnn_ext.go:9:28: undefined: Mat
go_path/src/gocv.io/x/gocv/dnn_ext.go:16:12: undefined: NewMatWithSize
go_path/src/gocv.io/x/gocv/dnn_ext.go:43:2: undefined: Resize
go_path/src/gocv.io/x/gocv/dnn_ext.go:43:38: undefined: InterpolationDefault
go_path/src/gocv.io/x/gocv/dnn_ext.go:46:3: undefined: CvtColor
go_path/src/gocv.io/x/gocv/dnn_ext.go:49:15: undefined: NewMat
go_path/src/gocv.io/x/gocv/dnn_ext.go:52:31: undefined: MatTypeCV32F

## Steps to Reproduce

Using below command to generate the exe

CGO_ENABLED=0 GOOS=windows GOARCH=386 go build -a -ldflags '-extldflags "-static" -X main.Version=0.0.1 -X main.Build=10/10/2018' -o windows_win32.exe *.go

## Your Environment

* Operating System and version: Ubuntu16.04 LTS
* GoCV version used: 0.16.0
* Go version: go1.11 linux/amd64
* go run *.go & go build *.go are working fine.

**Comment by deadprogram** [comment]
Hello @sushanth-s You cannot cross-compile code that uses OpenCV itself, you must compile on the desired target platform. This was discussed a bit in https://github.com/hybridgroup/gocv/issues/39

**Comment by sushanth-s** [comment]
@deadprogram thanks for the update, will try.
