### ISSUE TITLE
My C: diretory lacks of space, it will be kind if you support self-defined diretory

### ISSUE THREAD

**Issue by sanguohot** [hybridgroup/gocv#344]
I changed the `C:\` to `G:\` in `win_build_opencv.cmd`.
But it faild.
Then I built it with `go build -x -v`.
I found there still be some places which used `C:\`.
By the way, does it support windows7?
Any help would be greatly appreciated.

**Comment by deadprogram** [comment]
This is the same as the newer #510 so closing this one. Thanks!
