### ISSUE TITLE
Any denoising function available?

### ISSUE THREAD

**Issue by CloudTsang** [hybridgroup/gocv#346]
Hello , I'm developing an book-OCR project with golang using opencv to preprocess the paper photos.

In python , function fastNlMeansDenoising can denoise an image  , very simple and works well for most photos.
```
im = cv2.imread(path, cv2.IMREAD_GRAYSCALE)
cv2.fastNlMeansDenoising(im, im,10, 7, 21)
```

In gocv , I can't see such function or any function to denoise img provided. Fcuntion fastNlMeansDenoising is in opencv_photoXXX.dll
```
void __cdecl cv::fastNlMeansDenoising(class cv::_InputArray const & __ptr64,class cv::_OutputArray const & __ptr64,float,int,int)
```
How can I modify my code to use this function ?
Or you will add it in the following release?

Sorry for my poor English and waiting for your reponse!

**Comment by deadprogram** [comment]
Hi @CloudTsang your English is perfectly understandable. :+1: 

OK, to your question. There is not yet support in GocV for the `photo` module. It is on the roadmap https://github.com/hybridgroup/gocv/blob/master/ROADMAP.md

If you would be willing to contribute this functionality, please take a look at our contribution guidelines here: https://github.com/hybridgroup/gocv/blob/master/CONTRIBUTING.md#how-to-add-a-function-from-opencv-to-gocv

I have also tagged this issue as "enhancement".

Thanks!

**Comment by dacrypt** [comment]
Hi. I was looking for denoising options and found this. Are there any alternatives since this was published?

**Comment by kyeno** [comment]
Surprisingly this is the first result on Google, but I also found this:
https://pkg.go.dev/gocv.io/x/gocv@v0.35.0#FastNlMeansDenoising

Seems like it's implemented now.

**Comment by deadprogram** [comment]
Thanks for updating this issue @kyeno
