### ISSUE TITLE
MatchTemplate occur segmentation violation error

### ISSUE THREAD

**Issue by purplegourd** [hybridgroup/gocv#347]
## Steps to Reproduce

demo code ：

```go
package main
import (
	cv3 "gocv.io/x/gocv"
	"fmt"
)
func main() {
	tpl := cv3.IMRead("tpl.jpg",cv3.IMReadGrayScale)
	src := cv3.IMRead("source.jpg",cv3.IMReadGrayScale)
	fmt.Println(tpl,src)
	mask := cv3.IMRead("source.jpg",cv3.IMReadGrayScale)
	result := new(cv3.Mat)
	cv3.MatchTemplate(tpl,src,result,cv3.TmCcoeffNormed,mask)
	window := cv3.NewWindow("hello")
	window.IMShow(*result)
	window.WaitKey(0)
}
```

1. go run cv2.go

error as:

> fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x4 pc=0x814f0c0]

runtime stack:
runtime.throw(0x4102384, 0x2a)
	/usr/local/go/src/runtime/panic.go:608 +0x72
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:374 +0x2f2

goroutine 1 [syscall]:
runtime.cgocall(0x409b590, 0xc000040ea8, 0x29)
	/usr/local/go/src/runtime/cgocall.go:128 +0x5e fp=0xc000040e70 sp=0xc000040e38 pc=0x400596e
gocv.io/x/gocv._Cfunc_MatchTemplate(0xbd01690, 0xbd016f0, 0x0, 0x5, 0xbd01750)
	_cgo_gotypes.go:3888 +0x45 fp=0xc000040ea8 sp=0xc000040e70 pc=0x4097145
gocv.io/x/gocv.MatchTemplate.func1(0xbd01690, 0xbd016f0, 0x0, 0x5, 0xbd01750)
	/Users/yong/go/src/gocv.io/x/gocv/imgproc.go:392 +0x101 fp=0xc000040ee0 sp=0xc000040ea8 pc=0x4097b11
gocv.io/x/gocv.MatchTemplate(0xbd01690, 0xbd016f0, 0xc000040f60, 0x5, 0xbd01750)
	/Users/yong/go/src/gocv.io/x/gocv/imgproc.go:392 +0x55 fp=0xc000040f18 sp=0xc000040ee0 pc=0x4097825
main.main()
	/workspace/go_projects/opencv/cv2.go:16 +0x126 fp=0xc000040f98 sp=0xc000040f18 pc=0x4097e46
runtime.main()
	/usr/local/go/src/runtime/proc.go:201 +0x207 fp=0xc000040fe0 sp=0xc000040f98 pc=0x402c057
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1333 +0x1 fp=0xc000040fe8 sp=0xc000040fe0 pc=0x4054501
exit status 2

## Your Environment

* Operating System and version: macOS 10.14
* OpenCV version used: 3.4.3
* How did you install OpenCV? 
brew install opencv
* GoCV version used:0.17.0
* Go version: go version go1.11.1 darwin/amd64

* Did you run the `env.sh` or `env.cmd` script before trying to `go run` or `go build`?
no

**Comment by matipan** [comment]
Hi @purplegourd! The reason why you are getting this error is because in order to initialize a new `mat` you need to use the [gocv.NewMat](https://godoc.org/gocv.io/x/gocv#NewMat) function. If you then need to send a pointer to that mat you can use the `&` operator.
For example, this code causes the same error, note we are using the `new` operator to create a new mat:
```go
package main

import (
	"gocv.io/x/gocv"
)

func main() {
	window := gocv.NewWindow("test")
	result := new(gocv.Mat)
	window.IMShow(*result)
}
```
If instead we use the `NewMat` function we would have this:
```go
package main

import (
	"gocv.io/x/gocv"
)

func main() {
	window := gocv.NewWindow("test")
	result := gocv.NewMat()
        // Use &result to reference the mat
	window.IMShow(result)
}
```

Rewrite your code using `NewMat` to create the `result` mat and then reference it with `&result` and try it out

**Comment by purplegourd** [comment]
> Hi @purplegourd! The reason why you are getting this error is because in order to initialize a new `mat` you need to use the [gocv.NewMat](https://godoc.org/gocv.io/x/gocv#NewMat) function. If you need the pointer to that mat you can use the `&` operator.
> For example, this code causes the same error, note we are using the `new` operator to create a new mat:
> 
> ```go
> package main
> 
> import (
> 	"gocv.io/x/gocv"
> )
> 
> func main() {
> 	window := gocv.NewWindow("test")
> 	result := new(gocv.Mat)
> 	window.IMShow(*result)
> }
> ```
> 
> If instead we use the `NewMat` function we would have this:
> 
> ```go
> package main
> 
> import (
> 	"gocv.io/x/gocv"
> )
> 
> func main() {
> 	window := gocv.NewWindow("test")
> 	result := gocv.NewMat()
>         // Use &result to reference the mat
> 	window.IMShow(result)
> }
> ```
> 
> Rewrite your code using `NewMat` to create the `result` mat and then reference it with `&result` and try it out. I hope it works! 😄

Hi @matipan !

**Comment by absencelul** [comment]
was this issue resolved ever, i'm having the same exact error.
