### ISSUE TITLE
Information about building on macos

### ISSUE THREAD

**Issue by theovosse** [hybridgroup/gocv#348]
Under macos, `make install` (quickly) terminates with an error message: cd: OLDPWD not set. That is because the current Makefile uses .ONESHELL, which is not supported by the version of make (3.81, installed by XCode). This can be resolved by first installing make via brew (`brew install make`), which (by default) calls it gmake. So the command to build gocv on macos then becomes

    $ gmake install

Edit: if you wish to build it use make install, of course

**Comment by deadprogram** [comment]
What version of macOS are you running, @theovosse as I have been using without this on High Sierra for a while...

**Comment by theovosse** [comment]
On 10.14 (Mojave), but the version of make didn't change. On both High Sierra and Mojave, `make -v` shows "GNU Make 3.81". IIRC, this it depends on XCode, not the OS itself.

BTW, I also had a problem with the "sudo": I don't have an admin account, so a warning about admin rights in the instructions could be helpful. And ldconfig doesn't exist on the mac, so calling it causes make to fail. Performing the steps by hand works well.

**Comment by deadprogram** [comment]
Actually you should not even be using make on macOS. Please take a look at https://github.com/hybridgroup/gocv#macos

**Comment by theovosse** [comment]
I saw that, but `brew install opencv` will not only install python2, python3 without any reason, it will compile gcc-8.2 on your system before continuing with opencv. That takes forever, so I took the Linux shortcut.

**Comment by deadprogram** [comment]
Hello @theovosse we recently introduced our own smaller Homebrew recipe here:

https://github.com/hybridgroup/homebrew-tools/blob/master/opencv.rb

You might find it useful.

I am going to close this issue, please reopen if you require further assistance.

**Comment by theovosse** [comment]
Thanks!

**Comment by cyberguy2891** [comment]
I used HomeBrew to install openCV
Then I did the following:
```
export $PKG_CONFIG_PATH=/usr/local/Cellar/opencv/4.5.1_3
brew install cmake
brew install gmake
gmake install
```
