### ISSUE TITLE
Cannot access values from HoughTransform / HoughTransformP

### ISSUE THREAD

**Issue by digitalpbk** [hybridgroup/gocv#35]
How do we get the underlying rho and theta values from lines Mat 
As in the test
https://github.com/hybridgroup/gocv/blob/master/imgproc_test.go#L330

It returns a 1 D Matrix

**Comment by deadprogram** [comment]
Hi @digitalpbk 

According to the OpenCV docs, the result matrix returned from HoughLines is a 1D, 2 channel Mat that contains `float` point values. The result returned by HoughLinesP is a 1D, 4 channel Mat that contains `int` values. I added a couple of tests that show how to retrieve the elements:

https://github.com/hybridgroup/gocv/blob/dev/imgproc_test.go#L291
https://github.com/hybridgroup/gocv/blob/dev/imgproc_test.go#L329

Hope that helps!

**Comment by deadprogram** [comment]
Would be great to have a sample for `HoughLines()` similar to the one recently added by @willdurand for `HoughCircles()`

**Comment by deadprogram** [comment]
This has been released as part of v0.15.0 now closing. Thank you!
