### ISSUE TITLE
IMDecode memory leaking?

### ISSUE THREAD

**Issue by russial** [hybridgroup/gocv#353]
## Description
Hey there, I was making an imageprocessing service that should get image through http MultipartForm.
When I started to send more requests to this service I saw enormous memory consumption.
About 1GB of RAM was used after ~500 requests and it was not released back. Even manual call of GC with debug.FreeOSMemory() didn't help.
Any ideas or suggestions how to fix that?

## Steps to Reproduce
https://gist.github.com/russial/52daf395f1c9d05ac28debbca506fc00 - here is a small preview of this issue

## Your Environment

* Operating System and version: Ubuntu 18.04
* OpenCV version used: 3.4.2
* How did you install OpenCV? Ran `make install` in GoCV folder
* GoCV version used: 0.17.0
* Go version: 1.11
* Did you run the `env.sh` or `env.cmd` script before trying to `go run` or `go build`? No

**Comment by dougnd** [comment]
Hi, I tested the gist you linked using 

```
for i in {1..1000}; do curl  -F "file=@tiger.jpg" localhost:8080/file; echo $i; done
```

Where tiger.jpg was a 1200x800 image.  I saw no significant increase in memory.  Can you provide any more details on how you are testing?

I am running on Mac OS X Mojave (perhaps that is the difference?), go 1.11, and tested gocv versions 0.17.0 and the dev branch.

**Comment by aspotashev** [comment]
May be related: https://github.com/LumiGuide/haskell-opencv/issues/109

**Comment by russial** [comment]
@dougnd Thank for your comment. I tried your approach, the main trouble is that curl is synchronous and it waits for an answer from server to do next request. I just pressed F5 button in Insomnia to flood service with async requests. And memory leaking was seen mostly when I sent a bunch of requests at the same time, which as I now see created a lot of new threads and allocated new memory, that wasn't deallocated later, when those threads were closing.

@aspotashev Thanks for your help!
Those links helped a lot.

I made several changes to the code in gist above:
1) Using constant goroutine pool for image processing. I'm now passing data to this pool through channel.
2) In each goroutine from threadpool I use `runtime.LockOSThread()` function on goroutine start,  [see example of function usage here](https://github.com/golang/go/wiki/LockOSThread). This approach for libraries using Thread Local State was originally presented by Russ Cox 

Here is the code based on previous gist with those changes: [Link](https://gist.github.com/russial/19c661c189d37095fb5f3bbefbdaa65a)

Now I have memory usage near 200Mb in peak and it drops down to ~70Mb when there is small load.

**Comment by yutkin** [comment]
Have memory leak with `gocv.IMDecode` too. `runtime.LockOSThread()` does not help.

**Comment by russial** [comment]
> Have memory leak with `gocv.IMDecode` too. `runtime.LockOSThread()` does not help.

@yutkin 
Can you show me some example code where you can reproduce the problem?
Maybe I can help.

**Comment by yutkin** [comment]
@russial
```go
go func() {
		runtime.LockOSThread()
		fd, err := model.New(worker.modelPath)
		if err != nil {
			log.Fatalln("Fail to create face detector:", err)
		}
		defer fd.Close()
		defer actor.Conn.Disconnect()

		for preprocessedImage := range imageChan {
			t1 := time.Now()
			scores, bboxes, err := fd.FindFaces(preprocessedImage.image)

			// ...

```

```go
func (fd *FaceDetector) FindFaces(i []byte) ([]float32, [][]int32, error) {
	decodedImage, err := gocv.IMDecode(i, gocv.IMReadColor)
	defer decodedImage.Close()
	if err != nil {
		return nil, nil, err
	}

	if decodedImage.Empty() {
		return nil, nil, fmt.Errorf("image is empty")
	}
        
        // Doing forward here....

	boundingBoxes := make([][]int32, 0)
	scores := make([]float32, 0)

	return scores, boundingBoxes, nil
}
```
This snippet leaks. Here a graph with step-wise memory leak:
![image](https://user-images.githubusercontent.com/2982775/75777348-e2b85500-5d66-11ea-8714-5d9c44ee0621.png)

**Comment by anoop54** [comment]
Was this resolved ? I am still having this issue.

**Comment by anoop54** [comment]
Any update on this? Still having this issue.

**Comment by lpil** [comment]
I believe we may also be having this problem. We're not using a threadpool or locking the OS thread, we shall try that.

**Comment by lpil** [comment]
After adding a thread pool with thread locked users we still have a memory leak.

**Comment by dimuls** [comment]
@lpil maybe you passing gocv.Mat between goroutines? I resolved my memory leaks by JPEG encoding/decoding layers between goroutines in addition to threadpool with OS thread locking.

**Comment by lpil** [comment]
We were not I'm afraid. I no longer have access to this project so I'm not
able to test more at the moment.

**Comment by akiSa** [comment]
I'm having memory leaks too, and I'm not passing gocv.Mat between goroutines (i decode, then process, then encode and send that). runtime.LockOSThread() does not help

**Comment by exitstop** [comment]
I'm using gocv. Noticed a memory leak on ubuntu 16.04 aarch64 rk3399. There is a leak on aarch64 on amd64 there is no leak. I have not yet figured out which function is flowing but IMDecode is also used.

**Comment by galindocode** [comment]
I solved it by adding the `defer img.Close`
```go
img, err := gocv.IMEncode(".jpg", img)
if err != nil {
   return nil, err
}
defer img.Close()
```
