### ISSUE TITLE
OpenCV Versions difference in Makefile and Install Gude

### ISSUE THREAD

**Issue by dmitry-sensei** [hybridgroup/gocv#358]
OpenCV Versions difference in Makefile and Install Gude. Install Guide on site has OpenCV version 3.4.3. In Makefile You have version 3.4.2

**Comment by deadprogram** [comment]
We're updating to OpenCV 4.0.0 actually. So we will need to update that as well.

**Comment by deadprogram** [comment]
This was released as part of v0.18.0 now closing.
