### ISSUE TITLE
Whats up with dyld library ???

### ISSUE THREAD

**Issue by vinchauhan** [hybridgroup/gocv#364]
Followed the steps as documented in getting started

## Description

dyld: Library not loaded: /usr/local/opt/freetype/lib/libfreetype.6.dylib
  Referenced from: /usr/local/opt/opencv/lib/libopencv_freetype.4.0.dylib
  Reason: image not found
signal: abort trap

## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Operating System and version:
* OpenCV version used: 4.0
* How did you install OpenCV? As documented using brew
* GoCV version used:
* Go version: 1.10
* Did you run the `env.sh` or `env.cmd` script before trying to `go run` or `go build`?

**Comment by vinchauhan** [comment]
For anyone stuck with this - I had to update a few packages manually to make it work.

>go run main.go
dyld: Library not loaded: /usr/local/opt/freetype/lib/libfreetype.6.dylib
  Referenced from: /usr/local/opt/opencv/lib/libopencv_freetype.4.0.dylib
  Reason: image not found
signal: abort trap

>brew install freetype


>go run main.go
dyld: Library not loaded: /usr/local/opt/harfbuzz/lib/libharfbuzz.0.dylib
  Referenced from: /usr/local/opt/opencv/lib/libopencv_freetype.4.0.dylib
  Reason: image not found
signal: abort trap

>brew install harfbuzz

>go run main.go
dyld: Library not loaded: /usr/local/opt/glog/lib/libglog.0.3.5.dylib
  Referenced from: /usr/local/opt/opencv/lib/libopencv_sfm.4.0.dylib
  Reason: image not found
signal: abort trap

>brew install glog

>go run main.go
gocv version: 0.18.0
opencv lib version: 4.0.0

**Comment by deadprogram** [comment]
Hi @vinchauhan out of curiosity what macOS version are you running?

**Comment by vinchauhan** [comment]
I am running on MacOS High Sierra 10.13.6

**Comment by vinchauhan** [comment]
> Hi @vinchauhan out of curiosity what macOS version are you running?

I am running on MacOS High Sierra 10.13.6
