### ISSUE TITLE
caffe-classifier example is not working

### ISSUE THREAD

**Issue by vinchauhan** [hybridgroup/gocv#365]
caffe-classifier not working
## Description

go run ./cmd/caffe-classifier/main.go 0 ~/Downloads/bvlc_googlenet.caffemodel ~/Downloads/bvlc_googlenet.prototxt ~/Downloads/synset_words.txt openvino fp16

Start reading device: 0
libc++abi.dylib: terminating with uncaught exception of type cv::Exception: OpenCV(4.0.0) /tmp/opencv-20181121-81383-twk5h6/opencv-4.0.0/modules/dnn/src/dnn.cpp:892: error: (-215:Assertion failed) haveInfEngine() in function 'wrapMat'

SIGABRT: abort
PC=0x7fff73f21b66 m=0 sigcode=0
signal arrived during cgo execution

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x40a1bf0, 0xc000043d20, 0xc000043d28)
	/usr/local/Cellar/go/1.11.2/libexec/src/runtime/cgocall.go:128 +0x5e fp=0xc000043cf0 sp=0xc000043cb8 pc=0x400553e
gocv.io/x/gocv._Cfunc_Net_Forward(0xb6189d0, 0xe325930, 0x0)
	_cgo_gotypes.go:4025 +0x4e fp=0xc000043d20 sp=0xc000043cf0 pc=0x409c0ee
gocv.io/x/gocv.(*Net).Forward.func2(0xb6189d0, 0xe325930, 0xe325930)
	/Users/vchauhan/go/src/gocv.io/x/gocv/dnn.go:133 +0x60 fp=0xc000043d58 sp=0xc000043d20 pc=0x409e250
gocv.io/x/gocv.(*Net).Forward(0xc000043e48, 0x0, 0x0, 0x0)
	/Users/vchauhan/go/src/gocv.io/x/gocv/dnn.go:133 +0x83 fp=0xc000043d88 sp=0xc000043d58 pc=0x409d0b3
main.main()
	/Users/vchauhan/go/src/github.com/vinchauhan/gocv/cmd/caffe-classifier/main.go:108 +0x4e1 fp=0xc000043f98 sp=0xc000043d88 pc=0x409f461
runtime.main()
	/usr/local/Cellar/go/1.11.2/libexec/src/runtime/proc.go:201 +0x207 fp=0xc000043fe0 sp=0xc000043f98 pc=0x402bd37
runtime.goexit()
	/usr/local/Cellar/go/1.11.2/libexec/src/runtime/asm_amd64.s:1333 +0x1 fp=0xc000043fe8 sp=0xc000043fe0 pc=0x40541e1

rax    0x0
rbx    0x7fffac4fa380
rcx    0x7ffeefbfda58
rdx    0x0
rdi    0x307
rsi    0x6
rbp    0x7ffeefbfda90
rsp    0x7ffeefbfda58
r8     0x7ffeefbfd920
r9     0x16b3a490
r10    0x0
r11    0x206
r12    0x307
r13    0x30
r14    0x6
r15    0x2d
rip    0x7fff73f21b66
rflags 0x206
cs     0x7
fs     0x0
gs     0x0
exit status 2

## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Operating System and version:
* OpenCV version used:
* How did you install OpenCV?
* GoCV version used:
* Go version:
* Did you run the `env.sh` or `env.cmd` script before trying to `go run` or `go build`?

**Comment by deadprogram** [comment]
Hello @vinchauhan you cannot install OpenVINO on macOS, and you cannot use the `openvino fp16` params unless it is installed.

Hope that helps.

**Comment by deadprogram** [comment]
Now closing, please reopen if further assistance is needed. Thanks.

**Comment by guruvishnuvardan** [comment]
Hi Folks,
Can you please help me fix the following error, when I added the following code(in block letters) in to OpenCV Python, OpenVINO

net = cv.dnn.readNetFromCaffe("MobileNetSSD_deploy.prototxt", "MobileNetSSD_deploy.caffemodel")
            blob = cv.dnn.blobFromImage(frame, inScaleFactor, (inWidth, inHeight), meanVal)
            **net.setPreferableBackend(cv.dnn.DNN_BACKEND_INFERENCE_ENGINE)
            net.setPreferableTarget(cv.dnn.DNN_TARGET_CPU)**

error: OpenCV(4.0.0) /io/opencv/modules/dnn/src/dnn.cpp:892: error: (-215:Assertion failed) haveInfEngine() in function 'wrapMat'

OS: Ubuntu 16.04
OpenCV Version : 4.0
Model:Caffe
Lang: Python 2.7
Processor: Intel i3(8th Gen), NUC
Thanks
Guru

**Comment by miaochenGuo** [comment]
@guruvishnuvardan i meet the same question with c++,do you solve it?thx
