### ISSUE TITLE
OS X installation issues: missing dependencies

### ISSUE THREAD

**Issue by njern** [hybridgroup/gocv#366]
## Steps to Reproduce

1. Install OpenCV 4 / GoCV according to the README (using `brew install hybridgroup/tools/opencv`)
2. Try to run `go run ./cmd/version/main.go` from the GoCV folder
3. Error out because of a missing dependency (`harfbuzz`)

```
go run ./cmd/version/main.go
dyld: Library not loaded: /usr/local/opt/harfbuzz/lib/libharfbuzz.0.dylib
  Referenced from: /usr/local/opt/opencv/lib/libopencv_freetype.4.0.dylib
  Reason: image not found
signal: abort trap
```

This can be fixed with `brew install harfbuzz`

4. Try again:

```
go run ./cmd/version/main.go
dyld: Library not loaded: /usr/local/opt/glog/lib/libglog.0.3.5.dylib
  Referenced from: /usr/local/opt/opencv/lib/libopencv_sfm.4.0.dylib
  Reason: image not found
signal: abort trap
```

This goes away with `brew install glog`

-> After this, things work. I'm no brew expert but I assume you should add these two packages as dependencies for the `hybridgroup/tools/opencv` keg? 

## Your Environment

* Operating System and version: **OS X Mojave (10.14.1)**
* OpenCV version used: **OpenCV 4**
* How did you install OpenCV? `brew install hybridgroup/tools/opencv`
* GoCV version used: **0.18.0**
* Go version: `go version devel +7da1f7addf Thu Nov 8 08:19:48 2018 +0000 darwin/amd64`
* Did you run the `env.sh` or `env.cmd` script before trying to `go run` or `go build`? **No.**

**Comment by dougnd** [comment]
I ran into this issue too (both `harfbuzz` and `glog` needed to be installed).

**Comment by deadprogram** [comment]
I wonder if I already had those dependencies installed on my macOS, and did not realize that they were now required.

@milosgajdos83 what do you think?

**Comment by milosgajdos83** [comment]
Yeah, I'm wondering if it's now a prerequisite, but it wasn't in the previous [release](https://github.com/Homebrew/homebrew-core/blob/master/Formula/opencv.rb#L13-L24)

I too presume that I had those two packages installed on my laptop.

**Comment by deadprogram** [comment]
Seems like a couple parts of OpenCV Contrib are what bring in these dependencies. For example, https://github.com/opencv/opencv_contrib/tree/master/modules/freetype

We will update the brew soon, I think.

**Comment by deadprogram** [comment]
I think this has now been addressed by https://github.com/hybridgroup/homebrew-tools/pull/2

Now closing, please reopen if needed. Thanks @milosgajdos83
