### ISSUE TITLE
Opencv: I already have OpenCV4 installed.

### ISSUE THREAD

**Issue by icommit** [hybridgroup/gocv#367]
## Description

Running <make install> attempts to build opencv all over. Will this override my installation?

**Comment by deadprogram** [comment]
Hi @icommit what OS are you running? 

As long as you have pkg-config installed, then GoCV should be able to find the current install on Linux or macOS.

**Comment by yuriy-yarosh** [comment]
> As long as you have pkg-config installed, then GoCV should be able to find the current install on Linux or macOS.

Nope, [this](https://github.com/hybridgroup/gocv/blob/2ec65a33d136d139ab177b078e67e1ac9988db6d/contrib/cgo.go#L8) should've been changed just to 
```
#cgo !windows pkg-config: opencv
```

because `pkgconfig` usually picks any opencv installed, homebrew has no opencv4 formulae right now. I'll add it later today... and pkg-config will be picking it as `opencv` lib, not `opencv4`.

**Comment by deadprogram** [comment]
Hello @yuriy-yarosh as mentioned in the GoCV docs for this release here https://github.com/hybridgroup/gocv#macos we now have our own Homebrew recipe.

Here is the repo: https://github.com/hybridgroup/homebrew-tools/blob/master/opencv.rb

Also, OpenCV v4 changed the name of the pkg-config file to opencv4.

Hope that helps!

**Comment by yuriy-yarosh** [comment]
Made a [PR](https://github.com/Homebrew/homebrew-core/pull/34839)

**Comment by Sauraus** [comment]
> Hello @yuriy-yarosh as mentioned in the GoCV docs for this release here https://github.com/hybridgroup/gocv#macos we now have our own Homebrew recipe.

Except some of us have to use the python bindings as well for opencv so not having them doesn't work that well for us, also its not clear from the documentation why the python bindings are an issue.

**Comment by deadprogram** [comment]
To be clear, the `hybridgroup` brew is intended for people who do not wish to install all of the Python bindings due to not using them. The main tap's brew is a "kitchen sink" that installs everything. Depends what your needs are.

**Comment by deadprogram** [comment]
Now closing, please reopen if needed. Thanks everyone!
