### ISSUE TITLE
Openvino R4 undefined references

### ISSUE THREAD

**Issue by diegosz** [hybridgroup/gocv#369]
## Description

With the last release **v0.18.0**, when trying to run some samples with **Openvino R4**, it errors with undefined references:

`/usr/local/lib/libopencv_face.so: undefined reference to 'cv::FileNodeIterator::readRaw(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, void*, unsigned long)'
/usr/local/lib/libopencv_xfeatures2d.so: undefined reference to 'cv::FileNode::operator float() const'
/usr/local/lib/libopencv_face.so: undefined reference to 'cv::FileNode::operator std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >[abi:cxx11]() const'
/usr/local/lib/libopencv_face.so: undefined reference to 'cv::FileNodeIterator::operator*() const'
/usr/local/lib/libopencv_tracking.so: undefined reference to 'cv::FileNode::isString() const'
/usr/local/lib/libopencv_face.so: undefined reference to 'cv::FileNode::end() const'
/usr/local/lib/libopencv_face.so: undefined reference to 'cv::fillConvexPoly(cv::_InputOutputArray const&, cv::Point_<int> const*, int, cv::Scalar_<double> const&, int, int)'
/usr/local/lib/libopencv_face.so: undefined reference to 'cv::FileStorage::writeRaw(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, void const*, unsigned long)'
/usr/local/lib/libopencv_face.so: undefined reference to 'cv::FileNode::operator int() const'
/usr/local/lib/libopencv_face.so: undefined reference to 'cv::FileNode::empty() const'
/usr/local/lib/libopencv_face.so: undefined reference to 'cv::FileNode::begin() const'
/usr/local/lib/libopencv_face.so: undefined reference to 'cv::FileStorage::getFirstTopLevelNode() const'
/usr/local/lib/libopencv_face.so: undefined reference to 'cv::FileNodeIterator::remaining() const'
/usr/local/lib/libopencv_face.so: undefined reference to 'cv::operator!=(cv::FileNodeIterator const&, cv::FileNodeIterator const&)'
`

## Steps to Reproduce

1. source /opt/intel/computer_vision_sdk/bin/setupvars.sh
2. source $GOPATH/src/gocv.io/x/gocv/openvino/env.sh
3. export CGO_LDFLAGS="$CGO_LDFLAGS -lopencv_face -lopencv_xfeatures2d -lopencv_tracking -lopencv_img_hash"
4. ln -s /usr/local/include/opencv4/opencv2 /usr/local/include/opencv2
5. cd $GOPATH/src/gocv.io/x/gocv
6. go run -tags openvino cmd/img-similarity/main.go -all images/space_shuttle.jpg images/toy.jpg

## Your Environment

* Operating System and version: Ubuntu 16:04
* OpenCV version used: 4.0.0
* Openvino version used: l_openvino_toolkit_p_2018.4.420
* How did you install OpenCV? gocv make
* GoCV version used: v0.18.0
* Go version: go1.11.2 linux/amd64
* Did you run the `env.sh` or `env.cmd` script before trying to `go run` or `go build`? 
`source /opt/intel/computer_vision_sdk/bin/setupvars.sh &&  
source $GOPATH/src/gocv.io/x/gocv/openvino/env.sh && export CGO_LDFLAGS="$CGO_LDFLAGS -lopencv_face -lopencv_xfeatures2d -lopencv_tracking -lopencv_img_hash"`

## Notes

1. Need to add "-lopencv_face -lopencv_xfeatures2d -lopencv_tracking -lopencv_img_hash" to $CGO_LDFLAGS. If not it gives undefined references for face, img_hash.

2. Need to do `ln -s /usr/local/include/opencv4/opencv2 /usr/local/include/opencv2`. Without this when you try to use `-tags openvino` it says that could no find opencv2/face.hpp
`In file included from face.cpp:1:0:
    face.h:6:10: fatal error: opencv2/face.hpp: No such file or directory
    #include <opencv2/face.hpp>
            ^~~~~~~~~~~~~~~~~~`

3. If I try without openvino, it gives the same undefined references error.
`go run cmd/img-similarity/main.go -all images/space_shuttle.jpg images/toy.jpg`

4. If you clean the `openvino/env.sh` settings:
`export CGO_CXXFLAGS=
export CGO_CPPFLAGS=
export CGO_LDFLAGS=
export PKG_CONFIG_PATH=`
And run without openvino:
`go run cmd/img-similarity/main.go -all images/space_shuttle.jpg images/toy.jpg` **It runs OK**:
`PHash: similarity 32
AverageHash: similarity 32
BlockMeanHash: similarity 117
BlockMeanHash: similarity 443
ColorMomentHash: similarity 42.20263981441593
MarrHildrethHash: similarity 256
RadialVarianceHash: similarity 0.49630117006887825`

5. After building without openvino `go build -o img-similarity cmd/img-similarity/main.go` this is the ldd output:
`ldd img-similarity | grep opencv | sort

	libopencv_calib3d.so.4.0 => /opt/intel/computer_vision_sdk_2018.4.420/opencv/lib/libopencv_calib3d.so.4.0 (0x00007f5ff42ae000)

	libopencv_core.so.4.0 => /opt/intel/computer_vision_sdk_2018.4.420/opencv/lib/libopencv_core.so.4.0 (0x00007f5feb011000)

	libopencv_dnn.so.4.0 => /opt/intel/computer_vision_sdk_2018.4.420/opencv/lib/libopencv_dnn.so.4.0 (0x00007f5ff27c5000)

	libopencv_face.so.4.0 => /usr/local/lib/libopencv_face.so.4.0 (0x00007f5ff5001000)

	libopencv_features2d.so.4.0 => /opt/intel/computer_vision_sdk_2018.4.420/opencv/lib/libopencv_features2d.so.4.0 (0x00007f5ff3fe3000)

	libopencv_flann.so.4.0 => /opt/intel/computer_vision_sdk_2018.4.420/opencv/lib/libopencv_flann.so.4.0 (0x00007f5fe9f2b000)

	libopencv_highgui.so.4.0 => /opt/intel/computer_vision_sdk_2018.4.420/opencv/lib/libopencv_highgui.so.4.0 (0x00007f5ff3dcd000)

	libopencv_img_hash.so.4.0 => /usr/local/lib/libopencv_img_hash.so.4.0 (0x00007f5ff56df000)

	libopencv_imgcodecs.so.4.0 => /opt/intel/computer_vision_sdk_2018.4.420/opencv/lib/libopencv_imgcodecs.so.4.0 (0x00007f5ff333f000)

	libopencv_imgproc.so.4.0 => /opt/intel/computer_vision_sdk_2018.4.420/opencv/lib/libopencv_imgproc.so.4.0 (0x00007f5fecb39000)

	libopencv_objdetect.so.4.0 => /opt/intel/computer_vision_sdk_2018.4.420/opencv/lib/libopencv_objdetect.so.4.0 (0x00007f5ff4d7e000)

	libopencv_tracking.so.4.0 => /usr/local/lib/libopencv_tracking.so.4.0 (0x00007f5ff5297000)

	libopencv_video.so.4.0 => /opt/intel/computer_vision_sdk_2018.4.420/opencv/lib/libopencv_video.so.4.0 (0x00007f5ff4662000)

	libopencv_videoio.so.4.0 => /opt/intel/computer_vision_sdk_2018.4.420/opencv/lib/libopencv_videoio.so.4.0 (0x00007f5ff3b87000)

	libopencv_xfeatures2d.so.4.0 => /usr/local/lib/libopencv_xfeatures2d.so.4.0 (0x00007f5ff48c7000)
` **You could see it's using it's using lopencv_core. Also you could see it's also using /usr/local/lib for libopencv_face. Thats the same behavior like with the previous gocv v0.17.0 + openvino R3**.

6. Just in case, something to note is **that OpenCV version built by gocv is 4.0.0 but the OpenCV version from the Openvino R4 is 4.0.0-pre**
`opencv_version
4.0.0
/opt/intel/computer_vision_sdk/opencv/bin/opencv_version 
4.0.0-pre`

7. Any hint ? 
:-) Many thanks

**Comment by deadprogram** [comment]
The OpenVINO distribution does not include the OpenCV contrib modules, so that example will not work, not can any others that use the `"gocv.io/x/gocv/contrib"` package.

Basically you can either use OpenVINO, or you can use OpenCV contrib. but not both at the same time.

**Comment by deadprogram** [comment]
Sounds like the LD paths were both added, perhaps, and it somehow is able to find the missing ones in the other path? That sounds like anomalous behavior, that perhaps just so happens to work for you.

**Comment by diegosz** [comment]
Yes, really nuts :-)

```bash
go run cmd/img-similarity/main.go -all images/space_shuttle.jpg images/toy.jpg 
PHash: similarity 32
AverageHash: similarity 32
BlockMeanHash: similarity 117
BlockMeanHash: similarity 443
ColorMomentHash: similarity 42.20263981441593
MarrHildrethHash: similarity 256
RadialVarianceHash: similarity 0.49646512207080923

go run -tags openvino cmd/img-similarity/main.go -all images/space_shuttle.jpg images/toy.jpg 
PHash: similarity 32
AverageHash: similarity 32
BlockMeanHash: similarity 117
BlockMeanHash: similarity 443
ColorMomentHash: similarity 42.20263981441593
MarrHildrethHash: similarity 256
RadialVarianceHash: similarity 0.49646512207080923
```

I have it also running this way in a docker container.

I'm going to check the Dockerfile to find trick

**Comment by deadprogram** [comment]
We've updated to OpenVINO 2019 R3 now, so now closing. Thank you.
