### ISSUE TITLE
support webp encode and eocde mat from buffer?

### ISSUE THREAD

**Issue by hurkgu** [hybridgroup/gocv#37]

**Comment by deadprogram** [comment]
Hi @hurkgu the various imgcodec functions should have no problem supporting WebP, according to OpenCV docs.

For example, https://godoc.org/gocv.io/x/gocv#IMWrite you should be able to:

```go
gocv.IMWrite("cool_stuff.webp", img)
```

and the resulting file should be WebP encoded.

You should be able to do the same with https://godoc.org/gocv.io/x/gocv#IMEncode and IMDecode. Please note that `IMDecode` is still in the `dev` branch and will be included in the next GoCV release.

Hope that helps!
