### ISSUE TITLE
OpenVINO R5 compatibility issues on Raspberry Pi

### ISSUE THREAD

**Issue by njern** [hybridgroup/gocv#375]
## Description

I installed the latest version of OpenVINO (R5) using the OpenVINO install instructions [here](https://software.intel.com/articles/OpenVINO-Install-RaspberryPI) on a Raspberry Pi 3B+ with a fresh install of Raspbian (the November 2018 release).

When I try to run `go run -tags openvino ./cmd/version/main.go` I get the following output:

```
pi@raspberrypi:~/go/src/gocv.io/x/gocv $ go run -tags openvino ./cmd/version/main.go
# runtime/cgo
/usr/bin/ld: cannot find -ldliaPlugin
/usr/bin/ld: cannot find -lHeteroPlugin
/usr/bin/ld: cannot find -lMKLDNNPlugin
/usr/bin/ld: cannot find -lmyriadPlugin
/usr/bin/ld: cannot find -linference_engine
/usr/bin/ld: cannot find -lclDNNPlugin
/usr/bin/ld: cannot find -lopencv_pvl
collect2: error: ld returned 1 exit status
```

**NOTE:** I have confirmed the OpenVINO installation itself works fine by running the two examples from the OpenVINO R5 installation guide.

## Steps to Reproduce

1. Acquire a Raspberry Pi 3B+.
2. Install [Raspbian](https://www.raspberrypi.org/downloads/raspbian/). 
3. [Install OpenVINO R5](https://software.intel.com/articles/OpenVINO-Install-RaspberryPI) 
4. Follow the GoCV instructions for OpenVINO [here](https://github.com/hybridgroup/gocv/tree/master/openvino)
5. Try to run `go run -tags openvino ./cmd/version/main.go`

## Your Environment

* Operating System and version: `Linux raspberrypi 4.14.79-v7+ #1159 SMP Sun Nov 4 17:50:20 GMT 2018 armv7l GNU/Linux`
* OpenCV version used: `4.0 (OpenVINO R5)`
* How did you install OpenCV? Via OpenVINO
* GoCV version used: `0.18.0`
* Go version: `go version go1.11.4 linux/arm`
* Did you run the `env.sh` or `env.cmd` script before trying to `go run` or `go build`? I ran `source openvino/env.sh`

**Comment by njern** [comment]
The first part of the problem is that the path used in [openvino/env.sh](https://github.com/hybridgroup/gocv/blob/master/openvino/env.sh) is hardcoded to `... /ubuntu_16.04/intel64` where for the Raspberry Pi version of OpenVINO the path should be `.../raspbian_9/armv7l`

Changing this reduces the list of link failures down to the following:

```
pi@raspberrypi:~/go/src/gocv.io/x/gocv $ go run -tags openvino ./cmd/version/main.go
# runtime/cgo
/usr/bin/ld: cannot find -ldliaPlugin
/usr/bin/ld: cannot find -lMKLDNNPlugin
/usr/bin/ld: cannot find -lclDNNPlugin
/usr/bin/ld: cannot find -lopencv_pvl
collect2: error: ld returned 1 exit status
```

**Comment by njern** [comment]
By removing the offending flags from `env.sh` I can successfully get the `version/main.go` example to compile with the following output:

```
gocv version: 0.18.0
opencv lib version: 4.0.1-openvino
```

This is using the following modifications to `env.sh`:

```
-export CGO_LDFLAGS="-L${INTEL_CVSDK_DIR}/opencv/lib -L${INTEL_CVSDK_DIR}/deployment_tools/inference_engine/lib/ubuntu_16.04/intel64 -lpthread -ldl -ldliaPlugin -lHeteroPlugin -lMKLDNNPlugin -lmyriadPlugin -linference_engine -lclDNNPlugin -lopencv_core -lopencv_pvl -lopencv_videoio -lopencv_imgproc -lopencv_highgui -lopencv_imgcodecs -lopencv_objdetect -lopencv_features2d -lopencv_video -lopencv_dnn -lopencv_calib3d"
+export CGO_LDFLAGS="-L${INTEL_CVSDK_DIR}/opencv/lib -L${INTEL_CVSDK_DIR}/deployment_tools/inference_engine/lib/raspbian_9/armv7l -lpthread -ldl -lHeteroPlugin -lmyriadPlugin -linference_engine -lopencv_core -lopencv_videoio -lopencv_imgproc -lopencv_highgui -lopencv_imgcodecs -lopencv_objdetect -lopencv_features2d -lopencv_video -lopencv_dnn -lopencv_calib3d"
```

However, if I try to run one of the examples (`ssd-facedetect`)
```
pi@raspberrypi:~/go/src/gocv.io/x/gocv/cmd/ssd-facedetect $ DISPLAY=:0 ./ssd-facedetect -1 deploy.prototxt res10_300x300_ssd_iter_140000_fp16.caffemodel 

(ssd-facedetect:18617): GStreamer-CRITICAL **: gst_element_get_state: assertion 'GST_IS_ELEMENT (element)' failed
Start reading device: -1
terminate called after throwing an instance of 'cv::Exception'
  what():  OpenCV(4.0.1-openvino) /home/jenkins/workspace/OpenCV/OpenVINO/build/opencv/modules/dnn/src/op_inf_engine.cpp:553: error: (-215:Assertion failed) in function 'initPlugin'
> Failed to initialize Inference Engine backend: Cannot find plugin to use :
> 
SIGABRT: abort
PC=0x75c9e45c m=0 sigcode=4294967290
signal arrived during cgo execution

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0xca3e8, 0xc9fe68, 0xc9fe6c)
	/usr/local/go/src/runtime/cgocall.go:128 +0x5c fp=0xc9fe50 sp=0xc9fe38 pc=0x38a70
gocv.io/x/gocv._Cfunc_Net_Forward(0xaaba20, 0xa9ff70, 0x0)
	_cgo_gotypes.go:3980 +0x38 fp=0xc9fe64 sp=0xc9fe50 pc=0xc2784
gocv.io/x/gocv.(*Net).Forward.func2(0xaaba20, 0xa9ff70, 0xa9ff70)
	/home/pi/go/src/gocv.io/x/gocv/dnn.go:133 +0x4c fp=0xc9fe7c sp=0xc9fe64 pc=0xc4278
gocv.io/x/gocv.(*Net).Forward(0xc9ff28, 0x117cc2, 0xd, 0x0)
	/home/pi/go/src/gocv.io/x/gocv/dnn.go:133 +0x68 fp=0xc9fe90 sp=0xc9fe7c pc=0xc33c0
main.main()
	/home/pi/go/src/gocv.io/x/gocv/cmd/ssd-facedetect/main.go:114 +0x45c fp=0xc9ffc4 sp=0xc9fe90 pc=0xc5104
runtime.main()
	/usr/local/go/src/runtime/proc.go:201 +0x204 fp=0xc9ffe4 sp=0xc9ffc4 pc=0x5f584
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm.s:867 +0x4 fp=0xc9ffe4 sp=0xc9ffe4 pc=0x85e30

trap    0x0
error   0x0
oldmask 0x0
r0      0x0
r1      0x7ebce3c8
r2      0x0
r3      0x8
r4      0x0
r5      0x7ebce3c8
r6      0x6fab5000
r7      0xaf
r8      0x7ebce4dc
r9      0xbc7078
r10     0x7ebce76c
fp      0x762a680c
ip      0x20
sp      0x7ebce3c8
lr      0xffffffff
pc      0x75c9e45c
cpsr    0x10
fault   0x0
pi@raspberrypi:~/go/src/gocv.io/x/gocv/cmd/ssd-facedetect $ 
```

**Comment by deadprogram** [comment]
What files are in the `deployment_tools/inference_engine/lib/raspbian_9/armv7l` sub-directory of the OpenVINO install?

**Comment by njern** [comment]
```
libcpu_extension.so  
libHeteroPlugin.so  
libinference_engine.so  
libmyriadPlugin.so  
mvnc/
myriad_compile  
myriad_perfcheck
```

**Comment by dkurt** [comment]
@njern, For Raspberry Pi distribution there is only Myriad plugin (Movidius NCS). That means you can use RPI only as a host and NCS as a target device.

> Failed to initialize Inference Engine backend: Cannot find plugin to use :

This a bit confusing message appears when IE tries to load plugin that doesn't exist (i.e. CPU plugin which must be by default, isn't it?).

**Comment by 1343464520** [comment]
> @njern, For Raspberry Pi distribution there is only Myriad plugin (Movidius NCS). That means you can use RPI only as a host and NCS as a target device.

hi, njern, if i install Ubuntu-mate OS on my Raspberry Pi, can openvino support it? 
If so, can i only use OpenVINO for accelerating the network inference without Movidius NCS? 
And my opencv version is 3.4.3, if this version support openvino?  if it should be upgrade to 4.0v?
thank you !

**Comment by 1343464520** [comment]
Hello, @dkurt. what do you think about my question above? 
looking forward to ur reply! thank you!

**Comment by njern** [comment]
Just installed the latest version of OpenVINO (https://download.01.org/opencv/2019/openvinotoolkit/l_openvino_toolkit_raspbi_p_2019.1.094.tgz) and this is still an issue. 

Updated list of files in the `armv7l` folder:

```
libcpu_extension.so  libinference_engine.so  MvNCAPI-ma2450.mvcmd  myriad_compile
libHeteroPlugin.so   libmyriadPlugin.so      MvNCAPI-ma2480.mvcmd  myriad_perfcheck
```

Which means the error is now: 

```
# runtime/cgo
/usr/bin/ld: cannot find -lMKLDNNPlugin
/usr/bin/ld: cannot find -lclDNNPlugin
/usr/bin/ld: cannot find -lopencv_pvl
collect2: error: ld returned 1 exit status
```

**Comment by alfandinorasyid** [comment]
I have some problem like this, anyone knows what that's mean?

Traceback (most recent call last):
  File "openvino_real_time_object_detection.py", line 85, in <module>
    detections = net.forward()
cv2.error: OpenCV(4.0.1-openvino) /home/jenkins/workspace/OpenCV/OpenVINO/build/opencv/modules/dnn/src/op_inf_engine.cpp:553: error: (-215:Assertion failed) Failed to initialize Inference Engine backend: AssertionFailed: ind >= 0 && ind < _data.size() in function 'initPlugin'

I use the 2019 version of openvino in rasbian, and I use ReadFromTensorflow for the detection script

**Comment by deadprogram** [comment]
We've just updated to support OpenVINO 2019 R3, so now closing. Please reopen if needed, thank you!
