### ISSUE TITLE
Missing Matrix Multiply

### ISSUE THREAD

**Issue by vincentchu** [hybridgroup/gocv#376]
GoCV implements element-wise and scalar multiplication of matrices, but not normal matrix multiplication. This makes it somewhat harder to apply a rotation to a vector or similar. 

I have an implementation I hacked together and would be happy to submit a PR to close this issue if people want. The signature is:

```
func (m *Mat) MatrixMultiply(o *Mat) Mat {
    // impl here
}
```

and used like this:

```
rotatedVec := rotMat.MatrixMultiply(vec)
```

**Comment by deadprogram** [comment]
This was addressed by #559 so now closing. Thank you!
