### ISSUE TITLE
Cross compile for Linux from Mac OS

### ISSUE THREAD

**Issue by kafan1986** [hybridgroup/gocv#381]
I am trying to cross compile executable for linux environment from my Mac OS based PC but it is throwing me error. The Mac version builds fine. Do you have steps necessary for cross compiling?

env GOOS=linux GOARCH=amd64 go build mirror

# gocv.io/x/gocv
goWork/src/gocv.io/x/gocv/dnn_ext.go:9:28: undefined: Mat
goWork/src/gocv.io/x/gocv/dnn_ext.go:16:12: undefined: NewMatWithSize
goWork/src/gocv.io/x/gocv/dnn_ext.go:43:2: undefined: Resize
goWork/src/gocv.io/x/gocv/dnn_ext.go:43:38: undefined: InterpolationDefault
goWork/src/gocv.io/x/gocv/dnn_ext.go:46:3: undefined: CvtColor
goWork/src/gocv.io/x/gocv/dnn_ext.go:49:15: undefined: NewMat
goWork/src/gocv.io/x/gocv/dnn_ext.go:52:31: undefined: MatTypeCV32F

**Comment by deadprogram** [comment]
Hello @kafan1986 you might want to take a look at our new Docker container: https://github.com/hybridgroup/gocv/blob/dev/README.md#docker

Even though the docs are in the `dev` branch the container is available now.

**Comment by RifeWang** [comment]
I got the same error ,  will this lib support for cross compiling in the future ?
