### ISSUE TITLE
 connectedComponents and connectedComponentsWithStats functions

### ISSUE THREAD

**Issue by sshibs** [hybridgroup/gocv#383]
Hello, I am using gocv in a project and was hoping to use opencv's connectedComponents and connectedComponentsWithStats functions in go.

It looks like it is on the roadmap but has not been implemented yet. Is it ok if I contribute to this, or is someone already working on it?

Thanks for the help.

**Comment by deadprogram** [comment]
Hi @sshibs that would be great if you were to contribute this. Please, and thank you!

**Comment by deadprogram** [comment]
Thank you for the PR @sshibs it has been merged and will be included in the next release.

**Comment by deadprogram** [comment]
This has now been released. Thanks again!
