### ISSUE TITLE
4.0.1 patch release is out

### ISSUE THREAD

**Issue by Sauraus** [hybridgroup/gocv#386]
Update to 4.0.1 patch release, does `gocv` use pkg-config properly on OSX?

## Description
/usr/local/Cellar/go/1.11.4/libexec/pkg/tool/darwin_amd64/link: running clang++ failed: exit status 1
ld: warning: directory not found for option '-L/usr/local/Cellar/opencv/4.0.0/lib'
ld: library not found for -lopencv_freetype
clang: error: linker command failed with exit code 1 (use -v to see invocation)

## Steps to Reproduce
1. brew install opencv ( -> 4.0.1)
2. run any Go program that is dependent on `gocv` and it will error out at the linker stage (see above)
## Your Environment

* Operating System and version:
OSX Mojave
* OpenCV version used:
4.0.1
* How did you install OpenCV?
brew
* GoCV version used:
0.18.0
* Go version:
go version go1.11.4 darwin/amd64
* Did you run the `env.sh` or `env.cmd` script before trying to `go run` or `go build`?

**Comment by deadprogram** [comment]
The only recommended was to install on macOS is to use the Homebrew brews, either the official one or else the `hybridgroup` tap. I suggest trying one of those out. you might also want to `brew upgrade opencv` instead of `brew install` to avoid installing both versions side by side.

**Comment by pyting** [comment]
change files
gocv.io/x/gocv/cgo.h
gocv.io/x/gocv/contrib/cgo.h
----
```golang
// +build !customenv,!openvino

package contrib

// Changes here should be mirrored in gocv/cgo.go.

/*
#cgo !windows pkg-config: opencv4
#cgo CXXFLAGS:   --std=c++11
#cgo windows  CPPFLAGS:   -ID:/opencv/mingw_4.0.1/include
#cgo windows  LDFLAGS:    -LD:/opencv/mingw_4.0.1/x64/mingw/lib -lopencv_core401 -lopencv_face401 -lopencv_videoio401 -lopencv_imgproc401 -lopencv_highgui401 -lopencv_imgcodecs401 -lopencv_objdetect401 -lopencv_features2d401 -lopencv_video401 -lopencv_dnn401 -lopencv_xfeatures2d401 -lopencv_plot401 -lopencv_tracking401 -lopencv_img_hash401 -lopencv_calib3d401
*/
import "C"
`

**Comment by deadprogram** [comment]
We're on OpenCV 4.1.2 now, which is the same as the current Homebrew, so now closing. Thank you.
