### ISSUE TITLE
how can i copy a png to another png

### ISSUE THREAD

**Issue by linyongzuo** [hybridgroup/gocv#387]
first i load a logo from file
logoMat = gocv.IMRead("/users/linyongzuo/workspace/doc/logo.png",gocv.IMReadUnchanged)
second i read a img from video 
mat := gocv.NewMat()
		if !videoCaptuer.Read(&mat) {
			mat.Close()
			continue
		}
third, i want copy logomat to mat 
i use 
regionMat := mat.Region(image.Rectangle{Min:image.Point{X:0,Y:0},Max:image.Point{X:logoMat.Cols(),Y:logoMat.Rows()}} )
		logoMat.CopyTo(&regionMat)
but it seems not work right

**Comment by ydf** [comment]
best https://github.com/hybridgroup/gocv/pull/429
