### ISSUE TITLE
Cross Compile for Raspberry Pi

### ISSUE THREAD

**Issue by joek** [hybridgroup/gocv#39]
Hi,
first of all, thanks for your great work. I really like it and will be happy to integrate mjpeg streamer into my little robot project.  

One thing which I have not found so far. Is there a way to corss compile gocv based projects for raspberry? I tried GOARM=6 GOARCH=arm GOOS=linux go build but this is not working.

Cheers
Johannes

**Comment by deadprogram** [comment]
Hello @joek cross-compiling when CGo is involved is usually very difficult. I would suggest looking into creating a docker container if you need to go this route. At the moment the easiest thing is to build on the target platform.

**Comment by deadprogram** [comment]
You can for sure compile from other Debian, in my case Ubuntu, for Raspbian, as long as you are using the latest changes to the `dev` branch.

**Comment by deadprogram** [comment]
This code has now been released as part of v0.12.0 so now closing. Thanks again!
