### ISSUE TITLE
does gocv implement initUndistortRectifyMap

### ISSUE THREAD

**Issue by linyongzuo** [hybridgroup/gocv#393]

**Comment by deadprogram** [comment]
Hello, @linyongzuo were you referring to the imgproc `initUndistortRectifyMap()` or to the calib3d `initUndistortRectifyMap()` function? In either case, both are on the roadmap but not yet implemented:

https://github.com/hybridgroup/gocv/blob/bc016e27fba3560070e16affd605768d68110867/ROADMAP.md#L57

and 

https://github.com/hybridgroup/gocv/blob/bc016e27fba3560070e16affd605768d68110867/ROADMAP.md#L138

**Comment by deadprogram** [comment]
Your PR was already been added to GoCV with PR https://github.com/hybridgroup/gocv/pull/405 but I did not update this issue.

Now closing thank you @linyongzuo for your contribution.
