### ISSUE TITLE
Implement blobFromImages

### ISSUE THREAD

**Issue by WendelHime** [hybridgroup/gocv#395]
I've seen documentation and code and didn't find the function blobFromImages, it shouldn't be on ROADMAP.md or someone is already implementing?

**Comment by deadprogram** [comment]
Hi @WendelHime you are correct, it needs to be added to roadmap and also implemented.

**Comment by sukhoi** [comment]
The signature in V2 and V3 is different from V4. Any suggestions/clarifications/workarounds for that?
@WendelHime : In case you haven't started on this one, I'd like to pick this up. I started without checking if someone was already working :(. Please let me know.
Thanks. -H

**Comment by WendelHime** [comment]
Hi @sukhoi , I need to learn more about the communication between languages and OpenCV C++, so I didn't try.

**Comment by deadprogram** [comment]
Hello @sukhoi I suggest target only OpenCV 4 since the rest of GoCV is currently doing that now.

To use OpenCV 3.4 a person will need to use an older version of GoCV now anyhow.

**Comment by sukhoi** [comment]
@deadprogram : Would it be wise to put placeholders/signatures for the methods that needed to be implemented so that who ever picks up the code does not worry about the version, syntax, source reference, etc.
