### ISSUE TITLE
Rotation

### ISSUE THREAD

**Issue by 221bytes** [hybridgroup/gocv#40]
Is it possible to rotate a Mat in a way close to 
https://docs.opencv.org/3.0-beta/doc/py_tutorials/py_imgproc/py_geometric_transformations/py_geometric_transformations.html#rotation ?

**Comment by 221bytes** [comment]
I've coded GetRotationMatrix2D and WarpAffine myself so the issue can be close. Thanks for your work and the lib !

**Comment by deadprogram** [comment]
Please feel free to submit a PR with those, should you feel so inclined. Thanks!

**Comment by 221bytes** [comment]
Sure why not ! I sent you a couple of questions on the Gophers slack !
