### ISSUE TITLE
`make build` on OSX Mojava fails with /tmp/opencv/opencv_contrib-4.0.0/modules/text/src/precomp.hpp:54:10: fatal error: 'tesseract/baseapi.h' file not found

### ISSUE THREAD

**Issue by Sauraus** [hybridgroup/gocv#400]
`make build` on Max OSX Mojave 10.14.2 fails with /tmp/opencv/opencv_contrib-4.0.0/modules/text/src/precomp.hpp:54:10: fatal error: 'tesseract/baseapi.h' file not found

## Steps to Reproduce

1. Download source code with `go get ...`
2. make build -> crash

## Your Environment

* Operating System and version:
Mac OSX Mojave 10.14.2
* OpenCV version used:
4.0.1
* How did you install OpenCV?
brew install opencv (NOTE: `make download` grabs the sources.

* GoCV version used:
dev branch at 5a0e230
* Go version:
go version go1.11.4 darwin/amd64
* Did you run the `env.sh` or `env.cmd` script before trying to `go run` or `go build`?

**Comment by deadprogram** [comment]
Hello @Sauraus the `Makefile` support is intended only for Linux installation. 

To install on macOS you should use one of the Homebrew brews, either the official one or else the `hybridgroup` tap.

Hope that helps!
