### ISSUE TITLE
Implement jaccardDistance

### ISSUE THREAD

**Issue by sukhoi** [hybridgroup/gocv#402]
The NMSBoxes implementation has a dependency on jaccardDistance. I checked but couldnot find it implemented anywhere. is this already implemented? if not, should this be a part of a single PR ? 
Thanks. -H

**Comment by dkurt** [comment]
@sukhoi, It uses `jaccardDistance` internally. See [NMSBoxes](https://docs.opencv.org/master/d6/d0f/group__dnn.html#ga9d118d70a1659af729d01b10233213ee).
