### ISSUE TITLE
How to change Mat pixel color using Trackbar

### ISSUE THREAD

**Issue by hermes7308** [hybridgroup/gocv#409]
package main

	import (
		"log"

		"gocv.io/x/gocv"
	)

	func main() {
		windowForTrackbar := gocv.NewWindow("Trackbar Window")
		trackbarR := windowForTrackbar.CreateTrackbar("R", 255)
		trackbarG := windowForTrackbar.CreateTrackbar("G", 255)
		trackbarB := windowForTrackbar.CreateTrackbar("B", 255)

		mat := gocv.NewMatWithSize(300, 300, gocv.MatTypeCV16U)
		RGB := []int{0, 0, 0}

		for {
			RGB[0] = trackbarR.GetPos()
			RGB[1] = trackbarG.GetPos()
			RGB[2] = trackbarB.GetPos()

			log.Println("-----------------------")
			log.Println("RGB:", RGB)
			log.Println("Rows:", mat.Rows())
			log.Println("Cols:", mat.Cols())
			log.Println("-----------------------")

			// Something do

			windowForTrackbar.IMShow(mat)

			key := windowForTrackbar.WaitKey(3)
			if key == 27 {
				break
			}
		}

		windowForTrackbar.Close()
	}

I want to controll pixel color using Trackbar please help me. 
If Trackbar change value, then Mat shown window color is changed

**Comment by deadprogram** [comment]
Hi @hermes7308 please check out CVScope project for some examples of using trackbar with GoCV https://github.com/hybridgroup/cvscope
