### ISSUE TITLE
YOLO example

### ISSUE THREAD

**Issue by entrehuihui** [hybridgroup/gocv#414]
Can you give a simple example of yolo, I am not very familiar with this block, the program always crashes when outs := net.Forward() or can't wait for the result, the program I wrote is simulated by python.
Thank you very much for any help.

**Comment by deadprogram** [comment]
Hi @entrehuihui do you have a specific model you are trying to use, or Python code you are trying to replicate using GoCV? That would help us help you.

**Comment by entrehuihui** [comment]
> 你好@entrehuihui你有一个你想要使用的特定模型，或者你试图使用GoCV复制的Python代码？这将有助于我们帮助您。

Thank you very much for your reply!
I tried to use this model on the official website . yolov3.weights and yolov3.cfg 
 https://pjreddie.com/darknet/yolo/ .
Partial code of  python reference lile:
blob = cv.dnn.blobFromImage(frame, 1/255, (inpWidth, inpHeight), [0,0,0], 1, crop=False)
 
    # Sets the input to the network
    net.setInput(blob)
 
    # Runs the forward pass to get output of the output layers
    outs = net.forward(getOutputsNames(net))
 
    # Remove the bounding boxes with low confidence
    postprocess(frame, outs)


but I Can't find getOutputsNames in gocv, 
I am very sorry for your time, maybe my question is very simple, because I just learned machine learning, I have been watching other people's source implementation.

**Comment by entrehuihui** [comment]
Thank you very much for the help of the project, I have solved the problem.
