### ISSUE TITLE
https://github.com/opencv/opencv/archive/4.0.0.tar.gz not found

### ISSUE THREAD

**Issue by xcl3721** [hybridgroup/gocv#422]
brew install hybridgroup/tools/opencv

## Description
brew install hybridgroup/tools/opencv 

url: (56) LibreSSL SSL_read: SSL_ERROR_SYSCALL, errno 54
Error: Failed to download resource "opencv"
Download failed: https://github.com/hybridgroup/homebrew-tools/releases/download/v0.10.1/opencv-4.0.0.high_sierra.bottle.tar.gz
Warning: Bottle installation failed: building from source.
==> Downloading https://github.com/opencv/opencv/archive/4.0.0.tar.gz
==> Downloading from https://codeload.github.com/opencv/opencv/tar.gz/4.0.0

curl: (22) The requested URL returned error: 404 Not Found

## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Operating System and version:
* OpenCV version used:
* How did you install OpenCV?
* GoCV version used:
* Go version:
* Did you run the `env.sh` or `env.cmd` script before trying to `go run` or `go build`?

**Comment by deadprogram** [comment]
Hello @xcl3721 I would check your firewall or other network settings, because the file resolves from here:

```shell
$ curl -Is https://codeload.github.com/opencv/opencv/tar.gz/4.0.0 | head -1
HTTP/1.1 200 OK
```

Hope that helps!

**Comment by xcl3721** [comment]
er  curl -Is https://github.com/opencv/opencv/archive/4.0.0.tar.gz | head -1
HTTP/1.1 302 Found
HTTP/1.1 302 Found
zsh: no such file or directory: HTTP/1.1
 ✘ changlong.xu@changlong  ~/go/src/gocv.io/x/gocv/cmd/facedetect   master  curl -Is https://codeload.github.com/opencv/opencv/tar.gz/4.0.0 | head -1
HTTP/1.1 200 OK
HTTP/1.1 404 Not Found
zsh: no such file or directory: HTTP/1.1
 ✘ changlong.xu@changlong  ~/go/src/gocv.io/x/gocv/cmd/facedetect   master 

**Comment by deadprogram** [comment]
Like I said I would check your firewall or other network settings. The files are hosted by Github, so not much we can do about that part.

**Comment by xcl3721** [comment]
ok
and i found https://github.com/opencv/opencv/archive/4.0.1.zip this one file can download

**Comment by xcl3721** [comment]
thank you sir
it's seem something wrong with opencv 
when i open this on browser

404
There isn't a GitHub Pages site here.

If you're trying to publish one, read the full documentation to learn how to set up GitHub Pages for your repository, organization, or user account.

**Comment by deadprogram** [comment]
I think there may be an issue with the recent update to Homebrew 2.0 and that brew.

I think it would be better to use the "main" Homebrew now that they have updated it to OpenCV 4.0.1

`brew install opencv`

**Comment by deadprogram** [comment]
I've updated both the web site and the README to match this corrected installation info. If you try again please let me know that it works as you exptect.

**Comment by xcl3721** [comment]
let me try~

**Comment by xcl3721** [comment]
changlong.xu@changlong  ~  brew install hybridgroup/tools/opencv
Updating Homebrew...
==> Installing opencv from hybridgroup/tools
Error: opencv 4.0.1 is already installed
To install 4.0.0, first run `brew unlink opencv`

**Comment by deadprogram** [comment]
First run `brew uninstall opencv` then run `brew install opencv`.

**Comment by xcl3721** [comment]
sure i do it  installed 4.0.1

**Comment by xcl3721** [comment]
yes i do this by step but installed 4.0.1

**Comment by deadprogram** [comment]
Right but you need to remove all versions, then install only the main brew of 4.0.1

**Comment by xcl3721** [comment]
changlong.xu@changlong  ~  brew uninstall opencv
Uninstalling /usr/local/Cellar/opencv/4.0.1... (679 files, 226MB)
 changlong.xu@changlong  ~  brew uninstall opencv
Error: No such keg: /usr/local/Cellar/opencv
 ✘ changlong.xu@changlong  ~  brew install opencv
==> Downloading https://homebrew.bintray.com/bottles/opencv-4.0.1.mojave.bo
Already downloaded: /Users/changlong.xu/Library/Caches/Homebrew/downloads/c7b0969835645b18c29b3db48dd0a0fac66eddf51d1d4ea1566f27716fc766ff--opencv-4.0.1.mojave.bottle.tar.gz
==> Pouring opencv-4.0.1.mojave.bottle.tar.gz
Warning: opencv dependency gcc was built with a different C++ standard
library (libstdc++ from clang). This may cause problems at runtime.
🍺  /usr/local/Cellar/opencv/4.0.1: 679 files, 226MB
 changlong.xu@changlong  ~  brew install hybridgroup/tools/opencv
==> Installing opencv from hybridgroup/tools
Error: opencv 4.0.1 is already installed
To install 4.0.0, first run `brew unlink opencv`
 ✘ changlong.xu@changlong  ~ 

**Comment by deadprogram** [comment]
You probably want to post a request for support on the Homebrew for that. One you get OpenCV 4.0.1 installed come back here.

**Comment by deadprogram** [comment]
Wait.

DO NOT run `brew install hybridgroup/tools/opencv`

I thought I explained already to oonly run `brew install opencv`.

Please uninstall everything then ONLY run `brew install opencv`

**Comment by xcl3721** [comment]
wow! it's worked!! install depend and run

**Comment by xcl3721** [comment]
Thank you sir!

**Comment by deadprogram** [comment]
My pleasure, glad I could help.
