### ISSUE TITLE
Package opencv4 was not found in the pkg-config search path

### ISSUE THREAD

**Issue by maiguangyang** [hybridgroup/gocv#427]
[root@localhost gocv]# go run ./cmd/version/main.go
# pkg-config --cflags opencv4
Package opencv4 was not found in the pkg-config search path.
Perhaps you should add the directory containing `opencv4.pc'
to the PKG_CONFIG_PATH environment variable
No package 'opencv4' found
pkg-config: exit status 1

----------------------------------------------------------------
How to solve this error?

**Comment by ItsFunny** [comment]
how to solve it

**Comment by BATMAN-CYT** [comment]
how to solve it？
