### ISSUE TITLE
Gtk-WARNING **: 12:46:58.287: cannot open display: exit status 1

### ISSUE THREAD

**Issue by maiguangyang** [hybridgroup/gocv#430]
go run ./cmd/capwindow/main.go 0

(Capture Window:6947): Gtk-WARNING **: 12:46:58.287: cannot open display:
exit status 1
----------------------------------------------------------------------------------

LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	CentOS
Description:	CentOS Linux release 7.6.1810 (Core)
Release:	7.6.1810
Codename:	Core

gocv version: 0.19.0
opencv lib version: 4.0.1

go version go1.12.1 linux/amd64
-------------------------------------------------------------------------------

help me

**Comment by deadprogram** [comment]
Hi @maiguangyang are you trying to run on a headless system or within a Docker container?
