### ISSUE TITLE
Install error at build

### ISSUE THREAD

**Issue by maxrousseau** [hybridgroup/gocv#431]
## Description
When installing the package, compilation fails after running make install.

## Steps to Reproduce

1. go get -u -d gocv.io/x/gocv
2. cd $GOPATH/src/gocv.io/x/gocv
3. make install

## Environment

* Operating System and version: Ubuntu 18.04
* OpenCV version used: 4.0.1
* How did you install OpenCV?: make install (after go get and 
* GoCV version used: v0.19.0
* Go version: go1.10..4

## Output from make install

Here is the error that I get from the install:

```sh
[ 81%] Building CXX object modules/xfeatures2d/CMakeFiles/opencv_xfeatures2d.dir/src/boostdesc.cpp.o
modules/xfeatures2d/CMakeFiles/opencv_xfeatures2d.dir/build.make:80: recipe for target 'modules/xfeatures2d/CMakeFiles/opencv_xfeatures2d.dir/src/boostdesc.cpp.o' failed
CMakeFiles/Makefile2:6776: recipe for target 'modules/xfeatures2d/CMakeFiles/opencv_xfeatures2d.dir/all' failed
Makefile:162: recipe for target 'all' failed
/home/max/go/src/gocv.io/x/gocv
rm -rf /tmp/opencv
Makefile:89: recipe for target 'clean' failed
```
Thank you.

**Comment by deadprogram** [comment]
Hello @maxrousseau the `xfeatures2d` module in OpenCV is part of the OpenCV contrib. You might be missing some of the dependencies that it requires.

See https://github.com/hybridgroup/gocv/tree/master/contrib#how-to-use

```
Note that some of the features in this package require building OpenCV with the OPENCV_ENABLE_NONFREE=ON option. You can run make build_nonfree to build with this option.
```

**Comment by maxrousseau** [comment]
Hello @deadprogram, thank you for responding.

Yes, I am pretty sure that you are right. However, I was under the impression that running make install or sudo make install would take care of the build of contrib modules as well. I am unsure how to solve this error.

From the page you linked:
_"If you have followed the installation instructions from the main README, then the OpenCV contrib modules have already been compiled and installed."_

**Comment by deadprogram** [comment]
The `make build_nonfree` exists to solve this.

https://github.com/hybridgroup/gocv/blob/release/Makefile#L119

Closing due to age, reopen if needed. Thanks!
