### ISSUE TITLE
don't work base example(motion-detect) 

### ISSUE THREAD

**Issue by beho1der** [hybridgroup/gocv#432]
I use base example movedetection + http web server with rtsp camera (https://pastebin.com/Kb3wnPwA)
Project build, but when i run, create error:

terminate called after throwing an instance of 'cv::Exception'
  what():  OpenCV(4.1.0-pre) /home/captain/opencv/modules/core/src/matrix.cpp:757: error: (-215:Assertion failed) dims <= 2 && step[0] > 0 in function 'locateROI'

SIGABRT: abort
PC=0x7f95c152ee97 m=0 sigcode=18446744073709551610

goroutine 0 [idle]:
runtime: unknown pc 0x7f95c152ee97
stack: frame={sp:0x7ffcebd7aab0, fp:0x0} stack=[0x7ffceb57c308,0x7ffcebd7b330)
......

Base example [mjpeg-streamer](https://github.com/hybridgroup/gocv/tree/master/cmd/mjpeg-streamer) WORK. I use mix example,because on system missing Xorg

* Operating System and version: debian 9
* OpenCV version used: 4.1.0-pre
* How did you install OpenCV? from source with support CUDA
* GoCV version used: lattest
* Go version: go1.11.2 linux/amd64
* Did you run the `env.sh` or `env.cmd` script before trying to `go run` or `go build`? go build

**Comment by deadprogram** [comment]
Hello @beho1der this is not one of the examples include in the project, although you have used parts of 2 different examples. 

I cannot really debug your code for you, however from a quick glance you never read in a `Mat` from your `webcam`. That is probably why that assertion is failing.

Hope that helps!
