### ISSUE TITLE
Set text utf-8 garbled

### ISSUE THREAD

**Issue by khlipeng** [hybridgroup/gocv#440]
`	gocv.PutText(&aiImg, "中文", image.Point{
				10,
				10,
			}, gocv.FontHersheyPlain, 1, red, 1)

`

**Comment by deadprogram** [comment]
Hi @khlipeng utf-8 characters are not supported by OpenCV itself. See https://stackoverflow.com/questions/15519373/opencv-puttext-utf-8-characters

Hope that helps!

**Comment by deadprogram** [comment]
Now closing.
