### ISSUE TITLE
Cannot execute code w/ specfic inputs

### ISSUE THREAD

**Issue by GitThatCyber** [hybridgroup/gocv#443]
## Description

NOOB here! I am getting familiarized with the Golang. These libraries have been quite useful so far. Now that I am trying to progress there seems to be a required argument that I am unfamiliar with. The exact argument sample is 'go run facetracker.go [model] [config] ([backend] [device])'. For the 'model' input I am using 'res10_300x300_ssd_iter_140000.caffemodel' and for the 'config' input I am using 'deploy.prototxt.txt'. I have searched far and wide for any advice on what exactly '([backend] [device])' refers to with no avail. Any assistance would be greatly appreciated. 
## Steps to Reproduce

1. go run tello_facetracker_edit.go res10_300x300_ssd_iter_140000.caffemodel deploy.prototxt.txt 
2.
3.
4.

## Your Environment

* Operating System and version: Ubuntu 18.04
* OpenCV version used: 3.2.0
* How did you install OpenCV? Website instructions
* GoCV version used: 0.19.0
* Go version: go1.12.4
* Did you run the `env.sh` or `env.cmd` script before trying to `go run` or `go build`? No. I believe the GOPATH configuration has been setup via the bashrc script.

**Comment by deadprogram** [comment]
Hi @GitThatCyber that is code that can only work with the Tello drone, first of all.

In any case, take alook at https://godoc.org/gocv.io/x/gocv#Net.SetPreferableBackend and https://godoc.org/gocv.io/x/gocv#Net.SetPreferableTarget

Hope that helps.
