### ISSUE TITLE
Install on Ubuntu 18.04 failed

### ISSUE THREAD

**Issue by vinchauhan** [hybridgroup/gocv#448]
## Description
`rm -rf /tmp/opencv
go run ./cmd/version/main.go`
`# bytes
/usr/local/go/src/bytes/bytes_decl.go:10:6: IndexByte redeclared in this block
	previous declaration at /usr/local/go/src/bytes/bytes.go:101:34
/usr/local/go/src/bytes/bytes_decl.go:17:6: Equal redeclared in this block
	previous declaration at /usr/local/go/src/bytes/bytes.go:18:25
/usr/local/go/src/bytes/bytes_decl.go:24:6: Compare redeclared in this block
	previous declaration at /usr/local/go/src/bytes/bytes.go:37:27
Makefile:106: recipe for target 'verify' failed
make: *** [verify] Error 2`

## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Operating System and version: Ubuntu 18.04
* OpenCV version used:
* How did you install OpenCV? 
1. go get -u -d gocv.io/x/gocv
2. cd $GOPATH/src/gocv.io/x/gocv
3. make install

* GoCV version used:
* Go version:
* Did you run the `env.sh` or `env.cmd` script before trying to `go run` or `go build`?

**Comment by deadprogram** [comment]
Hi @vinchauhan what version of Go do you have installed?

**Comment by vinchauhan** [comment]
> Hi @vinchauhan what version of Go do you have installed?

I recently migrated to latest on this machine and this is the first time I am installing gocv on it.

~/go/src/gocv.io/x/gocv$ go version
go version go1.12.5 linux/amd64

**Comment by deadprogram** [comment]
Looks like a problem with your overall Go install. Hard to tell from the info you sent, but it is known to work on that OS.

**Comment by vinchauhan** [comment]
Yeah looks like I had to reinstall Go as many other things were giving the same error - I havent tried to reinstall gocv yet after I reinstalled my Go - It was likely an install issue on my end.
