### ISSUE TITLE
How to access the RTSP stream video?

### ISSUE THREAD

**Issue by sage-z** [hybridgroup/gocv#449]
## Description

How to access the RTSP stream video？I wanted to receive the webcam stream in real time, but I only saw an int type of device ID in the parameters of OpenVideoCapture。
## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Operating System and version:
* OpenCV version used: 4.1
* How did you install OpenCV?
* GoCV version used: 0.19.0
* Go version: 1.12.3
* Did you run the `env.sh` or `env.cmd` script before trying to `go run` or `go build`?

**Comment by deadprogram** [comment]
If you look at https://godoc.org/gocv.io/x/gocv#OpenVideoCapture you will see you can pass an `int` for the camera ID or a string for a file or URL.

Hope that helps!

**Comment by sage-z** [comment]
My mistake, because I see that converting string to int in OpenVideoCapture，so I thought the url was unsupported. Thank you ~
