### ISSUE TITLE
AdaptiveThreshold, FindContours runtime error

### ISSUE THREAD

**Issue by anysz** [hybridgroup/gocv#451]
# Runtime Error
Hi, I just build opencv 4.0.1 then i tried to compile the program, and it's success
but when the application run AdaptiveThreshold, FindContours it got runtime error.
I wonder is there any mistake?

This is the sample code
```golang
package main
import (
	"fmt"
	_ "image"
	cv2 "gocv.io/x/gocv"
)
func main() {
	path := "yuuki_tatsuya_b.jpg"
	window := cv2.NewWindow("testing")
	img := cv2.IMRead(path, cv2.IMReadColor)
	if img.Empty() {
		fmt.Println("cant read image")
		fmt.Println("end.")
		return
	}
	imgray := cv2.NewMat()
	cv2.CvtColor(img, &imgray, cv2.ColorBGRToGray)
	//th1 := cv2.NewMat() // got error
	//cv2.AdaptiveThreshold(img, &th1, 255.0, cv2.AdaptiveThresholdGaussian, cv2.ThresholdBinary, 1023, 0.0)
	th2 := cv2.NewMat()
	cv2.Threshold(img, &th2, 8.0, 255.0, cv2.ThresholdBinary)

	contours := cv2.FindContours(img, cv2.RetrievalExternal, cv2.ChainApproxSimple) // got error too
	fmt.Printf("%+v\n", contours)

	cv2.IMWrite("testing.jpg", imgray)
	cv2.IMWrite("testing2.jpg", th2)

	for { 
		window.IMShow(img)
		if window.WaitKey(1) >= 0 {
			break
		}
	}
}
```

And got error:
![image](https://user-images.githubusercontent.com/26342994/58177492-af707200-7cce-11e9-9f11-cfd172bfe0dc.png)

* Operating System and version: `Windows 10`
* OpenCV version used: `4.0.1`
* How did you install OpenCV? `Build from source`
* GoCV version used: `0.19.0`
* Go version: `go1.11.2 windows/amd64`
* Did you run the `env.sh` or `env.cmd` script before trying to `go run` or `go build`? no, because the content `ECHO This script is no longer necessary and has been deprecated.`

**Comment by deadprogram** [comment]
Closing due to age, please reopen if needed. Thank you.
