### ISSUE TITLE
Error opening video capture device: 0

### ISSUE THREAD

**Issue by hxdef2517** [hybridgroup/gocv#454]
I'm trying to get access for my Facetime hd camera on mac pro, but it always throws an error stated in the title. 

```
webcam, err := gocv.OpenVideoCapture(deviceID)
	if err != nil {
		fmt.Printf("Error opening video capture device: %v\n", deviceID)
		return
	}
	defer webcam.Close()
```

Any ideas on how to fix it ?

**Comment by hxdef2517** [comment]
Issue fixed using iTerm, using standard terminal permissions are not requested and progrma throws this exception

**Comment by XYZ0901** [comment]
can u tell me how to deal it
