### ISSUE TITLE
go run with error on centos 7

### ISSUE THREAD

**Issue by jilieryuyi** [hybridgroup/gocv#455]
Step 12/12 : RUN find / -name libopencv_gapi.so.4.1
 ---> Running in 2664a2feb61f
/usr/local/lib64/libopencv_gapi.so.4.1

error while loading shared libraries: libopencv_gapi.so.4.1: cannot open shared object file: No such file or directory

file exists path: /usr/local/lib64/libopencv_gapi.so.4.1
how to fixed it ?

**Comment by jilieryuyi** [comment]
fixed by ENV LD_LIBRARY_PATH="LD_LIBRARY_PATH:/usr/local/lib64/"

**Comment by judas852** [comment]
Hi. I have this problem. please explain detail. T__T

**Comment by litterGuy** [comment]
thanks
