### ISSUE TITLE
OpenVideoCapture concurrently

### ISSUE THREAD

**Issue by XieGP** [hybridgroup/gocv#456]
Hello!
I have some questions while calling gocv.OpenVideoCapture().
Can I call `gocv.OpenVideoCapture(uri)` concurrently? I've tried to open it in different goroutines, but it seem to be opened one by one.

I'm using latest version of gocv on alpine, and version of opencv is 4.0.1.

Thank you very much!

**Comment by litterGuy** [comment]
can u tell me how to deal it
