### ISSUE TITLE
Liveness Detection with gocv

### ISSUE THREAD

**Issue by hxdef2517** [hybridgroup/gocv#457]
Basically as a title states, I'm looking for any example for liveness detection using gocv. Is it possible with the current version or not? 

Sample video of what I'm trying to achieve:
https://www.youtube.com/watch?v=MPedzm6uOMA

**Comment by deadprogram** [comment]
Looks interesting, let us know what you find out there code-wise.

**Comment by hxdef2517** [comment]
@deadprogram you are the creator of this repo ^^ I thought you are the best to answer my question ))))

**Comment by deadprogram** [comment]
The OpenCV ecosystem is huge. Let us know what you discover.
