### ISSUE TITLE
CovertTo panics when trying to convert Mat

### ISSUE THREAD

**Issue by awebb-nz** [hybridgroup/gocv#459]
## Description

I was trying to port some [opencv code](https://docs.opencv.org/3.4/d5/dc4/tutorial_video_input_psnr_ssim.html) from c++ to go, and had converted the following c++ code from 

```c_cpp
Mat I1, I2;
i1.convertTo(I1, d);
```

to

```go
var I1, I2 gocv.Mat
i1.ConvertTo(&I1, gocv.MatTypeCV32F)
```

However, when I try to run the code it panics in the `ConvertTo()` call:

```
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x4 pc=0x7dea538]
```

I have tried using different images, and converting to different types, but I get the same result. It is very possible that I am just doing something daft, but I am not even sure how to debug the problem. Any suggestions most welcome! 

Note: I have other projects that use gocv and they seem to work fine.

## Steps to Reproduce
Here is a minimal(-ish) example:

```go
package main

import (
	"fmt"
	"os"

	"gocv.io/x/gocv"
)

func main() {
	img1 := gocv.IMRead("some_image.jpg", gocv.IMReadGrayScale)
	if img1.Empty() {
		fmt.Println("unable to read image file")
		os.Exit(1)
	}
	fmt.Printf("Image size: %v\n", img1.Size()) // check that the size makes sense
	var i1 gocv.Mat
	img1.ConvertTo(&i1, gocv.MatTypeCV32F) // panic occurs here
	fmt.Printf("Image size: %v\n", i1.Size())
}
```

## Your Environment

* Operating System and version: macOS 10.13.6
* OpenCV version used: 4.1.0
* How did you install OpenCV? homebrew
* GoCV version used: v0.20.0
* Go version: 1.12.5

**Comment by deadprogram** [comment]
You probably want to use

```
i1 := gocv.NewMat()
```

instead of

```
var i1 gocv.Mat
```

because you need to actually tell OpenCV itself to perform the allocation of the new empty Mat.

Hope that helps!

**Comment by awebb-nz** [comment]
That does seem to have fixed the problem. Thanks for your help!
