### ISSUE TITLE
windows7 使用 win_build_opencv.cmd 安装到 最后 报错

### ISSUE THREAD

**Issue by dzwvip** [hybridgroup/gocv#463]
## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Operating System and version:
* OpenCV version used:
* How did you install OpenCV?
* GoCV version used:
* Go version:
* Did you run the `env.sh` or `env.cmd` script before trying to `go run` or `go build`?
![image](https://user-images.githubusercontent.com/17947637/58870295-87333b00-86f2-11e9-9a70-97860598c049.png)

**Comment by deadprogram** [comment]
Sorry, but WIndows 7 is not an official supported config for this project.

You might want to investigate whatever was done in PR https://github.com/hybridgroup/gocv/pull/350

Hope that helps!
