### ISSUE TITLE
I get this error ”Error opening file: D:/learning/video/07.avi“，when use VideoCaptureFile

### ISSUE THREAD

**Issue by zl2211987** [hybridgroup/gocv#469]
I use gocv VideoCaptureFile like this：

        window := gocv.NewWindow("Hello")
	defer window.Close()
	window.ResizeWindow(960,540)
	img := gocv.NewMat()
	defer img.Close()
	cap,err := gocv.VideoCaptureFile("D:/learning/video/07.avi")
	defer cap.Close()
        for {
		cap.Read(&img)
		window.IMShow(img)
		window.WaitKey(1)
	}

Error message is :
          Error opening file: D:/learning/video/07.avi

My Environment:
* Operating System and version: win 10
* OpenCV version used: 4.1.0
* GoCV version used: 0.20.0
* Go version:1.12.5

**Comment by zl2211987** [comment]
The error has been solved：
   the reason is when compiling with cmake，opencv_ffmpeg_64.dll and opencv_ffmpeg.dll download failure

**Comment by xusk** [comment]
cmake check video ffmpeg

**Comment by Wenshiqi222** [comment]
i did this on my centOS machine,but still got the same error when i use the VideoCaptureFile in my code, what should i do ? Did i miss sth with  the opencv component?

**Comment by xusk** [comment]
opencv 编译的时候，要看下 ffmpeg 编译进去了没有，有这个依赖

**Comment by feipengheart** [comment]
Where can I download ffMPEG manually, and how to edit it after downloading
