### ISSUE TITLE
Does gocv support existing opencv3?

### ISSUE THREAD

**Issue by ZXHSunSalt** [hybridgroup/gocv#470]
## Description

I have installed opencv3 before. Now I want to use gocv with opencv3. I use origin opencv.pc file. When I go build the project, it occurs some errors:
# gocv.io/x/gocv
core.cpp: In function ‘void Mat_Size(Mat, IntVector*)’:
core.cpp:145:27: error: ‘struct cv::MatSize’ has no member named ‘dims’
     int* ids = new int[ms.dims()];
                                       ^~~~
core.cpp:147:31: error: ‘struct cv::MatSize’ has no member named ‘dims’
     for (size_t i = 0; i < ms.dims(); ++i) {  
core.cpp:151:22: error: ‘struct cv::MatSize’ has no member named ‘dims’
     res->length = ms.dims();

## Your Environment

* Operating System and version: Jetson nano arm system
* OpenCV version used: 3.3.0
* GoCV version used: latest version
* Go version:1.12
* Did you run the `env.sh` or `env.cmd` script before trying to `go run` or `go build`? yes

**Comment by WendelHime** [comment]
On OpenCV 3.3, MatSize doesn't support the function [dims()](https://docs.opencv.org/3.4.2/df/d63/structcv_1_1MatSize.html#a5e7cfd2e21867c010f973db8c915bfaa), this function was added on version 3.4.2.

If you try to run with an older gocv version, I think you'll miss a lot of features. Currently, gocv is based on OpenCV 4.1, to run with OpenCV 3.3 you'll  have to rewrite the functions to resolve all conflicts and I think it will give a lot of work.

Is there a problem with OpenCV 4.1?

**Comment by deadprogram** [comment]
The most recent release of GoCV requires OpenCV 4.1.0

You will need to upgrade your OpenCV installation in order to use the latest version of GoCV.

Hope that helps! Now closing.
