### ISSUE TITLE
Release through binary packages

### ISSUE THREAD

**Issue by lchjczw** [hybridgroup/gocv#473]
首先非常感谢gocv的开发者和参与者，这是个非常好的开发版本，不过我在使用的过程中，发生了一些问题，先说下我的使用经历：
我折腾了一个下午，就是为了解决opencv的环境兼容问题，因为特殊原因，我windows上的mingw需要安装两个版本，然后我开始了一下午配置的过程，最终虽然能用了，但是破坏了我本地的一些其他配置，所以我想，能不能发布binary packages，这样对应平台下载对应的binary packages就可以了，利用golang本身的平台兼容性，让所有开发的人都不用折腾开发环境的问题。

**Comment by WendelHime** [comment]
Hi @lchjczw , I've translated with google (sorry if I didn't understand what you mean).

Your suggestion is to make and distribute an unofficial pre-built OpenCV package to minimize the configuration process on windows?

I think it'll be amazing, some things like environment variables will still need to be changed, I don't know if there'll be a performance problem. I'm just don't know why OpenCV doesn't provide pre-built packages

**Comment by lchjczw** [comment]
@WendelHime  I'm sorry, I think this document can fully express what I mean

Golang's official notes:

`https://github.com/golang/proposal/blob/master/design/2775-binary-only-packages.md`

**Comment by lchjczw** [comment]
This method is similar to the static link library of the C language

**Comment by deadprogram** [comment]
Unfortunately that does not work quite as you expect with Go packages that use CGo. So it is not an option for GoCV.

For OpenCV, you might have success with a pre-built set of binaries for your distro, but that would be better supported by the OpenCV team themselves.
