### ISSUE TITLE
Latency in RTSP stream vs a client like VLC

### ISSUE THREAD

**Issue by acharyab15** [hybridgroup/gocv#475]
## Description

I am trying to work with RTSP streams with GoCV and I am seeing a delay in the displayed images by around 5 seconds -- which seems a bit high. All I am doing is essentially running
the hello world example: 

```
package main

import (
	"gocv.io/x/gocv"
)

func main() {
	webcam, _ := gocv.OpenVideoCapture(<rtsp url>)
	window := gocv.NewWindow("Hello")
	img := gocv.NewMat()

	for {
		webcam.Read(&img)
		window.IMShow(img)
		window.WaitKey(1)
	}
}

```

To compare, I tried with vlc by running `vlc <rtsp url>`. 

If I watch both feeds at the same time, the GoCV video is behind by around 5 seconds. Is this normal? Am I missing something?

I am using the following versions if it helps.
go: go1.12 darwin/amd64
gocv version: 0.20.0
opencv lib version: 4.1.0
![Screen Shot 2019-06-28 at 12 16 01 PM](https://user-images.githubusercontent.com/7025404/60365797-97ab9e00-999e-11e9-8afc-dd46bf1b7f3b.png)

**Comment by deadprogram** [comment]
If all you want is to display the video, what's wrong with using VLC? I think the best use of GoCV/OpenCV is to use the various algorithms on the video data, as OpenCV is not optimized for reducing video display latency on streams per se.

I have no actual performance stats to back up that statement, but seems like a pretty safe bet.

**Comment by acharyab15** [comment]
Since the GoCV display of video was delayed, I was concerned if there was some preprocessing / buffering going on somewhere that would delay my OpenCV algorithms as well. And I couldn't find anything as such other than the C calls so I was confused. However, a teammate tried it on his machine, and the GoCV performance was actually a lot better, and even better than VLC for him. So it's probably just my machine that was acting weird. Thanks for your input!
