### ISSUE TITLE
please add FlannBasedMatcher feature matcher

### ISSUE THREAD

**Issue by semihs** [hybridgroup/gocv#480]
when do you plan FlannBasedMatcher feature ?

**Comment by tazzaoui** [comment]
Any progress on this? Happy to help if needed

**Comment by deadprogram** [comment]
Hi @tazzaoui a PR that added this would be gratefully accepted.

Please see https://github.com/hybridgroup/gocv/blob/master/CONTRIBUTING.md#how-to-add-a-function-from-opencv-to-gocv for our contribution guidelines.

**Comment by deadprogram** [comment]
Code added for this feature that will be included in the next release.

**Comment by deadprogram** [comment]
This has now been released so closing. Thanks!
