### ISSUE TITLE
Memory Leak in Mat.Size()

### ISSUE THREAD

**Issue by sshibs** [hybridgroup/gocv#486]
I am using gocv to process a large number of images and I noticed I had a bit of a memory leak. I narrowed it down to the Mat.Size() call. It could be you already know about this, and I don't know what the solution would be, but I thought I would post it just incase.

## Description

Looking at the C++ code for Mat_Size it looks like the issue is because "new" is called to make the ids array, but it is never deleted because ids is returned to the go code.

```
void Mat_Size(Mat m, IntVector* res) {
    cv::MatSize ms(m->size);
    int* ids = new int[ms.dims()];

    for (size_t i = 0; i < ms.dims(); ++i) {
        ids[i] = ms[i];
    }

    res->length = ms.dims();
    res->val = ids;
    return;
}
```

## Steps to Reproduce

Here is a simple program to reproduce the issue:
```
import (
	"gocv.io/x/gocv"
)

func main() {
	img := gocv.NewMatWithSizeFromScalar(gocv.Scalar{0, 0, 0, 0}, 500, 500, gocv.MatTypeCV8UC3)
	defer img.Close()
	for i := 0; i < 100000000; i++ {
		img.Size()
	}
}
```

## Your Environment

* Operating System and version: Ubuntu 18.04
* OpenCV version used: 4.1
* How did you install OpenCV? installation guide
* GoCV version used: 0.20.0
* Go version: 1.12.1
* Did you run the `env.sh` or `env.cmd` script before trying to `go run` or `go build`? No

**Comment by deadprogram** [comment]
This issue was corrected by #580 so now closing. Thank you!
