### ISSUE TITLE
Issue with openvino/env.sh (GoCV, Openvino, and Ubuntu 18.04)

### ISSUE THREAD

**Issue by bus710** [hybridgroup/gocv#491]
## Description

This is my workaround to solve the problem I met (though I don't know what happen if I want to use PVL in the near future).

In the first compilation as the guide (https://github.com/hybridgroup/gocv/tree/master/openvino), I tried to get the version number at the end of the installation.

I got the errors from the linker:
```
/usr/bin/ld: cannot find -ldliaPlugin
/usr/bin/ld: cannot find -lHeteroPlugin
/usr/bin/ld: cannot find -lMKLDNNPlugin
/usr/bin/ld: cannot find -lmyriadPlugin
/usr/bin/ld: cannot find -linference_engine
/usr/bin/ld: cannot find -lclDNNPlugin
/usr/bin/ld: cannot find -lopencv_pvl
```

I eventually had to modify the env.sh under openvino as below and the issue is gone:
```
export CGO_CXXFLAGS="--std=c++11"
export CGO_CPPFLAGS="-I${INTEL_CVSDK_DIR}/opencv/include -I${INTEL_CVSDK_DIR}/deployment_tools/inference_engine/include"
export CGO_LDFLAGS="-L${INTEL_CVSDK_DIR}/opencv/lib -L${INTEL_CVSDK_DIR}/deployment_tools/inference_engine/lib/intel64 -lpthread -ldl -lHeteroPlugin -lMKLDNNPlugin -lmyriadPlugin -linference_engine -lclDNNPlugin -lopencv_core -lopencv_videoio -lopencv_imgproc -lopencv_highgui -lopencv_imgcodecs -lopencv_objdetect -lopencv_features2d -lopencv_video -lopencv_dnn -lopencv_calib3d"
export PKG_CONFIG_PATH=/usr/lib64/pkgconfig
```

The points are:
- The path to the lib is changed since openvino on ubuntu 18.04 has different path.
- **lopencv_pvl** is removed since I couldn't find it anywhere. 

Other than the file contents, I didn't touch other things yet and the compilation gave this output:
```
$ bus710@test:gocv$ pwd
/home/bus710/go/src/gocv.io/x/gocv

$ bus710@test:gocv$ go run --tags openvino cmd/version/main.go 
gocv version: 0.20.0
opencv lib version: 4.1.1-openvino
```

## Steps to Reproduce

The problem came out in following the doc (https://github.com/hybridgroup/gocv/tree/master/openvino).

## Your Environment

* Operating System and version: Ubuntu 18.04
* OpenCV version used: 4.1.1-openvino
* How did you install OpenCV?: Openvino
* GoCV version used: 0.20.0
* Go version: 1.12.5
* Did you run the `env.sh` or `env.cmd` script before trying to `go run` or `go build`?

**Comment by bus710** [comment]
This could be addressed already since it seems like I am little late to the party.
If so, please share the link to the Q&A and close this.

**Comment by bus710** [comment]
I am trying to compile the example of PVL and getting this error:

```
face.h:8:10: fatal error: opencv2/pvl.hpp: No such file or directory
```

This seems like this issue:
- https://github.com/hybridgroup/gocv/issues/245

**Comment by bus710** [comment]
So now the env.sh became like this:
```
export CGO_CXXFLAGS="--std=c++11"
export CGO_CPPFLAGS="-I${INTEL_CVSDK_DIR}/opencv/include -I${INTEL_CVSDK_DIR}/deployment_tools/inference_engine/include"
export CGO_LDFLAGS="-L${INTEL_CVSDK_DIR}/opencv/lib -L${INTEL_CVSDK_DIR}/deployment_tools/inference_engine/lib/intel64 -L${LD_LIBRARY_PATH} -lpthread -ldl -lHeteroPlugin -lMKLDNNPlugin -lmyriadPlugin -linference_engine -lclDNNPlugin -lopencv_core -lopencv_videoio -lopencv_imgproc -lopencv_highgui -lopencv_imgcodecs -lopencv_objdetect -lopencv_features2d -lopencv_video -lopencv_dnn -lopencv_calib3d -lopencv_pvl" 
export PKG_CONFIG_PATH=/usr/lib64/pkgconfig
```

And the run command (go run -tags openvino cmd/openvino/pvl/facerecognizer/main.go) shows this error:
 
```
# runtime/cgo
/usr/bin/ld: cannot find -lopencv_pvl
collect2: error: ld returned 1 exit status
```

This is probably the newer version of openvino didn't install PVL library somehow.

**Comment by bus710** [comment]
Okay, so that is no libopencv_pvl.so for **openvino_2019.2.242** (at least in my system).
but for some reason there that is for **openvino_2019.1.144**.

**Comment by bus710** [comment]
From this release note of Openvino 2019 R2 (https://software.intel.com/en-us/articles/OpenVINO-RelNotes): 

OpenCV*
- Version changed to 4.1.1
- Merged all Python* 3 wrappers into one universal binary: <openvino>/python/python3/cv2.<ext>
- Added MediaSDK plugin for opencv_videoio module
- Enabled TBB backend for parallel computations (on Linux platforms)
- **Removed opencv_pvl module**, please consider using corresponding algorithms from the Open Model Zoo

PVL is indeed removed.

**Comment by deadprogram** [comment]
Would anyone like to submit a PR to remove the PVL support from GoCV? I'd gladly accept it! :)

**Comment by bus710** [comment]
@deadprogram 

After couple days of struggling with OpenVINO, I just decided to make some IPC between CPP/PY OpenVINO app and Go app because it seems like there is no more support from Intel.

Let me close this.
