### ISSUE TITLE
Simple govc sample hangs under windows 10 64 bits

### ISSUE THREAD

**Issue by jcbritobr** [hybridgroup/gocv#492]
## Description
When running a simple gocv sample, and hiting a key to exit, the program hangs and crashs under windows 10.

## Steps to Reproduce
1) Run the below program
2) Hit any key to exit
3) Program hangs and don't exit
```go
package main

import (
	"gocv.io/x/gocv"
)

func main() {

	webcam, _ := gocv.VideoCaptureDevice(0)
	window := gocv.NewWindow("Simple Sample")
	img := gocv.NewMat()

	for {
		webcam.Read(&img)
		window.IMShow(img)
		if window.WaitKey(10) >= 0 {
			break
		}
	}
}
```

## Your Environment

* Operating System and version: windows 10 home 64 bits
* OpenCV version used: 4.1.0
* How did you install OpenCV? Using gocv instructions for windows
* GoCV version used: 0.20.0
* Go version: go 1.12.1 windows/64
* Did you run the `env.sh` or `env.cmd` script before trying to `go run` or `go build`?
GOPATH is exported

**Comment by entrehuihui** [comment]
> ## 重现步骤
> 1. 运行以下程序
> 2. 按任意键退出
> 3. 程序挂起，不退出
> 
> ```go
> 包主
> 
> import（
> 	 “ gocv.io/x/gocv ”
> ）
> 
> func  main（）{
> 
> 	摄像头，_  ：= gocv。VideoCaptureDevice（0）
> 	 窗口 ：= gocv。NewWindow（“简单样本”）
> 	 img  ：= gocv。NewMat（）
> 
> 	for {
> 		摄像头。阅读（＆img）
> 		窗口。IMShow（img）
> 		 if window。WaitKey（10）> = 0 {
> 			 break
> 		}
> 	}
> }
> ```
> 
> ## 你的环境
> * 操作系统和版本：windows 10 home 64位
> * 使用的OpenCV版本：4.1.0
> * 你是如何安装OpenCV的？使用gocv指令的窗口
> * 使用的GoCV版本：0.20.0
> * 转到版本：去1.12.1 windows / 64
> * 在尝试或之前你是否运行过`env.sh`或`env.cmd`脚本？
>   GOPATH已导出`go run``go build`



> ## Description
> When running a simple gocv sample, and hiting a key to exit, the program hangs and crashs under windows 10.
> 
> ## Steps to Reproduce
> 1. Run the below program
> 2. Hit any key to exit
> 3. Program hangs and don't exit
> 
> ```go
> package main
> 
> import (
> 	"gocv.io/x/gocv"
> )
> 
> func main() {
> 
> 	webcam, _ := gocv.VideoCaptureDevice(0)
> 	window := gocv.NewWindow("Simple Sample")
> 	img := gocv.NewMat()
> 
> 	for {
> 		webcam.Read(&img)
> 		window.IMShow(img)
> 		if window.WaitKey(10) >= 0 {
> 			break
> 		}
> 	}
> }
> ```
> 
> ## Your Environment
> * Operating System and version: windows 10 home 64 bits
> * OpenCV version used: 4.1.0
> * How did you install OpenCV? Using gocv instructions for windows
> * GoCV version used: 0.20.0
> * Go version: go 1.12.1 windows/64
> * Did you run the `env.sh` or `env.cmd` script before trying to `go run` or `go build`?
>   GOPATH is exported

You have to turn off your open device use defer

**Comment by jcbritobr** [comment]
There are no defer in samples entrehuihui

package main

import (
	"gocv.io/x/gocv"
)

func main() {
	webcam, _ := gocv.VideoCaptureDevice(0)
	window := gocv.NewWindow("Hello")
	img := gocv.NewMat()

	for {
		webcam.Read(&img)
		window.IMShow(img)
		window.WaitKey(1)
	}
}

**Comment by entrehuihui** [comment]
> There are no defer in samples entrehuihui
> 
> ```
> package main
> 
> 
> import (
> 	"gocv.io/x/gocv"
> )
> 
> func main() {
> 	webcam, _ := gocv.VideoCaptureDevice(0)
> 	window := gocv.NewWindow("Hello")
> 	img := gocv.NewMat()
> 
> 	for {
> 		webcam.Read(&img)
> 		window.IMShow(img)
> 		window.WaitKey(1)
> 	}
> }
> ```

func main() {
	webcam, _ := gocv.VideoCaptureDevice(0)
	defer webcam.Close()
	window := gocv.NewWindow("Simple Sample")
	window.Close()
	img := gocv.NewMat()

	for {
		webcam.Read(&img)
		window.IMShow(img)
		if window.WaitKey(10) >= 0 {
			break
		}
	}
}


I will copy your code and add a delay statement before it will crash. 
I think the main thing is defer webcam.Close(), You don't have to use this device to shut down, the specific reason should be the operation of designing memory to memory.

**Comment by deadprogram** [comment]
Closing due to age, please reopen if needed. Thanks!
