### ISSUE TITLE
Ask recording video with this lib

### ISSUE THREAD

**Issue by yogihardi** [hybridgroup/gocv#495]
Hi,

I just want to ask, is there possible to record the video that being captured and analyzed with this lib? so, it will be parallel processing: stream, record and analyze an object (e.g: detect face/human)? 

thanks.

**Comment by deadprogram** [comment]
Take a look at the docs for https://godoc.org/gocv.io/x/gocv#VideoWriter and the example here https://github.com/hybridgroup/gocv/blob/master/cmd/savevideo/main.go

Hope that helps start you in the right direction. Now closing.
