### ISSUE TITLE
Error:Invalid UE golomb code,when using docker

### ISSUE THREAD

**Issue by ximencoder** [hybridgroup/gocv#516]
I used Dockerfile to build a container,which verison is 
gocv version: 0.20.0
opencv lib version: 4.1.0

And Got many errors when capturing a  video source by rtmp url,like this:
**Invalid UE golomb code.**
How to fix this? thank you

**Comment by deadprogram** [comment]
This error appears to be generated by ffmpeg. Probably you are not able to connect to the host because of Docker network settings?

In any case, this is outside the scope of GoCV itself, so now closing. Please reopen if this was in error. Thank you.
