### ISSUE TITLE
add param1, param2, minRadius, maxRadius params to HoughCircles

### ISSUE THREAD

**Issue by df-andrew** [hybridgroup/gocv#52]
Currently `HoughCircles` takes in 4 parameters
```func HoughCircles(src Mat, circles Mat, method int, dp float64, minDist float64)```

the OpenCV HoughCircles methods lets you pass in ```double param1, double param2, int minRadius, int maxRadius``` as well as the 4 params currently present.

any chance HoughCircles will be updated to allow for the extra 4 params?

**Comment by deadprogram** [comment]
Hello @df-andrew the typical pattern that we have been following, is to provide both a default aka `HoughCircles()` function thta uses all the defaults possible, and then a `HoughCirclesWithParams()` function that requires all of the various params be passed in.

Take a look at https://github.com/hybridgroup/gocv/issues/29 for an example.

A PR adding this would be gratefully accepted.

**Comment by deadprogram** [comment]
Additional sample and `WithParams` variation have been released as part of v0.11.0 thank you everyone! Now closing.
