### ISSUE TITLE
findHomography not implemented

### ISSUE THREAD

**Issue by LarryHanson** [hybridgroup/gocv#534]
I'm in need of the function findHomography, but it does not appear to be implemented 

The closed issue #301 was resolved by pointing to https://github.com/hybridgroup/gocv/blob/master/ROADMAP.md, but findHomography doesn't appear to be in the roadmap.

If findHomography is not yet in the works by someone else, I'd be happy to dive in and implement it if pointed in the correct general direction. I've read through https://github.com/hybridgroup/gocv/blob/master/CONTRIBUTING.md. If there are helpful specifics for implementing findHomography I'd appreciate any pointers.

## Your Environment
* Operating System and version: MacOS 10.14.5
* OpenCV version used: 
* How did you install OpenCV? brew install opencv
* GoCV version used: opencv lib version: 4.1.2
* Go version: go version go1.13.3 darwin/amd64

**Comment by deadprogram** [comment]
Hi @LarryHanson I just updated the ROADMAP, 

The TLDR version is none of the functions in `calib3d` are implemented yet. Some of the `calib3d::fisheye` functions are implemented, which can provide some guidance. Please see https://github.com/hybridgroup/gocv/blob/master/calib3d.go

**Comment by deadprogram** [comment]
I added `findHomography()` way back here https://github.com/hybridgroup/gocv/commit/7c69402dd24948222ca8c07a7f792886c8618355 but forgot to close this issue.
