### ISSUE TITLE
generate string names of constants

### ISSUE THREAD

**Issue by mh-cbon** [hybridgroup/gocv#539]
I was looking for a quick way to select a colorspace from a given string, because there is so many i have tried to use stringer (https://godoc.org/golang.org/x/tools/cmd/stringer).

unfortunately, this does not work with distant package type.

can you generate constants string value using the stringer ?

```go
//go:generate stringer -output=colorspace.go -trimprefix=Color -type=ColorConversionCode
```

**Comment by deadprogram** [comment]
Thank you so much @mh-cbon for your contribution #552 that addressed this issue? Now closing, please re-open if I was in error.
