### ISSUE TITLE
Face detect - Error reading cascade file: data/haarcascade_frontalface_default.xml

### ISSUE THREAD

**Issue by yunholeeme** [hybridgroup/gocv#573]
## Description

![gocv](https://user-images.githubusercontent.com/12512309/70779051-0ce12300-1dc7-11ea-96ae-e41065f87420.PNG)

go install
result in
C:\coding\GoApp\Go-lang\bin>gocv.exe
Error reading cascade file: data/haarcascade_frontalface_default.xml

C:\coding\GoApp\Go-lang\bin>     

Thank you

## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Operating System and version: Microsoft Windows [Version 10.0.18362.476]
* OpenCV version used: opencv lib version: 4.1.2
* How did you install OpenCV? win_build_opencv.cmd
* GoCV version used: gocv version: 0.21.0
* Go version: go version go1.13.4 windows/amd64
* Did you run the `env.sh` or `env.cmd` script before trying to `go run` or `go build`? no

**Comment by deadprogram** [comment]
Hello @yunholeeme are you sure you have the correct path to the XML file? That error looks a lot like the file could not be found.

**Comment by yunholeeme** [comment]
Hello @deadprogram Thank you. I got it.
