### ISSUE TITLE
Install issue .... `dnn.cpp:119:102: warning: passing NULL to non-pointer argument 1`

### ISSUE THREAD

**Issue by jhaoheng** [hybridgroup/gocv#582]
## Description
1. I followed the readme to install opencv.
2. when I finished the install step ... I got this issue...

Does anyone know what is it means?

```
# gocv.io/x/gocv
dnn.cpp: In function 'cv::Mat* Net_BlobFromImage(Mat, double, Size, Scalar, bool, bool)':
dnn.cpp:119:102: warning: passing NULL to non-pointer argument 1 of 'cv::Scalar_<_Tp>::Scalar_(_Tp) [with _Tp = double]' [-Wconversion-null]
         return new cv::Mat(cv::dnn::blobFromImage(*image, scalefactor, sz, NULL, swapRB, crop, ddepth));
```

and then, when I run the gocv, this issue always has happened.

## Your Environment
```
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

* Operating System and version: debian
* OpenCV version used: opencv lib version: 4.2.0
* How did you install OpenCV? use makefile
* GoCV version used: gocv version: 0.22.0
* Go version: go version go1.13.1 linux/amd64
* Did you run the `env.sh` or `env.cmd` script before trying to `go run` or `go build`? No

**Comment by jhaoheng** [comment]
The OpenCV is workable, but when I run with the gocv, this issue will show at the screen.
How to fix this issue? any idea?

**Comment by jhaoheng** [comment]
I try to build OpenCV & install GoCV at a new docker container(Debian).
And run `go run ./cmd/showimage/main.go /home/img-resources/bona.jpg`
Although the image is shown at the screen, it also has the same warning on the command line.

**Comment by yumanchao** [comment]
the same problem.

**Comment by deadprogram** [comment]
`go run` performs a compile, which is where this warning comes from.

Building and then executing the program does not display any compiler warnings since the code is already, well, compiled. :)

This is the source of the compiler warning, if someone knows how to get around it: https://github.com/hybridgroup/gocv/pull/577#issuecomment-568183200

**Comment by jhaoheng** [comment]
@deadprogram Thank you, and I go back to use OpenCV 4.1.2 and not getting the same issue.

**Comment by sepvan** [comment]
I have the same problem with the gocv.io/x/gocv/main.go example of the Getting Started guide (openCV 4.2.0 in Windows).  Either with gor run or go build of main.go file.
What i have to do?

**Comment by AlstonLicoder** [comment]
I have properly finished  the problem. It's different between the gocv and opencv version. You should download the same version of the gocv and opencv.

**Comment by steph-dmts** [comment]
Hi, I'm having this problem as well, @jhaoheng  can you explain what you mean by that ? How do I uninstall openCV to install 4.1.2 ?

**Comment by steph-dmts** [comment]
> Hi, I'm having this problem as well, @jhaoheng can you explain what you mean by that? How do I uninstall openCV to install 4.1.2?

My bad, I thought this warning was an error, not a warning and that no executable was built.

**Comment by SHT** [comment]
I've managed to suppress mentioned warning with `set CGO_CXXFLAGS=-w` before using `go run` .

**Comment by ITfreeman** [comment]
the same problem.

**Comment by deadprogram** [comment]
I have just merged some code into the `dev` branch that removes this warning.

**Comment by rkawajan** [comment]
the same problem.

**Comment by MikolajMGT** [comment]
same for me

**Comment by karl-ford** [comment]
It brothered me about 2days until I switch (**`gocv 0.22.0`** + **`OpenCV 4.2.0`**)  to **`gocv 0.21.0`** + **`OpenCV __4.1.2__`**).
May be you can got some spark from my exprience. 

## My Environment
* Operating System and version: Windows 10
* Go version: go version go1.13.3 windows/amd64
* OpenCV version used: opencv lib version: 4.2.0
* GoCV version used: gocv version: 0.22.0
* MinGW-w64 version: 8.1.0 (I tried both 8.1.0/7.3.0)
`go run .\cmd\version\main.go`
didn't run smoothly, I got the same problem and the error exit status.
```
dnn.cpp: In function 'cv::Mat* Net_BlobFromImage(Mat, double, Size, Scalar, bool, bool)':
dnn.cpp:119:102: warning: passing NULL to non-pointer argument 1 of 'cv::Scalar_<_Tp>::Scalar_(_Tp) [with _Tp = double]' [-Wconversion-null]
         return new cv::Mat(cv::dnn::blobFromImage(*image, scalefactor, sz, NULL, swapRB, crop, ddepth));
```
I have tried the **`gocv 0.22.0`** with **`OpenCV 4.1.2`**, but **nothing change**.
At last, I have to try **`gocv 0.21.0`** with **`OpenCV 4.1.2`** and **it worked**.

**Comment by hbmask** [comment]
```
//        return new cv::Mat(cv::dnn::blobFromImage(*image, scalefactor, sz, NULL, swapRB, crop, ddepth));
        return new cv::Mat(cv::dnn::blobFromImage(*image, scalefactor, sz, cv::Scalar(), swapRB, crop, ddepth));
```

**Comment by micln** [comment]
the same problem.
