### ISSUE TITLE
[Question] Mat, ToByte()

### ISSUE THREAD

**Issue by jhaoheng** [hybridgroup/gocv#585]
## Description

When I use as below ... the pic output can not read.
```
b, _ := ioutil.ReadFile("xxx.jpg")
BGR, _ := gocv.IMDecode(b, gocv.IMReadUnchanged)
b = BGR.ToBytes()
pic := base64.StdEncoding.EncodeToString(b)
fmt.Println(pic)
```

but when I use `toImage` and then transfer to byte ... it works ...
```
b, _ := ioutil.ReadFile("xxx.jpg")
BGR, _ := gocv.IMDecode(b, gocv.IMReadUnchanged)
to_img, _ := BGR.ToImage()
buf := new(bytes.Buffer)
jpeg.Encode(buf, to_img, nil)
b := buf.Bytes()
pic := base64.StdEncoding.EncodeToString(b)
fmt.Println(pic)
```

About the first, what I made wrong?

**Comment by deadprogram** [comment]
`BGR.ToBytes()` will return the raw `[]byte` data of the `Mat`.

`BGR.ToImage()` converts the raw `Mat` data to a Go `image.RGBA{}` type.

Hope that helps!

**Comment by deadprogram** [comment]
Hi @jhaoheng I was actually just trying to use `ToBytes()` and discovered it was always returning an empty `Mat` for one of my test images. 

I will look into this a little further and let you know what I find out.

**Comment by jhaoheng** [comment]
Thanks @deadprogram

**Comment by deadprogram** [comment]
Reopening so it does not get forgotten.

**Comment by modanesh** [comment]
@deadprogram Any luck on this issue?

**Comment by deadprogram** [comment]
That was addressed a number of releases ago, now closing.
