### ISSUE TITLE
iteration times on Windows seem unbearable

### ISSUE THREAD

**Issue by directive-cary** [hybridgroup/gocv#59]
I'm using Windows 10 with an i7-7700 CPU.  I followed the installation instructions from https://gocv.io/getting-started/windows/ (very well written, by the way--better than the opencv officials docs imo!) and everything did work.

Unfortunately, even toy 10-line programs that do something like "load an image from a file, do Canny edge detection, and display it in a window," are taking 10-15 seconds to compile and link.  Is it possible I've misconfigured something?  Is this unusual?  Or is this just "how things are" with the current state of cgo and large C++ libraries?

I don't want to be overly melodramatic, but as someone who's not already an OpenCV expert, this kind of iteration time is a deal breaker for experimenting and learning the library.

**Comment by deadprogram** [comment]
Hi @directive-cary I would say that the performance of C++ compilation/linking in general of any large project is not great, as I am sure you discovered when installing OpenCV itself.

Also, Windows in general is much slower when compiling C++ using open source toolchains. This is not specific to GoCV itself, but part of needing to compile/link against a large C++ codebase using CGo.

You might want to experiment with precompiled headers, which I have not had time to explore. They are turned off in the Windows build atm due to some incompatibilities in the build I did not dig too far into.

Hope that helps!

**Comment by directive-cary** [comment]
Actually, I dug into things a bit more and a great deal of this pain was me being unfamiliar with the proper care and feeding of cgo modules.  The instructions at https://gocv.io/getting-started/windows/ download gocv using `go get`, then install the OpenCV native libraries, then tell you to go off and write code.  While this works, it means that even if you're just a consumer of the gocv library and not hacking on it at all, you'll still be compiling it from scratch every time you compile your own program.

*I now recommend the setup instructions be amended to reflect this.*

As written, the instructions are perfect for someone who wants to contribute to gocv development.

For someone who wants to consume gocv as a library, there should be a section after the `mingw32-make install` step, and **before** the "how to build/run code" step, that recommends running `go install gocv.io/x/gocv`.  This will pre-build the gocv library into a gocv.a file that's stored under the {GOPATH}/pkg folder.  Then when you write and run an example program that consumes the gocv package, `go build` will merely link with that library, and you will get the < 1s build/link times that you would expect from a typical toy program.

**Comment by deadprogram** [comment]
That is a very good idea @directive-cary any interest in committing a PR with that info added to the README?

**Comment by directive-cary** [comment]
After thinking about a couple different wordings, I decided that being succinct in the readme worked better than a paragraph giving the full explanation of what happens and why to do it.  I hope this matches what you expected.  :)

**Comment by deadprogram** [comment]
Thanks for the PR @directive-cary I will close this issue once the next GoCV release is out.

**Comment by deadprogram** [comment]
This documentation was released as part of v0.8.0 so now closing. Thanks again!

**Comment by rikonor** [comment]
I encountered the same in Linux. Running `go install gocv.io/x/gocv` like @directive-cary mentioned fixed the issue.
