### ISSUE TITLE
Waitting for CUDA GPU predict

### ISSUE THREAD

**Issue by lanybass** [hybridgroup/gocv#596]
I have tried dnn with CUDA in opencv 4.2 cpp version, It's awesome. Can't wait to play in go ^_^
TODO:
support DNN_TARGET_CUDA  and DNN_BACKEND_CUDA

**Comment by Danile71** [comment]
@lanybass, see https://github.com/hybridgroup/gocv/pull/610

**Comment by deadprogram** [comment]
This has been released with v0.23 so now closing. Thanks!
