### ISSUE TITLE
Add function to cast Mat into io.Reader

### ISSUE THREAD

**Issue by plutov** [hybridgroup/gocv#60]
When I use this code:
```
imgFace := img.Region(r)
```
Then to be able to get image data, I need to save into file using:
```
gocv.IMWrite(imgName, imgFace)
```
And then I can use `os.Open` and get `io.Reader` type. But I think it can be helpful to have this in gocv.

**Comment by deadprogram** [comment]
Hello, @plutov sounds like you might be looking for what the `IMEncode()` function already does:

https://godoc.org/gocv.io/x/gocv#IMEncode

**Comment by plutov** [comment]
Awesome, didn't see it.
