### ISSUE TITLE
Openvino+cuda

### ISSUE THREAD

**Issue by Danile71** [hybridgroup/gocv#611]
**Using Openvino+cuda**

## Description
I manualy build and install Opencv+dldt and now I can use Openvino and cuda.
Tested on ubuntu 20.04 and ubuntu 18.04

**Minimum GPU cuda api:** 5.3

## Steps to Reproduce
```
#!/bin/bash
git clone https://github.com/opencv/dldt && \
            (cd dldt/inference-engine && \
            git submodule init && \
            git submodule update --recursive && \
            ./install_dependencies.sh && \
            mv -f thirdparty/clDNN/common/intel_ocl_icd/6.3/linux/Release thirdparty/clDNN/common/intel_ocl_icd/6.3/linux/RELEASE && \
            mkdir -p build && \
            cd build && \
            cmake -D CMAKE_BUILD_TYPE=RELEASE \
                  -D CMAKE_INSTALL_PREFIX=/usr/local \
                  -D BUILD_SHARED_LIBS=ON \
                  -D ENABLE_TESTS=OFF \
                  -D ENABLE_VPU=ON \
                  -D ENABLE_MKL_DNN=ON \
                  -D ENABLE_CLDNN=ON .. && \
                  make -j $(nproc --all) && \
                  touch VERSION && \
                  mkdir -p src/ngraph && \
                  sudo cp -r ../bin/intel64/RELEASE/lib/* /usr/local/lib && \
                  cp thirdparty/ngraph/src/ngraph/version.hpp src/ngraph && \
                  sudo make install)

OPENCV_VERSION="4.2.0"

# install opencv
curl -Lo opencv.zip https://github.com/opencv/opencv/archive/${OPENCV_VERSION}.zip && \
            unzip -q opencv.zip && \
            curl -Lo opencv_contrib.zip https://github.com/opencv/opencv_contrib/archive/${OPENCV_VERSION}.zip && \
            unzip -q opencv_contrib.zip && \
            rm opencv.zip opencv_contrib.zip && \
            (cd opencv-${OPENCV_VERSION} && \
            mkdir build && cd build && \
            cmake -D CMAKE_BUILD_TYPE=RELEASE \
                  -D CMAKE_INSTALL_PREFIX=/usr/local \
                  -D OPENCV_EXTRA_MODULES_PATH=../../opencv_contrib-${OPENCV_VERSION}/modules \
                  -D InferenceEngine_DIR=../../../dldt/inference-engine/build \
                  -D WITH_JASPER=OFF \
                  -D BUILD_DOCS=OFF \
                  -D BUILD_EXAMPLES=OFF \
                  -D ENABLE_CXX11=ON \
                  -D WITH_INF_ENGINE=ON \
                  -D WITH_QT=OFF \
                  -D WITH_GTK=ON \
                  -D WITH_FFMPEG=OFF \
                  -D CUDA_ARCH_BIN=5.3,6.0,6.1,7.0,7.5 \
                  -D CUDA_ARCH_PTX=5.3 \
                  -D WITH_CUDA=ON \
                  -D WITH_CUDNN=ON \
                  -D OPENCV_DNN_CUDA=ON \
                  -D ENABLE_FAST_MATH=1 \
                  -D WITH_CUBLAS=1 \
                  -D WITH_TIFF=OFF \
                  -D WITH_WEBP=OFF \
                  -D WITH_QT=OFF \
                  -D WITH_PNG=OFF \
                  -D WITH_1394=OFF \
                  -D HAVE_OPENEXR=OFF \
                  -D BUILD_TESTS=OFF \
                  -D BUILD_PERF_TESTS=OFF \
                  -D BUILD_opencv_java=NO \
                  -D BUILD_opencv_python=NO \
                  -D BUILD_opencv_python2=NO \
                  -D BUILD_opencv_python3=NO \
                  -D BUILD_SHARED_LIBS=ON \
                  -D OPENCV_GENERATE_PKGCONFIG=ON .. && \
            make -j $(nproc --all) && \
            sudo make preinstall && sudo make install && sudo ldconfig )
```
After, need set env
```
export CGO_CXXFLAGS="--std=c++11"
export CGO_CPPFLAGS="-I/usr/local/include/opencv4"
export CGO_LDFLAGS="-lpthread -ldl -lopencv_core -lopencv_videoio -lopencv_imgproc -lopencv_highgui -lopencv_imgcodecs -lopencv_objdetect -lopencv_features2d -lopencv_video -lopencv_dnn -lopencv_calib3d"
export PKG_CONFIG_PATH=/usr/lib64/pkgconfig
```
go build -tags openvino

**Comment by Danile71** [comment]
With [pull request](https://github.com/hybridgroup/gocv/pull/612) not need set env's now!


```
export CGO_CXXFLAGS="--std=c++11"
export CGO_CPPFLAGS="-I/usr/local/include/opencv4"
export CGO_LDFLAGS="-lpthread -ldl -lopencv_core -lopencv_videoio -lopencv_imgproc -lopencv_highgui -lopencv_imgcodecs -lopencv_objdetect -lopencv_features2d -lopencv_video -lopencv_dnn -lopencv_calib3d"
export PKG_CONFIG_PATH=/usr/lib64/pkgconfig
```

**Comment by deadprogram** [comment]
This for sure looks like a better way, now that DLDT is fully open source. Great to just be able to use the pkg-config setup for all versions.

We will need to update some of the docs as well to example this.

It would also probably be great to add a make task to perform the install.

Also this implies we will be able to include in the normal CI tests.

**Comment by Danile71** [comment]
Maybe add checks for cuda/openvino functions and disable tags?
If cuda/openvino not installed use nop-functions?

**Comment by deadprogram** [comment]
I'm not sure if there is a way for us to determine that at compile time without a build tag, or else an ENV var. However since we probably want to entirely skip the compilation of those bits, build tags are probably the "correct" way to do this.

What do you think?

**Comment by Danile71** [comment]
Now I have 08:30 PM, but tomorrow I will try some ideas and pull it to repository.

**Comment by Danile71** [comment]
With this [commit](https://github.com/hybridgroup/gocv/pull/614) tested 

- [x] make install
- [x] make install_openvino
- [x] make install_cuda
- [x] make install_all

Now need to make Openvino for windows and add Dockerfile

**Comment by deadprogram** [comment]
This has been released with v0.23 so now closing. Thanks!

**Comment by alaayousef87** [comment]
Hi
First really big thanks for you I learn a lot from your profile :)
I have Ubuntu server with gpu cuda cudnn enabled and successfully configured and tested 
I want to use openvino but also with cuda
my server have only NVIDIA gpu i  dont't have any intel gpu and it will be difficult to have intel gpu because that's a dedicated server

my question in my case can I still used openvino with NVIDIA cuda   without intel GPU in opencv?
I hope if anyone can answer my quastion because I will be crazy I am trying doing that from one month but I am failed :(((

when i install gocv with cuda it is success and i have successfully gocv with opencv cuda enabled
but when I install all to have openvino together with cuda I have the cuda success and also openvino but when I activate the opencv of openvino verstion by go cv openvino env environment file I lost the cuda :( and even the openvino the ie import failed
last point I see in make file dldt but that's change to openvino so I am confused about this point also
Thank you

**Comment by Danile71** [comment]
@alaayousef87, intel rename dldt -> openvino.
If you have intel cpu without intel Gpu - you can use openvino.
please, upload errors.
