### ISSUE TITLE
memory leak in motion-detection sample

### ISSUE THREAD

**Issue by jondot** [hybridgroup/gocv#62]
Hi all,
Thanks for a great library, I find the API much simpler than any other Go open-cv library.
If you'd run the motion-detection sample, you'll see memory always grows. I came a full circle to this porting an open-cv 2.x project I have to `gocv`, and I knew I should be looking for leaks, from previous experience. I then validated the case with your sample, as an isolated example of the problem.

I think here the leak comes from FindContours, somehow.

**Comment by deadprogram** [comment]
Hello @jondot thank you for paying attention to memory usage. 

I just committed this code to the `dev` branch: https://github.com/hybridgroup/gocv/commit/77bc4f33407e589b0d2a1802475d31e867df6661

I think it should address the leaks you found, and a few more. Would you be able to try it out?

**Comment by jondot** [comment]
I actually patched it on my side, and include one more edge case than what you did I believe, I can submit a PR. I'm just busy with other things right now.

**Comment by deadprogram** [comment]
That sounds great, thanks!

**Comment by jondot** [comment]
@deadprogram Feel free to check out my pull request
Thanks for a great library, I've been looking for an opencv3 library for Go for ages.

**Comment by deadprogram** [comment]
This code is now in the `dev` branch I will leave this issue open until the next GoCV release. Thanks again!

**Comment by deadprogram** [comment]
This code was released as part of v0.8.0 so now closing. Thanks again!
