### ISSUE TITLE
(*Net) GetLayerNames() returns invalid strings

### ISSUE THREAD

**Issue by glarchev** [hybridgroup/gocv#622]
I exported a standard Keras model as a frozen graph, and am trying to import it into GoCV. The protobuf file imports fine, but when I try to read layer names using `GetLayerNames()`, the returned strings are not valid.

Here's my code:

```
package main

import (
	"fmt"
	"gocv.io/x/gocv"
)

func main() {
	modelname := "myfolder/frozen_graph.pb"

	net := gocv.ReadNetFromTensorflow(modelname)

	if net.Empty() {
		fmt.Println("Error reading model")
	} else {
		fmt.Println("Read model successfully!")
	}
	defer net.Close()

	names := net.GetLayerNames()

	fmt.Printf("Length of names: %d\n", len(names))

	for _, name := range names {
		fmt.Println(len(name))
	}

	for _, name := range names {
		fmt.Println(name)
	}
}
```

And here's the output:
```
Read model successfully!
Length of names: 42
282067424
282067488
282068080
282068144
282068208
282068272
282068336
282068400
282068464
282068528
282068608
282068672
282068736
282068800
282068864
285213417
285213465
285213513
285213561
285213609
282069024
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
unexpected fault address 0x122e5000
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x1 addr=0x122e5000 pc=0x4055acb]
```

So it looks like the layer names are not valid strings. I'm not sure how the import process works, so it's possible that the protobuf data is corrupted, but it would be nice to include some error checking.

- OS: MacOS
- OpenCV Version: 4.2.0
- How did you install OpenCV: brew
- Go Version: go version go1.11.2 darwin/amd64

**Comment by deadprogram** [comment]
This was fixed by https://github.com/hybridgroup/gocv/pull/732 and is now in the `dev` branch so I will mark as "next-release".

**Comment by deadprogram** [comment]
This has now been released so closing. Thanks!
