### ISSUE TITLE
ubuntu19.10 warning for dnn scalar

### ISSUE THREAD

**Issue by robomentor** [hybridgroup/gocv#623]
ubuntu@ubuntu:~/test/src/www$ go run main.go
# gocv.io/x/gocv
dnn.cpp: In function ‘cv::Mat* Net_BlobFromImage(Mat, double, Size, Scalar, bool, bool)’:
dnn.cpp:119:76: warning: passing NULL to non-pointer argument 1 of ‘cv::Scalar_<_Tp>::Scalar_(_Tp) [with _Tp = double]’ [-Wconversion-null]
  119 |         return new cv::Mat(cv::dnn::blobFromImage(*image, scalefactor, sz, NULL, swapRB, crop, ddepth));
      |                                                                            ^~~~
In file included from /usr/local/include/opencv4/opencv2/core.hpp:58,
                 from /usr/local/include/opencv4/opencv2/opencv.hpp:52,
                 from dnn.h:7,
                 from dnn.cpp:1:
/usr/local/include/opencv4/opencv2/core/types.hpp:2207:27: note:   declared here
 2207 | Scalar_<_Tp>::Scalar_(_Tp v0)
      |                       ~~~~^~
gocv version: 0.22.0
opencv lib version: 4.2.0
ubuntu@ubuntu:~/test/src/www$

**Comment by Danile71** [comment]
warning, not error

**Comment by deadprogram** [comment]
The `dev` branch now has code to remove this warning.

**Comment by deadprogram** [comment]
This has been released with v0.23 so now closing. Thanks!
