### ISSUE TITLE
ubuntu make install could not resolve  host:codeload.github.com

### ISSUE THREAD

**Issue by shumintao** [hybridgroup/gocv#632]
ubuntu :16.04
cd $GOAPTH/src/gocv.io/x/gocv
sudo make install 

mac 我们无法连接至 codeload.github.com

**Comment by deadprogram** [comment]
Looks like a network issue on your side? Please reopen if needed. Thanks!

**Comment by shumintao** [comment]
> Looks like a network issue on your side? Please reopen if needed. Thanks!

i have sove this problem 
Because Chinese ping is different from this address
 need to use an agent
