### ISSUE TITLE
gocv build static fail

### ISSUE THREAD

**Issue by thanatos915** [hybridgroup/gocv#637]
我在win 10 上，按照 [https://gocv.io/getting-started/windows/](https://gocv.io/getting-started/windows/) 的方法，安装了opencv 和 gocv。 运行报错

`
dnn.cpp: In function 'cv::Mat* Net_BlobFromImage(Mat, double, Size, Scalar, bool, bool)':
dnn.cpp:119:76: warning: passing NULL to non-pointer argument 1 of 'cv::Scalar_<_Tp>::Scalar_(_Tp) [with _Tp = double]' [-Wconversion-null]
  119 |         return new cv::Mat(cv::dnn::blobFromImage(*image, scalefactor, sz, NULL, swapRB, crop, ddepth));
      |                                                                            ^~~~
In file included from C:/opencv/build/install/include/opencv2/core.hpp:58,
                 from C:/opencv/build/install/include/opencv2/opencv.hpp:52,
                 from dnn.h:7,
                 from dnn.cpp:1:
C:/opencv/build/install/include/opencv2/core/types.hpp:2207:27: note:   declared here
 2207 | Scalar_<_Tp>::Scalar_(_Tp v0)
`

但这似乎是提示信息，程序可以继续运行。但是当我 go build 时，在其他没有安装opencv 的电脑运行是，会提示找不到 libopencv_core420。 我参考 [#601](https://github.com/hybridgroup/gocv/issues/601) 静态编译了opencv 。之后报的错误是

`
D:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/opencv/build/install/x64/mingw/lib/libopencv_calib3d420.a(ptsetreg.cpp.obj):ptsetreg.cpp:(.rdata$_ZTVN2cv25RANSACPointSetRegistratorE[_ZTVN2cv25RANSACPointSetRegistratorE]+0x48): undefined reference to `cv::Algorithm::getDefaultName[abi:cxx11]() const'
D:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/opencv/build/install/x64/mingw/lib/libopencv_calib3d420.a(ptsetreg.cpp.obj):ptsetreg.cpp:(.rdata$_ZTVN2cv24LMeDSPointSetRegistratorE[_ZTVN2cv24LMeDSPointSetRegistratorE]+0x40): undefined reference to `cv::Algorithm::save(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const' D:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/opencv/build/install/x64/mingw/lib/libopencv_calib3d420.a(ptsetreg.cpp.obj):ptsetreg.cpp:(.rdata$_ZTVN2cv24LMeDSPointSetRegistratorE[_ZTVN2cv24LMeDSPointSetRegistratorE]+0x48): undefined reference to `cv::Algorithm::getDefaultName[abi:cxx11]() const'
D:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/opencv/build/install/x64/mingw/lib/libopencv_calib3d420.a(undistort.dispatch.cpp.obj):undistort.dispatch.cpp:(.text$_ZL25cvUndistortPointsInternalPK5CvMatPS_S1_S1_S1_S1_N2cv12TermCriteriaE+0x378): undefined reference to `cvConvertScale'
D:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/opencv/build/install/x64/mingw/lib/libopencv_calib3d420.a(undistort.dispatch.cpp.obj):undistort.dispatch.cpp:(.text$_ZL25cvUndistortPointsInternalPK5CvMatPS_S1_S1_S1_S1_N2cv12TermCriteriaE+0x47f): undefined reference to `cvConvertScale'
D:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/opencv/build/install/x64/mingw/lib/libopencv_calib3d420.a(undistort.dispatch.cpp.obj):undistort.dispatch.cpp:(.text$_ZL25cvUndistortPointsInternalPK5CvMatPS_S1_S1_S1_S1_N2cv12TermCriteriaE+0x569): undefined reference to `cvConvertScale'
D:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/opencv/build/install/x64/mingw/lib/libopencv_calib3d420.a(undistort.dispatch.cpp.obj):undistort.dispatch.cpp:(.text$_ZL25cvUndistortPointsInternalPK5CvMatPS_S1_S1_S1_S1_N2cv12TermCriteriaE+0x63b): undefined reference to `cvConvertScale'
collect2.exe: error: ld returned 1 exit status
`

现在我不知道，怎样可以build 后 在一台没有安装opencv的电脑上运行。Please help me

**Comment by kahlil29** [comment]
@thanatos915 did you manage to build a static binary executable?
