### ISSUE TITLE
Can not use it, need help.

### ISSUE THREAD

**Issue by Horizon-42** [hybridgroup/gocv#649]
## Description
I followed the readme file to install gocv and make install opencv, but still got errors.
./calib3d_string.go:3:9: undefined: CalibFlag
./core_string.go:3:9: undefined: MatType
./core_string.go:57:9: undefined: CompareType
./core_string.go:75:9: undefined: CovarFlags
./core_string.go:93:9: undefined: DftFlags
./core_string.go:113:9: undefined: RotateFlag
./core_string.go:125:9: undefined: KMeansFlags
./core_string.go:137:9: undefined: NormType
./core_string.go:159:9: undefined: TermCriteriaType
./core_string.go:169:9: undefined: SolveDecompositionFlags
./core_string.go:169:9: too many errors
I try to rebuild opencv myself, config the pkg files, but the eorrors still there.

## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Operating System and version:Ubuntu 18.04
* OpenCV version used:opencv 4.2
* How did you install OpenCV?
build it from source
* GoCV version used: v0.22.0
* Go version:go 1.14.1
* Did you run the `env.sh` or `env.cmd` script before trying to `go run` or `go build`?
yes, and it sad This script is no longer necessary and has been deprecated.
See the Custom Environment section of the README if you need to customize your environment.

**Comment by Horizon-42** [comment]
ok,my fault. I make a stupid fault， use the wrong go binary. sorry.

**Comment by giovanni-annunzio** [comment]
I have the same issue - did you /@Horizon-42) find an answer or what was the reason you closed the thread?

**Comment by giovanni-annunzio** [comment]
Hi @Horizon-42,

I had the same issue. I figured out the env was CGO_ENABLED=0, after setting it CGO_ENABLED=1 it worked fine :-)

Regards
Gianni

**Comment by iammeizu** [comment]
Still not work @giovanni-annunzio

**Comment by deadprogram** [comment]
You must have the matching version of OpenCV for whatever version of GoCV you are trying to use. Errors of this sort are usually due to a mismatch in versions.

I would suggest install OpenCV 4.5.1 and try out the latest release of GoCV which is 0.2.6

Hope that helps!
