### ISSUE TITLE
Error while feeding blob to net (YOLOv2)

### ISSUE THREAD

**Issue by anisbhsl** [hybridgroup/gocv#650]
Hello,
Thank you for this amazing package. I am trying to use pre-trained ```tiny YOLO``` model from [pjreddie's](https://pjreddie.com/darknet/yolo/) to detect objects. I am quite new to DNN and GoCV. 

## Description

While trying to feed the blob (frame resized to yolo input size) using: 
```
net.SetInput(blob,"")
```
I am receiving this error: 
```
OpenCV(4.2.0) /tmp/opencv/opencv-4.2.0/modules/dnn/src/dnn.cpp:562: error: (-2:Unspecified error) Can't create layer "init" of type "NoOp" in function 'getLayerInstance'
```
I have tried using input layer name ```net``` as specified in [cfg](https://github.com/pjreddie/darknet/blob/master/cfg/yolov2-tiny.cfg) file from ```pjreddie's``` but same issue occurs. 

## Steps to Reproduce

Here's my  code: 

```
func main(){
input,_:=gocv.OpenVideoCapture(0)

window:=gocv.NewWindow("Object Tracking")
defer window.Close()

img:=gocv.NewMat()
defer img.Close()

net:=gocv.ReadNet("bin/tiny-yolo-voc.weights","cfg/tiny-yolo-voc-1c.cfg")
for{
	if ok:=input.Read(&img);!ok{
	        log.Printf("cannot read device \n")
		return
	}
	if img.Empty(){
		continue
	}

       	blob:=gocv.BlobFromImage(img, 1.0,image.Pt(416,416),gocv.NewScalar(0,0,0,0),false,false)
        net.SetInput(blob,"") //<--error occurs here (tried using layer name "net" but same issue) 
       preds:=net.Forward("")
       fmt.Println(preds)
      
      window.IMShow(img)
      if window.WaitKey(1)>=0{
		break
	 }
      }
}
```
I think the problem is with layer names but I have already tried names provided in [cfg](https://github.com/pjreddie/darknet/blob/master/cfg/yolov2-tiny.cfg) files. Could you help me solve this problem? 

## My Environment

* Operating System and version: Ubuntu 18 
* OpenCV version used: 4.2.0
* How did you install OpenCV?  As per instructions in GoCV docs.
* GoCV version used: 0.22
* Go version: 1.14.1

**Comment by zzy444626905** [comment]
you can use python like this

net = cv2.dnn.readNet("yolov3.weights", "yolov3.cfg")
net.setPreferableBackend(cv2.dnn.DNN_BACKEND_DEFAULT)
net.setPreferableTarget(cv2.dnn.DNN_TARGET_OPENCL_FP16)

**Comment by zzy444626905** [comment]
gocv is so weak , python is the best language in the world

**Comment by anisbhsl** [comment]
I went with ```tf-go``` to serve the model and used ```gocv``` to render detections. 

> gocv is so weak , python is the best language in the world

I don't think gocv is weak. It might lack some features but that don't have anything to do with python. Both languages have their own strong points.  :)

**Comment by entrehuihui** [comment]
> 我随即使用`tf-go`该模型并用于`gocv`渲染检测。
> 
> > gocv太弱了，python是世界上最好的语言
> 
> 我不认为gocv很弱。它可能缺少某些功能，但与python没有任何关系。两种语言都有各自的长处。:)



> I went with `tf-go` to serve the model and used `gocv` to render detections.
> 
> > gocv is so weak , python is the best language in the world
> 
> I don't think gocv is weak. It might lack some features but that don't have anything to do with python. Both languages have their own strong points. :)

Do you find a solution, I am also trying to use gocv for yolo development

**Comment by entrehuihui** [comment]
> I went with `tf-go` to serve the model and used `gocv` to render detections.
> 
> > gocv is so weak , python is the best language in the world
> 
> I don't think gocv is weak. It might lack some features but that don't have anything to do with python. Both languages have their own strong points. :)

Do you find a solution, I am also trying to use gocv for yolo development
