### ISSUE TITLE
Building cuda/cudawarping_string.go :33:2: duplicate case BorderDefault (value 4) in switch

### ISSUE THREAD

**Issue by scryptosan** [hybridgroup/gocv#652]
Hello, i'm using gocv on aarch64.
I compiled opencv with cuda support.
And have issue with cuda package compilation

# gocv.io/x/gocv/cuda
../../go/pkg/mod/gocv.io/x/gocv@v0.22.0/cuda/cudawarping_string.go:33:2: duplicate case BorderDefault (value 4) in switch
	previous case at ../../go/pkg/mod/gocv.io/x/gocv@v0.22.0/cuda/cudawarping_string.go:29:2

## Steps to Reproduce

1. Compile opencv with cuda support
2. installing gocv (its compile OK, and show version opencv 4.2.0 and gocv 0.22.0
3. while i starting using cuda packages a got error below
If I'm commenting this error case statement its compile and works good. Looks like Its new golang version issue or some thing like this.

I'm using golang 1.14.1

* Operating System and version: ubuntu 18.4 aarch 64 for JetsonNano (JetPack 4.3)
* OpenCV version used: 4.2.0
* How did you install OpenCV? Compile from source
* GoCV version used: 0.22.0
* Go version: 1.14.1
* Did you run the `env.sh` or `env.cmd` script before trying to `go run` or `go build`? No. Its deprecated.

**Comment by deadprogram** [comment]
This has been addressed by https://github.com/hybridgroup/gocv/pull/607 which will be in the next release.

**Comment by deadprogram** [comment]
This has been released with v0.23 so now closing. Thanks!
