### ISSUE TITLE
docker gpu

### ISSUE THREAD

**Issue by x0rzkov** [hybridgroup/gocv#654]
Hi guys,

Hope you are all well !

Is there a gpu version of the dockerfile ?

Thanks in advance for any insights or inputs on that topic.

Cheers,
X

**Comment by khlipeng** [comment]
help

**Comment by deadprogram** [comment]
For info on that topic, please see https://github.com/NVIDIA/nvidia-docker

**Comment by deadprogram** [comment]
See https://github.com/hybridgroup/gocv/blob/release/Dockerfile.opencv-gpu-cuda-10 and https://github.com/hybridgroup/gocv/blob/release/Dockerfile.opencv-gpu-cuda-11

to be used with https://github.com/hybridgroup/gocv/blob/release/Dockerfile.gpu

Hope that helps. Now closing.
