### ISSUE TITLE
Gpu installation not work well on linux

### ISSUE THREAD

**Issue by omriLAnyvision** [hybridgroup/gocv#656]
Gpu installation not work well on linux

## Description
Following [this](https://github.com/hybridgroup/gocv/tree/master/cuda) guide and install the cuda version on linux ubunto
 

## Your Environment
Kernel: 5.3.0-42-generic
Ubunto version 18.04
NVIDIA-SMI 440.64.00    
Driver Version: 440.64.00    
CUDA Version: 10.2
GeForce GTX 1070

* Operating System and version:
- gocv version: 0.22.0
- opencv lib version: 4.2.0
* Go version: go version go1.14.1 linux/amd64
* Did you run the `env.sh` or `env.cmd` script before trying to `go run` or `go build`? no

Terminal error when running `gor un ./cmd/cuda/main.go`
```

 go run ./cmd/cuda/main.go 
# gocv.io/x/gocv
dnn.cpp: In function ‘cv::Mat* Net_BlobFromImage(Mat, double, Size, Scalar, bool, bool)’:
dnn.cpp:119:102: warning: passing NULL to non-pointer argument 1 of ‘cv::Scalar_<_Tp>::Scalar_(_Tp) [with _Tp = double]’ [-Wconversion-null]
         return new cv::Mat(cv::dnn::blobFromImage(*image, scalefactor, sz, NULL, swapRB, crop, ddepth));
                                                                                                      ^
# gocv.io/x/gocv/cuda
In file included from cudabgsegm.cpp:1:0:
cudabgsegm.h:14:27: error: ‘BackgroundSubtractorMOG2’ is not a member of ‘cv::cuda’
 typedef cv::Ptr<cv::cuda::BackgroundSubtractorMOG2>* CudaBackgroundSubtractorMOG2;
                           ^~~~~~~~~~~~~~~~~~~~~~~~
cudabgsegm.h:14:27: note: suggested alternative:
In file included from /usr/local/include/opencv4/opencv2/video.hpp:57:0,
                 from /usr/local/include/opencv4/opencv2/opencv.hpp:95,
                 from cudabgsegm.h:5,
                 from cudabgsegm.cpp:1:
/usr/local/include/opencv4/opencv2/video/background_segm.hpp:90:20: note:   ‘cv::BackgroundSubtractorMOG2’
 class CV_EXPORTS_W BackgroundSubtractorMOG2 : public BackgroundSubtractor
                    ^~~~~~~~~~~~~~~~~~~~~~~~
In file included from cudabgsegm.cpp:1:0:
cudabgsegm.h:14:27: error: ‘BackgroundSubtractorMOG2’ is not a member of ‘cv::cuda’
 typedef cv::Ptr<cv::cuda::BackgroundSubtractorMOG2>* CudaBackgroundSubtractorMOG2;
                           ^~~~~~~~~~~~~~~~~~~~~~~~
cudabgsegm.h:14:27: note: suggested alternative:
In file included from /usr/local/include/opencv4/opencv2/video.hpp:57:0,
                 from /usr/local/include/opencv4/opencv2/opencv.hpp:95,
                 from cudabgsegm.h:5,
                 from cudabgsegm.cpp:1:
/usr/local/include/opencv4/opencv2/video/background_segm.hpp:90:20: note:   ‘cv::BackgroundSubtractorMOG2’
 class CV_EXPORTS_W BackgroundSubtractorMOG2 : public BackgroundSubtractor
                    ^~~~~~~~~~~~~~~~~~~~~~~~
In file included from cudabgsegm.cpp:1:0:
cudabgsegm.h:14:51: error: template argument 1 is invalid
 typedef cv::Ptr<cv::cuda::BackgroundSubtractorMOG2>* CudaBackgroundSubtractorMOG2;
                                                   ^
cudabgsegm.h:15:27: error: ‘BackgroundSubtractorMOG’ is not a member of ‘cv::cuda’
 typedef cv::Ptr<cv::cuda::BackgroundSubtractorMOG>* CudaBackgroundSubtractorMOG;
                           ^~~~~~~~~~~~~~~~~~~~~~~
cudabgsegm.h:15:27: error: ‘BackgroundSubtractorMOG’ is not a member of ‘cv::cuda’
cudabgsegm.h:15:50: error: template argument 1 is invalid
 typedef cv::Ptr<cv::cuda::BackgroundSubtractorMOG>* CudaBackgroundSubtractorMOG;
                                                  ^
cudabgsegm.cpp: In function ‘int* CudaBackgroundSubtractorMOG2_Create()’:
cudabgsegm.cpp:4:34: error: ‘BackgroundSubtractorMOG2’ is not a member of ‘cv::cuda’
     return new cv::Ptr<cv::cuda::BackgroundSubtractorMOG2>(cv::cuda::createBackgroundSubtractorMOG2());
                                  ^~~~~~~~~~~~~~~~~~~~~~~~
cudabgsegm.cpp:4:34: note: suggested alternative:
In file included from /usr/local/include/opencv4/opencv2/video.hpp:57:0,
                 from /usr/local/include/opencv4/opencv2/opencv.hpp:95,
                 from cudabgsegm.h:5,
                 from cudabgsegm.cpp:1:
/usr/local/include/opencv4/opencv2/video/background_segm.hpp:90:20: note:   ‘cv::BackgroundSubtractorMOG2’
 class CV_EXPORTS_W BackgroundSubtractorMOG2 : public BackgroundSubtractor
                    ^~~~~~~~~~~~~~~~~~~~~~~~
cudabgsegm.cpp:4:34: error: ‘BackgroundSubtractorMOG2’ is not a member of ‘cv::cuda’
     return new cv::Ptr<cv::cuda::BackgroundSubtractorMOG2>(cv::cuda::createBackgroundSubtractorMOG2());
                                  ^~~~~~~~~~~~~~~~~~~~~~~~
cudabgsegm.cpp:4:34: note: suggested alternative:
In file included from /usr/local/include/opencv4/opencv2/video.hpp:57:0,
                 from /usr/local/include/opencv4/opencv2/opencv.hpp:95,
                 from cudabgsegm.h:5,
                 from cudabgsegm.cpp:1:
/usr/local/include/opencv4/opencv2/video/background_segm.hpp:90:20: note:   ‘cv::BackgroundSubtractorMOG2’
 class CV_EXPORTS_W BackgroundSubtractorMOG2 : public BackgroundSubtractor
                    ^~~~~~~~~~~~~~~~~~~~~~~~
cudabgsegm.cpp:4:58: error: template argument 1 is invalid
     return new cv::Ptr<cv::cuda::BackgroundSubtractorMOG2>(cv::cuda::createBackgroundSubtractorMOG2());
                                                          ^
cudabgsegm.cpp:4:70: error: ‘createBackgroundSubtractorMOG2’ is not a member of ‘cv::cuda’
     return new cv::Ptr<cv::cuda::BackgroundSubtractorMOG2>(cv::cuda::createBackgroundSubtractorMOG2());
                                                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cudabgsegm.cpp:4:70: note: suggested alternative:
In file included from /usr/local/include/opencv4/opencv2/video.hpp:57:0,
                 from /usr/local/include/opencv4/opencv2/opencv.hpp:95,
                 from cudabgsegm.h:5,
                 from cudabgsegm.cpp:1:
/usr/local/include/opencv4/opencv2/video/background_segm.hpp:221:5: note:   ‘cv::createBackgroundSubtractorMOG2’
     createBackgroundSubtractorMOG2(int history=500, double varThreshold=16,
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cudabgsegm.cpp: In function ‘void CudaBackgroundSubtractorMOG2_Apply(CudaBackgroundSubtractorMOG2, GpuMat, GpuMat)’:
cudabgsegm.cpp:12:9: error: base operand of ‘->’ is not a pointer
     (*b)->apply(*src, *dst);
         ^~
cudabgsegm.cpp: In function ‘int* CudaBackgroundSubtractorMOG_Create()’:
cudabgsegm.cpp:16:34: error: ‘BackgroundSubtractorMOG’ is not a member of ‘cv::cuda’
     return new cv::Ptr<cv::cuda::BackgroundSubtractorMOG>(cv::cuda::createBackgroundSubtractorMOG());
                                  ^~~~~~~~~~~~~~~~~~~~~~~
cudabgsegm.cpp:16:34: error: ‘BackgroundSubtractorMOG’ is not a member of ‘cv::cuda’
cudabgsegm.cpp:16:57: error: template argument 1 is invalid
     return new cv::Ptr<cv::cuda::BackgroundSubtractorMOG>(cv::cuda::createBackgroundSubtractorMOG());
                                                         ^
cudabgsegm.cpp:16:69: error: ‘createBackgroundSubtractorMOG’ is not a member of ‘cv::cuda’
     return new cv::Ptr<cv::cuda::BackgroundSubtractorMOG>(cv::cuda::createBackgroundSubtractorMOG());
                                                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cudabgsegm.cpp: In function ‘void CudaBackgroundSubtractorMOG_Apply(CudaBackgroundSubtractorMOG, GpuMat, GpuMat)’:
cudabgsegm.cpp:24:9: error: base operand of ‘->’ is not a pointer
     (*b)->apply(*src, *dst);


```

**Comment by Ann-Geo** [comment]
Hi @omriLAnyvision,

I am getting the same error, when I run, go run ./cmd/cuda/main.go after installing gocv with cuda (by following the instructions here, https://github.com/hybridgroup/gocv/blob/master/cuda/README.md).  @omriLAnyvision, were you able to solve this problem,

### Environment:
Kernel: 4.10.0-28-generic
Ubuntu version: 16.04.3 LTS
GPU: Nvidia GeForce GTX 1060
Nvidia Driver Version: 440.33.01    
CUDA Version: 10.2
cuDNN: v7.6.5
gocv version: 0.23.0
opencv lib version: 4.3.0
go version go1.13.3 linux/amd64


Any help from anyone would be appreciated.

Error obtained while running go run ./cmd/cuda/main.go -

In file included from cudabgsegm.cpp:1:0:
cudabgsegm.h:14:17: error: ‘BackgroundSubtractorMOG2’ is not a member of ‘cv::cuda’
 typedef cv::Ptr<cv::cuda::BackgroundSubtractorMOG2>* CudaBackgroundSubtractorMOG2;
                 ^
cudabgsegm.h:14:17: note: suggested alternative:
In file included from /usr/local/include/opencv4/opencv2/video.hpp:57:0,
                 from /usr/local/include/opencv4/opencv2/opencv.hpp:89,
                 from cudabgsegm.h:5,
                 from cudabgsegm.cpp:1:
/usr/local/include/opencv4/opencv2/video/background_segm.hpp:90:20: note:   ‘cv::BackgroundSubtractorMOG2’
 class CV_EXPORTS_W BackgroundSubtractorMOG2 : public BackgroundSubtractor
                    ^
In file included from cudabgsegm.cpp:1:0:
cudabgsegm.h:14:17: error: ‘BackgroundSubtractorMOG2’ is not a member of ‘cv::cuda’
 typedef cv::Ptr<cv::cuda::BackgroundSubtractorMOG2>* CudaBackgroundSubtractorMOG2;
                 ^
cudabgsegm.h:14:17: note: suggested alternative:
In file included from /usr/local/include/opencv4/opencv2/video.hpp:57:0,
                 from /usr/local/include/opencv4/opencv2/opencv.hpp:89,
                 from cudabgsegm.h:5,
                 from cudabgsegm.cpp:1:
/usr/local/include/opencv4/opencv2/video/background_segm.hpp:90:20: note:   ‘cv::BackgroundSubtractorMOG2’
 class CV_EXPORTS_W BackgroundSubtractorMOG2 : public BackgroundSubtractor
                    ^
In file included from cudabgsegm.cpp:1:0:
cudabgsegm.h:14:51: error: template argument 1 is invalid
 typedef cv::Ptr<cv::cuda::BackgroundSubtractorMOG2>* CudaBackgroundSubtractorMOG2;
                                                   ^
cudabgsegm.h:15:17: error: ‘BackgroundSubtractorMOG’ is not a member of ‘cv::cuda’
 typedef cv::Ptr<cv::cuda::BackgroundSubtractorMOG>* CudaBackgroundSubtractorMOG;
                 ^
cudabgsegm.h:15:17: error: ‘BackgroundSubtractorMOG’ is not a member of ‘cv::cuda’
cudabgsegm.h:15:50: error: template argument 1 is invalid
 typedef cv::Ptr<cv::cuda::BackgroundSubtractorMOG>* CudaBackgroundSubtractorMOG;
                                                  ^
cudabgsegm.cpp: In function ‘int* CudaBackgroundSubtractorMOG2_Create()’:
cudabgsegm.cpp:4:24: error: ‘BackgroundSubtractorMOG2’ is not a member of ‘cv::cuda’
     return new cv::Ptr<cv::cuda::BackgroundSubtractorMOG2>(cv::cuda::createBackgroundSubtractorMOG2());
                        ^
cudabgsegm.cpp:4:24: note: suggested alternative:
In file included from /usr/local/include/opencv4/opencv2/video.hpp:57:0,
                 from /usr/local/include/opencv4/opencv2/opencv.hpp:89,
                 from cudabgsegm.h:5,
                 from cudabgsegm.cpp:1:
/usr/local/include/opencv4/opencv2/video/background_segm.hpp:90:20: note:   ‘cv::BackgroundSubtractorMOG2’
 class CV_EXPORTS_W BackgroundSubtractorMOG2 : public BackgroundSubtractor
                    ^
cudabgsegm.cpp:4:24: error: ‘BackgroundSubtractorMOG2’ is not a member of ‘cv::cuda’
     return new cv::Ptr<cv::cuda::BackgroundSubtractorMOG2>(cv::cuda::createBackgroundSubtractorMOG2());
                        ^
cudabgsegm.cpp:4:24: note: suggested alternative:
In file included from /usr/local/include/opencv4/opencv2/video.hpp:57:0,
                 from /usr/local/include/opencv4/opencv2/opencv.hpp:89,
                 from cudabgsegm.h:5,
                 from cudabgsegm.cpp:1:
/usr/local/include/opencv4/opencv2/video/background_segm.hpp:90:20: note:   ‘cv::BackgroundSubtractorMOG2’
 class CV_EXPORTS_W BackgroundSubtractorMOG2 : public BackgroundSubtractor
                    ^
cudabgsegm.cpp:4:58: error: template argument 1 is invalid
     return new cv::Ptr<cv::cuda::BackgroundSubtractorMOG2>(cv::cuda::createBackgroundSubtractorMOG2());
                                                          ^
cudabgsegm.cpp:4:60: error: ‘createBackgroundSubtractorMOG2’ is not a member of ‘cv::cuda’
     return new cv::Ptr<cv::cuda::BackgroundSubtractorMOG2>(cv::cuda::createBackgroundSubtractorMOG2());
                                                            ^
cudabgsegm.cpp:4:60: note: suggested alternative:
In file included from /usr/local/include/opencv4/opencv2/video.hpp:57:0,
                 from /usr/local/include/opencv4/opencv2/opencv.hpp:89,
                 from cudabgsegm.h:5,
                 from cudabgsegm.cpp:1:
/usr/local/include/opencv4/opencv2/video/background_segm.hpp:221:5: note:   ‘cv::createBackgroundSubtractorMOG2’
     createBackgroundSubtractorMOG2(int history=500, double varThreshold=16,
     ^
cudabgsegm.cpp: In function ‘void CudaBackgroundSubtractorMOG2_Apply(CudaBackgroundSubtractorMOG2, GpuMat, GpuMat)’:
cudabgsegm.cpp:12:9: error: base operand of ‘->’ is not a pointer
     (*b)->apply(*src, *dst);
         ^
cudabgsegm.cpp: In function ‘int* CudaBackgroundSubtractorMOG_Create()’:
cudabgsegm.cpp:16:24: error: ‘BackgroundSubtractorMOG’ is not a member of ‘cv::cuda’
     return new cv::Ptr<cv::cuda::BackgroundSubtractorMOG>(cv::cuda::createBackgroundSubtractorMOG());
                        ^
cudabgsegm.cpp:16:24: error: ‘BackgroundSubtractorMOG’ is not a member of ‘cv::cuda’
cudabgsegm.cpp:16:57: error: template argument 1 is invalid
     return new cv::Ptr<cv::cuda::BackgroundSubtractorMOG>(cv::cuda::createBackgroundSubtractorMOG());
                                                         ^
cudabgsegm.cpp:16:59: error: ‘createBackgroundSubtractorMOG’ is not a member of ‘cv::cuda’
     return new cv::Ptr<cv::cuda::BackgroundSubtractorMOG>(cv::cuda::createBackgroundSubtractorMOG());
                                                           ^
cudabgsegm.cpp: In function ‘void CudaBackgroundSubtractorMOG_Apply(CudaBackgroundSubtractorMOG, GpuMat, GpuMat)’:
cudabgsegm.cpp:24:9: error: base operand of ‘->’ is not a pointer
     (*b)->apply(*src, *dst);
         ^

**Comment by nibbleshift** [comment]
Reproduced same bug in:

Kernel: 4.9.140-tegra
Ubuntu version: 18.0.4 LTS
GPU: NVidia Jetson Xavier AGX / tegra194
Nvidia Driver Version: 440.33.01
CUDA Version: 10.0.326
cuDNN: v7.6.3.28
gocv version: 0.23.0
opencv lib version: 4.3.0
go version go1.14.2 linux/arm64

**Comment by nibbleshift** [comment]
Has anyone been able to resolve this issue?

**Comment by alexlbc** [comment]
I corrected for myself. Not enough inclusions in the following files:

gocv.io/x/gocv/cuda/cudabgsegm.h
#ifdef __cplusplus
#include <opencv2/opencv.hpp>
+#include <opencv2/cudabgsegm.hpp>

gocv.io/x/gocv/cuda/imgproc.h
#ifdef __cplusplus
#include <opencv2/opencv.hpp>
+#include <opencv2/cudaimgproc.hpp>
+#include <opencv2/cudaarithm.hpp>

gocv.io/x/gocv/cuda/objdetect.h
#ifdef __cplusplus
#include <opencv2/opencv.hpp>
#include <opencv2/core/cuda.hpp>
+#include <opencv2/cudaobjdetect.hpp>

~/go/src/gocv.io/x/gocv$ go run cmd/cuda/main.go
gocv version: 0.23.0
cuda information:
  Device 0:  "GeForce GTX 1080 Ti"  11172Mb, sm_61, Driver/Runtime ver.10.20/10.20

I hope you will help.

**Comment by deadprogram** [comment]
That seems like a major omission. I am working on getting a proper test setup to try this all myself to help get it sorted out. Thanks everyone for all the good research done so far!

**Comment by luismesas** [comment]
I tested on Jetson Nano and had he same issue. I can confirm that @alexlbc solution works.

```
nano@nano:~/go/src/gocv.io/x/gocv$ go run ./cmd/cuda/main.go
gocv version: 0.23.0
cuda information:
  Device 0:  "NVIDIA Tegra X1"  3964Mb, sm_53, Driver/Runtime ver.10.20/10.20
```

**Comment by scryptosan** [comment]
This issue reproducing only with opencv 4.3 and above. To use cuda you should compile opencv 4.2 and gocv 0.23.0. it works fine for me.

**Comment by gaond** [comment]
I've tested on opencv 4.4.0 with cuda

go run ./cmd/cuda/main.go
![image](https://user-images.githubusercontent.com/23079809/92677909-cb82a180-f35f-11ea-98f5-44a05373a81f.png)



git diff
```
diff --git a/cuda/cudabgsegm.h b/cuda/cudabgsegm.h
index 988b56a..4bd0421 100644
--- a/cuda/cudabgsegm.h
+++ b/cuda/cudabgsegm.h
@@ -3,7 +3,7 @@
 
 #ifdef __cplusplus
 #include <opencv2/opencv.hpp>
-
+#include <opencv2/cudabgsegm.hpp>
 extern "C" {
 #endif
 
diff --git a/cuda/imgproc.cpp b/cuda/imgproc.cpp
index 463f6a0..b0dd197 100644
--- a/cuda/imgproc.cpp
+++ b/cuda/imgproc.cpp
@@ -7,7 +7,7 @@ void GpuCvtColor(GpuMat src, GpuMat dst, int code) {
 }
 
 void GpuThreshold(GpuMat src, GpuMat dst, double thresh, double maxval, int typ) {
-    cv::cuda::threshold(*src, *dst, thresh, maxval, typ);
+    cv::threshold(*src, *dst, thresh, maxval, typ);
 }
 
 CannyEdgeDetector CreateCannyEdgeDetector(double lowThresh, double highThresh, int appertureSize, bool L2gradient) {
diff --git a/cuda/imgproc.h b/cuda/imgproc.h
index 344d42f..eb7e90b 100644
--- a/cuda/imgproc.h
+++ b/cuda/imgproc.h
@@ -6,6 +6,8 @@
 
 #ifdef __cplusplus
 #include <opencv2/opencv.hpp>
+#include <opencv2/cudaimgproc.hpp>
+
 extern "C" {
 #endif
 #include "cuda.h"
diff --git a/cuda/objdetect.h b/cuda/objdetect.h
index e4b31aa..bf9ac48 100644
--- a/cuda/objdetect.h
+++ b/cuda/objdetect.h
@@ -6,6 +6,7 @@
 #ifdef __cplusplus
 #include <opencv2/opencv.hpp>
 #include <opencv2/core/cuda.hpp>
+#include <opencv2/cudaobjdetect.hpp>
 
 extern "C" {
 #endif

```

**Comment by deadprogram** [comment]
This has now been released so closing. Thanks!
