### ISSUE TITLE
gocv.BlobFromImage is not work well.

### ISSUE THREAD

**Issue by knight2995** [hybridgroup/gocv#658]
## Description
I am trying to test dnn-detection [Code](https://github.com/hybridgroup/gocv/blob/master/cmd/dnn-detection/main.go)
. I am receiving an error message 
`gocv.io/x/gocv._Cfunc_Net_BlobFromImage(0x470f010, 0x3f80101010101010,...):`

I think the scalefactor parameter of the BlobFromImage seems to be wrong.
Only in 1.0 does not the error occur.

## Steps to Reproduce
1. I use TensorFlow Model and pbtxt config file.

## Your Environment

* Operating System and version: Windows 10
* OpenCV version used: 4.2.0
* How did you install OpenCV? No
* GoCV version used: 0.22.0
* Go version: 1.13.5
* Did you run the `env.sh` or `env.cmd` script before trying to `go run` or `go build`?

**Comment by deadprogram** [comment]
I think that the underlying API of OpenCV changed or else the model itself did, as I ran into a similar problem with scaling the input blob to a DNN recently. I will look into it further.

**Comment by knight2995** [comment]
Hi, I found this code in [opencv/dnn/dnn.cpp](https://github.com/opencv/opencv/blob/master/modules/dnn/src/dnn.cpp)

```
if (ddepth == CV_8U)  
    {
        CV_CheckEQ(scalefactor, 1.0, "Scaling is not supported for CV_8U blob depth");
        CV_Assert(mean_ == Scalar() && "Mean subtraction is not supported for CV_8U blob depth");
    }
```
I think this is the reason for the error. 

so, I try to change CV_8U to CV_32F, this code is worked fine.

```
// fix code
img.ConvertTo(&img, gocv.MatTypeCV32F)

blob := gocv.BlobFromImage(img, ratio, image.Pt(300, 300), mean, swapRGB, false)
```

**Comment by craigske** [comment]
Seeing this issue as well. Even converting doesn't work for me.
img.ConvertTo(&imgBlob, gocv.MatTypeCV32F)
		blob := gocv.BlobFromImage(imgBlob, 1.0, image.Pt(imgBlob.Rows(), imgBlob.Cols()), gocv.NewScalar(104, 117, 123, 0), false, false)

gives 
`libc++abi.dylib: terminating with uncaught exception of type cv::Exception: OpenCV(4.3.0) /tmp/opencv-20200531-90131-i8hdtq/opencv-4.3.0/modules/dnn/src/dnn.cpp:334: error: (-215:Assertion failed) mean_ == Scalar() && "Mean subtraction is not supported for CV_8U blob depth" in function 'blobFromImages'`

**Comment by wlwatkins** [comment]
Indeed, the conversion worked for me, will continue testing.

i guess it's similar to this issue https://stackoverflow.com/questions/55873713/assertation-failed-image-depth-in-blobfromimages

**Comment by liketheflower** [comment]
> Hi, I found this code in [opencv/dnn/dnn.cpp](https://github.com/opencv/opencv/blob/master/modules/dnn/src/dnn.cpp)
> 
> ```
> if (ddepth == CV_8U)  
>     {
>         CV_CheckEQ(scalefactor, 1.0, "Scaling is not supported for CV_8U blob depth");
>         CV_Assert(mean_ == Scalar() && "Mean subtraction is not supported for CV_8U blob depth");
>     }
> ```
> 
> I think this is the reason for the error.
> 
> so, I try to change CV_8U to CV_32F, this code is worked fine.
> 
> ```
> // fix code
> img.ConvertTo(&img, gocv.MatTypeCV32F)
> 
> blob := gocv.BlobFromImage(img, ratio, image.Pt(300, 300), mean, swapRGB, false)
> ```

It fixed my problem. Thanks.

**Comment by deadprogram** [comment]
Please see https://github.com/hybridgroup/gocv/issues/717

**Comment by EricaseJang** [comment]
> Hi, I found this code in [opencv/dnn/dnn.cpp](https://github.com/opencv/opencv/blob/master/modules/dnn/src/dnn.cpp)
> 
> ```
> if (ddepth == CV_8U)  
>     {
>         CV_CheckEQ(scalefactor, 1.0, "Scaling is not supported for CV_8U blob depth");
>         CV_Assert(mean_ == Scalar() && "Mean subtraction is not supported for CV_8U blob depth");
>     }
> ```
> 
> I think this is the reason for the error.
> 
> so, I try to change CV_8U to CV_32F, this code is worked fine.
> 
> ```
> // fix code
> img.ConvertTo(&img, gocv.MatTypeCV32F)
> 
> blob := gocv.BlobFromImage(img, ratio, image.Pt(300, 300), mean, swapRGB, false)
> ```

The issue occured both on Windows and macOS here.

It works. Thanks.
