### ISSUE TITLE
Compile binary for Web Assembly

### ISSUE THREAD

**Issue by pioz** [hybridgroup/gocv#660]
Compile a binary for Web Assembly seems not working
## Description
I'm trying to compile a simple main program that uses gocv for Web Assembly but I get some compile errors.

## Steps to Reproduce
I'm trying to compile this main.go file to run with Web Assembly.
```
package main

import (
	"fmt"
	"gocv.io/x/gocv"
)

func main() {
	m := gocv.NewMat()
	fmt.Println(m)
}
```
If I compile the file with `go build -o sample main.go` all works as expected.
But If I try to compile for web assembly with the command 
```
 GOOS=js GOARCH=wasm go build -o sample.wasm main.go
```
 I get the following compile error:
```
# gocv.io/x/gocv
../../Code/go/src/gocv.io/x/gocv/dnn_ext.go:9:28: undefined: Mat
../../Code/go/src/gocv.io/x/gocv/dnn_ext.go:16:12: undefined: NewMatWithSize
../../Code/go/src/gocv.io/x/gocv/dnn_ext.go:42:2: undefined: Resize
../../Code/go/src/gocv.io/x/gocv/dnn_ext.go:42:38: undefined: InterpolationDefault
../../Code/go/src/gocv.io/x/gocv/dnn_ext.go:45:3: undefined: CvtColor
../../Code/go/src/gocv.io/x/gocv/dnn_ext.go:48:15: undefined: NewMat
../../Code/go/src/gocv.io/x/gocv/dnn_ext.go:51:31: undefined: MatTypeCV32F
```
Any idea to solve this and compile a program with gocv for wasm?
## Your Environment

* Operating System and version: Mac OS X Catalina 10.15.4
* OpenCV version used: 4.2.0
* How did you install OpenCV? Homebrew
* GoCV version used: 0.23.0
* Go version: 1.14.1
* Did you run the `env.sh` or `env.cmd` script before trying to `go run` or `go build`? No

**Comment by deadprogram** [comment]
You would need a supported version of OpenCV compiled for WebAssembly for this to be possible, which  at this time does not yet exist as far as I know.

So this is not a supported configuration at this point.

Hope that helps!
