### ISSUE TITLE
MacOS Linux Cross Compile  By Docker: No Such File 

### ISSUE THREAD

**Issue by ItsFunny** [hybridgroup/gocv#662]
MacOS Linux Cross Compile : No Such File 
## Description

docker run -v ${GOPATH}:/go -v $PWD:/Users/joker/go/src/xxx.com/v2/xxx-file -w /Users/joker/go/src/xxx.com/v2/xxx-file/  -e GOOS=linux -e GOARCH=amd64 3f779b8e2183 go build --tags=nopkcs11 -v
## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

MacOS 
* Operating System and version: ubuntu 16.04
* OpenCV version used:     4.1.0
* How did you install OpenCV? 
* GoCV version used: 0.20.0
* Go version:  go version go1.13.8 linux/amd64
* Did you run the `env.sh` or `env.cmd` script before trying to `go run` or `go build`?

**Comment by deadprogram** [comment]
Sorry, I cannot tell anything about what your problem might be without seeing your code.
