### ISSUE TITLE
memory leak mat functions

### ISSUE THREAD

**Issue by cedricve** [hybridgroup/gocv#663]
I'm having a piece of code in an endless loop, and I can see after a long run it's leaking memory. Any thoughts?

    h1 := gocv.NewMat()
    gocv.AbsDiff(rgb, matArray[0], &h1)
    h2 := gocv.NewMat()
    gocv.AbsDiff(rgb, matArray[1], &h2)

    and := gocv.NewMat()
    gocv.BitwiseAnd(h1, h2, &and)
    h1.Close()
    h2.Close()

    thresh := gocv.NewMat()
    gocv.Threshold(and, &thresh, 30.0, 255.0, gocv.ThresholdBinary)
    and.Close()

    kernel := gocv.GetStructuringElement(gocv.MorphRect, image.Pt(3, 3))
    eroded := gocv.NewMat()
    gocv.Erode(thresh, &eroded, kernel)
    thresh.Close()
    kernel.Close()
    eroded.Close()

    changes := 0
    for _, c := range coordinatesToCheck {
    	value := eroded.GetUCharAt(c[1], c[0])
    	if value > 0 {
    		changes++
    	}
    }

   ...

**Comment by deadprogram** [comment]
Hello @cedricve 

In the code you provide, you are calling `eroded.Close()` before the `range` loop that uses it, which is invalid as the underlying OpenCV Mat can no longer be considered valid after closing it. It might work until the next next garbage collection or whatever, but for sure is not correct.

Hope that helps!

**Comment by cedricve** [comment]
thanks
