### ISSUE TITLE
Issue with rtcp stream

### ISSUE THREAD

**Issue by DmytroUsenko** [hybridgroup/gocv#671]
Hi Ron,
I have tried to use gocv 0.23 with rtcp streaming (h.264 25fps)
but have one issue/question. Maybe I do something wrong?
So the situation is the following:
I connect to IP cam. start streaming-> disconnect camera-> the stream is still running during ~12-15 sec ((
What is this? gocv use some sort of buffer? or what ? how can I manage it?
I wanna - lost stream-no actions (no frames from the stream). Is it possible to configure it?
Thanks in advance

**Comment by Danile71** [comment]
[Issue 475](https://github.com/hybridgroup/gocv/issues/475) 

Need to use custom package for rtsp

I am using [joy4](https://github.com/nareix/joy4)

P.s. customized/updated by 
[me](https://github.com/Danile71/joy4)

**Comment by DmytroUsenko** [comment]
Hi Danile. So the issue with gocv exists? As I saw joy4 is an FFmpeg binding? Thanks for the response I will try to see your fork.
Thank you.

**Comment by deadprogram** [comment]
If you search for "opencv rtcp latency" you will find many posts about this, having nothing to dp specifically with GoCV. Seems like the best option for many people has been using gstreamer, but I do not have much to offer for specific optimizations.

Hope that helps!

**Comment by DmytroUsenko** [comment]
Hi Ron,
I understood. thanks.
