### ISSUE TITLE
Support detectAndDecodeMulti for QRCodeDetector

### ISSUE THREAD

**Issue by OmriTreidel** [hybridgroup/gocv#674]
## Description
OpenCV  QRCodeDetector supports detection  and encoding of multiple QR codes. The goCV wrapper doesn't have a wrapper for it. It would be great to have it.

**Comment by OmriTreidel** [comment]
@deadprogram I've created a PR for this issue  a few months ago. Any chance of someone looking at it?

**Comment by OmriTreidel** [comment]
bump

**Comment by deadprogram** [comment]
This has now been released so closing. Thanks!
