### ISSUE TITLE
VideoCapture  Global variable is return nil pointer

### ISSUE THREAD

**Issue by buYoung** [hybridgroup/gocv#675]
After making VideoCapture as a global variable and returning it, the pointer is nil when reusing it. How do you solve this?

The result is the same when it's made into an interface, and the result is the same when it's made into a global variable.
## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

 Operating System and version: windows 10 // Raspberry pi 4 
* OpenCV version used: 4.3
* How did you install OpenCV? gocv install guide
* GoCV version used: newst
* Go version: newst
* Did you run the `env.sh` or `env.cmd` script before trying to `go run` or `go build`? go run // go build same

code :
camera.go [interface & in subfolder]
type Camst struct {
	Cv2 *gocv.VideoCapture
	Err error
	Img gocv.Mat
}
type Camz interface {
	Init()
	Read()
}

func (cv Camst) Init() {
	cv.Cv2, cv.Err = gocv.VideoCaptureDevice(0)
	cv.Cv2.Set(gocv.VideoCaptureFOURCC, Firstcam.ToCodec("MJPG"))
	cv.Img = gocv.NewMat()
	defer cv.Img.Close()
	fmt.Printf("%v\n", cv.Cv2)
}

func (cv Camst) Read(){
	fmt.Printf("%v\n", cv.Cv2)
	cv.Cv2.Read(&cv.Img)
}

main.go 
camstr := Global.Camst{}
	newimg := gocv.NewMat()
	var i Global.Camz
	i = camstr
	i.Init()

	for {
		time.Sleep(time.Second)
		i.Read()

		println(newimg.Empty())
	}

**Comment by deadprogram** [comment]
Sorry, but from the code you posted I cannot tell much.Please post a better formatted and more complete example for us to be able to help you. Thanks.

**Comment by buYoung** [comment]
Um... I wrote the code strangely.
I rewritten the code and tested it, and it works. Below is the code I tested.

main.go
Global
Global/Camera.go
Global/Varial.go

main.go:
```
package main

import (
	"../CVtest/Global"
	"time"
)

func main() {
	Global.SetCamera()

	for {
		Global.CameraRead()
		time.Sleep(time.Millisecond)
	}
}

```

Varial.go
```
package Global

import "gocv.io/x/gocv"

type Camera struct {
	Cam     *gocv.VideoCapture
	Camname string
}

var (
	Cameraz   Camera
	Image     gocv.Mat
	ShowImage gocv.Window
	err       error
)

```
Camera.go
```
package Global

import (
	"fmt"
	"gocv.io/x/gocv"
	"os"
	"time"
)

func init() {
	Image = gocv.NewMat()
}

func SetCamera() {
	go func() {
		Cameraz.Cam, err = gocv.VideoCaptureDevice(0)
		Cameraz.Camname = "first"
		if err != nil {
			println(err.Error())
		}
	}()
}
func CameraRead() {

	if Cameraz.Cam == nil {
		time.Sleep(time.Millisecond)
		return
	}
	fmt.Printf("%v %v\n", Cameraz.Cam, Cameraz.Camname)
	if ok := Cameraz.Cam.Read(&Image); ok {
		ShowImage.IMShow(Image)
		if ShowImage.WaitKey(1) == 27 {
			os.Exit(0)
		}
	}

}

```
