### ISSUE TITLE
Passing NULL to non-pointer argument 3 of 'BOOL AppendMenuA(HMENU, UINT, UINT_PTR, LPCSTR)'

### ISSUE THREAD

**Issue by AbhishekDimri** [hybridgroup/gocv#677]
void AddMenus(HWND hWnd)
{
    hMenu   = CreateMenu();
    HMENU hFileMenu     =   CreateMenu();
    HMENU hSubMenu      =   CreateMenu();

     AppendMenu(hSubMenu,MF_STRING,NULL,"Menu Item");//here is the error

    AppendMenu(hFileMenu,MF_STRING,FILE_MENU_NEW,"New");
    AppendMenu(hFileMenu,MF_POPUP,(UINT_PTR)hSubMenu,"Open");

    AppendMenu(hFileMenu,MF_SEPARATOR,NULL,NULL);//here also
    AppendMenu(hFileMenu,MF_STRING,FILE_MENU_EXIT,"Exit");

    AppendMenu(hMenu, MF_POPUP,(UINT_PTR)hFileMenu, "File");
    AppendMenu(hMenu, MF_STRING,NULL,"Help");//and lso here
    SetMenu(hWnd, hMenu);
}

**Comment by deadprogram** [comment]
Could you please explain how this question specifically pertains to GoCV? Thank you.
