### ISSUE TITLE
How to use iterations parameters in a Dilate function

### ISSUE THREAD

**Issue by jsrj78** [hybridgroup/gocv#682]
Hi everyone
I am a beginner, I want to  5 times dilation continuously, how do I use iteration parameters in the dilate function

**Comment by deadprogram** [comment]
Hi @jsrj78 we'd be happy to accept a pull request that added a "DilateWithParams()` function. Please see the last part of https://github.com/hybridgroup/gocv/blob/master/CONTRIBUTING.md#how-to-add-a-function-from-opencv-to-gocv for more details on how to do this.

**Comment by mbalayil** [comment]
Please take a look at my PR.

**Comment by mbalayil** [comment]
Have updated the PR. Please take a look.

**Comment by deadprogram** [comment]
Thanks @mbalayil for the contribution. Now merging this issue to be closed on next release.

**Comment by deadprogram** [comment]
Released in v0.28 so now closing. Thanks!
