### ISSUE TITLE
Video Writer Error handle

### ISSUE THREAD

**Issue by buYoung** [hybridgroup/gocv#684]
* Operating System and version: Raspebrry Pi 4
* OpenCV version used: 4.3
* How did you install OpenCV? RPi script
* GoCV version used: 0.22.0
* Go version: 1.14.2
* Did you run the `env.sh` or `env.cmd` script before trying to `go run` or `go build`? yes
 
Error Detail 
terminate called after throwing an instance of 'cv::Exception'
  what():  OpenCV(4.3.0) /tmp/opencv/opencv-4.3.0/modules/core/src/matrix.cpp:209: error: (-215:Assertion failed) 0 <= _dims && _dims <= CV_MAX_DIM in function 'setSize'

This error often occurs when the image is taken from the camera and sent to the channel.
I didn't test it when it wasn't a channel.

```
var (
imgchan    = make(chan gocv.Mat,5)
Check = false

)
cam, err := gocv.OpenVideoCapture(deviceID)
for {
			img := gocv.NewMat()
			if ok := cam.Read(&img); ok {
                        '''some Event '''
                        if event { 
                             go savemovie()
                           Check  = true
                        }
                       if Check {
                          imgchan <- img
                        }
     }
func savemovie(){
        writer, err := gocv.VideoWriterFile(filepath, "X264", 20, int(Camerainfo.width), int(Camerainfo.height), true)
	if err != nil {
		fmt.Printf("Don't make Movie file Reason : %v\n", err.Error())
		return
	}
        for {
		if writer.IsOpened() {
			break
		}
	     }
        for { 
       select {
		case img1 := <-imgchan:
				if img1.Empty() {
					continue
				}
				if img1.Cols() != int(640) {
					continue
				}
				if img1.Rows() != int(480) {
					continue
				}
				err := writer.Write(img1) <<<-An error occurred
				if err != nil {
					println("Error: ", err.Error())
				}
                    if someevent { 
                              writer.close()
                    }
                default
        }

}

**Comment by deadprogram** [comment]
It is a bit hard to tell from that examples what might be happening, but it does not appears to be directly related to GoCV.

Now closing, please reopen if needed. Thank you.
