### ISSUE TITLE
import error gocv.io/x/gocv/contrib

### ISSUE THREAD

**Issue by ilaer** [hybridgroup/gocv#685]
use gocv/contrib to recognize face，run error here:
`# gocv.io/x/gocv/contrib
/tmp/go-build753755959/b038/_x008.o：在函数‘BackgroundSubtractorCNT_Create’中：
../../go/pkg/mod/gocv.io/x/gocv@v0.22.0/contrib/bgsegm.cpp:4：对‘cv::bgsegm::createBackgroundSubtractorCNT(int, bool, int, bool)’未定义的引用
/tmp/go-build753755959/b038/_x010.o：在函数‘pHashCompute’中：
../../go/pkg/mod/gocv.io/x/gocv@v0.22.0/contrib/img_hash.cpp:4：对‘cv::img_hash::pHash(cv::_InputArray const&, cv::_OutputArray const&)’未定义的引用
/tmp/go-build753755959/b038/_x010.o：在函数‘averageHashCompute’中：
../../go/pkg/mod/gocv.io/x/gocv@v0.22.0/contrib/img_hash.cpp:11：对‘cv::img_hash::averageHash(cv::_InputArray const&, cv::_OutputArray const&)’未定义的引用
/tmp/go-build753755959/b038/_x010.o：在函数‘blockMeanHashCompute’中：
../../go/pkg/mod/gocv.io/x/gocv@v0.22.0/contrib/img_hash.cpp:18：对‘cv::img_hash::blockMeanHash(cv::_InputArray const&, cv::_OutputArray const&, int)’未定义的引用
/tmp/go-build753755959/b038/_x010.o：在函数‘colorMomentHashCompute’中：
../../go/pkg/mod/gocv.io/x/gocv@v0.22.0/contrib/img_hash.cpp:25：对‘cv::img_hash::colorMomentHash(cv::_InputArray const&, cv::_OutputArray const&)’未定义的引用
/tmp/go-build753755959/b038/_x010.o：在函数‘marrHildrethHashCompute’中：
../../go/pkg/mod/gocv.io/x/gocv@v0.22.0/contrib/img_hash.cpp:32：对‘cv::img_hash::marrHildrethHash(cv::_InputArray const&, cv::_OutputArray const&, float, float)’未定义的引用
/tmp/go-build753755959/b038/_x010.o：在函数‘radialVarianceHashCompute’中：
../../go/pkg/mod/gocv.io/x/gocv@v0.22.0/contrib/img_hash.cpp:39：对‘cv::img_hash::radialVarianceHash(cv::_InputArray const&, cv::_OutputArray const&, double, int)’未定义的引用
/tmp/go-build753755959/b038/_x010.o：在函数‘pHashCompare’中：
../../go/pkg/mod/gocv.io/x/gocv@v0.22.0/contrib/img_hash.cpp:7：对‘cv::img_hash::PHash::create()’未定义的引用
../../go/pkg/mod/gocv.io/x/gocv@v0.22.0/contrib/img_hash.cpp:7：对‘cv::img_hash::ImgHashBase::compare(cv::_InputArray const&, cv::_InputArray const&) const’未定义的引用
/tmp/go-build753755959/b038/_x010.o：在函数‘averageHashCompare’中：
../../go/pkg/mod/gocv.io/x/gocv@v0.22.0/contrib/img_hash.cpp:14：对‘cv::img_hash::AverageHash::create()’未定义的引用
../../go/pkg/mod/gocv.io/x/gocv@v0.22.0/contrib/img_hash.cpp:14：对‘cv::img_hash::ImgHashBase::compare(cv::_InputArray const&, cv::_InputArray const&) const’未定义的引用
/tmp/go-build753755959/b038/_x010.o：在函数‘blockMeanHashCompare’中：
../../go/pkg/mod/gocv.io/x/gocv@v0.22.0/contrib/img_hash.cpp:21：对‘cv::img_hash::BlockMeanHash::create(int)’未定义的引用
../../go/pkg/mod/gocv.io/x/gocv@v0.22.0/contrib/img_hash.cpp:21：对‘cv::img_hash::ImgHashBase::compare(cv::_InputArray const&, cv::_InputArray const&) const’未定义的引用
/tmp/go-build753755959/b038/_x010.o：在函数‘colorMomentHashCompare’中：
../../go/pkg/mod/gocv.io/x/gocv@v0.22.0/contrib/img_hash.cpp:28：对‘cv::img_hash::ColorMomentHash::create()’未定义的引用
../../go/pkg/mod/gocv.io/x/gocv@v0.22.0/contrib/img_hash.cpp:28：对‘cv::img_hash::ImgHashBase::compare(cv::_InputArray const&, cv::_InputArray const&) const’未定义的引用
/tmp/go-build753755959/b038/_x010.o：在函数‘marrHildrethHashCompare’中：
../../go/pkg/mod/gocv.io/x/gocv@v0.22.0/contrib/img_hash.cpp:35：对‘cv::img_hash::MarrHildrethHash::create(float, float)’未定义的引用
../../go/pkg/mod/gocv.io/x/gocv@v0.22.0/contrib/img_hash.cpp:35：对‘cv::img_hash::ImgHashBase::compare(cv::_InputArray const&, cv::_InputArray const&) const’未定义的引用
/tmp/go-build753755959/b038/_x010.o：在函数‘radialVarianceHashCompare’中：
../../go/pkg/mod/gocv.io/x/gocv@v0.22.0/contrib/img_hash.cpp:42：对‘cv::img_hash::RadialVarianceHash::create(double, int)’未定义的引用
../../go/pkg/mod/gocv.io/x/gocv@v0.22.0/contrib/img_hash.cpp:42：对‘cv::img_hash::ImgHashBase::compare(cv::_InputArray const&, cv::_InputArray const&) const’未定义的引用
/tmp/go-build753755959/b038/_x011.o：在函数‘Tracker_Init’中：
../../go/pkg/mod/gocv.io/x/gocv@v0.22.0/contrib/tracking.cpp:8：对‘cv::Tracker::init(cv::_InputArray const&, cv::Rect_<double> const&)’未定义的引用
/tmp/go-build753755959/b038/_x011.o：在函数‘Tracker_Update’中：
../../go/pkg/mod/gocv.io/x/gocv@v0.22.0/contrib/tracking.cpp:14：对‘cv::Tracker::update(cv::_InputArray const&, cv::Rect_<double>&)’未定义的引用
/tmp/go-build753755959/b038/_x011.o：在函数‘TrackerMIL_Create’中：
../../go/pkg/mod/gocv.io/x/gocv@v0.22.0/contrib/tracking.cpp:23：对‘cv::TrackerMIL::create()’未定义的引用
/tmp/go-build753755959/b038/_x011.o：在函数‘TrackerBoosting_Create’中：
../../go/pkg/mod/gocv.io/x/gocv@v0.22.0/contrib/tracking.cpp:31：对‘cv::TrackerBoosting::create()’未定义的引用
/tmp/go-build753755959/b038/_x011.o：在函数‘TrackerMedianFlow_Create’中：
../../go/pkg/mod/gocv.io/x/gocv@v0.22.0/contrib/tracking.cpp:39：对‘cv::TrackerMedianFlow::create()’未定义的引用
/tmp/go-build753755959/b038/_x011.o：在函数‘TrackerTLD_Create’中：
../../go/pkg/mod/gocv.io/x/gocv@v0.22.0/contrib/tracking.cpp:47：对‘cv::TrackerTLD::create()’未定义的引用
/tmp/go-build753755959/b038/_x011.o：在函数‘TrackerKCF_Create’中：
../../go/pkg/mod/gocv.io/x/gocv@v0.22.0/contrib/tracking.cpp:55：对‘cv::TrackerKCF::create()’未定义的引用
/tmp/go-build753755959/b038/_x011.o：在函数‘TrackerMOSSE_Create’中：
../../go/pkg/mod/gocv.io/x/gocv@v0.22.0/contrib/tracking.cpp:63：对‘cv::TrackerMOSSE::create()’未定义的引用
/tmp/go-build753755959/b038/_x011.o：在函数‘TrackerCSRT_Create’中：
../../go/pkg/mod/gocv.io/x/gocv@v0.22.0/contrib/tracking.cpp:71：对‘cv::TrackerCSRT::create()’未定义的引用
/tmp/go-build753755959/b038/_x012.o：在函数‘SIFT_Create’中：
../../go/pkg/mod/gocv.io/x/gocv@v0.22.0/contrib/xfeatures2d.cpp:5：对‘cv::xfeatures2d::SIFT::create(int, int, double, double, double)’未定义的引用
/tmp/go-build753755959/b038/_x012.o：在函数‘SURF_Create’中：
../../go/pkg/mod/gocv.io/x/gocv@v0.22.0/contrib/xfeatures2d.cpp:48：对‘cv::xfeatures2d::SURF::create(double, int, int, bool, bool)’未定义的引用
/tmp/go-build753755959/b038/_x009.o：在函数‘CreateLBPHFaceRecognizer’中：
../../go/pkg/mod/gocv.io/x/gocv@v0.22.0/contrib/face.cpp:4：对‘cv::face::LBPHFaceRecognizer::create(int, int, int, int, double)’未定义的引用
/tmp/go-build753755959/b038/_x009.o：在函数‘LBPHFaceRecognizer_Predict’中：
../../go/pkg/mod/gocv.io/x/gocv@v0.22.0/contrib/face.cpp:45：对‘cv::face::FaceRecognizer::predict(cv::_InputArray const&) const’未定义的引用
/tmp/go-build753755959/b038/_x009.o：在函数‘LBPHFaceRecognizer_PredictExtended’中：
../../go/pkg/mod/gocv.io/x/gocv@v0.22.0/contrib/face.cpp:55：对‘cv::face::FaceRecognizer::predict(cv::_InputArray const&, int&, double&) const’未定义的引用
collect2: error: ld returned 1 exit status
`

**Comment by deadprogram** [comment]
Looks like you perhaps need to compile your OpenCV installation using the `BUILD_SHARED_LIBS` flag.

See https://github.com/hybridgroup/gocv/blob/master/Makefile#L121 for an example.

**Comment by deadprogram** [comment]
Closing due to age, please reopen if needed.
