### ISSUE TITLE
Constants defined in const() block have the wrong type

### ISSUE THREAD

**Issue by Minnozz** [hybridgroup/gocv#686]
## Description
Example: https://github.com/hybridgroup/gocv/blob/v0.23.0/imgcodecs.go#L13
```
// IMReadFlag is one of the valid flags to use for the IMRead function.
type IMReadFlag int

const (
	// IMReadUnchanged return the loaded image as is (with alpha channel,
	// otherwise it gets cropped).
	IMReadUnchanged IMReadFlag = -1

	// IMReadGrayScale always convert image to the single channel
	// grayscale image.
	IMReadGrayScale = 0
```
`IMReadUnchanged` has type `IMReadFlag`.
`IMReadGrayScale` has type `int` because a value is specified and the type annotation is not repeated.

## Steps to Reproduce
See https://play.golang.org/p/wYFVwKAFicK for a minimal example.

**Comment by deadprogram** [comment]
#689 was merged into `dev` it will be part of the next release.

Thanks!
