### ISSUE TITLE
GetAffineTransform() function missing

### ISSUE THREAD

**Issue by Minnozz** [hybridgroup/gocv#687]
## Description

The following functions are available for a perspective transform:
```
func GetPerspectiveTransform(src, dst []image.Point) Mat
func GetPerspectiveTransform2f(src, dst []Point2f) Mat
func WarpPerspective(src Mat, dst *Mat, m Mat, sz image.Point)
```
These map to https://docs.opencv.org/master/da/d54/group__imgproc__transform.html#ga20f62aa3235d869c9956436c870893ae and https://docs.opencv.org/master/da/d54/group__imgproc__transform.html#gaf73673a7e8e18ec6963e3774e6a94b87

For an affine transform, the following functions are available:
```
func WarpAffine(src Mat, dst *Mat, m Mat, sz image.Point)
func WarpAffineWithParams(src Mat, dst *Mat, m Mat, sz image.Point, flags InterpolationFlags, borderType BorderType, borderValue color.RGBA)
```
These map to https://docs.opencv.org/master/da/d54/group__imgproc__transform.html#ga0203d9ee5fcd28d40dbc4a1ea4451983. However, the function to calculate the affine transformation matrix is missing.

I would expect the following signatures for that function:
```
func GetAffineTransform(src, dst []image.Point) Mat
func GetAffineTransform2f(src, dst []Point2f) Mat
```
Those would map to https://docs.opencv.org/master/da/d54/group__imgproc__transform.html#ga8f6d378f9f8eebb5cb55cd3ae295a999.

**Comment by deadprogram** [comment]
Hello @Minnozz 

Please see https://github.com/hybridgroup/gocv/blob/master/CONTRIBUTING.md#something-you-wantneed-from-opencv-does-not-appear-to-be-in-gocv

and then check the ROADMAP in the `dev` branch:

https://github.com/hybridgroup/gocv/blob/dev/ROADMAP.md

**Comment by Minnozz** [comment]
Hi @deadprogram, I made a PR at https://github.com/hybridgroup/gocv/pull/688 that adds the two functions I proposed.
