### ISSUE TITLE
Add cv::matchTemplate() bindings

### ISSUE THREAD

**Issue by littledot** [hybridgroup/gocv#69]
Hi,

I'm interested in adding `cv::matchTemplate()` bindings to GoCV. 
API: https://docs.opencv.org/3.2.0/df/dfb/group__imgproc__object.html#ga586ebfb0a7fb604b35a23d85391329be
Source: https://github.com/opencv/opencv/blob/master/modules/imgproc/src/templmatch.cpp#L1090

Are you OK with this?

**Comment by deadprogram** [comment]
Seems like a good idea to me.

https://docs.opencv.org/3.4.0/df/dfb/group__imgproc__object.html#ga586ebfb0a7fb604b35a23d85391329be

**Comment by deadprogram** [comment]
Thanks for the contribution @littledot I will close this issue once the next release goes out.

**Comment by littledot** [comment]
Thanks for the quick turnaround. 

Just curious, how often do you cut a release? I plan to add a few more API bindings.

**Comment by deadprogram** [comment]
We have been doing monthly releases so far.

**Comment by deadprogram** [comment]
The latest release 0.9.0 from today now includes this code. Thank you!
