### ISSUE TITLE
Expose apiPreference and int fourcc in VideoWriter Constructor

### ISSUE THREAD

**Issue by jhhurwitz** [hybridgroup/gocv#690]
Hello,

It seems currently the only way to create a VideoWriter is through the `C.VideoWriter_Open` function.

It would be great to expose a function that allows a user to specify the apiPreference (in my case to force CAP_GSTREAMER) and the fourcc as an int (to allow for fourcc=0) when constructing the VideoWriter. 

I was able to use such a function I created locally to make gstreamer video writing work consistently with gocv.

Happy to open a PR if that makes sense.

Thanks for the awesome library!

**Comment by deadprogram** [comment]
Hi @jhhurwitz that sounds like a good enhancement. Right now I think you can only do this for input by using the arcane GStreamer syntax as a string passed to the camera.

We would be really happy to get a PR that added this!

**Comment by nibbleshift** [comment]
Is there any status on this? I'd like this functionality.   If you need a PR, i could look into integrating this functionality.

**Comment by jhhurwitz** [comment]
@nibbleshift, unfortunately, some things changed recently with me, and I am unable to work on this right now. Would definitely be happy to see a PR, though.

**Comment by nibbleshift** [comment]
Thanks for the update.  I will look into getting this done.

**Comment by nibbleshift** [comment]
hi @deadprogram, i submitted PR https://github.com/hybridgroup/gocv/pull/718

If there are any changes you would like in the PR, let me know and I'll make them.

**Comment by deadprogram** [comment]
I just merged #739 which appears to have done the same sort of thing as #718 

@nibbleshift thank you anyhow for the contribution it is appreciated!

Marking this issue for next release.

**Comment by deadprogram** [comment]
This has now been released so closing. Thanks!
