### ISSUE TITLE
Unexpected behaviour in nonzerocount when drawing a rectangle

### ISSUE THREAD

**Issue by JoshChristie** [hybridgroup/gocv#692]
## Description
Changing the `B` channel in `color.RGBA` changes the nonzero count unexpectedly when drawing a rectangle.

My expectations are that the nonzero count should always either be 0 or 100.

## Steps to Reproduce
```
for b := 0; b < 10; b+=1 {
	mask1 := gocv.NewMatWithSize(20, 20, gocv.MatTypeCV8U)
	gocv.Rectangle(&mask1, image.Rect(0,0,9,9), color.RGBA{0,0,uint8(b),0}, -1)
	fmt.Println("b", b, "nonZeroCount", gocv.CountNonZero(mask1))
}
// output
b 0 nonZeroCount 0
b 1 nonZeroCount 100
b 2 nonZeroCount 100
b 3 nonZeroCount 100
b 4 nonZeroCount 100
b 5 nonZeroCount 116
b 6 nonZeroCount 116
b 7 nonZeroCount 116
b 8 nonZeroCount 116
b 9 nonZeroCount 120
```
## Environment

* Operating System and version: Ubuntu 18.04
* OpenCV version used: 4.3.0
* How did you install OpenCV? make install
* GoCV version used:  gocv 0.23.0
* Go version: 1.14.3 linux/amd64
* Did you run the `env.sh` or `env.cmd` script before trying to `go run` or `go build`? -

**Comment by golubaca** [comment]
It actually change behaviour when swapping variable b to a different position in RGBA, like `color.RGBA{uint8(b),0,0,0,}` and `color.RGBA{0,0,uint8(b),0,}` does not have same result.
Also, if you change mat type to MatTypeCV8S (or any other type except CV8U), you'll meet your expectations.

**Comment by deadprogram** [comment]
This question appears to have now been answered, so closing. Please reopen if needed. Thank you!
