### ISSUE TITLE
Add MultiplyWithParams()

### ISSUE THREAD

**Issue by Minnozz** [hybridgroup/gocv#696]
## Description
The current [Multiply](https://pkg.go.dev/gocv.io/x/gocv?tab=doc#Multiply) has no `scale` (and `dtype`) parameters, like [the OpenCV function](https://docs.opencv.org/master/d2/de8/group__core__array.html#ga979d898a58d7f61c53003e162e7ad89f) does. I'll make a PR that adds `MultiplyWithParams(src1 Mat, src2 Mat, dst *Mat, scale float64, dtype MatType)`, since that seems to fit into the current naming scheme best.

An alternative would be adding `MultiplyScale(src1 Mat, src2 Mat, dst *Mat, scale float64)`, that adds `scale` but ignores `dtype`.

**Comment by deadprogram** [comment]
Version v0.24.0 includes this so now closing. Thanks!
