### ISSUE TITLE
Unable to run the application using static lib

### ISSUE THREAD

**Issue by kevinsimard** [hybridgroup/gocv#698]
Hello, I'm trying to build an application on Windows that uses OpenCV. The ultimate goal is to be able to run this application on a PC that doesn't have OpenCV installed. I tried looking in all closed issues from this repository but none of the solutions is fixing my problem.

# Description

I followed all the instructions from the https://gocv.io/getting-started/windows/ page and the sample application from the repo ran successfully using the installed OpenCV library from `C:\opencv\build`.

I tried changing `DBUILD_SHARED_LIBS` variable from ON to OFF in `win_build_opencv.cmd` and rebuilt the library. Next step was to set the environment variables as your document is saying (beside that the directory changed from `mingw\lib` to `mingw\staticlib` because of that shared lib value.

```
set CGO_CXXFLAGS "--std=c++11"

set CGO_CPPFLAGS "-IC:\opencv\build\install\include"

set CGO_LDFLAGS "-LC:\opencv\build\install\x64\mingw\staticlib -lopencv_core430 -lopencv_face430 -lopencv_videoio430 -lopencv_imgproc430 -lopencv_highgui430 -lopencv_imgcodecs430 -lopencv_objdetect430 -lopencv_features2d430 -lopencv_video430 -lopencv_dnn430 -lopencv_xfeatures2d430 -lopencv_plot430 -lopencv_tracking430 -lopencv_img_hash430 -lopencv_calib3d430"
```

When I try to run the application with the -tags customenv parameter, I keep on getting the following error:

```
go run -tags customenv main.go
# gocv.io/x/gocv
In file included from calib3d.cpp:1:0:
calib3d.h:5:10: fatal error: opencv2/opencv.hpp: No such file or directory
 #include <opencv2/opencv.hpp>
          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

Is there anything I'm missing? Thank you!

@deadprogram 

## Steps to Reproduce

1. Change `DBUILD_SHARED_LIBS` from ON to OFF.
2. Follow the steps from the doc https://gocv.io/getting-started/windows/#custom-environment (make sure to change mingw\lib to mingw\staticlib).
3. Run `go run -tags customenv cmd\version\main.go` to test.

## Your Environment

* Operating System and version: Windows 10 Pro
* OpenCV version used: 4.3.0
* How did you install OpenCV? win_build_opencv.cmd
* GoCV version used: 0.23.0
* Go version: 1.14.4

**Comment by programmer10110** [comment]
@kevinsimard, did you manage to build this?
