### ISSUE TITLE
error when running gocv example on hisi armv7a

### ISSUE THREAD

**Issue by shockjiang** [hybridgroup/gocv#702]
I cross-compiled opencv-4.3.0 & contrib on linux, and created a simple image reading sample gocv example. 
Then cross-compiled with go build.  I got the arm application. But when I run it on the armv7a device, it gave me relocation error: 
'''./gocv-arm: relocation error: /root/lib4.3.0/lib/libopencv_gapi.so.4.3: symbol _ZTINSt13__future_base12_Result_baseE, version GLIBCXX_3.4.23 not defined in file libstdc++.so.6 with link time reference
'''

It seems that, this gocv-arm depends on all opencv libraries. Is there a way to remove unnecessary dependencies?

I also created a simple c++ program, which only relies on imgcodecs, core, and imgproc, which works well on the target device. 

## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Operating System and version:
* OpenCV version used: 4.3.0
* How did you install OpenCV?: 
* GoCV version used: latest
* Go version: 1.13
* Did you run the `env.sh` or `env.cmd` script before trying to `go run` or `go build`?

**Comment by deadprogram** [comment]
HI @shockjiang generally speaking, cross compiling when CGo is required (like GoCV) is very difficult. Hence is not a fully supported operation. 

You might have better luck by creating a docker container for ARM64 and compiling in that.

Hope that helps!
