### ISSUE TITLE
Mixed Blue and Red colours in gocv.DrawKeyPoints()

### ISSUE THREAD

**Issue by shanduur** [hybridgroup/gocv#707]
## Description

While performing merge of image and key points with DrawKeyPoints, I am receiving unexpected result. While the `RGBA{}` definition seems okay, and I am doing everything as in the docs, I am getting result in Blue instead of Red (screenshot is presented below). As I investigated, it MIGHT be connected with different colour definitions in OpenCV - there is used **BGRA** instead of **RGBA** in the OpenCV.  

## Steps to Reproduce

1. Start new project, create simple program loading photo and performing SIFT:
```go
package main

import (
	"gocv.io/x/gocv"
	"gocv.io/x/gocv/contrib"
	"image/color"
)

func main() {
	window := gocv.NewWindow("Example")
	img := gocv.IMRead("example.jpg", gocv.IMReadColor)
	sift := contrib.NewSIFT()
	kp := sift.Detect(img)
	gocv.DrawKeyPoints(img, kp, &img, color.RGBA{
		R: 255,
		G: 0,
		B: 0,
		A: 0,
	}, gocv.DrawDefault)
	for {
		window.IMShow(img)
		window.WaitKey(1)
	}
}
```
2. Outcome - key points are drawn in **Blue** instead of **Red**:

![Screenshot from 2020-07-08 15-07-32](https://user-images.githubusercontent.com/32583062/86922357-c79e8d00-c12c-11ea-903a-850721e64bd3.png)

## Your Environment

* Operating System and version: Pop!_OS 20.04 LTS
* OpenCV version used: 4.3.0
* How did you install OpenCV? `make install`
* GoCV version used: 0.23.0
* Go version: go1.14.4 linux/amd64
* Did you run the `env.sh` or `env.cmd` script before trying to `go run` or `go build`? No

**Comment by golubaca** [comment]
I agree that sometimes gocv and opencv does not have same features, and some features is very hard to translate to gocv.
I modified your code to convert loaded image to RGBA because we can only use color.RGBA, and after processing, we return the result image to BGR, which will correctly display red circles.
```go
package main

import (
    "image/color"

    "gocv.io/x/gocv"
    "gocv.io/x/gocv/contrib"
)

func main() {
    window := gocv.NewWindow("Example")
    img := gocv.IMRead("example.jpg", gocv.IMReadColor)
    gocv.CvtColor(img, &img, gocv.ColorBGRToRGBA) // can also be gocv.ColorBGRToRGBA, doesen't matter
    sift := contrib.NewSIFT()
    kp := sift.Detect(img)
    gocv.DrawKeyPoints(img, kp, &img, color.RGBA{
        R: 255,
        G: 0,
        B: 0,
        A: 0,
    }, gocv.DrawDefault)
    gocv.CvtColor(img, &img, gocv.ColorRGBAToBGR)
    window.IMShow(img)
    window.WaitKey(0)
}
```

One possible way to overcome this problem is to create custom color types to be parallel with opencv. color.RGBA is defined as
```go
type RGBA struct {
    R, G, B, A uint8
}
```
so it is basicaly a struct with 4 uint8 values. One of solution will be to create same struct (or multiple ones, like BGR..) inside gocv, and use that instead of image/color ones. In addition to creating custom structs, we need to modify functions as well, to include those custom structs. Functions can be named as
```go
    func DrawKeyPointsBGR(src Mat, keyPoints []KeyPoint, dst *Mat, color gocv.ColorBGR, flag DrawMatchesFlag)
```
and so on.

**Comment by golubaca** [comment]
Ok, tested this, and here are results:
```
issue707 $ C:\Go\bin\go.exe test -benchmem -bench . -benchtime=1m
goos: windows
goarch: amd64
pkg: programazer.xyz/golubaca/gocv_issues/issue707
BenchmarkWithColorConverting-16              457         153461301 ns/op          262171 B/op          3 allocs/op
BenchmarkWithCustomBGRA-16                   483         147834574 ns/op          262165 B/op          3 allocs/op
PASS
ok      programazer.xyz/golubaca/gocv_issues/issue707   172.847s
```

I modified features2d.go to include new function DrawKeyPointsBGR and also created ctruct `ColorBGRA` to reflect this change. So, in your example you'll change  `gocv.DrawKeyPoints` to `gocv.DrawKeyPointsBGRA` which will eliminate two color converting operations.
@deadprogram Do you agree with this decision or there is better way of handling this? We will have two functions for the same task, but with different parameters. Included benchmark show that we can get couple of more operations in the same time, tested it with 1m/benchFunc. If you agree, I'll create pull request after comparing more methods.

**Comment by golubaca** [comment]
Ok, after investigating code, I noticed that let say gocv.Rectangle  takes RGBA color vales, but changes the order inside function to BGRA, and passing to C code (code: https://github.com/hybridgroup/gocv/blob/master/imgproc.go#L1286). So I think it is better to change existing DrawKeyPoints function to behave same as others. I'll create pull request.

**Comment by deadprogram** [comment]
> So I think it is better to change existing DrawKeyPoints function to behave same as others.

That sounds like the least surprising solution, to me. Thanks for looking into this!

**Comment by deadprogram** [comment]
Version v0.24.0 includes this so now closing. Thanks!
