### ISSUE TITLE
imgproc.cpp:677:9: warning: use of GNU old-style field designator extension [-Wgnu-designator]

### ISSUE THREAD

**Issue by ka1i** [hybridgroup/gocv#709]
fix warning : `imgproc.cpp:677:9: warning: use of GNU old-style field designator extension [-Wgnu-designator]` 

## Description
`imgproc.cpp:676:9: warning: use of GNU old-style field designator extension [-Wgnu-designator]`
`imgproc.cpp:677:9: warning: use of GNU old-style field designator extension [-Wgnu-designator]`

## Steps to Reproduce

1. go get -u -d gocv.io/x/gocv
2. brew install opencv
3. brew install pkgconfig
4. go run ./cmd/version/main.go

## Your Environment

* Operating System and version: macOS Catalina
* OpenCV version used:4.3.0
* How did you install OpenCV? ye `brew install opencv`
* GoCV version used: 0.23.0
* Go version: go1.14.4 darwin/amd64
* Did you run the `env.sh` or `env.cmd` script before trying to `go run` or `go build`?

# solution
cd gocv.io/x/gocv@v0.23.0
modify imgproc.cpp row 676&677 ,=>  like this
`.x = float(result.x),`
`.y = float(result.y),`

**Comment by deadprogram** [comment]
Version v0.24.0 includes this so now closing. Thanks!
