### ISSUE TITLE
calib3d.h:5:10: fatal error: opencv2/opencv.hpp: No such file or directory

### ISSUE THREAD

**Issue by Dontmindmes** [hybridgroup/gocv#712]
I am using the latest version fo gocv

This is the error I get when I attempt to go build main.go

`// What it does:
//
// This example uses the VideoCapture class to capture a frame from a connected webcam,
// then save it to an image file on disk.
//
// How to run:
//
// saveimage [camera ID] [image file]
//
// 		go run ./cmd/saveimage/main.go 0 filename.jpg
//
// +build example

package main

import (
	"fmt"

	"gocv.io/x/gocv"
)

func main() {
	deviceID := 0
	saveFile := "test.png"

	webcam, err := gocv.OpenVideoCapture(deviceID)
	if err != nil {
		fmt.Printf("Error opening video capture device: %v\n", deviceID)
		return
	}
	defer webcam.Close()

	img := gocv.NewMat()
	defer img.Close()

	if ok := webcam.Read(&img); !ok {
		fmt.Printf("cannot read device %v\n", deviceID)
		return
	}
	if img.Empty() {
		fmt.Printf("no image on device %v\n", deviceID)
		return
	}

	gocv.IMWrite(saveFile, img)
}
`

Idk whats going on or why its not working

**Comment by deadprogram** [comment]
Closing due to age and lack of info on OS, etc. Please reopen if needed.
