### ISSUE TITLE
cv::dnn::NMSBoxes() doesn't seem to be implemented

### ISSUE THREAD

**Issue by darrenparkinson** [hybridgroup/gocv#713]
I am trying to use Yolov3 for object detection and wanted to use the equivalent of the python `cv2.dnn.NMSBoxes` and I don't seem to be able to find it.

It's possible that there is some other way of achieving the equivalent functionality?  

Apologies if this is a bit basic.

## Description

I'm trying to progress the example in Issue #465 and discovered that when trying to apply non-maxima suppression to remove weak overlapping bounding boxes, the function doesn't appear to exist.

Additionally I am having other problems with the example as outlined in #705 

## Your Environment

* Operating System and version: macOS Catalina Version 10.15.5
* OpenCV version used: 4.3.0
* How did you install OpenCV? brew
* GoCV version used: 0.23.0
* Go version: 1.14
* Did you run the `env.sh` or `env.cmd` script before trying to `go run` or `go build`? No.

**Comment by deadprogram** [comment]
Please see https://github.com/hybridgroup/gocv/blob/master/CONTRIBUTING.md#something-you-wantneed-from-opencv-does-not-appear-to-be-in-gocv

**Comment by darrenparkinson** [comment]
Ah, yes, I see. NMSBoxes is on that [ROADMAP.md](https://github.com/hybridgroup/gocv/blob/master/ROADMAP.md).  Apologies. 😬
