### ISSUE TITLE
Using dev branch

### ISSUE THREAD

**Issue by dvtkrlbs** [hybridgroup/gocv#715]
I am trying to use the dev branch of the code to be able to use some of the functions on the roadmap
and i am using go modules to just get the appropriate branch like this `go get gocv.io/x/gocv@dev` however this downloads dependencies to `$GOPATH/pkg/mod/gocv.io/x/gocv(and some gibberish hash)` and when i run `win_build_opencv.cmd`  and the script tries use the `$GOPATH/src` directory
## Steps to Reproduce

1. Create a go module
2. do `go get gocv.io/x/gocv@dev`
3. go to `$GOPATH/pkg/mod/gocv.io/x/gocv@(some gibberish version number)`
4. do `win_build_opencv.md`

## Your Environment

* Operating System and version: Windows
* OpenCV version used: 4.40
* How did you install OpenCV? win_build_opencv.cmd script
* GoCV version used: latest dev version
* Go version: 1.14
* Did you run the `env.sh` or `env.cmd` script before trying to `go run` or `go build`? no

**Comment by golubaca** [comment]
Can you just use normal `go get gocv.io/x/gocv` which will clone inside `$GOPATH/src/gocv.io/x/gocv` and then `git checkout dev`?

**Comment by dvtkrlbs** [comment]
oh i forgot to close this
