### ISSUE TITLE
Missing drawMatches(...) function?

### ISSUE THREAD

**Issue by shanduur** [hybridgroup/gocv#716]
## Description

**This is a feature request, not typical issue.** </br>
As I have seen in the roadmap file, you are currently working on writing a wrapper around function (`drawMatches(...)`), however there is nothing inside dev branch that could suggest how much of the work is done. Is there any option to see the changes / progress anywhere? Will it be available in the nearest future (e.g. in the dev branch)?

## Steps to Reproduce

No steps.

## Your Environment

* Operating System and version: Pop!_OS 20.04 LTS
* OpenCV version used: 4.3.0
* How did you install OpenCV? make install
* GoCV version used: 0.23.0
* Go version: go1.14.4 linux/amd64
* Did you run the `env.sh` or `env.cmd` script before trying to `go run` or `go build`? No

**Comment by golubaca** [comment]
It is stated that there is work in progress for the whole `Drawing Function of Keypoints and Matches` and it takes multiple functions. Also, it is stated that `The following functions still need implementation` and `drawMatches` is listed. This means that no-one created that specific function.

**Comment by shanduur** [comment]
I started implementation of this in my [forked repo](https://github.com/Shanduur/gocv/tree/features2d/drawMatches). I will test it later this week and probably create a PR. If you have any suggestions or remarks, I would be grateful for them.

**Comment by shanduur** [comment]
Everything was looking good until first build. I keep getting error:
```
$ go run ./cmd/hello-sift/main.go /home/shanduur/Pictures/box.png /home/shanduur/Pictures/box_in_scene.png
# gocv.io/x/gocv
/usr/bin/ld: $WORK/b032/_x006.o: in function `_cgo_8120a8f807ea_Cfunc_DrawMatches':
/tmp/go-build/cgo-gcc-prolog:333: undefined reference to `DrawMatches'

$ go build ./cmd/hello-sift/main.go
# gocv.io/x/gocv
/usr/bin/ld: $WORK/b032/_x006.o: in function `_cgo_8120a8f807ea_Cfunc_DrawMatches':
/tmp/go-build/cgo-gcc-prolog:333: undefined reference to `DrawMatches'
```
[CMD](https://github.com/Shanduur/gocv/blob/features2d/drawMatches/cmd/hello-sift/main.go)
[Fork](https://github.com/Shanduur/gocv/tree/features2d/drawMatches)

Do any of you have an idea what's the problem?

**Comment by shanduur** [comment]
I fixed all the issues, most of them were caused by typos...

I created [Pull Request](https://github.com/hybridgroup/gocv/pull/720), hope it is working as it sould.

Output from new CMD:

![Screenshot from 2020-07-31 13-57-07](https://user-images.githubusercontent.com/32583062/89032867-da743e00-d335-11ea-9057-75f4a73c63e1.png)

**Comment by golubaca** [comment]
Just a note. As I mention in #707  OpenCV uses BGR instead of RGB. As you can see in that issue, colours was off. Take a look at [gocv.Rectangle](https://github.com/hybridgroup/gocv/blob/release/imgproc.go#L1286) code, you'll see that colour values are swapped before passing to C function. Can you make your function in `features2d.go` to behave like this, we need consistency.

**Comment by shanduur** [comment]
Issue #707 was posted by me, and I am now comprehensively testing, if this is the case. I swapped it, as you suggested. Thank you for your help!

**Comment by shanduur** [comment]
Can someone point me, why am I getting no lines? The result is like this:

![Screenshot from 2020-08-02 20-55-07](https://user-images.githubusercontent.com/32583062/89130094-836f9400-d502-11ea-84bd-57e9fdd1ddb7.png)

While code (new CMD) which is a direct port of code from [Feature Matching tutorial](https://docs.opencv.org/3.4/d5/d6f/tutorial_feature_flann_matcher.html) with changed SURF to SIFT, should output the result from tutorial?

![Result of the SURF feature matching using the distance ratio test](https://docs.opencv.org/3.4/Feature_FlannMatcher_Result_ratio_test.jpg)

Also there is a version of it with SIFT [here](https://opencv-python-tutroals.readthedocs.io/en/latest/py_tutorials/py_feature2d/py_matcher/py_matcher.html) that shows that output:

![Output](https://opencv-python-tutroals.readthedocs.io/en/latest/_images/matcher_flann.jpg)

**Comment by shanduur** [comment]
At this point I managed to achieve my goal. I hope the result is as it's supposed to be.

![Screenshot from 2020-08-04 19-38-52](https://user-images.githubusercontent.com/32583062/89326669-f7d53f00-d68a-11ea-8535-08c38b163c45.png)

**Comment by shanduur** [comment]
@golubaca @deadprogram may you take a look at pull request #720 and **failing test**? It isn't connected to function developed in this branch, yet the check fails randomly - in my opinion one of tests is not deterministic **OR** there is some problem baked in the test function itself.

**Comment by golubaca** [comment]
on my local machine, all tests passed. Sometimes appveyor fails randomly. Test that fails is `TestReadNetMemory` which belongs to dnn module and your test comes later.
