### ISSUE TITLE
There is a problem with blobFromImages regarding "scalefactor"

### ISSUE THREAD

**Issue by dschissler** [hybridgroup/gocv#717]
## Description
I'm running `./dnn-pose-detection 0 dnn-pose-detection-res/pose_iter_440000.caffemodel dnn-pose-detection-res/openpose_pose_coco.prototxt` and its outputting the following error message.

```
[ WARN:0] global /tmp/opencv/opencv-4.3.0/modules/videoio/src/cap_gstreamer.cpp (935) open OpenCV | GStreamer warning: Cannot query video position: status=0, value=-1, duration=-1
Start reading device: 0
terminate called after throwing an instance of 'cv::Exception'
  what():  OpenCV(4.3.0) /tmp/opencv/opencv-4.3.0/modules/dnn/src/dnn.cpp:333: error: (-2:Unspecified error) in function 'void cv::dnn::dnn4_v20200310::blobFromImages(cv::InputArrayOfArrays, cv::OutputArray, double, cv::Size, const Scalar&, bool, bool, int)'
> Scaling is not supported for CV_8U blob depth (expected: 'scalefactor == 1.0'), where
>     'scalefactor' is 0.00392157
> must be equal to
>     '1.0' is 1

SIGABRT: abort
```

## Steps to Reproduce
1. Setup Ubuntu 20.04.
2. Build the OpenCL from the directions on the homepage.
3. Run the ddn-pose-detection example with `./dnn-pose-detection 0 dnn-pose-detection-res/pose_iter_440000.caffemodel dnn-pose-detection-res/openpose_pose_coco.prototxt`
4. See the error.

I want to add that the facedetect and fingers algorithm works.  The dnn examples don't work.

## Your Environment
Ubuntu 20.04

```
Linux hostnamehere 5.4.0-26-generic #30-Ubuntu SMP Mon Apr 20 16:58:30 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

```
go version go1.14.5 linux/amd64
```

```
gocv version: 0.23.0
opencv lib version: 4.3.0
```

I install OpenCV via the make setup provided by gocv.io/x/gocv

I did not run `env.sh` or `env.cmd`.

**Comment by nibbleshift** [comment]
Try adding the code below before you call BlobFromImage:
```
 img.ConvertTo(&img, gocv.MatTypeCV32F)
```

**Comment by berak** [comment]
@nibbleshift, while this idea will work, the actual problem seems to be here:

https://github.com/hybridgroup/gocv/blob/6240320eed51651fa2be9cfd304605b7497f4b6f/dnn.cpp#L115

based on the ddepth flag, images should be converted to float (or not) internally, and this line overrides the default CV_32F.
so, the bad thing is, if we have a scalefactor of 1.0, ppl won't even realize, that they're sending CV_8U images into the network

**Comment by dschissler** [comment]
Hey everyone, this is far beyond me.  I haven't actually started programming in Go yet.  I was only researching the technologies for a passion project when I ran into this from the copy-pasted example.  My impression from reading past issues is that people have been running into this exact bug or a very similar one for quite a while.  It seems that some of the issues were simply closed due to inactivity.  If my assessment is correct then countless people have simply turned away from using this library after some of the examples didn't work.

**Comment by deadprogram** [comment]
Hello, everyone.

I just added this commit to the `dev` branch based on the comment from @berak which appears to have addressed the core issue.

I am going to mark this issue with "next-release" and close it once it makes it into our next update.

Thank you everyone!

**Comment by deadprogram** [comment]
This has now been released so closing. Thanks!
