### ISSUE TITLE
How to convert image.Image to Mat?

### ISSUE THREAD

**Issue by Nv7-GitHub** [hybridgroup/gocv#724]
## Description
I have an image.Image (go image format) in a variable. I want to convert it into a Mat to perform some processing on it, which is only available in OpenCV. I am trying to do this conversion in at most 5 ms, on an average laptop. How can I quickly convert this to a Mat?

## Your Environment

* Operating System and version:
MacOS 10.15.5
* GoCV version used:
The go.mod file has 1.13 in it, how do you find the version?
* Go version:
1.15

**Comment by golubaca** [comment]
90% of questions can be solved just by reading documentation. https://godoc.org/gocv.io/x/gocv#ImageToMatRGB
You can experiment with this function.

**Comment by Nv7-GitHub** [comment]
Oh wow! I was looking for InageToMat so I didn’t realize there was an InageToMatRGB. Thanks!
