### ISSUE TITLE
Add cv::approxPolyDP() bindings

### ISSUE THREAD

**Issue by littledot** [hybridgroup/gocv#73]
Hi,

I'm interested in adding `cv::approxPolyDP()` bindings to GoCV.

API: https://docs.opencv.org/3.4.0/d3/dc0/group__imgproc__shape.html#ga0012a5fdaea70b8a9970165d98722b4c
Source: https://github.com/opencv/opencv/blob/638a01a014cb1972a6ffa63755474ce89e3db9d8/modules/imgproc/src/approx.cpp#L675

Are you OK with this?

**Comment by deadprogram** [comment]
Yes, please, and thank you!

**Comment by deadprogram** [comment]
The latest release 0.9.0 includes this feature. Thank you for the code, I am now closing this issue.

**Comment by littledot** [comment]
Nice! Thank you!
