### ISSUE TITLE
calib3d.h:5:10: fatal error: opencv2/opencv.hpp: No such file or directory

### ISSUE THREAD

**Issue by Dontmindmes** [hybridgroup/gocv#730]
https://i.imgur.com/hDh9E3O.png

`# gocv.io/x/gocv
In file included from calib3d.cpp:1:
calib3d.h:5:10: fatal error: opencv2/opencv.hpp: No such file or directory
    5 | #include <opencv2/opencv.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
`

**Comment by deadprogram** [comment]
Hello @Dontmindmes looks like you need to install OpenCV 4.4.0 

Please see https://gocv.io/getting-started/windows/

**Comment by deadprogram** [comment]
Closing as duplicate.

**Comment by BryceWayne** [comment]
Terrible response. This is still a bug.
