### ISSUE TITLE
I want to use Gocv and CUDA on Windows

### ISSUE THREAD

**Issue by HaliComing** [hybridgroup/gocv#731]
## Description

I want to use Gocv and CUDA on Windows，But there are some problems when using CMake to compile Opencv.
```
CUDA compilation is disabled (due to only Visual Studio compiler supported on your platform).
```
Only supports MSVC, But opencv only supports MinGW. **So, I want to use gocv and msvc compiled opencv on Windows.**
Do you have solutions and solutions? thank you very much.
Do you have solutions and solutions? thank you very much.
Do you have solutions and solutions? thank you very much.
## Steps to Reproduce

1. Cmake WITH_CUDA=ON

## Your Environment

* Windows10
* OpenCV 4.4.0:
* How did you install OpenCV?
* GoCV version used:v0.24.0
* Go version:1.14

**Comment by abhikalitra** [comment]
https://github.com/golang/go/issues/20982

as of now golang/cgo doesn't support mscv

No easy solution for this.
