### ISSUE TITLE
Missing auto white balance property

### ISSUE THREAD

**Issue by JoshChristie** [hybridgroup/gocv#738]
Is there a way to enable/disable autobalance from VideoCapture? The C++/Python opencv versions have the property `CAP_PROP_AUTO_WB ` which achieves this. 

AFAIK there are only `VideoCaptureWhiteBalanceBlueU` and `VideoCaptureWhiteBalanceRedV`, but they don't work for the cameras I am testing.

**Comment by JoshChristie** [comment]
Switching the API backend to `V4L2` adds more ability to to control the properties. Created a PR #739 for it.

**Comment by OmriTreidel** [comment]
+1

**Comment by deadprogram** [comment]
This has now been released so closing. Thanks!
