### ISSUE TITLE
Add cv::arcLength() bindings

### ISSUE THREAD

**Issue by littledot** [hybridgroup/gocv#74]
Hi,

I'm interested in adding `cv::arcLength()` bindings to GoCV.

API: https://docs.opencv.org/3.4.0/d3/dc0/group__imgproc__shape.html#ga8d26483c636be6b35c3ec6335798a47c
Source: https://github.com/opencv/opencv/blob/ff190b1ef4bdf42af7c8d358ca6795bc906a1db4/modules/imgproc/src/shapedescr.cpp#L230

Are you OK with this?

**Comment by deadprogram** [comment]
That would be great. Thanks.

**Comment by littledot** [comment]
I looked at `FindContours()` and `ContourArea()` for guidance on how to implement contour-related API bindings and noticed that these APIs use type `image.Point` instead of `Mat`, which is typically used to plug `Input/OutputArray`. Would you mind explaining the reasoning behind this design?

**Comment by littledot** [comment]
I was reading the source code for `cv::findContours()` and noticed that in addition to `vector<vector<cv::Point>>`, it also allows `vector<cv::Mat>` and `vector<cv::UMat>` (https://github.com/opencv/opencv/blob/master/modules/imgproc/src/contours.cpp#L1891). 

Considering that contour-related APIs all accept `cv::Input/OutputArray`s, I was wondering if using more general types could reduce the amount of type conversions in GoCV's cgo code. My line of thinking is that since OpenCV decided to use general types like `cv::Mat` and `cv::UMat`, should we not also follow in OpenCV's footsteps and prefer `cv::Mat` and `cv::UMat` over more concrete types like `cv::Point`? (Do note that I am a beginner in OpenCV hence my line of thinking may be flawed ^_^!!! )

Here is a prototype I made using `gocv::Mats` and `vector<cv::Mat>` to do contour-related calculations.
```cpp
// gocv/imgproc.cpp
void CalcContoursAreaLength(Mat image, Mats* contours, Mat hierarchy, int mode, int method) {
    std::vector<cv::Mat> mats;
    cv::findContours(*image, mats, mode, method); // image -> "images/face-detect.jpg"
    
    Mat* goMats = new Mat[mats.size()];
    for(size_t i=0; i<mats.size(); i++){
        goMats[i] = &mats[i];
        float area = cv::contourArea(mats[i]);
        float length = cv::arcLength(mats[i], true);
        printf("area: %f len: %f\n", area, length); // "area: 127280.000000 len: 1436.828369"
    }
    
    contours->mats = goMats;
    contours->length = (int)mats.size();
}
```
It seems to work well. And if we use `Mat` here, it could simplify other bindings' implementation by replacing `gocv::Point` <-> `cv::Point` conversion with `gocv::Mat` <-> `cv::Mat` conversion, which is relatively trivial.

**Comment by littledot** [comment]
Actually, nevermind.

I realized that `cv::Mat` is just another concrete type that gets casted to `cv::InputArray`. If we wanted true generalization, we probably want `cv::InputArray` that is implemented as a go interface.

**Comment by deadprogram** [comment]
The @littledot PR is now in the `dev` branch. This issue will get closed next release.

**Comment by deadprogram** [comment]
The latest release 0.9.0 includes this code. Thanks again for your contribution @littledot now closing this issue.
