### ISSUE TITLE
How does GoCV PutText support Chinese？

### ISSUE THREAD

**Issue by opvexe** [hybridgroup/gocv#749]
for _, v := range points {
		gocv.Line(&mat, image.Point{
			X: v[0].X,
			Y: v[0].Y,
		}, image.Point{
			X: v[1].X,
			Y: v[1].Y,
		}, s.BorderColor, s.Thickness)
		// 标注圆点
		gocv.PutText(&mat,"." , image.Point{
			X: v[0].X,
			Y: v[0].Y,
		}, gocv.FontHersheySimplex, 1.5, RedColor, 8)
	}
	if len(s.Typ) != 0 {
		gocv.PutText(&mat,"中文",image.Point{
			X: points[0][0].X + 20,
			Y: points[0][0].Y + 40,
		}, gocv.FontHersheySimplex, 1.5, GreenColor, 6)
	}

**Comment by deadprogram** [comment]
According to this post, non-ascii character sets are not supported: https://answers.opencv.org/question/86997/how-can-i-put-text-on-image-using-opencv-puttext-function/

:crying_cat_face: sorry about that.

**Comment by opvexe** [comment]
> According to this post, non-ascii character sets are not supported: https://answers.opencv.org/question/86997/how-can-i-put-text-on-image-using-opencv-puttext-function/
> 
> 😿 sorry about that.

Thank you again. I have found another way to solve the problem of Chinese in the picture.

func (fb *TextBrush) DrawFontOnRGBA(rgba *image.RGBA, pt image.Point, content string) {
	var dy int
	lineSize := int(fb.TextWidth / int(fb.FontSize))

	// 计算行数以及拆解字符串
	lines := list.New()
	tl := fb.sliptString(content, lines, lineSize)
	dy = tl * int(fb.FontSize)

	c := freetype.NewContext()
	c.SetDPI(72)
	c.SetFont(fb.FontType)
	c.SetFontSize(fb.FontSize)
	c.SetClip(image.Rect(pt.X, pt.Y, pt.X+fb.TextWidth, pt.Y+dy))
	c.SetDst(rgba)
	c.SetSrc(fb.FontColor)

	intSize := int(fb.FontSize)

	var txtNext *list.Element
	for txt := lines.Front(); txt != nil; txt = txtNext {
		txtNext = txt.Next()
		t := txt.Value.(textLine)
		pt := freetype.Pt(pt.X, pt.Y+(t.Index+1)*intSize-int(c.PointToFixed(fb.FontSize))>>8)
		c.DrawString(t.Text, pt)
	}
}

**Comment by skytodmoon** [comment]
Greate！

**Comment by skytodmoon** [comment]
@shumintao I want to use your function, but I do not know how to import TextBrush? Can you help me?

**Comment by lz1998** [comment]
> > According to this post, non-ascii character sets are not supported: https://answers.opencv.org/question/86997/how-can-i-put-text-on-image-using-opencv-puttext-function/
> > 😿 sorry about that.
> 
> Thank you again. I have found another way to solve the problem of Chinese in the picture.
> 
> func (fb *TextBrush) DrawFontOnRGBA(rgba *image.RGBA, pt image.Point, content string) {
> var dy int
> lineSize := int(fb.TextWidth / int(fb.FontSize))
> 
> ```
> // 计算行数以及拆解字符串
> lines := list.New()
> tl := fb.sliptString(content, lines, lineSize)
> dy = tl * int(fb.FontSize)
> 
> c := freetype.NewContext()
> c.SetDPI(72)
> c.SetFont(fb.FontType)
> c.SetFontSize(fb.FontSize)
> c.SetClip(image.Rect(pt.X, pt.Y, pt.X+fb.TextWidth, pt.Y+dy))
> c.SetDst(rgba)
> c.SetSrc(fb.FontColor)
> 
> intSize := int(fb.FontSize)
> 
> var txtNext *list.Element
> for txt := lines.Front(); txt != nil; txt = txtNext {
> 	txtNext = txt.Next()
> 	t := txt.Value.(textLine)
> 	pt := freetype.Pt(pt.X, pt.Y+(t.Index+1)*intSize-int(c.PointToFixed(fb.FontSize))>>8)
> 	c.DrawString(t.Text, pt)
> }
> ```
> 
> }

What is freetype?
