### ISSUE TITLE
GetStructuringElement func could work as not expected

### ISSUE THREAD

**Issue by Lezh1k** [hybridgroup/gocv#75]
```
func GetStructuringElement(shape MorphShape, ksize image.Point) Mat {
	sz := C.struct_Size{
		height: C.int(ksize.X),
		width:  C.int(ksize.Y),
	}

	return Mat{p: C.GetStructuringElement(C.int(shape), sz)}
}
```
Here X used as height and Y as width. Sometimes it leads to unexpected result. 
For example old C++ code looks like this : 
`morphKernel = cv::getStructuringElement(cv::MORPH_RECT, cv::Size(9, 1));` 
but new gocv code should look like this : 
`morphKernel := gocv.GetStructuringElement(gocv.MorphRect, image.Point{1, 9})`

It's not issue, but it would be nice to add comment there.

**Comment by deadprogram** [comment]
That looks like an error to me. Height should be the `ksize.Y`, and width should be the `ksize.X`, would you agree?

**Comment by Lezh1k** [comment]
I don't think it's a critical error. Maybe somebody started to use this function and change will break something in their projects. So maybe it's better just to warn users. But of course it's up to you.

**Comment by deadprogram** [comment]
There were several occurances where the params were incorrect. They have all been fixed in the `dev` branch. I will close this issue once the next release goes out. Thank you @Lezh1k for pointing out this error.

**Comment by deadprogram** [comment]
The latest release 0.9.0 includes this code. Thanks again, now closing this issue.
