### ISSUE TITLE
Is cross platform compilation possible?

### ISSUE THREAD

**Issue by raiftekin** [hybridgroup/gocv#752]
Hi, I want compile my gocv code from amd64 to arm
Is it possible?

      env GOARCH=arm go build . 
      env CGO=1 CC=<arm_compiler> GOARCH=arm go build .

There are not working..

~Ubuntu18 - amd64

**Comment by deadprogram** [comment]
When CGo is concerned cross-compilation is usually impossible.

I would suggest doing the build inside a docker container.

Hope that helps!

**Comment by deadprogram** [comment]
Also see #702
