### ISSUE TITLE
Unable to fetch latest image from buffer

### ISSUE THREAD

**Issue by stunthamster** [hybridgroup/gocv#757]
I'm using GoCV to watch a UDP stream. I would expect that when I read the stream I would get whatever the latest image is; instead, I see buffering. I'm by no means an OpenCV expert, but reading the docs this isn't the behaviour I'd expect (However, more than happy to be told I'm wrong)

## Description
Given the example code below, I would expect to receive the latest frame from the UDP stream every second. Instead, it seems to buffer, so instead of the latest frame, I get the next transmitted frame. 

```
func main() {

	outputDir := "/Users/mduffy/Downloads/test"
	stream, _ := gocv.OpenVideoCapture("udp://10.0.1.185:6008?overrun_nonfatal=1")
	defer stream.Close()

	ticker := time.NewTicker(1 * time.Second)
	done := make(chan bool)

	go func() {
		for {
			select {
			case <-done:
				return
			case t := <-ticker.C:
				img := gocv.NewMat()
				stream.Read(&img)
				filename := fmt.Sprintf("%v/file-%v.jpg", outputDir, t.UnixNano())
				gocv.IMWrite(filename, img)
			}
		}
	}()
	select {}
}

```

## Your Environment
* Operating System and version:
MacOS or Linux; I can reproduce on both

* OpenCV version used:
4.4.0_2

* How did you install OpenCV?
Homebrew 

* GoCV version used:
v0.24.0

* Go version:
go version go1.15.2 darwin/amd64

* Did you run the `env.sh` or `env.cmd` script before trying to `go run` or `go build`? 
No

**Comment by stunthamster** [comment]
Interestingly, I've just tried using RTP (rtp://10.0.1.185:6009?overrun_nonfatal=1) instead of UDP and I'm seeing the same issue.

**Comment by deadprogram** [comment]
I would expect to see whatever buffering that is introduced by ffmpeg/gstreamer which are what opencv uses when you specify udp/rtp/http stream. You might want to write some Go code to receive the UDP packets and then use GoCV to decode it. You probably also can adjust some of the capture params for this purpose, you might want to try that also.

Hope that helps!

**Comment by golubaca** [comment]
You are reading frame once every one second. If your stream have more then 1 fps,you are creating buffer. Solution is to let opencv decide when to read. You can achieve this by using loop that has no time attached, and later on display newest frame based on time you selected.
Sudo code would be to use loop and use frame.Read() and store to a variable that can be accesed by display code,and when timer ticks,display that frame.

**Comment by stunthamster** [comment]
Cheers folks - some sensible suggestions. It sounds like this is not a GoCV issue, so I'll go ahead and close the issue. Again, thanks for the suggestions @deadprogram and @golubaca .
