### ISSUE TITLE
Installation on ArchLinux

### ISSUE THREAD

**Issue by etiennedaspe** [hybridgroup/gocv#76]
Hello,

I would like to run gocv on my machine running with an ArchLinux distrib.

The Makefile is compatible only with Debian based distrib, so if you know the equivalent dependencies in Arch repo it would be helpful.

**Comment by Lezh1k** [comment]
@etiennedaspe  I've just installed opencv with pacman and everything started to work.

**Comment by etiennedaspe** [comment]
Thanks, it's easier than I thought!
