### ISSUE TITLE
'SIFT' is not a member of 'cv'

### ISSUE THREAD

**Issue by skreimeyer** [hybridgroup/gocv#764]
## Description
After attempting to validate an install of gocv, `go run ./cmd/version/main.go` returns an error:

```
In file included from features2d.cpp:1:
features2d.h:23:21: error: ‘SIFT’ is not a member of ‘cv’
   23 | typedef cv::Ptr<cv::SIFT>* SIFT;
      |                     ^~~~
features2d.h:23:21: error: ‘SIFT’ is not a member of ‘cv’
features2d.h:23:25: error: template argument 1 is invalid
   23 | typedef cv::Ptr<cv::SIFT>* SIFT;
      |                         ^
... error snipped for brevity ...
features2d.cpp: In function ‘KeyPoints SIFT_Detect(SIFT, Mat)’:
features2d.cpp:487:9: error: base operand of ‘->’ is not a pointer
  487 |     (*d)->detect(*src, detected);
      |         ^~
features2d.cpp: In function ‘KeyPoints SIFT_DetectAndCompute(SIFT, Mat, Mat, Mat)’:
features2d.cpp:504:9: error: base operand of ‘->’ is not a pointer
  504 |     (*d)->detectAndCompute(*src, *mask, detected, *desc);
      |         ^~
```

I think this may be because the system version of opencv (latest RPM is v.4.2) is not compatible with the source used by gocv (v.4.5). Since SIFT was moved out of a "nonfree" module between 4.2 and 4.5, I assume this is what the problem is.

## Steps to Reproduce
1. `go get -u -d gocv.io/x/gocv`
2. `make install` -> error

Also:

1. `go get -u -d gocv.io/x/gocv`
2. `make deps`
3. `make download`
4. `make sudo_install`
5. `go run ./cmd/version/main.go` -> error

`dnf remove opencv` and then installing did not change the result.

Building opencv-4.5 from source with cmake did not make a difference. I'm not a C++ guy, so I'm not sure if there's something in the makefile that links the build against the opencv/opencv_contrib version blessed by the OS package manager, but that would make sense to me.

## Your Environment
Fedora 32 / x64 arch
system opencv-4.2

**Comment by topherbullock** [comment]
I had a similar issue, but only when using the latest release(`v0.25.0`) of `gocv.io/x/gocv` in my project via `go.mod`:

```gomod
require (
// ...
  gocv.io/x/gocv v0.25.0
// ...
)
```

`go run ./cmd/version/main.go` was working from `$GOPATH/gocv.io/x/gocv/`, where I had checked out an earlier version : `v0.23.0` @ df73d544675c731b2197d46622224839e1af07a6

` go mod edit -replace gocv.io/x/gocv=$GOPATH/gocv.io/x/gocv` resolved this issue for me, so it's possible something is broken in `v0.25.0`.

**Comment by deadprogram** [comment]
Yes, the latest GoCV requires the latest OpenCV.

**Comment by skreimeyer** [comment]
This is closed? Can I at least get a recommendation on what to do? I've uninstalled and built cv4.5 from source and from this project's makefile with no success.

**Comment by deadprogram** [comment]
It appears from message that you are compile/linking against older OpenCV. The most recent release of GoCV requires OpenCV 4.5+ due to SIFT moving from contrib into main OpenCV repo. If you have installed both OpenCV version but they are in different locations you can build against 4.5 by using a custom env instead of relying on pkg-config.

Please see https://github.com/hybridgroup/gocv#custom-environment for more info.

Hopefully that helps.

**Comment by skreimeyer** [comment]
OK, tried the custom environment tag, but that threw an error about missing files (`features2d.cpp` and others). I probably did not pass the correct flags, but I don't have any intelligent guesses as to what I should tweak, so I tried to reinstall.
`dnf remove opencv`
then I removed anything found with `locate opencv`
`cd ~/go/src/gocv.io/x/gocv && make install`

which led to:

```
go run ./cmd/version/main.go
# pkg-config --cflags  -- opencv4
Package opencv4 was not found in the pkg-config search path.
Perhaps you should add the directory containing `opencv4.pc'
to the PKG_CONFIG_PATH environment variable
Package 'opencv4', required by 'virtual:world', not found
pkg-config: exit status 1
make: *** [Makefile:208: verify] Error 2
```

which surprised me because the same error occurs even after setting the path to `opencv.pc` to that environment variable.

```
$ echo $PKG_CONFIG_PATH 
/usr/lib64/pkgconfig/opencv.pc
```

I think there maybe some differences between Fedora's environment and Ubuntu (the latter being referenced in your README, so I'm assuming that's the environment the developers [or most users] are using.) I'll try try to install Ubuntu and then install gocv and report if that solves the problem.

**Comment by skreimeyer** [comment]
Using Ubuntu 20.04, I am able to install following the instructions on the README without issue.

There must be a difference in the environments resulting in linking the opencv version which is the default for Fedora package manager (4.2). It's a bit beyond my expertise to discover what that might be.

Thank you for your help!

**Comment by wlwatkins** [comment]
> Yes, the latest GoCV requires the latest OpenCV.

if the latest version of OpenCV (i.e. 4.6) then maybe the windows installer should be updated as it installs opencv 4.3 (I'm trying out right now by just changing the 4.3 to 4.6 in `win_build_opencv.cmd` but I do't think this will be as simple as that....

edit: Oh I see that latest github release branch has version 4.6 however, this is not what is downloaded when doing `go get -u -d gocv.io/x/gocv`

**Comment by deadprogram** [comment]
Also keep in mind that you need to use a specific version of OpenCV with any version of GoCV.

See https://github.com/hybridgroup/gocv/tags for which GoCV goes with which OpenCV version.
