### ISSUE TITLE
I encountered this error when followed steps of installation for mac osx, "imgproc.cpp:61:28: error: expected '(' for function-style cast or type construction"

### ISSUE THREAD

**Issue by n1tz53** [hybridgroup/gocv#77]

**Comment by bjorand** [comment]
I encouter the same error. Do not forget to `source ./env.sh` on macOS (https://github.com/hybridgroup/gocv#how-to-go-buildgo-run-your-code).

**Comment by n1tz53** [comment]
thanks, it is sorted now.
