### ISSUE TITLE
Get Mat Channels

### ISSUE THREAD

**Issue by kmuchmore** [hybridgroup/gocv#78]
In python and c++ I can get the height, width, and channels which is the whole shape of the mat. Maybe I just missed it but I can only figure out how to get the rows and cols of the Mats in gocv, how would I access the channels?

I see in the RoadMap it says "Structural Analysis and Shape Descriptors" but I'm not sure if channels would fall under this because you already have rows and columns.

Thanks

**Comment by deadprogram** [comment]
Hi @kmuchmore perhaps you are looking to determine the Channels() for a particular Mat, which I have just added to the `dev` branch:

https://github.com/hybridgroup/gocv/commit/8cfe04b1a69772579502eb265fca1d2c64f14cbd

**Comment by kmuchmore** [comment]
That's exactly what I was looking for. Thank you!
