### ISSUE TITLE
Support LineType in gocv.Circle, gocv.Rectangle and gocv.FillPoly

### ISSUE THREAD

**Issue by renewboy** [hybridgroup/gocv#787]
The `LineType` is very useful to render the shapes with antialiasing. Is there any plan to support this parameter?

**Comment by golubaca** [comment]
Sure, it can be done with `FunctionWithParams` (e.g. `CircleWithParams(img *Mat, center image.Point, radius int, c color.RGBA, thickness, lineType, shift int )`). I can start working on this as soon as I can.

**Comment by renewboy** [comment]
Thanks a million!!

**Comment by mbalayil** [comment]
Please take a look at my PR.

**Comment by deadprogram** [comment]
Released in v0.28 so now closing. Thanks!
