### ISSUE TITLE
findContours with hierarchy parameter

### ISSUE THREAD

**Issue by tbruyelle** [hybridgroup/gocv#793]
Currently `gocv.FindContours` is bound to a convenient version of `cv::FindContours` without the `hierarchy` parameter [1]. This missing parameter is very useful when you want to group contours together [2]. 

Could you consider supporting the full version of `cv::FindContours` ? [3]

[1] https://docs.opencv.org/3.3.0/d3/dc0/group__imgproc__shape.html#ga95f5b48d01abc7c2e0732db24689837b
[2] https://docs.opencv.org/master/d9/d8b/tutorial_py_contours_hierarchy.html
[3] https://docs.opencv.org/3.3.0/d3/dc0/group__imgproc__shape.html#ga17ed9f5d79ae97bd4c7cf18403e1689a

**Comment by deadprogram** [comment]
Hello @tbruyelle please see https://github.com/hybridgroup/gocv/blob/release/CONTRIBUTING.md#how-to-add-a-function-from-opencv-to-gocv

Basically, sounds like a `FindContoursWithParams()` func is needed, correct?

**Comment by tbruyelle** [comment]
Thanks for the link, I agree with the function name. I'll work on that.

**Comment by tbruyelle** [comment]
Hello @deadprogram , in case you didn't notice, I've created a PR on the subject :arrow_up: 
Have a good day

**Comment by deadprogram** [comment]
This has now been released, so I will close. Thank you!
