### ISSUE TITLE
Error while building MJPEG-Streamer

### ISSUE THREAD

**Issue by Shashwatsh** [hybridgroup/gocv#8]
i get this error while building ```https://github.com/hybridgroup/gocv/blob/master/cmd/mjpeg-streamer/main.go```

``` personal-surveillance go build
# github.com/Shashwatsh/personal-surveillance
./main.go:49:14: cannot assign *gocv.VideoCapture to webcam (type gocv.VideoCapture) in multiple assignment
```
any ideas?

**Comment by deadprogram** [comment]
Hi @Shashwatsh thanks for pointing that out. This commit https://github.com/hybridgroup/gocv/commit/32f736b3d516716d09d6a35298b4e780bc3307eb should correct that for you, and everyone else.

**Comment by deadprogram** [comment]
I will now close this issue, please reopen if needed. Thank you!
