### ISSUE TITLE
Installation Error in Ubuntu 18.04

### ISSUE THREAD

**Issue by hiteshhedwig** [hybridgroup/gocv#810]
I was trying to install gocv. While i have successfully installed go. General Command output goes like:

`go version` -> `go version go1.16 linux/amd64`
`which go` -> `/usr/local/go/bin/go`
..

Paths are initialized as follows :
`export $GOROOT=/usr/local/go`
`export PATH=$PATH:$GOROOT/bin`

## Description

When i follow the documentation guidelines. And type `sudo make install`. Around near 52% of build. This happens.

```
/tmp/opencv/opencv-4.5.1/modules/imgcodecs/src/grfmt_jpeg2000_openjpeg.cpp:22:10: error: ‘OPJ_CLRSPC_CMYK’ was not declared in this scope
     case OPJ_CLRSPC_CMYK:
          ^~~~~~~~~~~~~~~
/tmp/opencv/opencv-4.5.1/modules/imgcodecs/src/grfmt_jpeg2000_openjpeg.cpp:22:10: note: suggested alternative: ‘OPJ_CLRSPC_SYCC’
     case OPJ_CLRSPC_CMYK:
          ^~~~~~~~~~~~~~~
          OPJ_CLRSPC_SYCC
/tmp/opencv/opencv-4.5.1/modules/imgcodecs/src/grfmt_jpeg2000_openjpeg.cpp:26:10: error: ‘OPJ_CLRSPC_EYCC’ was not declared in this scope
     case OPJ_CLRSPC_EYCC:
          ^~~~~~~~~~~~~~~
/tmp/opencv/opencv-4.5.1/modules/imgcodecs/src/grfmt_jpeg2000_openjpeg.cpp:26:10: note: suggested alternative: ‘OPJ_CLRSPC_SYCC’
     case OPJ_CLRSPC_EYCC:
          ^~~~~~~~~~~~~~~
          OPJ_CLRSPC_SYCC
```
```
CMakeFiles/Makefile2:3735: recipe for target 'modules/imgcodecs/CMakeFiles/opencv_imgcodecs.dir/all' failed
make[1]: *** [modules/imgcodecs/CMakeFiles/opencv_imgcodecs.dir/all] Error 2
Makefile:162: recipe for target 'all' failed
make: *** [all] Error 2
/usr/local/go/src/gocv.io/x/gocv
go clean --cache
rm -rf /tmp/opencv
/bin/sh: 1: go: not found
go run ./cmd/version/main.go
make: go: Command not found
Makefile:209: recipe for target 'verify' failed
make: *** [verify] Error 127

```
## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

* Operating System and version: Ubuntu 18.04
* OpenCV version used: 4.5.1
* How did you install OpenCV? Using pip
* GoCV version used: 0.26.0
* Go version: 1.16 
* Did you run the `env.sh` or `env.cmd` script before trying to `go run` or `go build`?

**Comment by deadprogram** [comment]
Looks like you are missing the dependency for jpeg2000 in your installation. 

You probably need to run `sudo apt-get install -y libopenjp2-7-dev` or something like that.

Hope that helps!
