### ISSUE TITLE
CV_32FC2和vectr<Point2f)> | How to convert from Mat  CV_32FC2 to Point2fVector?

### ISSUE THREAD

**Issue by workyu** [hybridgroup/gocv#818]
std::vector<Point2f> obj;
std::vector<Point2f> scene;

for( int i = 0; i < good_matches.size(); i++ )
  {
    obj.push_back( keypoints_object[ good_matches[i].queryIdx ].pt );
    scene.push_back( keypoints_scene[ good_matches[i].trainIdx ].pt );
  }
  现在需要把obj和scene变成CV_32FC2格式的mat,这个应该如何用gocv实现

**Comment by deadprogram** [comment]
Hello, @workyu 

According to https://stackoverflow.com/a/23585237 the conversion itself should be straightforward.

To be able to do with GoCV, a new function will be needed such as `NewPoint2fVectorFromMat()`. This function would be similar to https://pkg.go.dev/gocv.io/x/gocv#NewPoint2fVectorFromPoints but probably event simpler implementation.

We would be very happy to receive a pull request that added this function! :)

---

你好@workyu

根据https://stackoverflow.com/a/23585237，转换本身应该很简单。

为了能够使用GoCV，将需要一个新功能，例如“ NewPoint2fVectorFromMat（）”。 此功能类似于https://pkg.go.dev/gocv.io/x/gocv#NewPoint2fVectorFromPoints，但可能是事件更简单的实现。

我们很高兴收到添加了此功能的拉取请求！ :)

请原谅我需要使用自动翻译。 我希望信息是明确的。

**Comment by workyu** [comment]
> 你好@workyu
> 
> 根据https://stackoverflow.com/a/23585237，转换本身应该很简单。
> 
> 为了能够使用GoCV，将需要一个新功能，例如`NewPoint2fVectorFromMat()`。此功能类似于[https://pkg.go.dev/gocv.io/x/gocv#NewPoint2fVectorFromPoints，](https://pkg.go.dev/gocv.io/x/gocv#NewPoint2fVectorFromPoints)但可能更简单地实现了事件。
> 
> 我们很高兴收到添加了此功能的拉取请求！:)
> 
> 你好@workyu
> 
> 根据[https://stackoverflow.com/a/23585237，转换本身应该很简单。](https://stackoverflow.com/a/23585237%EF%BC%8C%E8%BD%AC%E6%8D%A2%E6%9C%AC%E8%BA%AB%E5%BA%94%E8%AF%A5%E5%BE%88%E7%AE%80%E5%8D%95%E3%80%82)
> 
> 为了能够使用GoCV，将需要一个新功能，例如“NewPoint2fVectorFromMat（）”。功能此类似于[https://pkg.go.dev/gocv.io/x/gocv#NewPoint2fVectorFromPoints，但可能是事件更简单的实现。](https://pkg.go.dev/gocv.io/x/gocv#NewPoint2fVectorFromPoints%EF%BC%8C%E4%BD%86%E5%8F%AF%E8%83%BD%E6%98%AF%E4%BA%8B%E4%BB%B6%E6%9B%B4%E7%AE%80%E5%8D%95%E7%9A%84%E5%AE%9E%E7%8E%B0%E3%80%82)
> 
> 我们很高兴收到添加了此功能的拉取请求！:)
> 
> 请原谅我需要使用自动翻译。我希望信息是明确的。

请问预计什么时候添加"NewPoint2fVectorFromMat（）"

**Comment by deadprogram** [comment]
Hello @workyu please see https://github.com/hybridgroup/gocv/pull/842 that I have just added.

您好@workyu，请参阅我刚刚添加的https://github.com/hybridgroup/gocv/pull/842。

**Comment by deadprogram** [comment]
Released in v0.28 so now closing. Thanks!
