### ISSUE TITLE
OpenCV does not generate the pkgconfig during build

### ISSUE THREAD

**Issue by mpieczaba** [hybridgroup/gocv#819]
## Description
When I run the `make build` command, I get the following error:
```
# pkg-config --cflags  -- opencv4
Package opencv4 was not found in the pkg-config search path.
Perhaps you should add the directory containing `opencv4.pc'
to the PKG_CONFIG_PATH environment variable
Package 'opencv4', required by 'virtual:world', not found
pkg-config: exit status 1
```
This error may be caused by a typo in the Makefile in [this line](https://github.com/hybridgroup/gocv/blob/7d6aabe177057499dfcedbb542bfc3577cc2e717/Makefile#L92). 

## Steps to Reproduce
1. In [this line](https://github.com/hybridgroup/gocv/blob/7d6aabe177057499dfcedbb542bfc3577cc2e717/Makefile#L92) flag `-DOPENCV_GENERATE_PKGCONFIG=ON` should be split into `-D OPENCV_GENERATE_PKGCONFIG=ON`. 
2. There are more similar typos in the Makefile. For example in [this line](https://github.com/hybridgroup/gocv/blob/7d6aabe177057499dfcedbb542bfc3577cc2e717/Makefile#L125) and [here](https://github.com/hybridgroup/gocv/blob/7d6aabe177057499dfcedbb542bfc3577cc2e717/Makefile#L147). In my opinion, these typos should be also corrected.

## Your Environment
* Operating System and version: Alpine Linux running in the docker image
* OpenCV version used: 4.5.1
* How did you install OpenCV? With the `make install` command
* GoCV version used: v0.26.0
* Go version: 1.16
* Did you run the `env.sh` or `env.cmd` script before trying to `go run` or `go build`? Nope

**Comment by mpieczaba** [comment]
Next version of GoCV has been released and this crucial issue for (not only) docker users hasn't been fixed yet. 
Should I open a new pull request?

**Comment by deadprogram** [comment]
Hello @mpieczaba I use that exactly Makefile on Ubuntu without problem, so I wonder if there is some difference in Alpine? What do you think?

**Comment by mpieczaba** [comment]
> 
> 
> Hello @mpieczaba I use that exactly Makefile on Ubuntu without problem, so I wonder if there is some difference in Alpine? What do you think?

Yeah, I've got plenty of issues because of the musl and glibc incompatibilities, maybe it's another one. I will probably move to glibc-based distro.

**Comment by mpieczaba** [comment]
@deadprogram So I moved my project to the official GoCV docker image. It takes about 2.3 GB of space but it'll be much easier for me to be up to date with all of the changes in your code and OpenCV updates. 

All my issues were probably caused by musl and glibc incompatibilities. OpenCV seems to lack in musl support. :(

After days of trying to compile my project I agreed to this compromise. Thanks for your response and I think that it's a good time to close this issue.
