### ISSUE TITLE
OpenCV 4.5.2 Support?

### ISSUE THREAD

**Issue by Nv7-GitHub** [hybridgroup/gocv#820]
I just updated OpenCV using `brew upgrade opencv`. Now, it's not working. It is searching for OpenCV 4.5.1_3, but I have OpenCV 4.5.2. What do I do to support OpenCV 4.5.2?

**Comment by Nv7-GitHub** [comment]
For people having this issue, I found [this older formula for OpenCV](https://raw.githubusercontent.com/Homebrew/homebrew-core/9c03502bf100fa252640382e90bb4611cafe83d9/Formula/opencv.rb). I downloaded it and saved it to a file called `opencv.rb`. Then, I used 
```bash
brew install ./opencv.rb
``` 
to install OpenCV `4.5.1_3`.
Finally, I used
```bash
brew pin opencv
```
To prevent homebrew from upgrading OpenCV when I run 
```bash
brew upgrade
```
Once OpenCV 4.5.2 is supported, you can run 
```bash
brew unpin opencv
brew upgrade opencv
```
To get the newer version.

**Comment by deadprogram** [comment]
Please see https://github.com/hybridgroup/gocv/pull/822

**Comment by deadprogram** [comment]
This has now been released so closing. Thanks!
