### ISSUE TITLE
Question: Point in Polygon Test workaround

### ISSUE THREAD

**Issue by wilk3ns** [hybridgroup/gocv#838]
Hey people!

Is there any way to use Point Polygon Test in gocv? If not, is there an alternative

in c++ there is a cv::pointPolygonTest and in Python there is cv2.pointPolygonTest

What is the gocv alternative?

**Comment by deadprogram** [comment]
Please see https://github.com/hybridgroup/gocv/blob/release/CONTRIBUTING.md#something-you-wantneed-from-opencv-does-not-appear-to-be-in-gocv

We would be very happy to accept a PR that added this function!

**Comment by mbalayil** [comment]
I have raised a PR. Please take a look.

**Comment by deadprogram** [comment]
Released in v0.28 so now closing. Thanks!
