### ISSUE TITLE
Install at WSL 2 Win 10

### ISSUE THREAD

**Issue by hasanAjsf** [hybridgroup/gocv#839]
Can I install `gocv` at Ubunto WSL 2 system installed at Windows 10
I found it not smooth to cd into `cd $GOPATH/src/gocv.io/x/gocv` as per your documentation, so thought to ask before I continue.
```
hajsf@AIS-DM-YOUSEF-L:~$ go get -u -d gocv.io/x/gocv
hajsf@AIS-DM-YOUSEF-L:~$ cd $GOPATH/src/gocv.io/x/gocv
-bash: cd: /src/gocv.io/x/gocv: No such file or directory
hajsf@AIS-DM-YOUSEF-L:~$ ls
Downloads  data  go  immuadmin  immuclient  immudb  token  token_admin
hajsf@AIS-DM-YOUSEF-L:~$ cd go
hajsf@AIS-DM-YOUSEF-L:~/go$ ls
pkg
hajsf@AIS-DM-YOUSEF-L:~/go$ cd pkg
hajsf@AIS-DM-YOUSEF-L:~/go/pkg$ ls
mod  sumdb
hajsf@AIS-DM-YOUSEF-L:~/go/pkg$ cd mod
hajsf@AIS-DM-YOUSEF-L:~/go/pkg/mod$ ls
cache  gocv.io
hajsf@AIS-DM-YOUSEF-L:~/go/pkg/mod$ cd gocv.io/x/gocv
-bash: cd: gocv.io/x/gocv: No such file or directory
hajsf@AIS-DM-YOUSEF-L:~/go/pkg/mod$ cd gocv.io
hajsf@AIS-DM-YOUSEF-L:~/go/pkg/mod/gocv.io$ ls
x
hajsf@AIS-DM-YOUSEF-L:~/go/pkg/mod/gocv.io$ cd x
hajsf@AIS-DM-YOUSEF-L:~/go/pkg/mod/gocv.io/x$ ls
gocv@v0.27.0
hajsf@AIS-DM-YOUSEF-L:~/go/pkg/mod/gocv.io/x$ cd gocv@v0.27.0
hajsf@AIS-DM-YOUSEF-L:~/go/pkg/mod/gocv.io/x/gocv@v0.27.0$ ls
```

![image](https://user-images.githubusercontent.com/46838626/116688399-4ec03880-a9bf-11eb-851d-075c75d98c68.png)

**UPDATE**

It was installed correctly:
![image](https://user-images.githubusercontent.com/46838626/116692325-d8bed000-a9c4-11eb-8021-fef7d0a2e560.png)

But failed to open the camera:

![image](https://user-images.githubusercontent.com/46838626/116692435-06a41480-a9c5-11eb-92e5-80291b259aae.png)

**UPDATE 2**
I tried to cross compile it to Windows by running:
```
$ GOOS=windows GOARCH=amd64 CGO_ENABLED=1 CC=x86_64-w64-mingw32-gcc CXX=x86_64-w64-mingw32-g++ go build -ldflags "-H windowsgui" hasan.cv
```
After installing the following dependencies:
```
$ sudo apt-get install binutils-mingw-w64
$ sudo apt-get install gcc-multilib
$ sudo apt-get install gcc-mingw-w64
$ sudo apt install g++-mingw-w64-x86-64
```

But I got:
```
# gocv.io/x/gocv
In file included from calib3d.cpp:1:
calib3d.h:5:10: fatal error: opencv2/opencv.hpp: No such file or directory
    5 | #include <opencv2/opencv.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

**Comment by BryceWayne** [comment]
Same error with goCV on Win10. I think this is not linking libs or is a go env flag issue??? 

![image](https://user-images.githubusercontent.com/35088752/118378019-a943c200-b585-11eb-95aa-306ca4176c0a.png)

**Comment by deadprogram** [comment]
I have never tried to install using WSL. The Windows build is not based on WSL, so I would be surprised if it would work.

For specifics of how we build for our the Windows continuous integration server, please see https://github.com/hybridgroup/gocv/blob/release/appveyor.yml#L18-L36 for the build steps, and also see https://github.com/hybridgroup/gocv/blob/release/win_build_opencv.cmd

**Comment by golubaca** [comment]
You are using gui which are not yet supported on WSL, and I think that the error you are getting is there. You can see that it can't init GTK backend. Try without gui, just open camera and read frames.

**Comment by hasanAjsf** [comment]
> Try without gui, just open camera and read frames

I got
```[ WARN:0] global /tmp/opencv/opencv-4.5.2/modules/videoio/src/cap_v4l.cpp (890) open VIDEOIO(V4L2:/dev/video0): can't open camera by index```

The code I tried is:
```go
package main

import (
	"gocv.io/x/gocv"
)

func main() {
	webcam, _ := gocv.VideoCaptureDevice(0)

	img := gocv.NewMat()

	for {
		webcam.Read(&img)
	}
}
```

**Comment by hasanAjsf** [comment]
I found it is related to [this](https://github.com/microsoft/WSL/issues/2195) issue, as USB/devices not yet supported at WSL2

**Comment by lukaswozniak** [comment]
Hi, I see that you tried to crosscompile from linux to windows. I faced the same issue, and managed to solve it. I created docker image that does exactly that: https://hub.docker.com/r/lukaswozniak/gocv-windows-crosscompile
