### ISSUE TITLE
gocv.Dilate causing segmentation fault

### ISSUE THREAD

**Issue by chand1012** [hybridgroup/gocv#847]
## Description

I am writing a function that takes in an image as a byte slice and returns another byte slice with dilated and eroded horizontal lines. Here is the function as currently written.

```go
func FixBrokenLinesH(buffer []byte) []byte {
	img, err := gocv.IMDecode(buffer, gocv.IMReadGrayScale)

	if err != nil {
		log.Fatal(err)
	}

	kernel := gocv.Ones(1, 20, gocv.MatTypeCV8U)

	var dImg *gocv.Mat
	var eImg *gocv.Mat

	gocv.Dilate(img, dImg, kernel)
	gocv.Erode(*dImg, eImg, kernel)

	return eImg.ToBytes()
}
```

When I try to call the function in my code, it returns this error:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x504b06]

goroutine 1 [running]:
gocv.io/x/gocv.Dilate.func1(0x26b2fe0, 0x0, 0x0, 0x0, 0x0, 0x26b2dd0, 0x0, 0x0, 0x0)
        /home/chandler/go/pkg/mod/gocv.io/x/gocv@v0.27.0/imgproc.go:268 +0x26
gocv.io/x/gocv.Dilate(0x26b2fe0, 0x0, 0x0, 0x0, 0x0, 0x26b2dd0, 0x0, 0x0, 0x0)
        /home/chandler/go/pkg/mod/gocv.io/x/gocv@v0.27.0/imgproc.go:268 +0x8b
github.com/chand1012/project/image_correction.FixBrokenLinesH(0xc0006da000, 0x3606, 0x4000, 0x740ae4, 0x3, 0xc0006da000)
        /home/chand1012/projects/project/image_correction/image.go:23 +0x14e
main.main()
        /home/chand1012/projects/project/test_program/main.go:39 +0x387
exit status 2
```

The image is a greyscale image, here is the one I am trying to use for initial testing.

![test](https://user-images.githubusercontent.com/3521582/119213875-63f52800-ba90-11eb-8bb9-fd779817415f.jpg)

I found [this](https://stackoverflow.com/a/43863448/5178731) StackOverflow post with some Python code that I was trying to accomplish with Go.

## Your Environment

* Operating System and version: Ubuntu 20.04 LTS WSL2
    * Output of `uname -a`: `Linux Chandler-Desktop 5.4.72-microsoft-standard-WSL2 #1 SMP Wed Oct 28 23:40:43 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux` 
* OpenCV version used: 4.5.1
* OpenCV installed from source 4.5.1 tar.gz
* GoCV version used: v0.27.0
* Go version: 1.16.4

**Comment by deadprogram** [comment]
This code is not correct:

```go
        var dImg *gocv.Mat
	var eImg *gocv.Mat
```

If you look at the various examples of using you can see that you need to create the `Mat` in order to receive the return data. Try this instead:

```
dImg := gocv.NewMat()
defer dImg.Close()

eImg := gocv.NewMat()
defer eImg.Close()
```

and then pass the params to your functions as `&dImg` and `&eImg`.

**Comment by chand1012** [comment]
That fixed it, thanks!
