### ISSUE TITLE
Installation failed on maxOS

### ISSUE THREAD

**Issue by jelech** [hybridgroup/gocv#859]
Run `go get gocv.io/x/gocv`

occur
```sh
  # gocv.io/x/gocv
  In file included from video.cpp:1:
  ./video.h:15:21: error: no member named 'Tracker' in namespace 'cv'
  ./video.h:16:21: error: no member named 'TrackerMIL' in namespace 'cv'
  ./video.h:17:21: error: no member named 'TrackerGOTURN' in namespace 'cv'
  video.cpp:53:14: error: member reference type 'int' is not a pointer
  video.cpp:59:25: error: member reference type 'int' is not a pointer
  video.cpp:68:28: error: no member named 'TrackerMIL' in namespace 'cv'
```

Is there anything I did wrong?
how do I do next?

**Comment by deadprogram** [comment]
Looks like you are trying to use a version of GoCV that does not match whatever version of OpenCV you have installed.

**Comment by jelech** [comment]
> Looks like you are trying to use a version of GoCV that does not match whatever version of OpenCV you have installed.

Thank you for your reply.
`brew info opencv` showing the version of opencv is 4.5.0

Is there any version of GoCV I can use?

**Comment by jelech** [comment]
> > Looks like you are trying to use a version of GoCV that does not match whatever version of OpenCV you have installed.
> 
> Thank you for your reply.
> `brew info opencv` showing the version of opencv is 4.5.0
> 
> Is there any version of GoCV I can use?

After update opencv version, it works.
