### ISSUE TITLE
imencode: low performance due to datacopies.

### ISSUE THREAD

**Issue by sashas-anyvision** [hybridgroup/gocv#867]
## Description
Currently IMEncode implemented the following way:

In Image_IMEncode std::vector is allocated and filled by cv::imencode
In Image_IMEncode function toByteArray allocated another native array
and copies the data from the vector
In IMEncode the result of Image_IMEncode is further copied to golang
allocated byte array.
Hence there are 2 additional copies of the data for each call to
IMEncode.
This is highly inefficient, especially if this needs to be performed
frequently.

## Steps to Reproduce
Looking at the code :)

## Your Environment
Linux

The proposed PR: https://github.com/hybridgroup/gocv/pull/866 solves the issue by avoiding datacopies.

**Comment by deadprogram** [comment]
Released in v0.28 so now closing. Thanks!
