### ISSUE TITLE
static build

### ISSUE THREAD

**Issue by Rehtt** [hybridgroup/gocv#882]
Compile and install through `make install_static` , and then use the command `go build -tags static --ldflags'-extldflags "-static"' -o static_version ./cmd/version/main.go` , the result is:
```
# runtime/cgo
/usr/bin/ld: cannot find -lippiw
/usr/bin/ld: cannot find -lippicv
collect2: error: ld returned 1 exit status
```

**Comment by Rehtt** [comment]
I solved this problem, modified the `cgo_static.go` file, replaced the value of `LDFLAGS` with the value of the `pkg-config --libs --static opencv4` command, and it succeeded.

command: `sed -i "/#cgo LDFLAGS/c\#cgo LDFLAGS: $(pkg-config --libs --static opencv4)" cgo_static.go`

**Comment by HEUBITLYJ** [comment]
hello，what is your operating system， i am run build gocv in docker，here is my dockerfile：
```
# builder image
FROM golang:1.17-buster AS builder

RUN apt-get update && apt-get install -y git sudo

RUN git clone https://github.com/hybridgroup/gocv.git 
RUN cd gocv && make deps
RUN cd gocv && make download
RUN cd gocv && make sudo_pre_install_clean
RUN cd gocv && make build_static
RUN cd gocv && make sudo_install
RUN cd gocv && make clean
RUN cd gocv && sed -i "/#cgo LDFLAGS/c\#cgo LDFLAGS: $(pkg-config --libs --static opencv4)" cgo_static.go
RUN cd gocv && make verify

````

i also get lotof error msg.
