### ISSUE TITLE
Text tecognition

### ISSUE THREAD

**Issue by gedw99** [hybridgroup/gocv#9]
I was wondering if text recognition can be done with this ?

**Comment by deadprogram** [comment]
Hi @gedw99 

It is possible to integrate https://github.com/opencv/opencv_contrib/tree/master/modules/text since opencv_contrib is built as part of the instructions for GoCV. 

You would need to add a GoCV wrapper, since that is not yet part of the GoCV package code. It also appears you would need to install Tesseract OCR before installing OpenCV to include that capability.

Hopefully that makes sense.

**Comment by gedw99** [comment]
it does !! thank you very much.. If i get it going will buzz a repo link, you as others might like it.

@deadprogram One more.. DO you know if any of this works on Mobile yet. I do a fair bit of golang on mobiles and its possibel to get this going on mobile, but just wanted to ask first...

**Comment by deadprogram** [comment]
If you are so inspired, we'd love a PR with code to add support to GoCV for the `text` module, please and thank you.

I have not tried any of this on mobile, but would love to know how to support "officially". That really would be awesome.

**Comment by gedw99** [comment]
will give it a whirl..

For Text Module. Def yes.

For Mobile GUI, planning to use Gomatcha. 
https://github.com/gomatcha/matcha
Its compelling i must say.

I asked about linking here for webrtc, but for openCV its similar integration issue:
https://github.com/gomatcha/matcha/issues/40

Will post repo of examples as i go...

**Comment by DeadNumbers** [comment]
For text recognition use Tesseract OCR https://github.com/otiai10/gosseract

**Comment by joeblew99** [comment]
Thanks.

For mobile compilation I have found it best to avoid using gomobile.

There is a github org called xlab that makes it easy to use c with golang on mobile. 
It also has a c to golang binding generator. Had good success with it.

**Comment by joeblew99** [comment]
Here for c to go bindings gen

https://github.com/xlab/c-for-go

**Comment by deadprogram** [comment]
Adding support for the `text` module from OpenCV Contrib is already on the ROADMAP.

https://github.com/hybridgroup/gocv/blob/master/ROADMAP.md

I will close this issue now, please reopen if needed. Thank you, everyone!
