### ISSUE TITLE
Adding support for cv::estimateAffine2D

### ISSUE THREAD

**Issue by mykillandjello** [hybridgroup/gocv#905]
### Description
I'd like to add support for https://docs.opencv.org/4.0.0/d9/d0c/group__calib3d.html#ga27865b1d26bac9ce91efaee83e94d4dd

**Comment by deadprogram** [comment]
That sounds awesome! Yes please and thank you!

**Comment by mykillandjello** [comment]
See pull request #906

**Comment by deadprogram** [comment]
Now released in 0.29.0. Thanks!
