### ISSUE TITLE
How to create a Mat that contains negative numbers?

### ISSUE THREAD

**Issue by MoonNarga** [hybridgroup/gocv#920]
## Description
I want to create a kernel for Filter2D just like sobel.
But I can‘t make a Mat that contains negative number such as -2 or -1 by the func NewMatFromBytes()
![image](https://user-images.githubusercontent.com/45871412/147386640-f371dffb-938c-4c8d-9380-26e8b38ef3f7.png)
```
kernel, err := gocv.NewMatFromBytes(3, 3, gocv.MatTypeCV8UC1, []byte{-2, -1, 0, -1, 0, 1, 0, 1, 2})
```

## Your Environment

* Operating System and version: Win11
* OpenCV version used: 4.5.4
* How did you install OpenCV? by run the win_build_opencv.cmd
* GoCV version used: 0.29.0
* Go version: 1.17.1
* Did you run the `env.sh` or `env.cmd` script before trying to `go run` or `go build`? no

**Comment by mitul93** [comment]
You can initialize kernel like this...

```
kernel := []int32{-2, -1, 0, -1, 0, 1, 0, 1, 2}
kernelMat := gocv.NewMatWithSize(1, len(kernel), gocv.MatTypeCV32S)

for index, val := range kernel {
    kernelMat.SetIntAt(0, index, val)
}
```

**Comment by MoonNarga** [comment]
> You can initialize kernel like this...
> 
> ```
> kernel := []int32{-2, -1, 0, -1, 0, 1, 0, 1, 2}
> kernelMat := gocv.NewMatWithSize(1, len(kernel), gocv.MatTypeCV32S)
> 
> for index, val := range kernel {
>     kernelMat.SetIntAt(0, index, val)
> }
> ```

Thanks for @mitul93 !
It really works!
