### ISSUE TITLE
Adding support for estimateAffine2DWithParams

### ISSUE THREAD

**Issue by mykillandjello** [hybridgroup/gocv#923]
I'd like to add support for `estimateAffine2D` but with the optional parameters.

https://docs.opencv.org/4.0.0/d9/d0c/group__calib3d.html#ga27865b1d26bac9ce91efaee83e94d4dd

**Comment by mykillandjello** [comment]
See #924

**Comment by deadprogram** [comment]
Closing this since it was already released. Thanks again!
