### ISSUE TITLE
exit status 0xc0000135

### ISSUE THREAD

**Issue by sun-unc** [hybridgroup/gocv#938]
Console: exit status 0xc0000135,How should I do?
![ccb3c747e284a5a5171eb6b37e1e3fd](https://user-images.githubusercontent.com/39368381/154682697-eba54c31-10a5-45d6-b338-f6e47eda4bb0.png)

**Comment by DSharifi** [comment]
How did you resolve this issue?

**Comment by feipengheart** [comment]
How can I solve this problem

**Comment by itltf512116** [comment]
You can try it like this：
1. add C:\opencv\build\bin to PATH;
2. reboot


> How can I solve this problem
