### ISSUE TITLE
overloading functions

### ISSUE THREAD

**Issue by berak** [hybridgroup/gocv#95]
e.g. ConvertTo() currently only takes a Mat and a flag, while the c++ counterpart also has a (optional) scale and offset, used like:

    Mat src; // assumed bgr in [0..255]
    dst = src.convertTo(dst, CV_32F, 1.0/255); // to [0..1] range

are there like, "Coding style Guidelines" ?

**Comment by deadprogram** [comment]
Some guidelines of this sort are needed. In the meantime, here is an example of how we have been handling: https://github.com/hybridgroup/gocv/issues/29

**Comment by berak** [comment]
yes, exactly, what i meant, thank you !

**Comment by Siriki-Saikiran** [comment]
Hi, unable to find ConvertToWithParams() function. Is there any alternative way to implement convertTo() with three arguments
