### ISSUE TITLE
Question: How can I get the indices of the convex hull points from Mat?

### ISSUE THREAD

**Issue by SuzukiHonoka** [hybridgroup/gocv#967]
## Description
I noticed the function `ConvexHull(points PointVector, hull *Mat, clockwise bool, returnPoints bool)`  only accepts Mat as the receiver.
According to the OpenCV documentation, it may return `std::vector<int>` while returnPoints=false.
I'd like to know how can I get the  `std::vector<int>`  from the Mat?
Thanks for the great work!

## Steps to Reproduce

```
hull := gocv.NewMat()
gocv.ConvexHull(approx, &hull, false, false)
```

## Your Environment

* Operating System and version: Windows 11
* OpenCV version used: 4.5.5
* How did you install OpenCV? build from source
* GoCV version used: 0.30.0
* Go version: 1.8
* Did you run the `env.sh` or `env.cmd` script before trying to `go run` or `go build`? yes

**Comment by ansoni-san** [comment]
@SuzukiHonoka What was the answer to this?

**Comment by SuzukiHonoka** [comment]
> @SuzukiHonoka What was the answer to this?

I still have no idea but gave up this, sorry.

**Comment by ansoni-san** [comment]
Thanks. I figured it out. It's just a single column of Int which you can get using GetIntAt. My problem was trying to use NewPointVectorFromMat. It doesn't understand the format.

**Comment by SuzukiHonoka** [comment]
> Thanks. I figured it out. It's just a single column of Int which you can get using GetIntAt. My problem was trying to use NewPointVectorFromMat. It doesn't understand the format.

Thanks for the tip! Gald you solved this!
