### ISSUE TITLE
exit status 0xc0000135 on win11

### ISSUE THREAD

**Issue by Baiyuetribe** [hybridgroup/gocv#974]
## Description

After normal installation, the output reports an error
## Steps to Reproduce

```
cd %GOPATH%\src\gocv.io\x\gocv
win_build_opencv.cmd
```
![image](https://user-images.githubusercontent.com/43716063/166414460-7261a1a9-bca5-4613-bdef-c5301484ad3a.png)

## Your Environment

* Operating System and version: win11 latest
* OpenCV version used:4.5.5
* How did you install OpenCV? auto install by gocv cmd
* GoCV version used:latest
* Go version:go1.17.8 windows/amd64
* Did you run the `env.sh` or `env.cmd` script before trying to `go run` or `go build`?yes

**Comment by Baiyuetribe** [comment]
Sorry, everything is fine after restarting the machine

**Comment by kern518** [comment]
me too

**Comment by weiwentao996** [comment]
Add C:\opencv\build\install\x64\mingw\bin to your System Path.
