### ISSUE TITLE
MatchTemplate with multiple results

### ISSUE THREAD

**Issue by J7mbo** [hybridgroup/gocv#991]
Hi! This is more a question - In Python there's the numpy lib which handles the matrix of results from calling `MatchTemplate` in opencv. However I haven't been able to find an example of doing this with Go and `gocv`, and it seems pretty complicated to do that.

How can one loop around the resulting `Mat` from calling `MatchTemplate` given a threshold, and extract all those Mats?

**Comment by qianniancn** [comment]
You can refer to the implementation of this code : https://github.com/vcaesar/gcv/blob/main/cv.go#L218

**Comment by J7mbo** [comment]
I'm looking at this code and what I don't get is why the infinite `for` loop will ever break. It doesn't seem like there's a change in the values being looped over any any time, I can't see an iterator. In fact, when I use most of this code locally, the for loop runs infinitely.

**Comment by J7mbo** [comment]
Maybe this question is for StackOverflow then. It seems there is literally nothing in Go on the internet apart from the single above code that handles multiple results from `MatchTemplate`, and there's no numpy.
